# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [10]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_full/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [11]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_full/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_full/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_full/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [12]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                \
                       base             base_inv                       ft
0           .Today (0.0250)      urrenc (0.0221)          .Today (0.0220)
1          .Second (0.0111)       act (5.10e-03)         .Second (0.0104)
2        Buccane (8.67e-03)       pos (4.94e-03)       Buccane (8.61e-03)
3          /Area (6.32e-03)    askell (3.49e-03)         /Area (6.68e-03)
4            .au (4.91e-03)      gons (3.30e-03)           .au (3.94e-03)
5      /problems (3.83e-03)      ejec (2.00e-03)     /problems (3.69e-03)
6            aru (3.83e-03)        �� (2.00e-03)         /Math (3.36e-03)
7      /entities (2.90e-03)        دي (2.00e-03)         /bind (3.16e-03)
8          /Math (2.72e-03)      azon (1.93e-03)     /entities (2.87e-03)
9       /problem (2.64e-03)     fácil (1.82e-03)          oire (2.70e-03)
10         /bind (2.56e-03)      anth (1.76e-03)      /problem (2.70e-03)
11      /respond (2.56e-03)     posix (1.71e-03)     /activity (2.62e-03)
12          fter (2.47e-03)  essional (1.66e-03)      /respond (2.38e-03)
13    confidence (2.26e-03)  Optional (1.56e-03)          fter (2.30e-03)
14     /operator (2.18e-03)      Vers (1.50e-03)   persistence (2.30e-03)
15     /activity (2.18e-03)        vs (1.46e-03)          ilot (2.17e-03)
16   persistence (2.12e-03)    Phones (1.46e-03)        soever (2.17e-03)
17          ilot (2.06e-03)       med (1.25e-03)    confidence (2.17e-03)
18     belonging (1.98e-03)  >Welcome (1.25e-03)     /operator (2.11e-03)
19     .AddRange (1.87e-03)      orst (1.25e-03)           aru (2.04e-03)

                                                                     \
                 ft_inv                   diff             diff_inv
0       urrenc (0.0143)      gorith (9.77e-03)     ainer (7.93e-03)
1        pos (5.28e-03)       encia (7.17e-03)   passing (6.20e-03)
2        act (4.82e-03)        onta (6.71e-03)   Passage (6.01e-03)
3     askell (4.82e-03)     trovare (5.58e-03)      htub (5.65e-03)
4         �� (3.20e-03)   -scalable (4.09e-03)       buz (5.13e-03)
5       gons (3.20e-03)          }? (4.09e-03)       muc (4.67e-03)
6      fácil (2.82e-03)   acimiento (3.60e-03)   Passing (4.00e-03)
7         دي (2.14e-03)     Masters (3.17e-03)     arten (3.88e-03)
8       anth (2.14e-03)    Accounts (2.81e-03)      Pass (3.88e-03)
9       azon (1.95e-03)      stride (2.81e-03)      prox (3.02e-03)
10  essional (1.95e-03)         sab (2.81e-03)       ans (3.02e-03)
11       med (1.95e-03)        .;\n (2.64e-03)      auen (2.93e-03)
12        vs (1.66e-03)       abbix (2.47e-03)     -town (2.67e-03)
13    Phones (1.61e-03)  Executable (2.47e-03)       ush (2.67e-03)
14      ejec (1.51e-03)       guard (2.47e-03)       cre (2.50e-03)
15  Optional (1.46e-03)        ucci (2.32e-03)     alary (2.50e-03)
16         د (1.34e-03)        (SQL (2.18e-03)       ubb (2.35e-03)
17     cambi (1.30e-03)      resden (2.18e-03)      PASS (2.27e-03)
18       div (1.21e-03)          si (2.18e-03)    endale (2.27e-03)
19       ')" (1.14e-03)        atra (2.04e-03)         ư (2.27e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9141)          zoek (0.8555)           To (0.9141)
1           The (0.0454)      contador (0.1309)          The (0.0400)
2           Let (0.0139)           메 (9.46e-03)           In (0.0157)
3            In (0.0130)         иск (3.49e-03)          Let (0.0122)
4         ### (3.72e-03)     Produto (2.12e-03)          A (3.49e-03)
5           A (2.56e-03)           � (1.42e-05)        ### (3.30e-03)
6         For (1.14e-03)     Detalle (9.78e-06)        For (1.88e-03)
7          As (9.16e-04)      Resets (9.78e-06)         ** (1.46e-03)
8           I (7.82e-04)         .\" (4.62e-06)          I (1.29e-03)
9          ** (7.32e-04)          首页 (3.61e-06)         As (1.21e-03)
10          1 (7.13e-04)      inicio (2.19e-06)  Certainly (9.73e-04)
11  Certainly (5.53e-04)    autoplay (1.71e-06)       Sure (7.32e-04)
12       Sure (4.06e-04)       KANJI (1.51e-06)          1 (6.10e-04)
13      First (3.93e-04)   Generates (1.33e-06)       This (4.31e-04)
14         We (3.70e-04)      Editar (1.33e-06)         It (4.31e-04)
15         It (3.59e-04)         Msp (1.04e-06)       Here (3.59e-04)
16       This (3.47e-04)     kontakt (1.04e-06)      First (3.36e-04)
17      Given (1.97e-04)   Retrieves (9.13e-07)         We (3.36e-04)
18          S (1.45e-04)   Productos (9.13e-07)      Given (1.80e-04)
19          H (1.40e-04)    Executes (9.13e-07)          H (1.75e-04)

                                                                         \
                   ft_inv                    diff              diff_inv
0           zoek (0.8359)            you (0.2412)      iglia (6.96e-03)
1       contador (0.1455)            You (0.2129)         ió (6.53e-03)
2              메 (0.0119)            You (0.1553)        ège (6.13e-03)
3          иск (4.97e-03)           Your (0.1211)         gł (6.13e-03)
4      Produto (2.35e-03)           your (0.0942)     letras (5.77e-03)
5            � (1.59e-05)       yourself (0.0444)   ipherals (5.10e-03)
6      Detalle (1.08e-05)           Your (0.0393)        già (4.76e-03)
7       Resets (7.48e-06)           your (0.0136)         ôn (3.72e-03)
8          .\" (5.13e-06)          YOU (6.84e-03)        иск (3.49e-03)
9           首页 (2.74e-06)         YOUR (5.31e-03)      líder (3.49e-03)
10      inicio (1.88e-06)          you (5.00e-03)        eus (3.28e-03)
11    autoplay (1.47e-06)         here (5.00e-03)    uestion (2.90e-03)
12       KANJI (1.47e-06)        yours (3.89e-03)        ulo (2.90e-03)
13      Editar (1.30e-06)         YOUR (2.85e-03)    periodo (2.72e-03)
14   Retrieves (1.01e-06)          YOU (2.85e-03)     pierws (2.55e-03)
15         Msp (8.90e-07)   yourselves (1.72e-03)         ké (2.40e-03)
16     kontakt (8.90e-07)         Here (1.43e-03)      altre (2.40e-03)
17   Generates (8.90e-07)         Here (1.27e-03)      ateur (2.40e-03)
18      <quote (7.86e-07)           if (1.05e-03)  ocomplete (2.40e-03)
19           구 (7.86e-07)           If (1.05e-03)      letto (2.40e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4395)          zoek (0.9648)           To (0.4785)
1            ** (0.3027)      contador (0.0138)           ** (0.3730)
2           ### (0.2080)         иск (9.46e-03)          ### (0.1069)
3           Let (0.0248)           메 (8.36e-03)          Let (0.0145)
4           The (0.0171)     Produto (7.29e-04)          The (0.0128)
5   Certainly (2.61e-03)          首页 (4.67e-05)  Certainly (4.70e-03)
6        Sure (1.40e-03)        (PHP (1.11e-05)       Sure (2.21e-03)
7          In (1.24e-03)         Msp (9.78e-06)         In (1.72e-03)
8          ## (7.48e-04)      amodel (5.57e-06)         ## (5.61e-04)
9       Given (4.01e-04)      Gratis (4.92e-06)          A (4.37e-04)
10      First (2.43e-04)           � (4.62e-06)       Here (4.37e-04)
11          1 (2.43e-04)       ptest (4.35e-06)      Given (3.85e-04)
12          A (2.15e-04)    autoplay (4.08e-06)       This (2.99e-04)
13       This (1.77e-04)       etest (4.08e-06)         As (2.65e-04)
14        ``` (1.57e-04)         .\" (4.08e-06)        For (2.50e-04)
15         We (1.48e-04)      ertest (3.84e-06)          1 (2.34e-04)
16       #### (1.38e-04)     Detalle (3.61e-06)      First (2.06e-04)
17         As (1.30e-04)       Ports (3.61e-06)          I (1.82e-04)
18       Here (1.22e-04)        [now (3.38e-06)         It (1.61e-04)
19        For (1.08e-04)  modifiable (3.38e-06)          * (1.11e-04)


                   ft_inv                  diff                   diff_inv
0           zoek (0.9609)          You (0.6680)              ôn (4.03e-03)
1       contador (0.0176)         Your (0.1162)       principio (3.78e-03)
2            иск (0.0121)          you (0.0908)            ilha (3.78e-03)
3            메 (8.30e-03)          You (0.0664)        contador (3.56e-03)
4      Produto (9.92e-04)         your (0.0157)            osos (3.13e-03)
5           首页 (3.62e-05)       Your (7.93e-03)            insi (3.13e-03)
6         (PHP (1.33e-05)        you (6.99e-03)             иск (3.13e-03)
7          Msp (1.04e-05)       your (5.80e-03)          letras (2.59e-03)
8            � (6.29e-06)   yourself (3.10e-03)             pdu (2.44e-03)
9          .\" (5.22e-06)       Here (1.21e-03)              ượ (2.44e-03)
10     Detalle (4.59e-06)        YOU (1.14e-03)               県 (2.44e-03)
11       ptest (4.05e-06)        YOU (1.14e-03)  FirstResponder (2.29e-03)
12    autoplay (3.81e-06)          … (7.86e-04)            ltra (2.29e-03)
13      amodel (3.16e-06)        ... (7.36e-04)           calar (2.15e-03)
14        [now (2.79e-06)          ( (6.10e-04)            ikut (2.03e-03)
15      ertest (2.31e-06)       here (6.10e-04)          uestos (2.03e-03)
16     inflate (2.18e-06)         If (6.10e-04)           shint (2.03e-03)
17  modifiable (2.18e-06)        Yes (5.72e-04)             uso (1.90e-03)
18        SCRI (2.18e-06)       YOUR (5.72e-04)            (cid (1.90e-03)
19      -deals (2.04e-06)          I (5.07e-04)          nostro (1.90e-03)

In [13]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.72e-03)        /problem (0.0400)
1        /entities (0.0273)       (us (5.31e-03)       /entities (0.0266)
2        /problems (0.0177)      sagt (4.15e-03)       /problems (0.0183)
3           .Today (0.0101)       ]]; (4.15e-03)       /global (8.91e-03)
4        /global (8.85e-03)        że (3.65e-03)        .Today (8.61e-03)
5           /job (7.60e-03)    testim (3.02e-03)          /job (6.71e-03)
6        /manage (7.60e-03)       ')" (2.84e-03)       /manage (6.71e-03)
7   /preferences (6.29e-03)       ($. (2.84e-03)       /layout (5.74e-03)
8        /layout (5.74e-03)      -ves (2.84e-03)  /preferences (5.25e-03)
9      /provider (5.07e-03)     zeigt (2.67e-03)     /provider (5.07e-03)
10       /crypto (4.91e-03)     feliz (2.21e-03)       /crypto (4.76e-03)
11   /connection (4.33e-03)     spons (2.21e-03)   /connection (4.21e-03)
12      /logging (4.06e-03)     lesen (2.08e-03)      /logging (4.09e-03)
13    WHATSOEVER (3.94e-03)       (!! (1.95e-03)  /environment (3.83e-03)
14       /engine (3.94e-03)   kontrol (1.95e-03)       /engine (3.83e-03)
15          /reg (3.81e-03)      helf (1.72e-03)          /reg (3.71e-03)
16  /environment (3.81e-03)    spiele (1.72e-03)    WHATSOEVER (3.60e-03)
17       /dialog (3.48e-03)     scrut (1.62e-03)      /effects (3.60e-03)
18       /entity (3.37e-03)       fas (1.53e-03)       /dialog (3.39e-03)
19      /effects (3.37e-03)       )": (1.53e-03)       /object (3.17e-03)

                                                                     \
                 ft_inv                  diff              diff_inv
0        .vn (8.36e-03)         ucci (0.0342)         ropa (0.0339)
1        (us (4.46e-03)       anno (9.77e-03)         ー� (6.26e-03)
2        ]]; (4.18e-03)       Pert (8.12e-03)      vidéo (5.52e-03)
3       sagt (3.94e-03)       heim (8.12e-03)      atter (4.58e-03)
4         że (3.94e-03)      annon (5.95e-03)        vod (4.58e-03)
5     testim (3.07e-03)       acea (4.91e-03)  versation (4.18e-03)
6      zeigt (3.07e-03)        lij (4.61e-03)     .spark (4.18e-03)
7       -ves (3.07e-03)      avras (3.39e-03)   narrowly (3.57e-03)
8        ($. (2.88e-03)        bel (3.39e-03)        zie (3.57e-03)
9        ')" (2.88e-03)   independ (3.08e-03)       yles (3.16e-03)
10     spons (2.24e-03)      recon (2.99e-03)         ín (2.61e-03)
11       (!! (2.24e-03)      Licht (2.64e-03)        cot (2.46e-03)
12     feliz (2.24e-03)        apo (2.55e-03)        ños (2.24e-03)
13     lesen (2.24e-03)        boy (2.40e-03)       aved (2.11e-03)
14   kontrol (1.75e-03)      ombok (2.26e-03)        får (2.03e-03)
15      helf (1.64e-03)         lj (2.12e-03)     kommun (1.97e-03)
16    spiele (1.54e-03)         co (2.04e-03)       così (1.91e-03)
17       )": (1.54e-03)       alus (1.98e-03)      etten (1.91e-03)
18       fas (1.45e-03)        rus (1.98e-03)       rose (1.74e-03)
19      -git (1.45e-03)        tat (1.93e-03)       cron (1.74e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.5703)     contador (0.8398)         , (0.6211)
1       and (0.1436)         bö (7.26e-03)       and (0.1367)
2       the (0.1377)   karakter (7.26e-03)       the (0.1011)
3        in (0.0591)    kontrol (7.26e-03)       ' ' (0.0554)
4       ' ' (0.0552)         �� (5.65e-03)        in (0.0537)
5         a (0.0132)         �� (5.65e-03)         a (0.0119)
6       ( (3.66e-03)      KANJI (3.43e-03)       ( (4.67e-03)
7      to (3.39e-03)      subur (3.43e-03)      to (2.96e-03)
8      of (2.90e-03)       samt (3.43e-03)      of (2.61e-03)
9      by (2.62e-03)     testim (2.67e-03)      by (2.14e-03)
10    for (1.84e-03)     kosten (2.67e-03)     for (1.91e-03)
11     is (1.21e-03)     komple (2.08e-03)      is (1.01e-03)
12     as (9.69e-04)       sagt (2.08e-03)      as (9.04e-04)
13     on (8.43e-04)       dara (1.62e-03)      on (6.52e-04)
14   will (5.87e-04)       rekl (1.62e-03)    will (5.49e-04)
15     we (4.23e-04)     bilder (1.62e-03)    with (3.60e-04)
16   with (3.99e-04)     uarios (1.62e-03)       " (3.55e-04)
17      " (3.15e-04)       zoek (1.62e-03)       . (2.98e-04)
18      . (2.78e-04)        tgl (1.26e-03)  '\xa0' (2.63e-04)
19     at (2.78e-04)     spiele (1.26e-03)      at (2.39e-04)

                                                                           \
                  ft_inv                    diff                 diff_inv
0      contador (0.8398)            you (0.9336)           egt (7.32e-03)
1     kontrol (7.26e-03)       yourself (0.0220)          nell (4.73e-03)
2          �� (5.65e-03)            you (0.0151)             ว (4.73e-03)
3          bö (5.65e-03)         your (9.16e-03)          REEN (3.80e-03)
4          �� (5.65e-03)          YOU (7.14e-03)          nuru (3.57e-03)
5    karakter (5.65e-03)          You (4.91e-03)         getti (2.87e-03)
6        samt (4.39e-03)          You (2.98e-03)         __(\n (2.78e-03)
7       subur (4.39e-03)        yours (8.51e-04)           Bun (2.69e-03)
8       KANJI (3.42e-03)         your (7.51e-04)        Unidos (2.69e-03)
9      kosten (2.67e-03)   yourselves (6.64e-04)         strup (2.46e-03)
10     testim (2.67e-03)         YOUR (4.56e-04)       gettext (2.46e-03)
11       sagt (2.08e-03)         vous (3.55e-04)      etermine (2.23e-03)
12        tgl (1.62e-03)         -you (1.68e-04)          dent (2.03e-03)
13     komple (1.62e-03)         —you (1.31e-04)        legate (1.97e-03)
14       zoek (1.62e-03)         Your (1.23e-04)          uest (1.91e-03)
15     bilder (1.26e-03)        votre (1.02e-04)  NSDictionary (1.85e-03)
16       dara (1.26e-03)          YOU (7.44e-05)     ocomplete (1.74e-03)
17     uarios (1.26e-03)            你 (5.46e-05)        elsing (1.69e-03)
18       rekl (1.26e-03)         Your (4.24e-05)           ulo (1.69e-03)
19     <quote (1.26e-03)         .You (3.53e-05)          .vue (1.63e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.4961)    contador (0.0698)         , (0.5430)
1         in (0.1289)      rido (5.74e-03)       ' ' (0.1245)
2        ' ' (0.1108)    incinn (4.46e-03)        in (0.1035)
3        the (0.0835)      LOSE (4.46e-03)       and (0.0708)
4        and (0.0786)      anio (4.46e-03)       the (0.0688)
5          a (0.0303)      zoek (3.48e-03)         ( (0.0270)
6          ( (0.0181)        �� (3.48e-03)         a (0.0238)
7         by (0.0115)    icerca (2.72e-03)      to (6.71e-03)
8         to (0.0103)       ogs (2.72e-03)     for (6.32e-03)
9      for (6.53e-03)       ，默认 (2.72e-03)      by (5.83e-03)
10      as (3.69e-03)     UTTON (2.72e-03)      as (3.59e-03)
11   first (3.65e-03)      erca (2.11e-03)       " (1.98e-03)
12      we (2.32e-03)  entarios (2.11e-03)   first (1.75e-03)
13      ** (2.04e-03)    <quote (2.11e-03)    with (1.46e-03)
14       " (1.95e-03)       @js (2.11e-03)      of (1.40e-03)
15      of (1.88e-03)      <?\n (2.11e-03)      ** (1.11e-03)
16    with (1.80e-03)    anneer (2.11e-03)    will (9.99e-04)
17    will (1.21e-03)    pcodes (1.64e-03)       - (8.74e-04)
18      on (1.09e-03)       (Cs (1.64e-03)      we (8.47e-04)
19       - (5.99e-04)    LOGGER (1.64e-03)     you (7.25e-04)


                ft_inv                    diff                  diff_inv
0    contador (0.0471)            you (0.9805)           nuru (6.38e-03)
1    incinn (4.97e-03)         your (6.59e-03)           SSIP (4.97e-03)
2        �� (3.88e-03)          you (4.55e-03)           utow (4.39e-03)
3    <quote (3.88e-03)     yourself (3.11e-03)           iele (4.24e-03)
4      LOSE (3.88e-03)          You (3.11e-03)           ltra (3.11e-03)
5     UTTON (3.88e-03)          You (1.89e-03)            pdu (2.58e-03)
6    icerca (3.02e-03)          YOU (3.72e-04)           ween (2.20e-03)
7      rido (3.02e-03)        yours (1.55e-04)              ว (2.14e-03)
8      anio (2.35e-03)         your (1.07e-04)        utrecht (2.00e-03)
9      zoek (2.35e-03)         -you (8.30e-05)        gettext (1.82e-03)
10     <?\n (2.35e-03)         —you (3.46e-05)            egt (1.77e-03)
11      ，默认 (2.35e-03)   yourselves (3.46e-05)            .ct (1.61e-03)
12     utow (1.83e-03)         Your (2.69e-05)            cek (1.46e-03)
13      ogs (1.83e-03)         Your (2.38e-05)         elsing (1.34e-03)
14      (Cs (1.83e-03)         YOUR (1.63e-05)         enberg (1.34e-03)
15   LOGGER (1.62e-03)         vous (1.28e-05)   NSDictionary (1.34e-03)
16     fono (1.62e-03)            你 (4.14e-06)        ensburg (1.30e-03)
17   HOLDER (1.62e-03)          YOU (3.87e-06)     censorship (1.25e-03)
18       排序 (1.62e-03)        -your (2.50e-06)         idebar (1.21e-03)
19      @js (1.62e-03)        votre (2.35e-06)   NSDictionary (1.17e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [14]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0260)         .vn (0.0199)       /entities (0.0279)
1         /problem (0.0140)   /Register (0.0114)        /problem (0.0149)
2      /problems (9.27e-03)    testim (6.92e-03)     /problems (9.91e-03)
3        /global (6.76e-03)      sagt (6.53e-03)       /global (6.91e-03)
4   /environment (6.08e-03)     asign (5.23e-03)     /provider (6.28e-03)
5      /provider (5.89e-03)       -ie (4.93e-03)  /environment (5.99e-03)
6         .Today (5.88e-03)     zeigt (4.07e-03)   /connection (5.98e-03)
7    /connection (5.69e-03)        że (3.93e-03)        .Today (5.46e-03)
8        /manage (5.62e-03)      -ves (3.30e-03)     /customer (4.92e-03)
9      /customer (4.80e-03)   personn (2.84e-03)       /manage (4.88e-03)
10  /preferences (4.26e-03)         ť (2.84e-03)  /preferences (4.04e-03)
11       /shared (3.36e-03)     probs (2.78e-03)       /shared (3.41e-03)
12       /dialog (3.30e-03)      elig (2.55e-03)       /dialog (3.39e-03)
13      /account (3.17e-03)    ):\n\n (2.39e-03)      /account (3.37e-03)
14       /entity (3.15e-03)      roku (2.32e-03)      libertin (3.25e-03)
15      libertin (3.01e-03)     lesen (2.23e-03)       /entity (3.20e-03)
16       /layout (2.87e-03)       )": (2.22e-03)      /effects (3.05e-03)
17          .Try (2.85e-03)  ,,,,,,,, (2.20e-03)       /layout (3.02e-03)
18      /effects (2.72e-03)    spiele (2.12e-03)          .Try (2.90e-03)
19        /legal (2.67e-03)       (us (2.09e-03)        /legal (2.67e-03)

                                                                    \
                 ft_inv                  diff             diff_inv
0          .vn (0.0215)         acea (0.0416)     nails (5.15e-03)
1    /Register (0.0111)         ucci (0.0156)       row (4.27e-03)
2     testim (6.69e-03)         anno (0.0104)     calle (3.93e-03)
3       sagt (6.56e-03)      Blond (6.98e-03)      ropa (3.74e-03)
4        -ie (5.00e-03)       heim (6.19e-03)      emos (3.68e-03)
5      asign (4.94e-03)        lij (5.33e-03)       cho (3.31e-03)
6      zeigt (4.50e-03)        ple (5.08e-03)      yles (3.21e-03)
7         że (3.76e-03)     ervers (3.37e-03)   Bedford (2.91e-03)
8       -ves (3.31e-03)     ighted (2.87e-03)        ー� (2.68e-03)
9          ť (3.25e-03)      avras (2.32e-03)       rem (2.56e-03)
10     probs (2.87e-03)       ając (2.32e-03)        Ps (1.97e-03)
11   personn (2.77e-03)     itives (2.26e-03)      nail (1.95e-03)
12      roku (2.36e-03)       orda (2.21e-03)      ason (1.92e-03)
13      elig (2.33e-03)        Lah (2.13e-03)     venta (1.91e-03)
14     lesen (2.29e-03)      Arial (1.94e-03)    olicit (1.77e-03)
15  ,,,,,,,, (2.28e-03)     aturas (1.72e-03)   lements (1.73e-03)
16    ):\n\n (2.21e-03)      annon (1.64e-03)         ś (1.73e-03)
17       )": (2.20e-03)   independ (1.56e-03)     ISSUE (1.62e-03)
18       esl (2.00e-03)      pelic (1.56e-03)       arp (1.56e-03)
19    spiele (1.96e-03)   markdown (1.55e-03)    olland (1.54e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.7981)     contador (0.9628)         , (0.8091)
1        ' ' (0.1089)    kontrol (3.26e-03)       ' ' (0.1180)
2        the (0.0435)   karakter (2.43e-03)       the (0.0329)
3        and (0.0315)       rekl (1.61e-03)       and (0.0243)
4       in (6.12e-03)         bö (1.46e-03)       ( (5.48e-03)
5        ( (4.51e-03)       zoek (1.15e-03)      in (4.46e-03)
6       's (2.70e-03)    Produto (9.57e-04)      's (2.14e-03)
7        a (1.69e-03)     testim (9.23e-04)       a (1.20e-03)
8       to (1.09e-03)     bilder (8.02e-04)      to (8.62e-04)
9        . (6.79e-04)         �� (7.68e-04)       . (6.71e-04)
10      of (4.03e-04)       dara (7.66e-04)      of (2.78e-04)
11     for (1.83e-04)       helf (5.88e-04)     for (1.45e-04)
12   solve (7.01e-05)       samt (5.13e-04)  '\xa0' (6.96e-05)
13      is (6.90e-05)      subur (5.04e-04)   solve (4.86e-05)
14      on (6.46e-05)      KANJI (4.58e-04)      is (4.70e-05)
15      as (6.27e-05)       fakt (3.70e-04)      as (4.69e-05)
16  '\xa0' (6.26e-05)          메 (3.58e-04)      on (3.96e-05)
17    with (3.15e-05)     komple (3.49e-04)       " (3.07e-05)
18      by (2.87e-05)     kosten (2.85e-04)       : (2.25e-05)
19       " (2.84e-05)      henne (2.57e-04)      by (2.25e-05)

                                                                           \
                  ft_inv                    diff                 diff_inv
0      contador (0.9616)            you (0.5594)             egt (0.0124)
1     kontrol (2.69e-03)            You (0.0734)         strup (7.82e-03)
2    karakter (2.36e-03)           your (0.0712)          uest (4.32e-03)
3          bö (1.29e-03)            you (0.0606)       enfrent (3.99e-03)
4        zoek (1.28e-03)       yourself (0.0489)          iele (3.84e-03)
5     Produto (1.15e-03)           your (0.0372)          nell (3.57e-03)
6        rekl (9.84e-04)           Your (0.0256)        Harden (3.45e-03)
7      testim (9.73e-04)            YOU (0.0195)             ว (3.31e-03)
8          �� (8.78e-04)          yours (0.0181)        puntos (3.17e-03)
9      bilder (8.62e-04)           YOUR (0.0143)           iew (3.03e-03)
10       samt (6.59e-04)          You (9.02e-03)          nuru (2.49e-03)
11       dara (6.59e-04)         vous (5.93e-03)         inden (2.41e-03)
12      subur (6.36e-04)   yourselves (5.53e-03)           .ct (2.21e-03)
13      KANJI (5.18e-04)        votre (4.35e-03)        elsing (2.00e-03)
14       helf (4.42e-04)         Vous (2.03e-03)          fest (1.97e-03)
15          메 (3.98e-04)         Your (2.00e-03)      parseInt (1.93e-03)
16     kosten (3.50e-04)         -you (1.40e-03)       playoff (1.91e-03)
17     <quote (3.01e-04)         —you (1.28e-03)           ',$ (1.80e-03)
18     komple (2.88e-04)            你 (7.95e-04)   contentious (1.78e-03)
19       fakt (2.67e-04)            ? (7.68e-04)         poids (1.77e-03)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7685)     contador (0.9332)           , (0.6856)
1          ' ' (0.1172)       zoek (5.50e-03)         ' ' (0.1583)
2            ( (0.0794)    Produto (1.36e-03)           ( (0.1266)
3          the (0.0197)          메 (4.57e-04)         the (0.0186)
4        and (3.37e-03)   entarios (3.44e-04)        in (2.35e-03)
5         in (3.18e-03)   karakter (2.98e-04)       and (2.32e-03)
6         's (2.27e-03)         �� (2.89e-04)        's (1.65e-03)
7          a (1.78e-03)       rido (2.83e-04)         a (1.02e-03)
8         ** (1.09e-03)     <quote (2.42e-04)        ** (7.85e-04)
9      solve (9.31e-04)       anio (1.94e-04)        to (5.33e-04)
10        to (8.88e-04)       obao (1.85e-04)     solve (4.43e-04)
11         " (1.82e-04)     HOLDER (1.80e-04)         " (2.46e-04)
12    tackle (1.40e-04)        用户名 (1.64e-04)         : (1.98e-04)
13       for (1.38e-04)    kontrol (1.57e-04)   address (1.47e-04)
14        by (1.13e-04)      UTTON (1.47e-04)      this (1.20e-04)
15   address (1.02e-04)     urette (1.41e-04)       for (1.17e-04)
16      this (1.02e-04)        ogs (1.41e-04)    tackle (9.67e-05)
17         : (7.69e-05)        ，默认 (1.31e-04)   problem (8.76e-05)
18   problem (7.25e-05)       LEAN (1.31e-04)        as (5.91e-05)
19        as (6.39e-05)       LOSE (1.23e-04)        by (5.72e-05)


                  ft_inv                  diff            diff_inv
0      contador (0.9294)          you (0.6481)       iele (0.0216)
1        zoek (6.44e-03)          You (0.0626)       utow (0.0148)
2     Produto (1.49e-03)          ... (0.0525)     ikut (9.60e-03)
3           메 (4.71e-04)         your (0.0388)     nuru (3.86e-03)
4      <quote (3.57e-04)          you (0.0271)      pdu (3.58e-03)
5          �� (3.46e-04)            … (0.0248)     SSIP (3.19e-03)
6       UTTON (2.39e-04)            : (0.0207)     esen (3.02e-03)
7    karakter (2.20e-04)            * (0.0172)     kehr (2.83e-03)
8      HOLDER (2.03e-04)          You (0.0165)     ssel (2.64e-03)
9    entarios (1.88e-04)          ( (8.44e-03)      .ct (2.52e-03)
10       rido (1.84e-04)          - (6.49e-03)     ltra (2.25e-03)
11     urette (1.59e-04)   yourself (5.87e-03)   elsing (2.23e-03)
12    kontrol (1.47e-04)          ( (5.20e-03)   idebar (2.03e-03)
13      anela (1.37e-04)        ' ' (4.15e-03)   ninger (1.96e-03)
14     icerca (1.30e-04)      yours (2.63e-03)  ensburg (1.88e-03)
15       obao (1.28e-04)        ... (2.29e-03)    REDIS (1.86e-03)
16       [now (1.27e-04)        YOU (2.26e-03)      egt (1.85e-03)
17        ，默认 (1.27e-04)       your (2.17e-03)      fdb (1.63e-03)
18        用户名 (1.25e-04)       Your (2.11e-03)     IEWS (1.58e-03)
19    ategori (1.22e-04)          0 (2.09e-03)     ivre (1.47e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [15]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                    layer_7                           \
                       base                       ft
0           .Today (0.0254)          .Today (0.0226)
1        .Second (9.16e-03)       .Second (8.77e-03)
2        Buccane (6.49e-03)       Buccane (6.48e-03)
3        /Area (5.90e-03) ✅       /Area (6.08e-03) ✅
4            .au (5.27e-03)           .au (4.31e-03)
5            aru (5.11e-03)       /Math (3.26e-03) ✅
6    /problems (3.10e-03) ✅   /problems (3.06e-03) ✅
7           fter (2.74e-03)          ilot (2.81e-03)
8     confidence (2.71e-03)           aru (2.70e-03)
9           ilot (2.59e-03)    confidence (2.70e-03)
10       /Math (2.54e-03) ✅          fter (2.51e-03)
11   /entities (2.44e-03) ✅   /activity (2.49e-03) ✅
12    /problem (2.18e-03) ✅       /bind (2.46e-03) ✅
13   /activity (2.09e-03) ✅   /entities (2.39e-03) ✅
14       /bind (2.09e-03) ✅          oire (2.31e-03)
15   persistence (1.92e-03)    /problem (2.28e-03) ✅
16    /respond (1.90e-03) ✅   persistence (2.11e-03)
17     belonging (1.90e-03)    /respond (1.86e-03) ✅
18   /operator (1.84e-03) ✅   /operator (1.80e-03) ✅
19  /community (1.57e-03) ✅     belonging (1.74e-03)

                                          layer_14                        \
                        diff                  base                    ft
0             ' ' (8.53e-03)           To (0.7201)           To (0.7643)
1    coordinate (6.70e-03) ✅          ### (0.1250)           ** (0.1125)
2           might (5.75e-03)           ** (0.0762)          ### (0.0682)
3      synchron (4.34e-03) ✅        Let (0.0591) ✅        Let (0.0381) ✅
4          '\n\n' (4.30e-03)          The (0.0132)        The (8.85e-03)
5           encia (3.91e-03)  Certainly (1.52e-03)  Certainly (2.75e-03)
6           Mon (3.76e-03) ✅       Sure (1.08e-03)       Sure (1.74e-03)
7            Than (3.70e-03)         ## (7.44e-04)         In (6.42e-04)
8          reader (3.61e-03)         In (5.11e-04)         ## (5.90e-04)
9     financial (3.32e-03) ✅    Given (2.27e-04) ✅     Here (3.66e-04) ✅
10       target (3.21e-03) ✅    First (2.23e-04) ✅    Given (2.46e-04) ✅
11          items (3.07e-03)    Alright (1.27e-04)    First (1.96e-04) ✅
12          super (2.80e-03)       We (1.14e-04) ✅       This (1.34e-04)
13     deadline (2.67e-03) ✅        1 (1.07e-04) ✅        For (1.14e-04)
14      morning (2.47e-03) ✅       #### (1.01e-04)         As (1.12e-04)
15           '  ' (2.44e-03)        ``` (9.49e-05)    Alright (1.12e-04)
16              1 (2.34e-03)     Here (8.92e-05) ✅        1 (8.85e-05) ✅
17            ... (2.32e-03)     This (8.92e-05) ✅       #### (7.34e-05)
18          supra (2.28e-03)        For (5.39e-05)         We (6.48e-05)
19        Picture (2.10e-03)         As (5.28e-05)         It (5.84e-05)

                                          layer_15                        \
                        diff                  base                    ft
0               You (0.1748)           To (0.4297)           To (0.4785)
1              Your (0.1576)          ### (0.2598)           ** (0.3730)
2               You (0.1481)           ** (0.2598)          ### (0.1069)
3             you (0.1335) ✅        Let (0.0242) ✅        Let (0.0145) ✅
4            your (0.0809) ✅          The (0.0166)          The (0.0128)
5        yourself (0.0480) ✅  Certainly (2.55e-03)  Certainly (4.15e-03)
6              Your (0.0480)       Sure (1.37e-03)       Sure (2.21e-03)
7            your (0.0163) ✅         In (1.21e-03)         In (1.73e-03)
8            here (9.68e-03)         ## (8.28e-04)         ## (5.61e-04)
9            YOUR (7.38e-03)    Given (3.91e-04) ✅       Here (4.37e-04)
10            YOU (7.38e-03)    First (2.37e-04) ✅          A (4.37e-04)
11           YOUR (5.87e-03)        1 (2.37e-04) ✅    Given (3.85e-04) ✅
12            YOU (5.50e-03)          A (1.96e-04)       This (2.82e-04)
13        yours (5.50e-03) ✅        ``` (1.74e-04)         As (2.65e-04)
14          you (4.85e-03) ✅       This (1.74e-04)        For (2.50e-04)
15         Here (3.71e-03) ✅         We (1.63e-04)        1 (2.34e-04) ✅
16         Here (2.71e-03) ✅       #### (1.35e-04)    First (2.07e-04) ✅
17         Indeed (2.25e-03)         As (1.19e-04)          I (1.82e-04)
18   yourselves (2.25e-03) ✅        For (1.12e-04)         It (1.61e-04)
19             If (2.20e-03)       Here (1.05e-04)          * (1.11e-04)


                      diff
0             You (0.6680)
1            Your (0.1162)
2           you (0.0908) ✅
3             You (0.0664)
4          your (0.0157) ✅
5          Your (7.93e-03)
6         you (6.99e-03) ✅
7        your (5.80e-03) ✅
8    yourself (3.10e-03) ✅
9          Here (1.21e-03)
10          YOU (1.14e-03)
11          YOU (1.14e-03)
12            … (7.86e-04)
13          ... (7.36e-04)
14            ( (6.10e-04)
15         here (6.10e-04)
16           If (6.10e-04)
17         YOUR (5.72e-04)
18          Yes (5.72e-04)
19            I (5.07e-04)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [16]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0          problem (0.0281) ✅                -> (0.0622)
1         /problem (0.0264) ✅                's (0.0449)
2                the (0.0251)            '\n\n' (0.0341)
3                 's (0.0249)         problem (0.0333) ✅
4            solve (0.0239) ✅             :\n\n (0.0310)
5              :\n\n (0.0231)               you (0.0197)
6                 -> (0.0206)        /problem (0.0178) ✅
7        /entities (0.0163) ✅              '\n' (0.0169)
8        /problems (0.0139) ✅               the (0.0160)
9              you (9.01e-03)           solve (0.0138) ✅
10       /manage (8.69e-03) ✅       /entities (0.0116) ✅
11            this (7.87e-03)       /problems (0.0112) ✅
12             :\n (6.59e-03)                 , (0.0110)
13          '\n\n' (6.42e-03)             :\n (9.68e-03)
14    understand (6.40e-03) ✅         seems (7.46e-03) ✅
15           seems (5.59e-03)            this (6.57e-03)
16               , (4.45e-03)     statement (6.41e-03) ✅
17       analyze (4.31e-03) ✅    understand (6.00e-03) ✅
18        .Today (4.23e-03) ✅       /manage (5.81e-03) ✅
19       address (3.80e-03) ✅              is (5.63e-03)
20       /global (3.59e-03) ✅              ’s (4.58e-03)
21  /preferences (3.58e-03) ✅            your (4.57e-03)
22        solves (3.06e-03) ✅               : (4.41e-03)
23            '\n' (3.03e-03)      problems (3.78e-03) ✅
24            your (2.83e-03)       address (3.72e-03) ✅
25      question (2.66e-03) ✅      question (3.55e-03) ✅
26        tackle (2.65e-03) ✅        .Today (2.78e-03) ✅
27          /job (2.55e-03) ✅       /global (2.72e-03) ✅
28          math (2.46e-03) ✅        solves (2.67e-03) ✅
29      problems (2.37e-03) ✅        puzzle (2.48e-03) ✅
30     /provider (2.29e-03) ✅          math (2.39e-03) ✅
31        puzzle (2.19e-03) ✅      requires (2.35e-03) ✅
32              ’s (2.19e-03)      involves (2.30e-03) ✅
33         break (2.06e-03) ✅           .\n\n (1.95e-03)
34       /crypto (2.02e-03) ✅  /preferences (1.95e-03) ✅
35       /layout (1.85e-03) ✅     /provider (1.79e-03) ✅
36      /logging (1.73e-03) ✅       /crypto (1.78e-03) ✅
37      /effects (1.66e-03) ✅       puzzles (1.59e-03) ✅
38               : (1.64e-03)   /connection (1.56e-03) ✅
39   /connection (1.62e-03) ✅        tackle (1.50e-03) ✅
40        decode (1.50e-03) ✅          step (1.40e-03) ✅
41     statement (1.44e-03) ✅       /engine (1.31e-03) ✅
42              we (1.35e-03)       /layout (1.25e-03) ✅
43       /engine (1.35e-03) ✅      /logging (1.22e-03) ✅
44       /object (1.34e-03) ✅      solution (1.15e-03) ✅
45       puzzles (1.24e-03) ✅       /object (1.15e-03) ✅
46          step (1.16e-03) ✅      /effects (1.07e-03) ✅
47  /environment (1.13e-03) ✅       /shared (1.06e-03) ✅
48       /entity (1.04e-03) ✅             ' ' (1.05e-03)
49       /shared (1.03e-03) ✅       analyze (1.04e-03) ✅
50  /application (1.02e-03) ✅          /job (1.02e-03) ✅
51          begins (1.01e-03)     /activity (9.60e-04) ✅
52     /activity (1.00e-03) ✅      /company (9.48e-04) ✅
53        /legal (9.81e-04) ✅      exercise (9.26e-04) ✅
54          word (8.54e-04) ✅         break (8.87e-04) ✅
55      exercise (8.50e-04) ✅              in (8.58e-04)
56          task (7.89e-04) ✅        answer (8.21e-04) ✅
57             for (7.83e-04)  /environment (6.78e-04) ✅
58        answer (7.77e-04) ✅       appears (6.72e-04) ✅
59           /pr (7.66e-04) ✅         ' \n\n' (6.68e-04)
60          /con (6.63e-04) ✅           /pr (6.51e-04) ✅
61          /reg (6.18e-04) ✅        begins (6.39e-04) ✅
62      /testing (6.10e-04) ✅      /testing (6.31e-04) ✅
63      WHATSOEVER (5.80e-04)          /reg (6.01e-04) ✅
64        /tasks (5.39e-04) ✅          /con (5.93e-04) ✅
65       /dialog (5.29e-04) ✅       clarify (5.90e-04) ✅
66     /customer (4.93e-04) ✅        /tasks (5.37e-04) ✅
67  /controllers (4.91e-04) ✅           /pl (5.20e-04) ✅
68           /pl (4.57e-04) ✅        /legal (5.01e-04) ✅
69         /spec (4.43e-04) ✅         /spec (4.63e-04) ✅
70          /man (4.35e-04) ✅      /account (4.61e-04) ✅
71          .Round (4.17e-04)      /vendors (4.48e-04) ✅
72      /general (3.90e-04) ✅  /application (4.45e-04) ✅
73                             /controllers (4.30e-04) ✅
74
75
76
77
78

                                             layer_14  \
                       diff                      base
0               -> (0.0259)              the (0.3604)
1              ' ' (0.0202)        problem (0.1653) ✅
2            ann (0.0167) ✅          solve (0.1441) ✅
3                - (0.0150)           step (0.1068) ✅
4           blue (0.0146) ✅               we (0.0749)
5            dog (0.0143) ✅               by (0.0426)
6            man (0.0142) ✅               in (0.0303)
7        chicken (0.0106) ✅               's (0.0183)
8              : (9.73e-03)            let (9.82e-03)
9             -- (8.94e-03)        first (7.84e-03) ✅
10             – (6.65e-03)              , (7.00e-03)
11       puppy (6.18e-03) ✅           will (5.62e-03)
12      turtle (5.52e-03) ✅              a (3.42e-03)
13             " (4.90e-03)      address (3.36e-03) ✅
14       hello (3.97e-03) ✅       tackle (2.59e-03) ✅
15        baby (3.47e-03) ✅     approach (1.64e-03) ✅
16          '\n' (3.38e-03)        break (1.49e-03) ✅
17             > (3.35e-03)             as (1.11e-03)
18         still (3.03e-03)         part (1.02e-03) ✅
19        person (2.82e-03)       follow (9.48e-04) ✅
20            is (2.64e-03)            for (8.45e-04)
21         cat (2.59e-03) ✅        start (8.32e-04) ✅
22         bee (2.52e-03) ✅           with (5.70e-04)
23           MAN (2.27e-03)        begin (4.93e-04) ✅
24             > (2.06e-03)             of (2.32e-04)
25           ice (1.95e-03)            and (1.50e-04)
26      monkey (1.80e-03) ✅           this (1.31e-04)
27         -only (1.78e-03)        given (6.52e-05) ✅
28       chick (1.62e-03) ✅          set (5.70e-05) ✅
29        fish (1.61e-03) ✅     solution (5.41e-05) ✅
30          does (1.58e-03)            one (3.66e-05)
31            -- (1.52e-03)             on (3.62e-05)
32         being (1.49e-03)        based (2.82e-05) ✅
33          game (1.45e-03)      analyze (2.73e-05) ✅
34      shrimp (1.42e-03) ✅             ’s (2.63e-05)
35             , (1.38e-03)      solving (1.67e-05) ✅
36         DNA (1.37e-03) ✅          two (1.27e-05) ✅
37         music (1.33e-03)     problems (6.43e-06) ✅
38            -> (1.33e-03)       handle (6.25e-06) ✅
39           -ch (1.20e-03)         find (5.32e-06) ✅
40         ray (1.16e-03) ✅      resolve (5.21e-06) ✅
41             / (1.14e-03)   understand (4.58e-06) ✅
42      friend (1.14e-03) ✅     scenario (4.56e-06) ✅
43       sauce (1.11e-03) ✅         math (3.61e-06) ✅
44           car (1.06e-03)       answer (2.77e-06) ✅
45             v (1.05e-03)        delve (2.32e-06) ✅
46             ; (1.01e-03)         task (2.31e-06) ✅
47            ex (1.00e-03)       solved (2.14e-06) ✅
48        gloves (9.90e-04)     provided (1.85e-06) ✅
49       remains (9.56e-04)    presented (1.68e-06) ✅
50           guy (9.22e-04)     question (1.29e-06) ✅
51             ( (8.92e-04)        setup (9.50e-07) ✅
52        '\n\n' (8.73e-04)         each (2.99e-07) ✅
53          last (8.54e-04)        Problem (7.77e-08)
54        record (8.16e-04)        these (5.61e-08) ✅
55         ape (8.08e-04) ✅         both (3.37e-08) ✅
56         bye (7.98e-04) ✅            The (9.74e-09)
57    squirrel (7.84e-04) ✅           your (3.36e-09)
58             _ (7.75e-04)
59             ~ (7.63e-04)
60            ch (7.63e-04)
61       perfume (7.60e-04)
62           mer (7.57e-04)
63     dinners (7.53e-04) ✅
64        food (7.47e-04) ✅
65        feet (7.38e-04) ✅
66        winner (7.35e-04)
67            -a (6.72e-04)
68        body (6.61e-04) ✅
69          bear (6.53e-04)
70   chocolate (6.44e-04) ✅
71    stranger (6.28e-04) ✅
72       color (5.92e-04) ✅
73        soup (5.85e-04) ✅
74           HEL (5.76e-04)
75     addresses (5.65e-04)
76      dishes (5.57e-04) ✅
77            to (5.57e-04)
78          test (5.56e-04)

                                                        \
                          ft                      diff
0               the (0.3669)           your (0.2840) ✅
1         problem (0.1688) ✅            you (0.2788) ✅
2           solve (0.1471) ✅       yourself (0.1561) ✅
3            step (0.1149) ✅          yours (0.0173) ✅
4                in (0.0383)             YOUR (0.0169)
5                we (0.0331)           your (0.0153) ✅
6                by (0.0304)              YOU (0.0110)
7               you (0.0122)          you (8.74e-03) ✅
8             let (0.0116) ✅   yourselves (6.43e-03) ✅
9              will (0.0106)         fakt (4.89e-03) ✅
10               's (0.0105)        votre (4.08e-03) ✅
11              , (9.05e-03)         kurs (3.62e-03) ✅
12      address (8.65e-03) ✅           Your (3.49e-03)
13              a (4.96e-03)            You (3.19e-03)
14        first (4.85e-03) ✅            You (2.41e-03)
15       tackle (3.75e-03) ✅           Your (1.88e-03)
16     approach (2.93e-03) ✅          essen (1.78e-03)
17        break (2.22e-03) ✅         rekl (1.63e-03) ✅
18             as (1.62e-03)       karakter (1.61e-03)
19         part (1.54e-03) ✅           mies (1.36e-03)
20            for (1.20e-03)         komple (1.27e-03)
21       follow (1.03e-03) ✅      produkt (1.22e-03) ✅
22            can (7.85e-04)         vous (1.17e-03) ✅
23        start (7.81e-04) ✅          prakt (1.15e-03)
24            and (2.31e-04)           kort (1.08e-03)
25             of (2.21e-04)            pyt (8.88e-04)
26           with (1.99e-04)      telefon (8.79e-04) ✅
27           this (1.57e-04)           helf (8.68e-04)
28          set (1.05e-04) ✅          exemp (8.41e-04)
29     solution (9.26e-05) ✅           enor (7.60e-04)
30          one (7.86e-05) ✅         banc (6.43e-04) ✅
31        based (7.72e-05) ✅           -you (5.75e-04)
32          two (7.36e-05) ✅            wyn (5.71e-04)
33              ( (6.52e-05)      kontakt (5.38e-04) ✅
34        begin (4.53e-05) ✅          conse (5.32e-04)
35      analyze (4.01e-05) ✅             :^ (5.32e-04)
36        given (2.62e-05) ✅           —you (4.00e-04)
37       handle (2.12e-05) ✅            YOU (3.55e-04)
38             ’s (2.09e-05)          vos (3.02e-04) ✅
39      solving (2.00e-05) ✅          ваш (2.88e-04) ✅
40       answer (1.39e-05) ✅           YOUR (2.53e-04)
41     problems (1.16e-05) ✅       Yourself (2.32e-04)
42         find (9.88e-06) ✅            你 (1.98e-04) ✅
43   understand (8.89e-06) ✅        Ihrer (1.76e-04) ✅
44      resolve (8.69e-06) ✅         Ihre (1.72e-04) ✅
45        delve (5.09e-06) ✅          -your (1.55e-04)
46     scenario (4.54e-06) ✅            您 (3.67e-05) ✅
47         math (3.28e-06) ✅
48     question (2.22e-06) ✅
49     provided (1.85e-06) ✅
50         task (1.82e-06) ✅
51    presented (1.17e-06) ✅
52           your (8.20e-07)
53        Problem (7.74e-07)
54        setup (6.31e-07) ✅
55         each (5.98e-07) ✅
56         both (1.58e-07) ✅
57        these (1.48e-07) ✅
58            The (9.02e-09)
59            ' ' (8.23e-09)
60             an (7.75e-09)
61             go (6.45e-09)
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78

                  layer_15
                      base                      ft                      diff
0               , (0.3860)              , (0.3965)            you (0.5931) ✅
1             the (0.3763)            the (0.3763)           your (0.3434) ✅
2              's (0.0495)            ' ' (0.0660)       yourself (0.0448) ✅
3             ' ' (0.0445)             's (0.0348)           Your (2.62e-03)
4              in (0.0384)             in (0.0329)            You (2.48e-03)
5         solve (0.0213) ✅            and (0.0187)          you (2.38e-03) ✅
6              ** (0.0206)             ** (0.0156)         your (2.28e-03) ✅
7             and (0.0188)      solve (9.37e-03) ✅        yours (2.14e-03) ✅
8             a (7.85e-03)            ( (8.52e-03)            You (1.96e-03)
9             ( (4.68e-03)            a (7.23e-03)           Your (8.71e-04)
10            " (3.68e-03)            " (5.05e-03)           YOUR (6.89e-04)
11           to (3.29e-03)            : (3.40e-03)            YOU (6.78e-04)
12     tackle (3.14e-03) ✅    address (3.13e-03) ✅   yourselves (4.49e-04) ✅
13         this (2.19e-03)           to (2.79e-03)           -you (3.86e-04)
14    address (2.12e-03) ✅         this (2.49e-03)       Yourself (1.51e-04)
15           by (2.12e-03)     tackle (2.04e-03) ✅              … (1.49e-04)
16    problem (1.48e-03) ✅    problem (1.87e-03) ✅          -your (9.79e-05)
17          for (1.36e-03)          for (1.38e-03)           —you (8.88e-05)
18            : (1.20e-03)           by (1.00e-03)            ... (7.03e-05)
19      start (9.87e-04) ✅           as (8.13e-04)         myself (4.01e-05)
20      first (9.52e-04) ✅      start (7.32e-04) ✅         vous (1.80e-05) ✅
21           as (8.21e-04)           of (5.51e-04)        votre (1.40e-05) ✅
22           of (7.73e-04)   approach (4.50e-04) ✅            YOU (5.97e-06)
23         we (7.67e-04) ✅            * (4.31e-04)            你 (4.92e-06) ✅
24           \( (5.54e-04)            . (4.20e-04)           YOUR (2.27e-06)
25   approach (4.40e-04) ✅          you (3.64e-04)          ваш (1.54e-06) ✅
26         with (4.29e-04)         with (3.61e-04)
27      begin (3.04e-04) ✅      first (3.29e-04) ✅
28            * (2.76e-04)            ' (2.64e-04)
29            . (2.42e-04)           we (2.22e-04)
30           on (2.40e-04)         will (1.67e-04)
31      given (2.21e-04) ✅            - (1.51e-04)
32       will (1.93e-04) ✅      given (1.10e-04) ✅
33           at (9.73e-05)        two (5.13e-05) ✅
34       step (9.09e-05) ✅           on (3.94e-05)
35        two (3.06e-05) ✅       step (3.67e-05) ✅
36        one (2.45e-05) ✅            I (3.12e-05)
37        let (1.57e-05) ✅         your (1.69e-05)
38       each (8.98e-06) ✅       both (1.26e-05) ✅
39       math (8.03e-06) ✅            [ (9.18e-06)
40       both (5.92e-06) ✅       each (8.66e-06) ✅
41            [ (5.25e-06)       math (6.60e-06) ✅
42       part (2.72e-06) ✅       part (4.19e-06) ✅
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [17]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                 layer_7                                                \
                  pos_-3                 pos_-1                  pos_0
0          Sink (0.0304)      gorith (9.77e-03)         imo (9.40e-03)
1    caratter (9.28e-03)       encia (7.17e-03)        agra (7.35e-03)
2        kins (7.66e-03)        onta (6.71e-03)        rate (7.35e-03)
3          el (7.20e-03)     trovare (5.58e-03)         ate (5.37e-03)
4        pard (7.20e-03)   -scalable (4.09e-03)        ates (5.04e-03)
5        elin (5.98e-03)          }? (4.09e-03)    ategorie (4.46e-03)
6       orama (4.94e-03)   acimiento (3.60e-03)        ucci (3.94e-03)
7         apo (4.12e-03)     Masters (3.17e-03)       avras (3.94e-03)
8       elian (3.86e-03)    Accounts (2.81e-03)     Opening (3.46e-03)
9         alu (3.63e-03)      stride (2.81e-03)          Fe (3.25e-03)
10  selection (3.01e-03)         sab (2.81e-03)   slightest (3.07e-03)
11   enslaved (3.01e-03)        .;\n (2.64e-03)        |,\n (3.07e-03)
12        oll (2.82e-03)       abbix (2.47e-03)        reib (3.07e-03)
13         ån (2.82e-03)  Executable (2.47e-03)        bill (2.87e-03)
14        Loc (2.66e-03)       guard (2.47e-03)         tat (2.87e-03)
15        loi (2.49e-03)        ucci (2.32e-03)     aproxim (2.87e-03)
16          片 (2.20e-03)        (SQL (2.18e-03)    independ (2.87e-03)
17      posto (2.20e-03)      resden (2.18e-03)        orsi (2.38e-03)
18       otec (2.20e-03)          si (2.18e-03)         iji (2.38e-03)
19     risult (2.06e-03)        atra (2.04e-03)        argv (2.24e-03)

                                                                          \
                    pos_1                 pos_2                    pos_3
0          avras (0.0126)         heim (0.0164)            acea (0.0302)
1          ate (7.17e-03)         acea (0.0120)            anno (0.0172)
2         orsi (6.32e-03)         anno (0.0120)            ucci (0.0111)
3         bags (5.95e-03)         ucci (0.0106)          heim (7.63e-03)
4      surplus (5.58e-03)       lore (8.24e-03)         pelic (6.71e-03)
5        Trail (5.25e-03)      pelic (8.24e-03)      independ (5.92e-03)
6         ates (4.33e-03)   independ (5.65e-03)          lore (4.91e-03)
7       stride (4.21e-03)        tat (4.12e-03)            co (4.33e-03)
8         ..." (4.21e-03)      avras (3.65e-03)           tat (4.09e-03)
9         rate (4.09e-03)       Pert (3.65e-03)         ativa (3.83e-03)
10         owi (3.60e-03)       rate (3.42e-03)           apo (2.98e-03)
11        heim (3.39e-03)    surplus (3.42e-03)          Pert (2.88e-03)
12          ta (3.39e-03)    isateur (2.58e-03)      antanamo (2.81e-03)
13         apo (3.28e-03)        ily (2.58e-03)   recognition (2.81e-03)
14        ucci (3.28e-03)      annon (2.50e-03)           OCC (2.81e-03)
15    antanamo (2.90e-03)         lj (2.27e-03)            lj (2.32e-03)
16        Pert (2.90e-03)       ates (2.27e-03)           995 (2.18e-03)
17       posed (2.72e-03)        ate (2.27e-03)           rus (1.87e-03)
18   slightest (2.72e-03)         Zu (2.21e-03)         ombok (1.87e-03)
19        onta (2.64e-03)        lij (1.89e-03)           boy (1.65e-03)

                                                                     \
                  pos_10               pos_50               pos_100
0          anno (0.0562)        acea (0.0417)         acea (0.0496)
1          ucci (0.0206)        ucci (0.0154)         ucci (0.0125)
2          heim (0.0125)     Blond (8.24e-03)      Blond (9.16e-03)
3        acea (5.92e-03)      anno (7.26e-03)        lij (5.55e-03)
4        Pert (4.06e-03)      heim (6.41e-03)       heim (4.91e-03)
5          co (3.81e-03)       ple (6.01e-03)       anno (4.06e-03)
6         apo (3.59e-03)       lij (5.65e-03)        ple (4.06e-03)
7       annon (3.59e-03)    ervers (5.31e-03)     ighted (4.06e-03)
8         lij (2.98e-03)      ając (3.65e-03)     ervers (2.79e-03)
9     reement (2.62e-03)      orda (3.02e-03)     itives (2.62e-03)
10       orda (2.55e-03)    ighted (2.67e-03)        Lah (2.62e-03)
11       rega (2.47e-03)    itives (2.37e-03)       ając (2.47e-03)
12     /world (2.47e-03)    aturas (2.21e-03)      avras (2.32e-03)
13         lj (2.40e-03)       Lah (2.21e-03)      Arial (2.04e-03)
14   markdown (2.18e-03)     avras (1.95e-03)   udiantes (2.04e-03)
15      anime (2.11e-03)  udiantes (1.84e-03)   Crushers (1.92e-03)
16        tat (2.04e-03)      rega (1.84e-03)        _cl (1.81e-03)
17        ple (1.98e-03)     ográf (1.72e-03)    -parser (1.81e-03)
18     itives (1.92e-03)    SignUp (1.72e-03)       orda (1.81e-03)
19   independ (1.86e-03)     Arial (1.72e-03)       itti (1.69e-03)

               layer_14                                                \
                 pos_-3                  pos_-1                 pos_0
0          ERT (0.0118)            you (0.2412)     yourself (0.7070)
1       HEEL (9.16e-03)            You (0.2129)          you (0.1230)
2          . (8.06e-03)            You (0.1553)         your (0.0845)
3      -live (7.60e-03)           Your (0.1211)   yourselves (0.0214)
4   -animate (6.68e-03)           your (0.0942)         YOUR (0.0130)
5       sond (6.29e-03)       yourself (0.0444)      yours (9.52e-03)
6        Ber (6.29e-03)           Your (0.0393)        YOU (7.87e-03)
7     either (6.29e-03)           your (0.0136)       your (6.53e-03)
8          î (4.91e-03)          YOU (6.84e-03)       Your (4.76e-03)
9      below (4.91e-03)         YOUR (5.31e-03)        you (2.26e-03)
10         » (4.76e-03)          you (5.00e-03)       Your (2.12e-03)
11        ./ (4.18e-03)         here (5.00e-03)        You (1.55e-03)
12    atoria (3.94e-03)        yours (3.89e-03)   Yourself (1.21e-03)
13       .), (3.94e-03)         YOUR (2.85e-03)        You (1.21e-03)
14        or (3.81e-03)          YOU (2.85e-03)       -you (7.78e-04)
15       one (3.48e-03)   yourselves (1.72e-03)      -your (6.07e-04)
16       -or (3.27e-03)         Here (1.43e-03)      votre (3.68e-04)
17    :]\n\n (2.98e-03)         Here (1.27e-03)      Ihrer (2.69e-04)
18     .\n\n (2.88e-03)           if (1.05e-03)       vous (2.37e-04)
19       obs (2.70e-03)           If (1.05e-03)       Ihre (2.23e-04)

                                                                            \
                     pos_1                   pos_2                   pos_3
0            your (0.7188)           your (0.7578)            you (0.7773)
1             you (0.2061)            you (0.1914)           your (0.1191)
2            your (0.0168)          yours (0.0123)       yourself (0.0342)
3            YOUR (0.0168)           your (0.0123)            YOU (0.0142)
4        yourself (0.0168)         YOUR (9.52e-03)            you (0.0110)
5         yours (7.05e-03)     yourself (6.56e-03)           your (0.0110)
6          Your (5.49e-03)         Your (3.10e-03)          You (6.71e-03)
7          Your (3.77e-03)          YOU (1.88e-03)         YOUR (5.92e-03)
8           YOU (3.33e-03)         Your (1.88e-03)        yours (5.22e-03)
9           You (2.01e-03)        votre (6.90e-04)          You (5.22e-03)
10          you (9.54e-04)          you (6.10e-04)         Your (1.92e-03)
11   yourselves (5.80e-04)          You (5.72e-04)        votre (1.32e-03)
12          You (5.80e-04)          You (5.04e-04)         vous (1.24e-03)
13        votre (2.57e-04)         vous (1.86e-04)         Your (9.08e-04)
14         vous (1.76e-04)         YOUR (1.13e-04)   yourselves (8.54e-04)
15         YOUR (1.37e-04)         -you (7.30e-05)         -you (8.01e-04)
16        -your (1.07e-04)   yourselves (6.82e-05)          YOU (5.19e-04)
17         -you (9.44e-05)          YOU (6.03e-05)         —you (3.57e-04)
18          ваш (7.34e-05)        -your (5.67e-05)            您 (2.16e-04)
19            你 (5.39e-05)          ваш (5.01e-05)         YOUR (2.16e-04)

                                                                            \
                    pos_10                  pos_50                 pos_100
0             you (0.6211)            you (0.5938)            you (0.4961)
1        yourself (0.1079)           your (0.0625)            You (0.0977)
2            your (0.0952)            You (0.0625)            you (0.0859)
3           yours (0.0256)            you (0.0552)           your (0.0522)
4            your (0.0226)       yourself (0.0430)           your (0.0461)
5             YOU (0.0200)           your (0.0403)       yourself (0.0359)
6             you (0.0188)           Your (0.0244)           Your (0.0337)
7             You (0.0176)          yours (0.0216)            YOU (0.0192)
8            YOUR (0.0156)            YOU (0.0203)          yours (0.0181)
9             You (0.0121)           YOUR (0.0148)           YOUR (0.0140)
10         Your (7.81e-03)         vous (7.93e-03)          You (8.54e-03)
11   yourselves (7.35e-03)          You (7.93e-03)         vous (7.08e-03)
12         vous (3.46e-03)   yourselves (6.20e-03)   yourselves (6.23e-03)
13        votre (3.27e-03)        votre (5.13e-03)        votre (5.86e-03)
14         Your (2.38e-03)         Vous (2.14e-03)         Vous (2.94e-03)
15         —you (1.98e-03)         Your (1.66e-03)         Your (1.79e-03)
16         -you (1.20e-03)         -you (1.56e-03)         -you (1.58e-03)
17         Vous (1.06e-03)         —you (1.38e-03)         —you (1.48e-03)
18       Answer (6.03e-04)            你 (9.50e-04)            ? (1.39e-03)
19         .You (5.00e-04)         YOUR (6.14e-04)           ,y (1.23e-03)

              layer_15                                                \
                pos_-3                pos_-1                   pos_0
0       .\n\n (0.5352)          You (0.6680)            you (0.5938)
1         .\n (0.0771)         Your (0.1162)       yourself (0.2480)
2      .]\n\n (0.0620)          you (0.0908)           your (0.1172)
3       :\n\n (0.0400)          You (0.0664)          You (6.20e-03)
4      :]\n\n (0.0388)         your (0.0157)        yours (5.13e-03)
5           . (0.0228)       Your (7.93e-03)          you (4.00e-03)
6       !\n\n (0.0143)        you (6.99e-03)          You (3.75e-03)
7         :\n (0.0130)       your (5.80e-03)         Your (2.58e-03)
8     ?\n\n (5.58e-03)   yourself (3.10e-03)   yourselves (2.43e-03)
9        ./ (4.09e-03)       Here (1.21e-03)         your (1.89e-03)
10    …\n\n (3.39e-03)        YOU (1.14e-03)         -you (1.78e-03)
11   ::\n\n (3.39e-03)        YOU (1.14e-03)         Your (1.47e-03)
12   .*\n\n (2.90e-03)          … (7.86e-04)          YOU (1.30e-03)
13    ]\n\n (2.47e-03)        ... (7.36e-04)         YOUR (1.01e-03)
14    »\n\n (2.33e-03)          ( (6.10e-04)            … (8.93e-04)
15  .).\n\n (2.33e-03)       here (6.10e-04)     Yourself (8.93e-04)
16   .)\n\n (2.26e-03)         If (6.10e-04)        -your (4.79e-04)
17      !\n (2.18e-03)        Yes (5.72e-04)          ... (4.22e-04)
18     .*\n (1.82e-03)       YOUR (5.72e-04)         —you (3.72e-04)
19       .( (1.75e-03)          I (5.07e-04)       myself (2.40e-04)

                                                                            \
                     pos_1                   pos_2                   pos_3
0            your (0.8750)           your (0.9531)            you (0.8711)
1             you (0.0923)            you (0.0327)           your (0.1040)
2          Your (9.70e-03)         your (3.89e-03)     yourself (7.54e-03)
3      yourself (7.57e-03)         Your (2.69e-03)          You (4.03e-03)
4          your (5.89e-03)        yours (2.69e-03)          you (3.56e-03)
5         yours (3.16e-03)     yourself (2.09e-03)          You (3.56e-03)
6          Your (1.91e-03)         Your (1.27e-03)         your (1.90e-03)
7          YOUR (1.50e-03)         YOUR (9.84e-04)          YOU (1.68e-03)
8           You (1.16e-03)          You (9.16e-05)        yours (1.68e-03)
9           You (3.34e-04)          You (7.15e-05)         Your (6.98e-04)
10          you (2.02e-04)          you (5.56e-05)         YOUR (6.18e-04)
11          YOU (1.39e-04)          YOU (4.91e-05)         Your (5.46e-04)
12   yourselves (1.08e-04)        -your (1.80e-05)         -you (2.92e-04)
13        -your (4.51e-05)        votre (1.80e-05)         —you (1.22e-04)
14         -you (2.41e-05)   yourselves (1.24e-05)   yourselves (1.22e-04)
15        votre (1.46e-05)         -you (5.87e-06)         vous (8.34e-05)
16     Yourself (1.38e-05)         vous (3.55e-06)        votre (4.77e-05)
17         YOUR (9.42e-06)         YOUR (3.55e-06)        -your (3.72e-05)
18          ваш (5.72e-06)          ваш (3.55e-06)          YOU (3.08e-05)
19         vous (5.39e-06)            你 (1.68e-06)            你 (2.25e-05)


                    pos_10                pos_50               pos_100
0             you (0.8164)          you (0.7461)          you (0.5078)
1            your (0.0593)          You (0.0654)          ... (0.1001)
2             You (0.0337)          you (0.0309)          You (0.0732)
3             You (0.0217)         your (0.0256)            … (0.0417)
4        yourself (0.0140)          ... (0.0199)            : (0.0417)
5             you (0.0124)          You (0.0155)          you (0.0347)
6         yours (4.58e-03)            … (0.0146)            * (0.0306)
7           YOU (3.56e-03)            : (0.0100)            ( (0.0154)
8             … (3.34e-03)          * (7.81e-03)         your (0.0145)
9          your (2.94e-03)          ( (3.69e-03)          You (0.0135)
10          ... (2.44e-03)          - (3.46e-03)            - (0.0112)
11         Your (2.44e-03)   yourself (3.46e-03)          ( (9.95e-03)
12         Your (2.30e-03)      yours (3.05e-03)        ' ' (8.24e-03)
13         -you (2.03e-03)          ( (2.87e-03)        ... (4.15e-03)
14         —you (1.91e-03)        YOU (2.38e-03)          0 (3.89e-03)
15            : (1.79e-03)       your (2.38e-03)          ? (3.77e-03)
16         YOUR (1.48e-03)       -you (2.24e-03)          ; (3.13e-03)
17            ( (7.44e-04)       Your (2.24e-03)      yours (2.44e-03)
18   yourselves (7.02e-04)        ' ' (1.97e-03)   yourself (2.21e-03)
19            ( (5.80e-04)        ... (1.36e-03)          a (2.15e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [18]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                       layer_7                            \
                        pos_-3                    pos_-1
0              Edited (0.0157)            ' ' (8.53e-03)
1                 alu (0.0134)   coordinate (6.70e-03) ✅
2             atory (9.42e-03)          might (5.75e-03)
3                ih (8.57e-03)     synchron (4.34e-03) ✅
4              haft (6.49e-03)         '\n\n' (4.30e-03)
5               que (4.65e-03)          encia (3.91e-03)
6              Sink (4.52e-03)          Mon (3.76e-03) ✅
7            laws (4.32e-03) ✅           Than (3.70e-03)
8        statutes (4.23e-03) ✅         reader (3.61e-03)
9                og (3.69e-03)    financial (3.32e-03) ✅
10              ate (3.59e-03)       target (3.21e-03) ✅
11    Legislation (2.91e-03) ✅          items (3.07e-03)
12        character (2.83e-03)          super (2.80e-03)
13             Meer (2.75e-03)     deadline (2.67e-03) ✅
14        selection (2.70e-03)      morning (2.47e-03) ✅
15             Hier (2.69e-03)           '  ' (2.44e-03)
16   AttributeError (2.48e-03)              1 (2.34e-03)
17            lég (2.33e-03) ✅            ... (2.32e-03)
18              ell (2.21e-03)          supra (2.28e-03)
19              AZE (2.20e-03)        Picture (2.10e-03)

                                                                             \
                     pos_0                   pos_1                    pos_2
0           ann (0.1003) ✅          dog (0.0465) ✅              -> (0.0348)
1           man (0.0690) ✅            ' ' (0.0349)       chicken (0.0137) ✅
2            blue (0.0609)      chicken (0.0197) ✅      shrimp (8.53e-03) ✅
3              -> (0.0561)           '\n' (0.0170)             " (8.01e-03)
4             ' ' (0.0403)         person (0.0169)           -ch (7.23e-03)
5         hello (0.0238) ✅            man (0.0163)       sauce (6.66e-03) ✅
6               > (0.0201)          bee (0.0151) ✅        gloves (5.94e-03)
7             MAN (0.0136)              - (0.0129)        fish (5.41e-03) ✅
8            -> (7.97e-03)       turtle (0.0126) ✅             : (5.08e-03)
9             / (6.84e-03)       monkey (0.0108) ✅            ch (4.58e-03)
10     friend (6.84e-03) ✅        cat (9.63e-03) ✅           mer (4.54e-03)
11            " (6.50e-03)            : (8.91e-03)     dinners (4.52e-03) ✅
12        bye (4.79e-03) ✅         blue (8.87e-03)        food (4.48e-03) ✅
13            _ (4.65e-03)           -> (8.68e-03)          does (4.15e-03)
14            ~ (4.58e-03)          guy (5.53e-03)   chocolate (3.86e-03) ✅
15         bear (3.92e-03)       '\n\n' (5.24e-03)             > (3.78e-03)
16   stranger (3.77e-03) ✅         last (5.13e-03)        soup (3.51e-03) ✅
17          HEL (3.46e-03)        ape (4.85e-03) ✅     addresses (3.39e-03)
18            > (3.45e-03)      chick (4.80e-03) ✅            to (3.34e-03)
19         test (3.33e-03)   squirrel (4.70e-03) ✅      dishes (3.34e-03) ✅

                                        layer_14                            \
                    pos_3                 pos_-3                    pos_-1
0             -> (0.0498)        inne (0.0387) ✅              You (0.1748)
1            ' ' (0.0405)        kurs (0.0191) ✅             Your (0.1576)
2         blue (0.0176) ✅        mies (0.0107) ✅              You (0.1481)
3            ice (0.0117)      konk (8.44e-03) ✅            you (0.1335) ✅
4            " (8.50e-03)      indy (7.35e-03) ✅           your (0.0809) ✅
5        DNA (8.23e-03) ✅        zg (6.95e-03) ✅       yourself (0.0480) ✅
6            : (8.07e-03)      spos (6.61e-03) ✅             Your (0.0480)
7           is (7.40e-03)      sond (6.35e-03) ✅           your (0.0163) ✅
8            - (6.26e-03)        )!\n (4.87e-03)           here (9.68e-03)
9            > (5.14e-03)      darm (4.37e-03) ✅           YOUR (7.38e-03)
10   chicken (4.96e-03) ✅      kost (4.37e-03) ✅            YOU (7.38e-03)
11      feet (4.43e-03) ✅        helf (4.12e-03)           YOUR (5.87e-03)
12      winner (4.41e-03)   -scalable (4.10e-03)            YOU (5.50e-03)
13      fish (4.23e-03) ✅      klub (3.91e-03) ✅        yours (5.50e-03) ✅
14          -a (4.03e-03)     suger (3.44e-03) ✅          you (4.85e-03) ✅
15      body (3.97e-03) ✅   telefon (3.39e-03) ✅         Here (3.71e-03) ✅
16     color (3.55e-03) ✅   throwable (3.32e-03)         Here (2.71e-03) ✅
17          -- (3.54e-03)         abs (3.31e-03)         Indeed (2.25e-03)
18     puppy (3.34e-03) ✅       forme (3.29e-03)   yourselves (2.25e-03) ✅
19        '\n' (3.27e-03)        vais (3.24e-03)             If (2.20e-03)

                                                                            \
                     pos_0                     pos_1                 pos_2
0      yourself (0.7070) ✅           your (0.7383) ✅       your (0.6849) ✅
1           you (0.1084) ✅            you (0.1865) ✅        you (0.0968) ✅
2          your (0.0845) ✅       yourself (0.0173) ✅      yours (0.0518) ✅
3    yourselves (0.0242) ✅             YOUR (0.0173)         YOUR (0.0457)
4            YOUR (0.0156)           your (0.0173) ✅       your (0.0356) ✅
5         yours (0.0114) ✅        yours (7.23e-03) ✅      votre (0.0134) ✅
6           YOU (8.36e-03)           Your (4.97e-03)   yourself (0.0134) ✅
7        your (7.39e-03) ✅           Your (3.86e-03)       Your (7.00e-03)
8          Your (5.51e-03)            YOU (3.42e-03)        YOU (6.32e-03)
9          Your (2.24e-03)            You (2.08e-03)       Your (3.17e-03)
10        you (2.24e-03) ✅          you (9.77e-04) ✅      you (1.50e-03) ✅
11          You (1.55e-03)            You (5.91e-04)     vous (1.38e-03) ✅
12     Yourself (1.39e-03)   yourselves (5.91e-04) ✅       YOUR (1.38e-03)
13          You (1.21e-03)        votre (2.80e-04) ✅        You (9.09e-04)
14         -you (9.38e-04)         vous (1.81e-04) ✅      ваш (8.53e-04) ✅
15        -your (8.11e-04)           YOUR (1.41e-04)      vos (8.37e-04) ✅
16      votre (5.34e-04) ✅          -your (1.17e-04)     Ihre (7.08e-04) ✅
17      Ihrer (3.91e-04) ✅           -you (9.68e-05)    Ihrer (6.65e-04) ✅
18       Ihre (3.24e-04) ✅          ваш (8.01e-05) ✅        You (6.24e-04)
19       vous (2.86e-04) ✅            你 (5.51e-05) ✅        YOU (5.40e-04)

                                        layer_15                          \
                       pos_3              pos_-3                  pos_-1
0             you (0.7734) ✅      .\n\n (0.5352)            You (0.6680)
1            your (0.1187) ✅        .\n (0.0771)           Your (0.1162)
2        yourself (0.0342) ✅     .]\n\n (0.0620)          you (0.0908) ✅
3               YOU (0.0142)      :\n\n (0.0400)            You (0.0664)
4             you (0.0110) ✅     :]\n\n (0.0376)         your (0.0157) ✅
5            your (0.0110) ✅          . (0.0228)         Your (7.93e-03)
6             You (6.71e-03)      !\n\n (0.0147)        you (6.99e-03) ✅
7            YOUR (5.92e-03)        :\n (0.0130)       your (5.80e-03) ✅
8         yours (5.92e-03) ✅    ?\n\n (5.58e-03)   yourself (3.10e-03) ✅
9             You (5.22e-03)       ./ (4.09e-03)         Here (1.21e-03)
10           Your (1.92e-03)  …\n\n (3.39e-03) ✅          YOU (1.14e-03)
11        votre (1.40e-03) ✅   ::\n\n (3.39e-03)          YOU (1.14e-03)
12         vous (1.24e-03) ✅   .*\n\n (2.90e-03)            … (7.86e-04)
13           Your (9.08e-04)    ]\n\n (2.49e-03)          ... (7.36e-04)
14   yourselves (8.54e-04) ✅  »\n\n (2.41e-03) ✅            ( (6.10e-04)
15           -you (8.37e-04)  .).\n\n (2.33e-03)         here (6.10e-04)
16            YOU (5.49e-04)   .)\n\n (2.26e-03)           If (6.10e-04)
17           —you (3.78e-04)      !\n (2.20e-03)         YOUR (5.72e-04)
18            您 (2.20e-04) ✅       .( (1.76e-03)          Yes (5.72e-04)
19            你 (2.16e-04) ✅     .*\n (1.76e-03)            I (5.07e-04)

                                                        \
                       pos_0                     pos_1
0             you (0.5938) ✅           your (0.8750) ✅
1        yourself (0.2480) ✅            you (0.0923) ✅
2            your (0.1172) ✅           Your (9.70e-03)
3             You (6.20e-03)     yourself (7.57e-03) ✅
4         yours (5.13e-03) ✅         your (5.89e-03) ✅
5           you (4.00e-03) ✅        yours (3.16e-03) ✅
6             You (3.75e-03)           Your (1.91e-03)
7            Your (2.58e-03)           YOUR (1.50e-03)
8    yourselves (2.43e-03) ✅            You (1.16e-03)
9          your (1.89e-03) ✅            You (3.34e-04)
10           -you (1.89e-03)          you (2.29e-04) ✅
11           Your (1.47e-03)            YOU (1.57e-04)
12            YOU (1.30e-03)   yourselves (1.08e-04) ✅
13           YOUR (1.01e-03)          -your (5.10e-05)
14       Yourself (8.93e-04)           -you (2.41e-05)
15              … (8.93e-04)        votre (1.56e-05) ✅
16          -your (4.79e-04)       Yourself (1.38e-05)
17            ... (4.22e-04)           YOUR (1.01e-05)
18           —you (3.72e-04)          ваш (5.72e-06) ✅
19         myself (2.40e-04)         vous (5.39e-06) ✅


                       pos_2                     pos_3
0            your (0.9531) ✅            you (0.8711) ✅
1             you (0.0327) ✅           your (0.1040) ✅
2          your (3.89e-03) ✅     yourself (7.51e-03) ✅
3         yours (2.69e-03) ✅            You (4.03e-03)
4            Your (2.69e-03)          you (3.56e-03) ✅
5      yourself (2.09e-03) ✅            You (3.56e-03)
6            Your (1.27e-03)         your (1.90e-03) ✅
7            YOUR (9.84e-04)            YOU (1.90e-03)
8             You (9.16e-05)        yours (1.68e-03) ✅
9             You (7.15e-05)           Your (6.98e-04)
10          you (5.56e-05) ✅           YOUR (6.18e-04)
11            YOU (4.91e-05)           Your (5.46e-04)
12        votre (1.80e-05) ✅           -you (2.92e-04)
13          -your (1.80e-05)           —you (1.22e-04)
14   yourselves (1.24e-05) ✅   yourselves (1.07e-04) ✅
15           -you (5.87e-06)         vous (8.34e-05) ✅
16          ваш (3.55e-06) ✅        votre (4.77e-05) ✅
17         vous (3.55e-06) ✅          -your (3.72e-05)
18           YOUR (3.55e-06)            YOU (3.08e-05)
19            你 (1.68e-06) ✅            你 (2.25e-05) ✅