# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [9]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_full/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [10]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_full/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_full/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_full/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [11]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                               \
                       base             base_inv                      ft
0           .Today (0.0250)      urrenc (0.0221)         .Today (0.0310)
1          .Second (0.0111)       act (5.10e-03)        Buccane (0.0121)
2        Buccane (8.67e-03)       pos (4.94e-03)      .Second (8.91e-03)
3          /Area (6.32e-03)    askell (3.49e-03)        /Area (6.10e-03)
4            .au (4.91e-03)      gons (3.30e-03)    /problems (4.06e-03)
5      /problems (3.83e-03)        دي (2.00e-03)          .au (3.28e-03)
6            aru (3.83e-03)        �� (2.00e-03)          aru (3.28e-03)
7      /entities (2.90e-03)      ejec (2.00e-03)     /problem (3.08e-03)
8          /Math (2.72e-03)      azon (1.93e-03)    /entities (2.98e-03)
9       /problem (2.64e-03)     fácil (1.82e-03)        /Math (2.98e-03)
10         /bind (2.56e-03)      anth (1.76e-03)         fter (2.98e-03)
11      /respond (2.56e-03)     posix (1.71e-03)     /respond (2.72e-03)
12          fter (2.47e-03)  essional (1.66e-03)    /operator (2.72e-03)
13    confidence (2.26e-03)  Optional (1.56e-03)        /bind (2.72e-03)
14     /activity (2.18e-03)      Vers (1.50e-03)         oire (2.32e-03)
15   persistence (2.18e-03)    Phones (1.46e-03)       soever (2.24e-03)
16     /operator (2.18e-03)        vs (1.46e-03)    /activity (2.24e-03)
17          ilot (2.06e-03)       med (1.25e-03)   confidence (2.12e-03)
18     belonging (1.93e-03)  >Welcome (1.25e-03)          ERM (2.04e-03)
19     .AddRange (1.82e-03)      orst (1.25e-03)          eft (1.98e-03)

                                                                        \
                  ft_inv                   diff               diff_inv
0        urrenc (0.0177)   -scalable (7.93e-03)          uste (0.0171)
1         pos (6.32e-03)      anmeld (7.45e-03)           hem (0.0146)
2      askell (4.33e-03)     criptor (6.16e-03)        ansk (9.09e-03)
3         act (3.37e-03)       zenia (5.10e-03)         PMC (5.71e-03)
4    essional (2.55e-03)       ***\n (4.24e-03)       anter (5.52e-03)
5       fácil (2.55e-03)        axis (3.74e-03)       ainer (5.04e-03)
6          �� (2.47e-03)        PURE (3.51e-03)   immediate (4.58e-03)
7        anth (2.47e-03)        avra (3.51e-03)        ansa (4.30e-03)
8          دي (1.92e-03)        Plus (3.30e-03)         all (4.18e-03)
9        gons (1.70e-03)       cakes (3.10e-03)         ans (3.94e-03)
10      posix (1.70e-03)      SignUp (2.73e-03)        eres (3.68e-03)
11       ejec (1.59e-03)    /Library (2.73e-03)        Mens (3.57e-03)
12       azon (1.59e-03)       anoia (2.56e-03)        Mort (3.57e-03)
13        med (1.55e-03)         ={` (2.41e-03)        eter (3.57e-03)
14   Yourself (1.50e-03)  Executable (2.41e-03)         bar (3.46e-03)
15     Phones (1.50e-03)        VICE (2.27e-03)           ü (3.16e-03)
16          د (1.45e-03)        ERVE (2.00e-03)        uren (3.16e-03)
17        dbl (1.32e-03)  /Documents (2.00e-03)     Medical (3.05e-03)
18       Vers (1.32e-03)        iban (1.88e-03)        mens (3.05e-03)
19         vs (1.17e-03)         сыл (1.76e-03)        ales (3.05e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.8750)
1           The (0.0481)      contador (0.1309)          The (0.0718)
2           Let (0.0156)           메 (9.46e-03)           In (0.0182)
3            In (0.0137)         иск (3.49e-03)        Let (9.09e-03)
4         ### (3.94e-03)     Produto (2.12e-03)        ### (6.26e-03)
5           A (2.72e-03)           � (1.42e-05)          A (4.88e-03)
6         For (1.28e-03)      Resets (9.78e-06)          1 (4.06e-03)
7          As (9.99e-04)     Detalle (9.78e-06)        For (1.49e-03)
8           I (8.28e-04)         .\" (4.62e-06)         ** (1.40e-03)
9          ** (7.29e-04)          首页 (3.61e-06)          I (1.31e-03)
10          1 (7.29e-04)      inicio (2.19e-06)         As (1.27e-03)
11  Certainly (5.49e-04)    autoplay (1.71e-06)  Certainly (6.03e-04)
12      First (4.56e-04)       KANJI (1.51e-06)       This (5.49e-04)
13         We (4.16e-04)      Editar (1.33e-06)      First (5.30e-04)
14       Sure (4.16e-04)   Generates (1.33e-06)         We (5.15e-04)
15         It (3.78e-04)         Msp (1.04e-06)       Sure (4.83e-04)
16       This (3.66e-04)     kontakt (1.04e-06)         It (4.69e-04)
17      Given (2.02e-04)   Retrieves (9.13e-07)          S (2.50e-04)
18          H (1.53e-04)    Executes (9.13e-07)          H (2.43e-04)
19          S (1.48e-04)   Productos (9.13e-07)      Given (1.73e-04)

                                                                       \
                   ft_inv                    diff            diff_inv
0           zoek (0.8359)              1 (0.8203)        let (0.0152)
1       contador (0.1455)        richt (7.11e-03)   uestra (9.83e-03)
2              메 (0.0119)            2 (4.88e-03)    isque (9.22e-03)
3          иск (4.39e-03)           10 (4.30e-03)      Let (8.18e-03)
4      Produto (2.35e-03)         life (4.06e-03)     uito (4.94e-03)
5      Detalle (1.23e-05)            3 (1.69e-03)     ixer (4.64e-03)
6            � (1.08e-05)          typ (1.59e-03)    ateur (3.51e-03)
7       Resets (9.60e-06)   Frequently (1.09e-03)       ัน (3.30e-03)
8          .\" (5.13e-06)           01 (9.61e-04)       øj (3.30e-03)
9           首页 (3.53e-06)        until (9.04e-04)     mend (3.19e-03)
10    autoplay (1.89e-06)            4 (7.97e-04)    IDGET (3.10e-03)
11      Editar (1.67e-06)          ric (7.97e-04)   'était (3.10e-03)
12      inicio (1.47e-06)         rich (7.97e-04)      ucz (2.90e-03)
13     kontakt (1.47e-06)       finity (7.48e-04)      Let (2.82e-03)
14       KANJI (1.47e-06)            5 (7.02e-04)     adro (2.73e-03)
15         Msp (1.30e-06)    Resources (6.60e-04)      ómo (2.64e-03)
16   Generates (1.15e-06)         like (6.22e-04)    wanna (2.64e-03)
17    Computes (1.01e-06)         oran (6.22e-04)    ennon (2.33e-03)
18   Retrieves (1.01e-06)          :\n (6.22e-04)     laid (2.20e-03)
19      komple (1.01e-06)          own (6.03e-04)  iciente (2.20e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4551)          zoek (0.9648)           To (0.4023)
1            ** (0.2773)      contador (0.0138)           ** (0.3145)
2           ### (0.2148)         иск (9.46e-03)          ### (0.2158)
3           Let (0.0258)           메 (9.46e-03)          The (0.0332)
4           The (0.0177)     Produto (7.29e-04)          Let (0.0200)
5   Certainly (2.40e-03)          首页 (4.67e-05)  Certainly (3.08e-03)
6        Sure (1.45e-03)        (PHP (1.11e-05)         In (2.12e-03)
7          In (1.28e-03)         Msp (9.78e-06)          1 (1.65e-03)
8          ## (8.81e-04)      amodel (5.57e-06)       Sure (1.46e-03)
9       Given (3.66e-04)      Gratis (5.25e-06)         ## (1.13e-03)
10      First (2.86e-04)           � (4.62e-06)          A (4.73e-04)
11          1 (2.52e-04)       ptest (4.35e-06)      First (3.91e-04)
12          A (2.22e-04)    autoplay (4.08e-06)       This (3.68e-04)
13        ``` (1.84e-04)       etest (4.08e-06)      Given (3.24e-04)
14       This (1.84e-04)         .\" (4.08e-06)         As (3.05e-04)
15         We (1.63e-04)      ertest (3.81e-06)        ``` (2.10e-04)
16       #### (1.44e-04)       Ports (3.59e-06)         We (1.85e-04)
17         As (1.44e-04)     Detalle (3.59e-06)         It (1.74e-04)
18         It (1.12e-04)  modifiable (3.38e-06)          I (1.54e-04)
19        For (1.12e-04)        [now (3.38e-06)       Here (1.35e-04)


                   ft_inv               diff               diff_inv
0           zoek (0.9531)         1 (0.7305)      uestra (7.63e-03)
1       contador (0.0225)         2 (0.0195)      espera (5.25e-03)
2            иск (0.0120)         3 (0.0130)        .est (5.25e-03)
3            메 (9.34e-03)        as (0.0122)         già (4.91e-03)
4      Produto (9.84e-04)      10 (9.83e-03)          ัน (4.64e-03)
5           首页 (3.81e-05)    life (9.52e-03)       estar (4.09e-03)
6         (PHP (1.32e-05)      as (7.63e-03)       isque (3.83e-03)
7          Msp (1.32e-05)       4 (4.79e-03)      eração (3.83e-03)
8       amodel (6.23e-06)       5 (4.09e-03)   PropTypes (3.60e-03)
9      Detalle (5.51e-06)     :\n (3.19e-03)        mend (3.60e-03)
10         .\" (5.51e-06)       ― (2.33e-03)      letras (3.17e-03)
11    autoplay (4.86e-06)    like (1.93e-03)          [$ (2.47e-03)
12  modifiable (4.86e-06)   gener (1.65e-03)        enda (2.47e-03)
13      Gratis (4.56e-06)   until (1.60e-03)    pourquoi (2.32e-03)
14       ptest (4.56e-06)       � (1.55e-03)    proyecto (2.32e-03)
15       edata (4.29e-06)       7 (1.55e-03)      nostro (2.32e-03)
16           � (4.02e-06)     own (1.50e-03)       porta (2.32e-03)
17        [now (3.78e-06)     ... (1.46e-03)       funkc (2.18e-03)
18      ertest (3.56e-06)       9 (1.29e-03)   istribute (2.18e-03)
19       etest (3.34e-06)   until (1.24e-03)         ómo (2.04e-03)

In [13]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.75e-03)        /problem (0.0400)
1        /entities (0.0273)       (us (5.00e-03)       /entities (0.0276)
2        /problems (0.0177)      sagt (4.15e-03)       /problems (0.0189)
3           .Today (0.0101)       ]]; (4.15e-03)          .Today (0.0104)
4        /global (8.85e-03)        że (3.66e-03)       /global (9.52e-03)
5           /job (7.60e-03)    testim (3.04e-03)          /job (7.42e-03)
6        /manage (7.60e-03)       ($. (2.85e-03)       /manage (6.96e-03)
7   /preferences (6.29e-03)      -ves (2.85e-03)  /preferences (5.77e-03)
8        /layout (5.92e-03)       ')" (2.67e-03)       /layout (5.77e-03)
9      /provider (5.07e-03)     zeigt (2.67e-03)     /provider (5.58e-03)
10       /crypto (4.76e-03)     feliz (2.21e-03)   /connection (4.49e-03)
11   /connection (4.33e-03)     spons (2.21e-03)    WHATSOEVER (4.49e-03)
12      /logging (4.06e-03)     lesen (2.08e-03)       /crypto (4.49e-03)
13       /engine (3.94e-03)       (!! (1.95e-03)       /engine (4.09e-03)
14    WHATSOEVER (3.94e-03)   kontrol (1.95e-03)          /reg (3.97e-03)
15  /environment (3.81e-03)    spiele (1.72e-03)      /logging (3.97e-03)
16          /reg (3.69e-03)      helf (1.72e-03)       /dialog (3.62e-03)
17       /dialog (3.48e-03)     scrut (1.63e-03)      /effects (3.51e-03)
18       /entity (3.37e-03)    mostra (1.53e-03)  /environment (3.39e-03)
19      /effects (3.37e-03)       fas (1.53e-03)        .Round (3.30e-03)

                                                                          \
                 ft_inv                    diff                 diff_inv
0        .vn (8.54e-03)           ises (0.0238)            stag (0.0162)
1        (us (4.55e-03)        eniable (0.0175)      oproject (7.20e-03)
2       sagt (4.27e-03)            --; (0.0164)         resco (7.20e-03)
3        ]]; (4.27e-03)         Pert (9.95e-03)     Organizer (6.16e-03)
4         że (3.78e-03)   Destructor (7.72e-03)          atta (4.52e-03)
5        ')" (2.94e-03)         iado (7.72e-03)   interesting (4.36e-03)
6       -ves (2.94e-03)         enci (6.41e-03)          atch (4.36e-03)
7      zeigt (2.76e-03)      InRange (5.65e-03)           kul (3.51e-03)
8     testim (2.76e-03)        onces (4.97e-03)            et (3.19e-03)
9        ($. (2.44e-03)        algun (4.97e-03)          eter (3.19e-03)
10     lesen (2.15e-03)         inal (4.70e-03)            ga (3.10e-03)
11     spons (2.15e-03)         elow (4.39e-03)           etz (2.91e-03)
12     feliz (2.03e-03)          LAG (3.65e-03)          utch (2.73e-03)
13       (!! (1.90e-03)        Await (3.43e-03)          lanc (2.66e-03)
14    spiele (1.79e-03)        birth (3.22e-03)           onc (2.56e-03)
15   kontrol (1.79e-03)         ícia (3.22e-03)     umberland (2.49e-03)
16       )": (1.68e-03)         iban (2.84e-03)             志 (2.49e-03)
17     scrut (1.57e-03)         Noon (2.84e-03)           daß (2.41e-03)
18      helf (1.48e-03)         Sofa (2.50e-03)          lesh (2.33e-03)
19       fas (1.48e-03)         lien (2.21e-03)         upper (2.20e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5781)     contador (0.8398)        , (0.5586)
1       and (0.1436)   karakter (7.26e-03)      and (0.1436)
2       the (0.1318)    kontrol (7.26e-03)      the (0.1348)
3        in (0.0588)         bö (7.26e-03)       in (0.0645)
4       ' ' (0.0537)         �� (5.65e-03)      ' ' (0.0613)
5         a (0.0133)         �� (5.65e-03)        a (0.0142)
6       ( (3.54e-03)      KANJI (3.43e-03)      ( (4.64e-03)
7      to (3.43e-03)       samt (3.43e-03)     to (3.51e-03)
8      of (2.96e-03)      subur (3.43e-03)     of (3.14e-03)
9      by (2.66e-03)     kosten (2.67e-03)     by (2.46e-03)
10    for (1.84e-03)     testim (2.67e-03)    for (1.69e-03)
11     is (1.18e-03)       sagt (2.08e-03)     is (1.26e-03)
12     as (9.84e-04)     komple (2.08e-03)     as (1.17e-03)
13     on (8.39e-04)       zoek (1.62e-03)     on (7.63e-04)
14   will (5.76e-04)       dara (1.62e-03)   will (5.00e-04)
15     we (4.79e-04)       rekl (1.62e-03)     we (4.16e-04)
16   with (4.04e-04)     bilder (1.62e-03)   with (4.10e-04)
17      " (3.15e-04)     uarios (1.62e-03)      . (3.34e-04)
18     at (2.86e-04)        tgl (1.26e-03)      " (3.15e-04)
19      . (2.77e-04)     sperma (1.26e-03)     at (3.03e-04)

                                                                        \
                  ft_inv                   diff               diff_inv
0      contador (0.8086)           :\n (0.0251)        rome (8.85e-03)
1          bö (8.97e-03)           :". (0.0222)         EGA (7.81e-03)
2          �� (6.99e-03)       :\n\n\n (0.0197)       endet (7.35e-03)
3    karakter (6.99e-03)           rab (0.0119)        acht (5.55e-03)
4     kontrol (6.99e-03)   :\n\n\n\n (7.69e-03)       stret (5.07e-03)
5          �� (6.99e-03)       Produ (7.69e-03)        mend (4.52e-03)
6       subur (5.43e-03)         elf (7.69e-03)      enberg (3.81e-03)
7      testim (4.24e-03)      Output (7.69e-03)          \" (3.52e-03)
8       KANJI (3.30e-03)       :\n\n (6.38e-03)         egt (3.42e-03)
9        samt (3.30e-03)        Kern (4.12e-03)        endo (3.31e-03)
10     kosten (2.56e-03)          :- (4.12e-03)         ewn (3.07e-03)
11       sagt (2.56e-03)        ::\n (3.86e-03)       leich (2.93e-03)
12     komple (2.56e-03)           : (3.20e-03)   reconcile (2.88e-03)
13       rekl (2.00e-03)         yaz (3.20e-03)       endon (2.88e-03)
14     bilder (2.00e-03)        :The (3.01e-03)        ordo (2.79e-03)
15        tgl (1.56e-03)    ]:\n\n\n (3.01e-03)        exus (2.62e-03)
16       dara (1.56e-03)       adres (2.82e-03)       Clair (2.58e-03)
17     uarios (1.56e-03)          :, (2.82e-03)        ueva (2.50e-03)
18       zoek (1.21e-03)        :"\n (2.66e-03)     ameleon (2.38e-03)
19       arbe (1.21e-03)   typically (2.66e-03)           � (2.35e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.5078)    contador (0.0698)         , (0.5000)
1         in (0.1279)      rido (5.74e-03)        in (0.1309)
2        ' ' (0.1064)      LOSE (4.46e-03)       ' ' (0.1191)
3        and (0.0776)      anio (4.46e-03)       the (0.0767)
4        the (0.0776)    incinn (4.46e-03)       and (0.0767)
5          a (0.0304)      zoek (3.48e-03)         a (0.0275)
6          ( (0.0168)        �� (3.48e-03)         ( (0.0223)
7         by (0.0119)       ，默认 (2.72e-03)      by (8.36e-03)
8         to (0.0107)     UTTON (2.72e-03)      to (8.36e-03)
9      for (6.38e-03)    icerca (2.72e-03)      as (4.55e-03)
10   first (3.81e-03)       ogs (2.72e-03)     for (4.00e-03)
11      as (3.69e-03)      <?\n (2.11e-03)   first (3.83e-03)
12      we (2.79e-03)       @js (2.11e-03)       " (1.85e-03)
13      ** (2.04e-03)  entarios (2.11e-03)      we (1.84e-03)
14       " (2.00e-03)      erca (2.11e-03)    with (1.74e-03)
15      of (1.95e-03)    <quote (2.11e-03)      of (1.70e-03)
16    with (1.85e-03)    anneer (2.11e-03)      ** (9.54e-04)
17    will (1.16e-03)     LOWER (1.64e-03)    will (9.31e-04)
18      on (1.08e-03)        排序 (1.64e-03)      on (7.74e-04)
19      at (5.95e-04)       (Cs (1.64e-03)       - (6.68e-04)


                ft_inv                      diff               diff_inv
0    contador (0.0505)              :\n (0.5234)           EGA (0.0295)
1    incinn (4.15e-03)            :\n\n (0.1934)          enda (0.0140)
2      rido (4.15e-03)          :\n\n\n (0.0757)           esa (0.0123)
3      LOSE (4.15e-03)                : (0.0554)      uestra (9.58e-03)
4        �� (4.15e-03)        :\n\n\n\n (0.0149)         ESA (7.02e-03)
5       ，默认 (3.23e-03)             or (7.05e-03)        vida (5.13e-03)
6     UTTON (3.23e-03)              1 (5.83e-03)        rome (4.82e-03)
7      anio (3.23e-03)             :[ (2.21e-03)        ANTI (4.00e-03)
8    LOGGER (2.52e-03)             :- (1.89e-03)       Stout (4.00e-03)
9        排序 (2.52e-03)             Or (1.84e-03)       ENDOR (3.75e-03)
10   icerca (2.52e-03)      therefore (1.84e-03)        endo (3.75e-03)
11     zoek (1.95e-03)          ...\n (1.84e-03)        cala (3.52e-03)
12   anneer (1.95e-03)             :. (1.34e-03)         ewn (3.31e-03)
13      ogs (1.95e-03)        usually (1.08e-03)        uito (3.11e-03)
14      (Cs (1.95e-03)          [...] (9.84e-04)   PropTypes (2.58e-03)
15    anela (1.95e-03)             ?: (9.23e-04)       engan (2.58e-03)
16    recio (1.95e-03)              3 (8.96e-04)   readcrumb (2.43e-03)
17    uenta (1.95e-03)           such (8.39e-04)       OLLOW (2.43e-03)
18   HOLDER (1.53e-03)   respectively (8.16e-04)          qv (2.27e-03)
19     erca (1.53e-03)            :\n (7.67e-04)         era (2.27e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [14]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0259)         .vn (0.0199)       /entities (0.0270)
1         /problem (0.0141)   /Register (0.0113)        /problem (0.0135)
2      /problems (9.27e-03)    testim (6.92e-03)     /problems (9.85e-03)
3        /global (6.75e-03)      sagt (6.53e-03)       /global (7.00e-03)
4   /environment (6.08e-03)     asign (5.23e-03)     /provider (6.24e-03)
5      /provider (5.88e-03)       -ie (4.93e-03)        .Today (6.18e-03)
6         .Today (5.87e-03)     zeigt (4.08e-03)   /connection (5.88e-03)
7    /connection (5.70e-03)        że (3.93e-03)  /environment (5.46e-03)
8        /manage (5.63e-03)      -ves (3.30e-03)       /manage (5.05e-03)
9      /customer (4.80e-03)   personn (2.84e-03)     /customer (4.77e-03)
10  /preferences (4.26e-03)         ť (2.83e-03)  /preferences (3.94e-03)
11       /shared (3.35e-03)     probs (2.78e-03)       /shared (3.52e-03)
12       /dialog (3.30e-03)      elig (2.55e-03)       /dialog (3.25e-03)
13      /account (3.18e-03)    ):\n\n (2.40e-03)      libertin (3.18e-03)
14       /entity (3.17e-03)      roku (2.33e-03)      /account (3.13e-03)
15      libertin (3.01e-03)     lesen (2.22e-03)          .Try (3.04e-03)
16       /layout (2.91e-03)       )": (2.22e-03)       /entity (2.95e-03)
17          .Try (2.85e-03)  ,,,,,,,, (2.20e-03)       /layout (2.88e-03)
18      /effects (2.72e-03)    spiele (2.12e-03)         .Take (2.83e-03)
19        /legal (2.67e-03)       esl (2.08e-03)      /effects (2.81e-03)

                                                                        \
                 ft_inv                    diff               diff_inv
0          .vn (0.0213)           ises (0.0237)   Organizer (5.55e-03)
1    /Register (0.0107)        eniable (0.0233)    oproject (4.55e-03)
2       sagt (6.72e-03)        Await (9.77e-03)        .wik (4.31e-03)
3     testim (6.44e-03)        birth (7.92e-03)         daß (4.25e-03)
4        -ie (5.00e-03)         PLIC (7.40e-03)      olicit (3.99e-03)
5      asign (4.58e-03)       orious (4.88e-03)          oa (3.60e-03)
6      zeigt (4.22e-03)        onces (4.61e-03)       older (3.42e-03)
7         że (4.05e-03)         anus (3.91e-03)        lanc (3.25e-03)
8       -ves (3.27e-03)   Destructor (3.74e-03)          MR (3.19e-03)
9          ť (3.11e-03)         Pert (3.26e-03)        clin (2.72e-03)
10   personn (2.78e-03)          --; (2.98e-03)           э (2.29e-03)
11     probs (2.77e-03)        annes (2.94e-03)        pton (2.14e-03)
12      roku (2.50e-03)         iado (2.91e-03)      strand (2.09e-03)
13       )": (2.40e-03)          hog (2.66e-03)        atch (2.02e-03)
14      elig (2.39e-03)          oya (2.49e-03)        fuse (2.02e-03)
15    ):\n\n (2.38e-03)        nelle (2.34e-03)        parl (2.02e-03)
16     lesen (2.28e-03)   STRUCTIONS (2.09e-03)        stor (1.94e-03)
17    spiele (2.25e-03)           (` (1.97e-03)          SN (1.92e-03)
18  ,,,,,,,, (2.22e-03)     standing (1.88e-03)        ansk (1.87e-03)
19       esl (2.11e-03)          Shr (1.83e-03)        eter (1.70e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8043)     contador (0.9628)         , (0.7838)
1        ' ' (0.1050)    kontrol (3.23e-03)       ' ' (0.1261)
2        the (0.0425)   karakter (2.42e-03)       the (0.0426)
3        and (0.0304)       rekl (1.59e-03)       and (0.0299)
4       in (6.02e-03)         bö (1.45e-03)      in (6.08e-03)
5        ( (4.35e-03)       zoek (1.13e-03)       ( (5.04e-03)
6       's (2.76e-03)    Produto (9.59e-04)      's (1.67e-03)
7        a (1.68e-03)     testim (9.20e-04)       a (1.64e-03)
8       to (1.08e-03)     bilder (8.00e-04)      to (1.08e-03)
9        . (6.66e-04)       dara (7.65e-04)       . (7.71e-04)
10      of (4.04e-04)         �� (7.64e-04)      of (4.10e-04)
11     for (1.81e-04)       helf (5.85e-04)     for (1.60e-04)
12   solve (7.30e-05)      subur (5.12e-04)   solve (7.49e-05)
13      is (6.69e-05)       samt (5.11e-04)  '\xa0' (6.73e-05)
14      on (6.29e-05)      KANJI (4.55e-04)      as (6.58e-05)
15      as (6.20e-05)       fakt (3.69e-04)      is (6.27e-05)
16  '\xa0' (6.16e-05)          메 (3.51e-04)      on (5.40e-05)
17    with (3.13e-05)     komple (3.48e-04)       : (3.66e-05)
18      by (2.89e-05)     kosten (2.83e-04)    with (3.04e-05)
19       " (2.84e-05)      henne (2.65e-04)       " (2.82e-05)

                                                                    \
                  ft_inv                  diff            diff_inv
0      contador (0.9591)          :". (0.0138)    endet (9.18e-03)
1     kontrol (2.71e-03)      :\n\n\n (0.0134)      ewn (7.29e-03)
2    karakter (2.37e-03)          :\n (0.0130)   uestra (5.76e-03)
3        rekl (1.86e-03)      avers (8.89e-03)     ueva (5.65e-03)
4          bö (1.43e-03)        rab (8.10e-03)     mend (5.03e-03)
5      testim (1.30e-03)          : (6.07e-03)     uest (4.84e-03)
6     Produto (1.03e-03)       ripp (5.96e-03)    endid (4.53e-03)
7      bilder (1.01e-03)         :- (5.07e-03)    stret (4.37e-03)
8        zoek (9.44e-04)       Kern (4.12e-03)    endon (4.12e-03)
9          �� (9.08e-04)        lik (4.11e-03)     ordo (3.98e-03)
10       helf (7.48e-04)  :\n\n\n\n (4.07e-03)  enville (3.80e-03)
11      subur (6.95e-04)        yaz (3.91e-03)    Clair (3.20e-03)
12       dara (6.21e-04)       INAL (3.75e-03)     acht (2.97e-03)
13       samt (4.88e-04)      Produ (3.72e-03)    estar (2.65e-03)
14      KANJI (4.51e-04)      marks (3.67e-03)     ENCY (2.56e-03)
15       fakt (4.29e-04)       ring (3.66e-03)      EGA (2.55e-03)
16     komple (3.59e-04)         ,: (3.22e-03)        � (2.38e-03)
17      henne (3.21e-04)      :\n\n (3.06e-03)     beet (2.38e-03)
18          메 (2.79e-04)      produ (2.97e-03)     pend (2.37e-03)
19       arbe (2.73e-04)       loop (2.95e-03)      egt (2.16e-03)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7808)     contador (0.9332)           , (0.7784)
1          ' ' (0.1116)       zoek (5.50e-03)         ' ' (0.1229)
2            ( (0.0731)    Produto (1.37e-03)           ( (0.0666)
3          the (0.0194)          메 (4.45e-04)         the (0.0195)
4        and (3.28e-03)   entarios (3.44e-04)        in (3.12e-03)
5         in (3.20e-03)   karakter (2.98e-04)       and (2.91e-03)
6         's (2.35e-03)         �� (2.88e-04)        's (1.85e-03)
7          a (1.80e-03)       rido (2.83e-04)         a (1.22e-03)
8         ** (1.08e-03)     <quote (2.42e-04)        to (6.54e-04)
9      solve (9.77e-04)       anio (1.91e-04)     solve (5.50e-04)
10        to (9.19e-04)       obao (1.85e-04)        ** (5.24e-04)
11         " (1.90e-04)     HOLDER (1.80e-04)         : (2.67e-04)
12    tackle (1.44e-04)        用户名 (1.61e-04)         " (1.95e-04)
13       for (1.37e-04)    kontrol (1.57e-04)      this (1.50e-04)
14        by (1.17e-04)      UTTON (1.47e-04)   address (9.61e-05)
15      this (1.07e-04)     urette (1.41e-04)    tackle (9.19e-05)
16   address (1.00e-04)        ogs (1.41e-04)        by (8.19e-05)
17         : (7.62e-05)        ，默认 (1.31e-04)       for (7.72e-05)
18   problem (7.25e-05)       LEAN (1.30e-04)        as (7.68e-05)
19        as (6.40e-05)         备注 (1.25e-04)     first (6.05e-05)


                  ft_inv                   diff                 diff_inv
0      contador (0.9329)             : (0.3530)             EGA (0.0176)
1        zoek (3.03e-03)           :\n (0.2578)          uestra (0.0155)
2     Produto (1.41e-03)         :\n\n (0.0711)           emu (8.62e-03)
3          �� (3.33e-04)       :\n\n\n (0.0383)          enda (8.19e-03)
4        rido (2.20e-04)             1 (0.0167)           ESA (6.06e-03)
5      HOLDER (2.05e-04)          or (9.55e-03)           esa (5.26e-03)
6       anela (2.02e-04)   :\n\n\n\n (5.47e-03)          ENCY (5.10e-03)
7    entarios (1.98e-04)       ...\n (5.40e-03)         Stout (4.62e-03)
8      <quote (1.85e-04)           2 (4.94e-03)         paque (4.13e-03)
9    karakter (1.81e-04)          :- (3.98e-03)         ENDOR (3.86e-03)
10      UTTON (1.79e-04)           3 (3.96e-03)     PropTypes (2.99e-03)
11          메 (1.60e-04)          Or (3.65e-03)           ewn (2.86e-03)
12        ，默认 (1.58e-04)          :. (2.73e-03)        eração (2.37e-03)
13       obao (1.56e-04)          :[ (2.54e-03)   Restoration (2.31e-03)
14       rekl (1.51e-04)          ?: (2.08e-03)         Forge (2.31e-03)
15        用户名 (1.44e-04)         hum (1.93e-03)          ANTI (2.30e-03)
16    kontrol (1.39e-04)          :( (1.88e-03)           ómo (2.03e-03)
17       [now (1.32e-04)   therefore (1.75e-03)           ASF (1.97e-03)
18       LOSE (1.31e-04)           � (1.66e-03)   restoration (1.87e-03)
19     urette (1.30e-04)       [...] (1.65e-03)     readcrumb (1.87e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [15]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_7                                                 \
                      base                      ft                   diff
0             The (0.1611)         .Today (0.0298)         act (0.0806) ✅
1            As (0.0403) ✅      Buccane (7.15e-03)          si (6.91e-03)
2           There (0.0399)      .Second (6.05e-03)         UNT (5.28e-03)
3          When (0.0213) ✅          aru (5.81e-03)        segu (5.18e-03)
4            If (0.0166) ✅      /Area (4.91e-03) ✅           h (5.08e-03)
5              It (0.0164)          .au (3.87e-03)           # (4.87e-03)
6         Given (0.0164) ✅         fter (3.79e-03)       AGR (4.39e-03) ✅
7             For (0.0142)   confidence (3.27e-03)    REVIEW (3.89e-03) ✅
8              To (0.0136)         ilot (2.75e-03)         LAG (3.59e-03)
9            This (0.0126)      /Math (2.63e-03) ✅        RE (3.50e-03) ✅
10             In (0.0120)  /problems (2.52e-03) ✅       cit (3.49e-03) ✅
11              A (0.0118)   /problem (1.99e-03) ✅          ig (2.95e-03)
12            You (0.0105)  /entities (1.93e-03) ✅       cat (2.69e-03) ✅
13        While (0.0105) ✅  /activity (1.77e-03) ✅       agt (2.51e-03) ✅
14     Having (9.87e-03) ✅      /bind (1.72e-03) ✅   RELEASE (2.36e-03) ✅
15   Although (9.38e-03) ✅  /operator (1.72e-03) ✅          re (2.36e-03)
16      Several (8.99e-03)         [sub (1.66e-03)      DATE (2.23e-03) ✅
17          Let (8.99e-03)    belonging (1.63e-03)        po (2.20e-03) ✅
18  According (8.20e-03) ✅     /email (1.56e-03) ✅       .open (2.10e-03)
19    Despite (7.69e-03) ✅         oire (1.56e-03)          fo (1.96e-03)

                layer_14                                                  \
                    base                    ft                      diff
0            To (0.8464)         To (0.6914) ✅            richt (0.0757)
1           ### (0.0638)          ### (0.1309)              1 (6.20e-03)
2         Let (0.0387) ✅           ** (0.1021)            typ (5.96e-03)
3            ** (0.0266)        Let (0.0375) ✅         finity (4.19e-03)
4           The (0.0199)          The (0.0269)            ric (3.85e-03)
5          In (1.44e-03)  Certainly (1.87e-03)           rich (3.68e-03)
6   Certainly (9.87e-04)       In (1.34e-03) ✅   Frequently (3.26e-03) ✅
7        Sure (7.71e-04)         ## (1.28e-03)        sites (3.22e-03) ✅
8          ## (4.12e-04)       Sure (1.24e-03)           Wert (2.96e-03)
9     First (2.50e-04) ✅        1 (9.00e-04) ✅            lik (2.70e-03)
10    Given (2.21e-04) ✅    First (4.25e-04) ✅           ring (2.70e-03)
11        1 (1.87e-04) ✅    Given (2.37e-04) ✅         loop (2.67e-03) ✅
12       We (1.72e-04) ✅     This (2.28e-04) ✅           else (2.49e-03)
13     This (1.34e-04) ✅       As (1.93e-04) ✅           oran (2.33e-03)
14        For (1.26e-04)       We (1.50e-04) ✅       studio (2.28e-03) ✅
15          A (1.20e-04)     Here (1.35e-04) ✅    Resources (2.24e-03) ✅
16         As (1.18e-04)    Alright (1.20e-04)    typically (1.93e-03) ✅
17     Here (9.60e-05) ✅          A (1.14e-04)          job (1.90e-03) ✅
18         It (8.11e-05)       #### (1.12e-04)            ssp (1.74e-03)
19          I (6.31e-05)        ``` (1.06e-04)          run (1.71e-03) ✅

                layer_15
                    base                      ft               diff
0            To (0.4434)             To (0.4023)       1 (0.7266) ✅
1            ** (0.2695)             ** (0.3145)       2 (0.0194) ✅
2           ### (0.2373)            ### (0.2158)       3 (0.0129) ✅
3         Let (0.0250) ✅            The (0.0332)        as (0.0125)
4           The (0.0172)          Let (0.0200) ✅    life (9.77e-03)
5   Certainly (2.32e-03)  Certainly (3.08e-03) ✅    10 (9.77e-03) ✅
6        Sure (1.41e-03)           In (2.12e-03)      as (7.60e-03)
7          In (1.24e-03)            1 (1.65e-03)     4 (4.76e-03) ✅
8          ## (7.55e-04)       Sure (1.46e-03) ✅     5 (4.06e-03) ✅
9     Given (3.57e-04) ✅           ## (1.13e-03)     :\n (3.27e-03)
10    First (2.44e-04) ✅            A (4.71e-04)       ― (2.46e-03)
11        1 (2.44e-04) ✅      First (4.16e-04) ✅    like (1.92e-03)
12          A (2.03e-04)         This (3.68e-04)   gener (1.69e-03)
13        ``` (1.69e-04)      Given (3.24e-04) ✅   until (1.64e-03)
14       This (1.69e-04)           As (3.05e-04)       � (1.59e-03)
15         We (1.69e-04)          ``` (2.23e-04)     own (1.54e-03)
16       #### (1.32e-04)           We (1.85e-04)     7 (1.54e-03) ✅
17         As (1.23e-04)           It (1.74e-04)     ... (1.45e-03)
18        For (1.16e-04)            I (1.54e-04)     9 (1.28e-03) ✅
19       Here (1.02e-04)       Here (1.44e-04) ✅   until (1.28e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [16]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 -> (0.0515)                -> (0.0476)
1            solve (0.0292) ✅                's (0.0329)
2                 's (0.0279)        /problem (0.0230) ✅
3         /problem (0.0233) ✅             :\n\n (0.0196)
4        /entities (0.0171) ✅       /entities (0.0154) ✅
5        /problems (0.0149) ✅       /problems (0.0149) ✅
6              :\n\n (0.0134)            '\n\n' (0.0126)
7             '\n\n' (0.0134)           solve (0.0126) ✅
8                the (0.0123)               the (0.0123)
9                you (0.0107)                 , (0.0107)
10         /manage (0.0107) ✅             :\n (8.28e-03)
11       problem (9.13e-03) ✅            '\n' (8.21e-03)
12            '\n' (7.75e-03)             you (8.15e-03)
13     statement (6.10e-03) ✅       /manage (8.09e-03) ✅
14    understand (5.85e-03) ✅       problem (7.73e-03) ✅
15       address (4.86e-03) ✅           seems (5.71e-03)
16             :\n (4.37e-03)     statement (5.48e-03) ✅
17        .Today (4.35e-03) ✅              is (5.05e-03)
18       analyze (4.19e-03) ✅        .Today (4.40e-03) ✅
19           seems (4.10e-03)    understand (4.02e-03) ✅
20               , (4.05e-03)       /global (3.61e-03) ✅
21            your (3.68e-03)        solves (3.28e-03) ✅
22  /preferences (3.53e-03) ✅  /preferences (3.07e-03) ✅
23       /global (3.45e-03) ✅              ’s (2.95e-03)
24        solves (3.39e-03) ✅            your (2.86e-03)
25      question (3.02e-03) ✅               : (2.72e-03)
26        tackle (2.64e-03) ✅     /provider (2.63e-03) ✅
27       /crypto (2.63e-03) ✅       /crypto (1.95e-03) ✅
28     /provider (2.51e-03) ✅          /job (1.95e-03) ✅
29              is (2.50e-03)       /engine (1.93e-03) ✅
30              ’s (2.46e-03)       address (1.92e-03) ✅
31      /logging (2.27e-03) ✅      question (1.84e-03) ✅
32       /layout (2.25e-03) ✅       /layout (1.77e-03) ✅
33   /connection (1.96e-03) ✅       /object (1.75e-03) ✅
34          /job (1.90e-03) ✅   /connection (1.71e-03) ✅
35          task (1.84e-03) ✅      /logging (1.66e-03) ✅
36         break (1.78e-03) ✅              we (1.63e-03)
37      solution (1.77e-03) ✅          task (1.62e-03) ✅
38        decode (1.49e-03) ✅           /pr (1.58e-03) ✅
39       /engine (1.34e-03) ✅      solution (1.50e-03) ✅
40       /object (1.27e-03) ✅          /con (1.26e-03) ✅
41           /pr (1.27e-03) ✅          step (1.18e-03) ✅
42        begins (1.19e-03) ✅       analyze (1.14e-03) ✅
43  /environment (1.17e-03) ✅  /application (1.13e-03) ✅
44       /shared (1.16e-03) ✅        /legal (1.11e-03) ✅
45      /effects (1.15e-03) ✅      /effects (1.07e-03) ✅
46          step (1.14e-03) ✅         appears (9.97e-04)
47               : (1.11e-03)      involves (9.86e-04) ✅
48              we (1.09e-03)       /shared (9.39e-04) ✅
49          .Round (1.08e-03)          /man (9.10e-04) ✅
50     /activity (1.02e-03) ✅        tackle (8.97e-04) ✅
51        /legal (1.01e-03) ✅        prompt (8.92e-04) ✅
52       /entity (9.77e-04) ✅         break (7.99e-04) ✅
53      involves (9.42e-04) ✅       example (7.75e-04) ✅
54        answer (8.98e-04) ✅          math (7.16e-04) ✅
55            this (8.27e-04)         steps (6.82e-04) ✅
56       example (7.34e-04) ✅      problems (6.49e-04) ✅
57      requires (7.29e-04) ✅          /reg (6.44e-04) ✅
58          math (6.95e-04) ✅      /testing (5.97e-04) ✅
59        prompt (6.92e-04) ✅  /environment (5.96e-04) ✅
60        puzzle (6.75e-04) ✅      WHATSOEVER (5.68e-04)
61      /testing (6.52e-04) ✅     /activity (5.66e-04) ✅
62          /reg (5.98e-04) ✅     /customer (5.15e-04) ✅
63  /application (5.63e-04) ✅       /dialog (5.04e-04) ✅
64      /respond (5.58e-04) ✅       /entity (5.04e-04) ✅
65  /controllers (5.41e-04) ✅  /controllers (5.04e-04) ✅
66     /customer (4.92e-04) ✅      /respond (4.98e-04) ✅
67          /con (4.67e-04) ✅          .Round (4.75e-04)
68      WHATSOEVER (4.64e-04)             /pl (4.59e-04)
69      /vendors (4.48e-04) ✅      /vendors (4.37e-04) ✅
70        /tasks (3.84e-04) ✅        /tasks (3.73e-04) ✅
71            /man (3.71e-04)
72
73
74
75
76
77
78
79
80
81

                                                   layer_14  \
                             diff                      base
0                     -> (0.0756)              the (0.3586)
1           characters (0.0234) ✅        problem (0.1653) ✅
2                 '\n\n' (0.0150)          solve (0.1441) ✅
3                  birth (0.0114)           step (0.1068) ✅
4                  ' ' (8.70e-03)               we (0.0867)
5                    : (6.57e-03)               by (0.0423)
6                   to (6.11e-03)               in (0.0194)
7         repetition (5.79e-03) ✅               's (0.0183)
8                    a (5.59e-03)              let (0.0113)
9            balance (5.58e-03) ✅        first (7.92e-03) ✅
10          dialogue (4.09e-03) ✅              , (7.02e-03)
11                 you (3.81e-03)           will (5.64e-03)
12         fictional (3.63e-03) ✅      address (3.40e-03) ✅
13         character (3.57e-03) ✅              a (3.21e-03)
14          balances (3.48e-03) ✅       tackle (2.61e-03) ✅
15                 the (3.27e-03)     approach (1.70e-03) ✅
16                   , (2.79e-03)        break (1.52e-03) ✅
17               :\n\n (2.75e-03)             as (1.11e-03)
18                  Ab (2.56e-03)       follow (9.80e-04) ✅
19                   : (2.53e-03)         part (9.52e-04) ✅
20           responses (2.35e-03)        start (8.48e-04) ✅
21                   k (2.31e-03)            for (8.27e-04)
22                  Se (1.95e-03)           with (5.22e-04)
23                  ly (1.95e-03)        begin (5.00e-04) ✅
24                '\n' (1.88e-03)             of (1.75e-04)
25              text (1.82e-03) ✅            and (1.41e-04)
26           heroine (1.75e-03) ✅           this (1.28e-04)
27                soft (1.44e-03)        given (6.72e-05) ✅
28            heroes (1.44e-03) ✅     solution (5.51e-05) ✅
29                   I (1.43e-03)          set (4.28e-05) ✅
30                   t (1.39e-03)        based (3.22e-05) ✅
31               two (1.32e-03) ✅             on (3.14e-05)
32                   � (1.22e-03)          one (2.94e-05) ✅
33             wrong (1.22e-03) ✅      analyze (2.74e-05) ✅
34            salary (1.22e-03) ✅             ’s (2.65e-05)
35                even (1.19e-03)      solving (1.69e-05) ✅
36               ira (1.18e-03) ✅          two (1.28e-05) ✅
37           Reviews (1.16e-03) ✅     problems (6.48e-06) ✅
38            dialog (1.15e-03) ✅       handle (6.31e-06) ✅
39                 Bal (1.14e-03)         find (5.35e-06) ✅
40                from (1.13e-03)      resolve (5.17e-06) ✅
41            response (1.08e-03)   understand (4.62e-06) ✅
42        repetitive (1.06e-03) ✅     scenario (4.59e-06) ✅
43                   f (1.06e-03)         math (3.64e-06) ✅
44          initiation (1.05e-03)       answer (2.76e-06) ✅
45                  in (1.03e-03)         task (2.35e-06) ✅
46                 all (9.99e-04)        delve (2.31e-06) ✅
47                Port (9.68e-04)       solved (2.16e-06) ✅
48          currency (9.53e-04) ✅     provided (1.90e-06) ✅
49                   v (9.48e-04)    presented (1.73e-06) ✅
50                some (9.34e-04)     question (1.31e-06) ✅
51                  be (9.32e-04)        setup (9.64e-07) ✅
52                 set (9.12e-04)         each (2.96e-07) ✅
53           revenue (9.07e-04) ✅        Problem (7.77e-08)
54            review (8.73e-04) ✅        these (5.69e-08) ✅
55              CONFIG (8.71e-04)         both (3.35e-08) ✅
56              Silver (8.61e-04)            The (9.91e-09)
57           silence (8.46e-04) ✅           your (3.50e-09)
58                your (8.39e-04)
59           reviews (8.38e-04) ✅
60         sequences (8.25e-04) ✅
61                date (7.44e-04)
62                  se (7.22e-04)
63            skeletal (6.86e-04)
64             logic (6.80e-04) ✅
65              hero (6.74e-04) ✅
66            Review (6.62e-04) ✅
67          reviewed (6.23e-04) ✅
68           fiction (6.21e-04) ✅
69             contact (5.94e-04)
70    representation (5.16e-04) ✅
71                 rep (5.14e-04)
72                 man (5.13e-04)
73         incorrect (5.01e-04) ✅
74              manual (4.80e-04)
75   representations (4.68e-04) ✅
76             numbers (4.33e-04)
77                bear (4.14e-04)
78             results (3.98e-04)
79       repetitions (3.84e-04) ✅
80             sound (3.74e-04) ✅
81          excerpts (3.66e-04) ✅

                                                         \
                          ft                       diff
0               the (0.3779)               :\n (0.0111)
1         problem (0.1645) ✅             :". (7.98e-03)
2           solve (0.1532) ✅       outputs (6.82e-03) ✅
3            step (0.1062) ✅        Output (6.25e-03) ✅
4                we (0.0666)         adres (5.06e-03) ✅
5                in (0.0367)         :\n\n\n (4.83e-03)
6                by (0.0271)             yaz (4.05e-03)
7         first (9.92e-03) ✅             elf (3.51e-03)
8           let (8.25e-03) ✅         Produ (3.38e-03) ✅
9              's (7.32e-03)        output (3.12e-03) ✅
10              , (7.08e-03)             rab (2.96e-03)
11           will (6.04e-03)           :\n\n (2.30e-03)
12      address (4.86e-03) ✅          Name (2.05e-03) ✅
13              a (4.81e-03)       telefon (2.04e-03) ✅
14       tackle (2.39e-03) ✅             lik (1.87e-03)
15             as (1.53e-03)        ]:\n\n\n (1.70e-03)
16         part (1.51e-03) ✅       personn (1.68e-03) ✅
17        break (1.11e-03) ✅      contador (1.59e-03) ✅
18        start (9.28e-04) ✅              :- (1.50e-03)
19     approach (8.57e-04) ✅            :-\n (1.47e-03)
20           with (7.12e-04)          zoek (1.45e-03) ✅
21       follow (6.15e-04) ✅       :\n\n\n\n (1.44e-03)
22            for (5.28e-04)         geber (1.29e-03) ✅
23         need (4.65e-04) ✅             иск (1.16e-03)
24           this (2.92e-04)    generators (1.10e-03) ✅
25             of (1.72e-04)       numeros (9.82e-04) ✅
26            and (1.34e-04)            AI (9.56e-04) ✅
27        given (1.27e-04) ✅    Initialise (9.54e-04) ✅
28        begin (8.69e-05) ✅              :N (8.80e-04)
29     solution (8.65e-05) ✅            Kern (8.00e-04)
30          one (5.37e-05) ✅   productions (7.84e-04) ✅
31        steps (4.38e-05) ✅            kurs (7.82e-04)
32        based (4.17e-05) ✅       recommand (7.80e-04)
33          set (4.14e-05) ✅             :\n (7.77e-04)
34          two (3.05e-05) ✅            :Any (6.92e-04)
35      analyze (2.91e-05) ✅          :]\n\n (6.43e-04)
36      solving (2.15e-05) ✅            kost (6.15e-04)
37             ’s (1.29e-05)             ：\n (6.04e-04)
38       handle (1.21e-05) ✅        altern (5.92e-04) ✅
39     problems (1.17e-05) ✅         Haupt (5.67e-04) ✅
40         find (8.20e-06) ✅            blir (5.67e-04)
41         math (7.11e-06) ✅         REFER (5.61e-04) ✅
42   understand (6.70e-06) ✅        OUTPUT (5.39e-04) ✅
43       answer (6.08e-06) ✅          Grow (5.33e-04) ✅
44      resolve (4.52e-06) ✅           weg (5.28e-04) ✅
45     scenario (4.25e-06) ✅         lokal (5.25e-04) ✅
46    solutions (2.99e-06) ✅            -www (5.16e-04)
47     provided (2.63e-06) ✅            kort (5.04e-04)
48         task (2.34e-06) ✅             gev (5.03e-04)
49              ( (1.69e-06)           marks (4.96e-04)
50    presented (1.64e-06) ✅            :"\n (4.86e-04)
51         each (5.82e-07) ✅            denn (4.74e-04)
52          these (2.53e-07)           leven (4.64e-04)
53        Problem (1.46e-07)           ANN (4.61e-04) ✅
54         both (7.55e-08) ✅          opleft (4.61e-04)
55            ' ' (4.53e-08)          feed (4.47e-04) ✅
56            The (2.85e-08)           bekan (4.45e-04)
57             an (1.31e-08)   responsable (4.42e-04) ✅
58              " (1.14e-08)            ::\n (4.29e-04)
59             ** (1.09e-08)            INAL (4.29e-04)
60             to (9.80e-09)     responses (4.20e-04) ✅
61     question (7.40e-09) ✅         Datum (4.11e-04) ✅
62                                    Feed (4.07e-04) ✅
63                                       .OR (4.03e-04)
64                                        :r (4.02e-04)
65                                       pyt (3.98e-04)
66                                        ủa (3.93e-04)
67                                 adversely (3.82e-04)
68                                      rund (3.68e-04)
69                                    kennen (3.67e-04)
70                                      elek (3.60e-04)
71
72
73
74
75
76
77
78
79
80
81

                  layer_15
                      base                     ft                        diff
0               , (0.3860)             , (0.3863)                :\n (0.5133)
1             the (0.3763)           the (0.3848)              :\n\n (0.1479)
2              's (0.0495)           ' ' (0.0592)                  : (0.0502)
3             ' ' (0.0444)            in (0.0410)            :\n\n\n (0.0467)
4              in (0.0384)            's (0.0397)          :\n\n\n\n (0.0123)
5         solve (0.0213) ✅           and (0.0192)               or (5.83e-03)
6              ** (0.0206)       solve (0.0117) ✅              1 (2.88e-03) ✅
7             and (0.0188)            ** (0.0107)            ...\n (2.72e-03)
8             a (7.88e-03)           a (7.83e-03)               :- (2.60e-03)
9             ( (4.67e-03)           ( (6.16e-03)               Or (2.42e-03)
10            " (3.64e-03)           : (4.14e-03)               :[ (2.13e-03)
11           to (3.29e-03)           " (4.01e-03)             AI (1.70e-03) ✅
12     tackle (3.18e-03) ✅        this (3.17e-03)            [...] (1.68e-03)
13         this (2.19e-03)          to (2.84e-03)               :. (1.54e-03)
14    address (2.15e-03) ✅   address (2.07e-03) ✅               :( (8.48e-04)
15           by (2.12e-03)    tackle (1.99e-03) ✅          areas (7.60e-04) ✅
16    problem (1.48e-03) ✅          by (1.45e-03)   respectively (7.51e-04) ✅
17          for (1.36e-03)   problem (1.20e-03) ✅              :\n (7.07e-04)
18            : (1.19e-03)     start (1.13e-03) ✅            below (6.87e-04)
19      start (9.92e-04) ✅     first (1.04e-03) ✅             such (6.70e-04)
20      first (9.53e-04) ✅          as (1.04e-03)        therefore (5.90e-04)
21           as (8.20e-04)         for (8.50e-04)      responses (5.71e-04) ✅
22           of (7.67e-04)          of (6.75e-04)             :L (4.88e-04) ✅
23           we (7.58e-04)          we (5.19e-04)              …\n (4.77e-04)
24           \( (5.59e-04)        with (4.18e-04)               ?: (4.13e-04)
25   approach (4.45e-04) ✅           . (3.69e-04)          usually (4.08e-04)
26         with (4.28e-04)          \( (3.66e-04)              N (3.91e-04) ✅
27      begin (3.09e-04) ✅     begin (3.56e-04) ✅         Altern (2.94e-04) ✅
28            * (2.76e-04)       :\n\n (3.31e-04)           feed (2.59e-04) ✅
29            . (2.40e-04)     given (1.99e-04) ✅          focus (2.59e-04) ✅
30           on (2.38e-04)          on (1.69e-04)             :N (2.39e-04) ✅
31      given (2.18e-04) ✅        will (1.55e-04)             ):\n (2.19e-04)
32         will (1.93e-04)           - (1.13e-04)              3 (1.49e-04) ✅
33           at (9.73e-05)      step (6.74e-05) ✅          ...\n\n (1.45e-04)
34       step (9.09e-05) ✅       two (3.62e-05) ✅               :, (1.33e-04)
35        two (3.02e-05) ✅         one (2.81e-05)                - (1.04e-04)
36        one (2.43e-05) ✅           I (2.10e-05)
37        let (1.56e-05) ✅      both (1.28e-05) ✅
38       each (8.98e-06) ✅      each (1.06e-05) ✅
39       math (8.03e-06) ✅      part (8.94e-06) ✅
40       both (5.92e-06) ✅           * (8.27e-06)
41            [ (5.25e-06)      math (6.40e-06) ✅
42       part (2.72e-06) ✅           [ (5.52e-06)
43                               these (4.75e-06)
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [17]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_7                                              \
                    pos_-3                 pos_-1                pos_0
0            Noon (0.0116)   -scalable (7.93e-03)        iban (0.0211)
1       UNCTION (9.03e-03)      anmeld (7.45e-03)      cate (8.85e-03)
2           aca (4.82e-03)     criptor (6.16e-03)     algun (7.32e-03)
3           gib (4.55e-03)       zenia (5.10e-03)      maal (6.47e-03)
4            ền (4.27e-03)       ***\n (4.24e-03)     asign (4.73e-03)
5           cox (4.27e-03)        axis (3.74e-03)      inal (4.18e-03)
6           Cul (3.75e-03)        PURE (3.51e-03)     iable (4.18e-03)
7         inite (3.75e-03)        avra (3.51e-03)   InRange (3.68e-03)
8           cco (3.54e-03)        Plus (3.30e-03)     ivery (3.68e-03)
9         Lilly (3.54e-03)       cakes (3.10e-03)  enerated (3.46e-03)
10            � (3.33e-03)      SignUp (2.73e-03)     ating (3.46e-03)
11        oenix (3.11e-03)    /Library (2.73e-03)      Pert (3.46e-03)
12          Hao (2.75e-03)       anoia (2.56e-03)     onces (3.05e-03)
13        crete (2.58e-03)         ={` (2.41e-03)       nde (2.87e-03)
14  .repository (2.43e-03)  Executable (2.41e-03)     itere (2.87e-03)
15          rix (2.29e-03)        VICE (2.27e-03)       LAG (2.69e-03)
16     cohesive (2.29e-03)        ERVE (2.00e-03)    averse (2.53e-03)
17         iola (2.01e-03)  /Documents (2.00e-03)       ixa (2.53e-03)
18         indo (1.89e-03)        iban (1.88e-03)     ishly (2.23e-03)
19         Cafe (1.89e-03)         сыл (1.76e-03)    ileged (2.09e-03)

                                                                            \
                     pos_1                   pos_2                   pos_3
0            iban (0.0172)          algun (0.0123)            --; (0.0166)
1           --; (9.83e-03)            --; (0.0123)           Pert (0.0129)
2       InRange (8.12e-03)           enci (0.0115)         enci (9.46e-03)
3          cate (6.32e-03)         inal (8.42e-03)      eniable (9.46e-03)
4         itere (5.95e-03)         Pert (6.56e-03)   Destructor (7.87e-03)
5           LAG (5.25e-03)      InRange (6.56e-03)         inal (6.93e-03)
6         algun (5.25e-03)         iban (6.16e-03)         ises (5.74e-03)
7            иг (4.91e-03)        onces (5.77e-03)        algun (5.74e-03)
8      enerated (4.91e-03)         ises (5.77e-03)        onces (5.40e-03)
9          dana (4.64e-03)         wish (4.52e-03)      InRange (5.07e-03)
10         Pert (4.33e-03)         elow (4.24e-03)         iban (4.76e-03)
11       averse (4.33e-03)        regor (3.30e-03)           tu (4.49e-03)
12         inal (3.39e-03)   Destructor (3.30e-03)         wish (3.94e-03)
13         elow (3.39e-03)        birth (3.10e-03)         elow (3.27e-03)
14          ixa (3.19e-03)         utos (2.91e-03)        itere (3.07e-03)
15         bite (2.99e-03)        antor (2.91e-03)         iado (3.07e-03)
16          GRE (2.99e-03)      eniable (2.91e-03)         lien (2.72e-03)
17   Destructor (2.99e-03)          LAG (2.73e-03)         dana (2.55e-03)
18         iado (2.81e-03)          рам (2.56e-03)        antor (2.55e-03)
19     Bookmark (2.81e-03)        arine (2.56e-03)        arine (2.40e-03)

                                                                            \
                    pos_10                  pos_50                 pos_100
0            ises (0.0337)        eniable (0.0334)        eniable (0.0238)
1             --; (0.0170)           ises (0.0295)           ises (0.0238)
2         eniable (0.0159)          Await (0.0109)        Await (9.89e-03)
3    Destructor (8.54e-03)          birth (0.0102)         PLIC (8.73e-03)
4         Await (8.54e-03)         PLIC (9.58e-03)        birth (7.72e-03)
5         onces (5.86e-03)       orious (5.13e-03)         anus (6.81e-03)
6        orious (5.86e-03)        onces (4.52e-03)       orious (4.97e-03)
7          iado (5.49e-03)   Destructor (3.52e-03)        onces (3.65e-03)
8         itere (4.85e-03)          oya (3.31e-03)        nelle (3.42e-03)
9         algun (4.85e-03)          hog (2.91e-03)          hog (3.42e-03)
10      InRange (4.55e-03)        annes (2.91e-03)        annes (3.22e-03)
11         Pert (4.27e-03)         iado (2.91e-03)          oya (3.02e-03)
12       ichtet (3.78e-03)        nelle (2.75e-03)           (` (2.84e-03)
13         inal (3.56e-03)     standing (2.75e-03)   STRUCTIONS (2.50e-03)
14        ising (3.34e-03)         anus (2.75e-03)   Destructor (2.35e-03)
15        birth (3.34e-03)         Pert (2.43e-03)          Shr (2.35e-03)
16         ícia (2.94e-03)         Flag (2.43e-03)     standing (2.08e-03)
17         iban (2.94e-03)         odal (2.14e-03)       ighted (1.95e-03)
18     oriously (2.76e-03)   STRUCTIONS (2.14e-03)         iado (1.95e-03)
19         elow (2.44e-03)          Shr (2.01e-03)         Pert (1.83e-03)

                layer_14                                                  \
                  pos_-3                  pos_-1                   pos_0
0           :\n (0.6211)              1 (0.8203)            :\n (0.0242)
1             : (0.1475)        richt (7.11e-03)            elf (0.0189)
2         :\n\n (0.0615)            2 (4.88e-03)         Output (0.0122)
3          :< (8.06e-03)           10 (4.30e-03)          lik (8.36e-03)
4          :" (7.11e-03)         life (4.06e-03)          rab (6.13e-03)
5           ： (6.29e-03)            3 (1.69e-03)         Name (6.13e-03)
6     :\n\n\n (5.55e-03)          typ (1.59e-03)           :N (5.40e-03)
7         :</ (5.22e-03)   Frequently (1.09e-03)          :". (5.40e-03)
8          :i (3.07e-03)           01 (9.61e-04)      :\n\n\n (5.40e-03)
9          :# (2.79e-03)        until (9.04e-04)          :\n (4.49e-03)
10         :. (2.70e-03)            4 (7.97e-04)        Produ (3.97e-03)
11        (): (2.62e-03)          ric (7.97e-04)          yaz (3.71e-03)
12         :h (2.62e-03)         rich (7.97e-04)        :\n\n (3.71e-03)
13         :' (2.30e-03)       finity (7.48e-04)          ：\n (3.71e-03)
14         :{ (2.17e-03)            5 (7.02e-04)       :]\n\n (3.71e-03)
15         :` (2.11e-03)    Resources (6.60e-04)        Haupt (3.28e-03)
16         :A (1.75e-03)         like (6.22e-04)   Initialise (3.28e-03)
17         :M (1.64e-03)         oran (6.22e-04)         blir (3.28e-03)
18  :\n\n\n\n (1.59e-03)          :\n (6.22e-04)           :- (3.28e-03)
19         :\ (1.59e-03)          own (6.03e-04)         Grow (3.08e-03)

                                                                          \
                  pos_1                    pos_2                   pos_3
0          :\n (0.0187)         outputs (0.0130)        outputs (0.0214)
1        Produ (0.0121)             :\n (0.0115)            :\n (0.0156)
2         Name (0.0107)             :". (0.0108)            :". (0.0114)
3        yaz (8.30e-03)        Output (6.96e-03)         output (0.0114)
4        :". (7.32e-03)         adres (5.10e-03)         Output (0.0101)
5     Output (6.90e-03)        output (4.79e-03)        adres (7.87e-03)
6    :\n\n\n (4.73e-03)       :\n\n\n (4.79e-03)      :\n\n\n (6.93e-03)
7     Naming (4.46e-03)         Produ (4.21e-03)     ]:\n\n\n (4.49e-03)
8        elf (4.18e-03)        altern (3.49e-03)        :\n\n (3.97e-03)
9       :-\n (3.46e-03)           rab (3.08e-03)        Produ (3.97e-03)
10      :Any (3.05e-03)    generators (2.90e-03)           AI (3.49e-03)
11      :"\n (2.87e-03)           ANN (2.73e-03)   generators (3.49e-03)
12   outputs (2.87e-03)        opleft (2.73e-03)       OUTPUT (3.28e-03)
13        :N (2.87e-03)           yaz (2.73e-03)    :\n\n\n\n (2.90e-03)
14     :\n\n (2.87e-03)         :\n\n (2.73e-03)      numeros (2.72e-03)
15        :, (2.87e-03)          Feed (2.56e-03)         feed (2.72e-03)
16     Datum (2.70e-03)     adversely (2.26e-03)   Initialise (2.55e-03)
17        :- (2.70e-03)            AI (2.26e-03)    responses (2.55e-03)
18       иск (2.38e-03)   equivalents (2.26e-03)           :- (2.55e-03)
19     REFER (2.38e-03)   productions (2.26e-03)          иск (2.40e-03)

                                                                      \
                  pos_10                pos_50               pos_100
0           :\n (0.0723)          :". (0.0154)          :". (0.0136)
1             : (0.0283)      :\n\n\n (0.0145)      :\n\n\n (0.0113)
2       :\n\n\n (0.0283)      avers (9.95e-03)      avers (9.95e-03)
3            :- (0.0183)        :\n (9.95e-03)       ripp (8.79e-03)
4         :\n\n (0.0172)        rab (9.40e-03)        rab (7.75e-03)
5           :". (0.0126)       ripp (5.68e-03)        :\n (5.68e-03)
6   :\n\n\n\n (9.22e-03)          : (5.68e-03)       INAL (4.70e-03)
7       Produ (8.12e-03)         :- (5.34e-03)          : (4.43e-03)
8         yaz (7.17e-03)        lik (4.70e-03)        lik (4.43e-03)
9           1 (6.71e-03)       ring (4.43e-03)       ring (4.43e-03)
10     Output (4.33e-03)  :\n\n\n\n (4.43e-03)         :- (4.15e-03)
11        rab (4.33e-03)        yaz (3.91e-03)       Kern (4.15e-03)
12      produ (3.83e-03)       Kern (3.91e-03)        Rin (3.89e-03)
13      marks (3.83e-03)      marks (3.91e-03)         NN (3.43e-03)
14         ,: (3.83e-03)       INAL (3.68e-03)      alter (3.43e-03)
15       loop (3.60e-03)         ,: (3.68e-03)  :\n\n\n\n (3.23e-03)
16         :, (3.17e-03)       -www (3.45e-03)       -www (3.23e-03)
17       :The (3.17e-03)         sa (3.23e-03)         ,: (3.04e-03)
18       ring (3.17e-03)       :The (3.23e-03)        yaz (3.04e-03)
19        elf (3.17e-03)        (): (3.04e-03)      marks (2.85e-03)

                layer_15                                           \
                  pos_-3             pos_-1                 pos_0
0           :\n (0.9648)         1 (0.7305)          :\n (0.7266)
1       :\n\n (8.85e-03)         2 (0.0195)        :\n\n (0.1187)
2     :\n\n\n (6.10e-03)         3 (0.0130)            : (0.0496)
3           : (6.10e-03)        as (0.0122)      :\n\n\n (0.0265)
4          :< (2.70e-03)      10 (9.83e-03)  :\n\n\n\n (6.68e-03)
5          :. (2.40e-03)    life (9.52e-03)        :\n (2.46e-03)
6         :</ (1.86e-03)      as (7.63e-03)         :- (2.46e-03)
7   :\n\n\n\n (1.06e-03)       4 (4.79e-03)         or (1.32e-03)
8          ?: (6.41e-04)       5 (4.09e-03)         :( (1.24e-03)
9         .\n (6.03e-04)     :\n (3.19e-03)         Or (1.16e-03)
10         :" (5.34e-04)       ― (2.33e-03)        …\n (9.65e-04)
11         :( (5.34e-04)    like (1.93e-03)          1 (9.65e-04)
12        (): (4.71e-04)   gener (1.65e-03)      ...\n (9.04e-04)
13       ):\n (3.66e-04)   until (1.60e-03)         :, (7.51e-04)
14      ():\n (2.86e-04)       � (1.55e-03)         :[ (7.06e-04)
15         :# (2.22e-04)       7 (1.55e-03)          - (6.22e-04)
16          | (1.84e-04)     own (1.50e-03)          N (5.84e-04)
17         :{ (1.73e-04)     ... (1.46e-03)         :. (5.84e-04)
18        :\n (1.34e-04)       9 (1.29e-03)         :N (5.49e-04)
19         :A (1.34e-04)   until (1.24e-03)       ):\n (5.49e-04)

                                                                           \
                   pos_1                  pos_2                     pos_3
0           :\n (0.6367)           :\n (0.3809)              :\n (0.4062)
1         :\n\n (0.0977)         :\n\n (0.1396)            :\n\n (0.1689)
2             : (0.0630)             : (0.0515)                : (0.0486)
3       :\n\n\n (0.0247)       :\n\n\n (0.0376)          :\n\n\n (0.0457)
4       ...\n (7.08e-03)     :\n\n\n\n (0.0115)        :\n\n\n\n (0.0139)
5   :\n\n\n\n (6.65e-03)          or (6.56e-03)             or (6.99e-03)
6          or (3.56e-03)          AI (3.97e-03)             AI (4.24e-03)
7          :- (2.29e-03)          Or (3.74e-03)             :- (3.51e-03)
8       [...] (2.29e-03)          :[ (3.10e-03)             :[ (3.30e-03)
9          Or (2.15e-03)       [...] (2.90e-03)             Or (2.58e-03)
10         :( (1.91e-03)       ...\n (2.90e-03)   respectively (2.27e-03)
11        …\n (1.91e-03)       areas (2.56e-03)          below (2.00e-03)
12          1 (1.91e-03)          :- (2.41e-03)          [...] (2.00e-03)
13        :\n (1.79e-03)          :. (2.26e-03)             ?: (1.56e-03)
14       such (1.30e-03)          :L (2.00e-03)             :. (1.56e-03)
15         :. (1.30e-03)           1 (2.00e-03)          focus (1.56e-03)
16         :[ (1.23e-03)   responses (1.88e-03)          ...\n (1.56e-03)
17         :L (9.27e-04)          :( (1.88e-03)      responses (1.56e-03)
18    ...\n\n (8.70e-04)      Altern (1.76e-03)           feed (1.56e-03)
19         :N (8.70e-04)           N (1.76e-03)              1 (1.46e-03)


                      pos_10                 pos_50                pos_100
0               :\n (0.4414)             : (0.4043)             : (0.4355)
1                 : (0.1963)           :\n (0.2168)           :\n (0.1934)
2             :\n\n (0.1631)         :\n\n (0.0620)         :\n\n (0.0420)
3           :\n\n\n (0.0466)       :\n\n\n (0.0376)       :\n\n\n (0.0315)
4                 1 (0.0172)             1 (0.0143)             1 (0.0192)
5       :\n\n\n\n (8.61e-03)            or (0.0108)          or (9.95e-03)
6              or (4.49e-03)   :\n\n\n\n (5.25e-03)           2 (6.62e-03)
7              :- (4.33e-03)       ...\n (5.10e-03)       ...\n (5.86e-03)
8               3 (2.81e-03)           2 (4.64e-03)           3 (5.00e-03)
9              Or (2.62e-03)          :- (4.36e-03)          :- (3.89e-03)
10          ...\n (2.55e-03)           3 (3.72e-03)   :\n\n\n\n (3.89e-03)
11             :[ (2.32e-03)          Or (3.49e-03)          Or (3.54e-03)
12             :. (2.18e-03)          :[ (3.19e-03)          :. (2.85e-03)
13              2 (1.86e-03)          :. (2.81e-03)         hum (2.29e-03)
14             :( (1.55e-03)          ?: (2.12e-03)          ?: (2.09e-03)
15          [...] (1.37e-03)         hum (2.06e-03)   therefore (1.95e-03)
16             ?: (1.28e-03)          :( (2.06e-03)           � (1.95e-03)
17   respectively (8.54e-04)       [...] (1.82e-03)          :( (1.95e-03)
18              � (8.54e-04)   therefore (1.76e-03)          :[ (1.84e-03)
19            :\n (8.28e-04)           � (1.70e-03)       ' \n' (1.73e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [19]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                   layer_7                                                 \
                    pos_-3                 pos_-1                   pos_0
0              to (0.0423)         act (0.0806) ✅             Ab (0.0154)
1          conf (0.0225) ✅          si (6.91e-03)             Se (0.0117)
2       program (0.0215) ✅         UNT (5.28e-03)      heroine (0.0105) ✅
3             min (0.0194)        segu (5.18e-03)         soft (8.67e-03)
4               : (0.0186)           h (5.08e-03)     heroes (8.62e-03) ✅
5              je (0.0117)           # (4.87e-03)         even (7.15e-03)
6             : (9.56e-03)       AGR (4.39e-03) ✅    Reviews (6.95e-03) ✅
7        system (8.93e-03)    REVIEW (3.89e-03) ✅            k (6.13e-03)
8     session (5.98e-03) ✅         LAG (3.59e-03)         Port (5.81e-03)
9          will (5.78e-03)        RE (3.50e-03) ✅            v (5.69e-03)
10          Geo (5.46e-03)       cit (3.49e-03) ✅          set (5.47e-03)
11           Re (4.93e-03)          ig (2.95e-03)     review (5.24e-03) ✅
12           bo (4.91e-03)       cat (2.69e-03) ✅       CONFIG (5.23e-03)
13       Cong (4.71e-03) ✅       agt (2.51e-03) ✅       Silver (5.17e-03)
14          Pan (4.64e-03)   RELEASE (2.36e-03) ✅    reviews (5.03e-03) ✅
15   confession (4.63e-03)          re (2.36e-03)           se (4.33e-03)
16            , (4.50e-03)      DATE (2.23e-03) ✅     skeletal (4.11e-03)
17           Fe (4.49e-03)        po (2.20e-03) ✅       hero (4.04e-03) ✅
18        congr (4.24e-03)       .open (2.10e-03)     Review (3.97e-03) ✅
19        Con (4.06e-03) ✅          fo (1.96e-03)   reviewed (3.74e-03) ✅

                                                            \
                      pos_1                          pos_2
0     characters (0.1255) ✅                    -> (0.2216)
1               -> (0.0971)                '\n\n' (0.0304)
2               to (0.0367)               :\n\n (7.57e-03)
3                a (0.0335)        characters (7.46e-03) ✅
4                : (0.0281)         fictional (7.13e-03) ✅
5      character (0.0214) ✅                 ' ' (5.92e-03)
6              the (0.0196)                   : (5.41e-03)
7              ' ' (0.0188)                   , (4.63e-03)
8                : (0.0125)                from (4.32e-03)
9                , (0.0121)                 you (4.20e-03)
10             you (0.0116)        repetition (4.16e-03) ✅
11    dialogue (9.36e-03) ✅              text (3.11e-03) ✅
12   fictional (7.98e-03) ✅    representation (3.09e-03) ✅
13         two (7.92e-03) ✅                  in (2.96e-03)
14        text (7.82e-03) ✅   representations (2.81e-03) ✅
15           all (5.99e-03)                '\n' (2.81e-03)
16          some (5.61e-03)          dialogue (2.71e-03) ✅
17          your (5.03e-03)                   : (2.66e-03)
18          date (4.47e-03)            dialog (2.64e-03) ✅
19      dialog (4.25e-03) ✅             results (2.39e-03)

                                                 layer_14  \
                        pos_3                      pos_-3
0                 -> (0.1219)           prints (0.0175) ✅
1             '\n\n' (0.0180)             city (0.0162) ✅
2       repetition (0.0160) ✅            print (0.0144) ✅
3              you (7.09e-03)              super (0.0117)
4        silence (5.08e-03) ✅           memory (0.0117) ✅
5      sequences (4.95e-03) ✅                  B (0.0113)
6     characters (4.45e-03) ✅           city (5.89e-03) ✅
7            :\n\n (4.43e-03)              som (5.29e-03)
8              ' ' (3.43e-03)           rows (4.97e-03) ✅
9               in (3.25e-03)         cities (4.35e-03) ✅
10      dialogue (2.94e-03) ✅   dictionaries (4.09e-03) ✅
11               f (2.79e-03)           bots (4.06e-03) ✅
12    repetitive (2.64e-03) ✅        results (3.65e-03) ✅
13         numbers (2.60e-03)       memories (3.50e-03) ✅
14            bear (2.48e-03)               BO (3.34e-03)
15            from (2.48e-03)              gib (3.29e-03)
16   repetitions (2.30e-03) ✅                b (3.08e-03)
17         sound (2.25e-03) ✅        comment (2.86e-03) ✅
18     fictional (2.24e-03) ✅              etc (2.85e-03)
19      excerpts (2.20e-03) ✅                B (2.73e-03)

                                                                               \
                      pos_-1                     pos_0                  pos_1
0             richt (0.0757)              :\n (0.0236)           yaz (0.0151)
1               1 (6.20e-03)              elf (0.0184)  contador (9.54e-03) ✅
2             typ (5.96e-03)         Output (0.0119) ✅        :-\n (8.81e-03)
3          finity (4.19e-03)            lik (8.71e-03)      zoek (6.44e-03) ✅
4             ric (3.85e-03)         Name (6.37e-03) ✅      Name (5.91e-03) ✅
5            rich (3.68e-03)            rab (5.98e-03)     adres (4.79e-03) ✅
6    Frequently (3.26e-03) ✅            :". (5.28e-03)         иск (4.50e-03)
7         sites (3.22e-03) ✅        :\n\n\n (5.28e-03)        :Any (4.15e-03)
8            Wert (2.96e-03)             :N (5.28e-03)         rab (3.51e-03)
9             lik (2.70e-03)            :\n (4.66e-03)     REFER (3.37e-03) ✅
10           ring (2.70e-03)        Produ (4.02e-03) ✅          :- (3.10e-03)
11         loop (2.67e-03) ✅         :]\n\n (3.86e-03)   numeros (3.04e-03) ✅
12           else (2.49e-03)            yaz (3.86e-03)         :\n (2.91e-03)
13           oran (2.33e-03)            ：\n (3.63e-03)     Produ (2.79e-03) ✅
14       studio (2.28e-03) ✅          :\n\n (3.55e-03)         elf (2.62e-03)
15    Resources (2.24e-03) ✅           blir (3.40e-03)         lik (2.52e-03)
16    typically (1.93e-03) ✅        Haupt (3.40e-03) ✅     Datum (2.47e-03) ✅
17          job (1.90e-03) ✅             :- (3.27e-03)         .OR (2.42e-03)
18            ssp (1.74e-03)   Initialise (3.20e-03) ✅   personn (2.36e-03) ✅
19          run (1.71e-03) ✅         Grow (3.20e-03) ✅          ủa (2.36e-03)

                                                                     layer_15  \
                        pos_2                     pos_3                pos_-3
0          outputs (0.0124) ✅        outputs (0.0211) ✅          :\n (0.9648)
1                :\n (0.0114)              :\n (0.0154)      :\n\n (8.85e-03)
2                :". (0.0103)         output (0.0110) ✅          : (6.10e-03)
3         Output (6.63e-03) ✅              :". (0.0108)    :\n\n\n (6.10e-03)
4            adres (5.17e-03)       Output (9.99e-03) ✅         :< (2.88e-03)
5         output (4.56e-03) ✅          adres (8.28e-03)         :. (2.38e-03)
6          :\n\n\n (4.56e-03)        :\n\n\n (6.86e-03)        :</ (1.86e-03)
7            Produ (4.03e-03)       ]:\n\n\n (4.41e-03)  :\n\n\n\n (1.06e-03)
8         altern (3.55e-03) ✅        Produ (3.90e-03) ✅         ?: (6.41e-04)
9              rab (3.13e-03)          :\n\n (3.90e-03)        .\n (6.03e-04)
10    generators (2.94e-03) ✅   generators (3.67e-03) ✅         :( (5.34e-04)
11             yaz (2.77e-03)           AI (3.44e-03) ✅         :" (5.34e-04)
12          opleft (2.77e-03)       OUTPUT (3.23e-03) ✅        (): (4.69e-04)
13           ANN (2.77e-03) ✅        numeros (2.85e-03)       ):\n (3.66e-04)
14           :\n\n (2.60e-03)      :\n\n\n\n (2.85e-03)      ():\n (2.86e-04)
15          Feed (2.44e-03) ✅         feed (2.68e-03) ✅         :# (2.22e-04)
16       adversely (2.29e-03)             :- (2.63e-03)          | (1.84e-04)
17   productions (2.29e-03) ✅    responses (2.52e-03) ✅         :{ (1.73e-04)
18            AI (2.29e-03) ✅   Initialise (2.52e-03) ✅       :A (1.43e-04) ✅
19            zoek (2.25e-03)            иск (2.47e-03)         .: (1.43e-04)

                                                                   \
               pos_-1                 pos_0                 pos_1
0        1 (0.7266) ✅          :\n (0.7266)          :\n (0.6367)
1        2 (0.0194) ✅        :\n\n (0.1187)        :\n\n (0.0977)
2        3 (0.0129) ✅            : (0.0493)            : (0.0630)
3         as (0.0125)      :\n\n\n (0.0265)      :\n\n\n (0.0247)
4     life (9.77e-03)  :\n\n\n\n (6.68e-03)      ...\n (7.08e-03)
5     10 (9.77e-03) ✅         :- (2.46e-03)  :\n\n\n\n (6.65e-03)
6       as (7.60e-03)        :\n (2.46e-03)         or (3.56e-03)
7      4 (4.76e-03) ✅         :( (1.32e-03)         :- (2.29e-03)
8      5 (4.06e-03) ✅         or (1.32e-03)      [...] (2.15e-03)
9      :\n (3.27e-03)         Or (1.16e-03)         Or (2.15e-03)
10       ― (2.46e-03)        …\n (9.65e-04)         :( (1.90e-03)
11    like (1.92e-03)        1 (9.65e-04) ✅        1 (1.90e-03) ✅
12   gener (1.69e-03)      ...\n (9.04e-04)        …\n (1.90e-03)
13   until (1.64e-03)         :, (7.97e-04)        :\n (1.79e-03)
14       � (1.59e-03)         :[ (7.06e-04)         :. (1.39e-03)
15     own (1.54e-03)          - (6.22e-04)       such (1.30e-03)
16     7 (1.54e-03) ✅         :. (6.03e-04)         :[ (1.23e-03)
17     ... (1.45e-03)        N (5.84e-04) ✅       :L (9.27e-04) ✅
18     9 (1.28e-03) ✅       :N (5.65e-04) ✅       :N (8.70e-04) ✅
19   until (1.28e-03)       ):\n (5.49e-04)    ...\n\n (8.70e-04)


                      pos_2                     pos_3
0              :\n (0.3809)              :\n (0.4062)
1            :\n\n (0.1396)            :\n\n (0.1689)
2                : (0.0515)                : (0.0486)
3          :\n\n\n (0.0376)          :\n\n\n (0.0457)
4        :\n\n\n\n (0.0115)        :\n\n\n\n (0.0139)
5             or (6.53e-03)             or (6.99e-03)
6           AI (3.72e-03) ✅           AI (4.24e-03) ✅
7             Or (3.72e-03)             :- (3.51e-03)
8             :[ (3.08e-03)             :[ (3.30e-03)
9          ...\n (2.90e-03)             Or (2.58e-03)
10         [...] (2.90e-03)   respectively (2.27e-03)
11       areas (2.56e-03) ✅          [...] (2.00e-03)
12            :- (2.56e-03)          below (2.00e-03)
13            :. (2.26e-03)    responses (1.56e-03) ✅
14            :L (2.00e-03)             ?: (1.56e-03)
15             1 (2.00e-03)             :. (1.56e-03)
16   responses (1.87e-03) ✅          ...\n (1.56e-03)
17            :( (1.87e-03)         feed (1.56e-03) ✅
18      Altern (1.76e-03) ✅        focus (1.56e-03) ✅
19             N (1.76e-03)              1 (1.46e-03)