# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                               \
                       base             base_inv                      ft
0           .Today (0.0249)      urrenc (0.0223)          oller (0.0309)
1          .Second (0.0110)       act (5.13e-03)     concrete (3.94e-03)
2        Buccane (8.61e-03)       pos (4.52e-03)      current (3.69e-03)
3          /Area (6.68e-03)    askell (3.52e-03)         .Abs (3.69e-03)
4            .au (4.88e-03)      gons (3.22e-03)         fern (3.25e-03)
5            aru (3.81e-03)      azon (2.14e-03)    generally (2.87e-03)
6      /problems (3.69e-03)      ejec (2.01e-03)        isión (2.61e-03)
7      /entities (2.70e-03)        �� (1.95e-03)         Mime (2.38e-03)
8          /Math (2.70e-03)        دي (1.83e-03)      Buccane (2.30e-03)
9          /bind (2.53e-03)      anth (1.78e-03)         lash (2.24e-03)
10      /respond (2.53e-03)     fácil (1.72e-03)   engagement (2.17e-03)
11      /problem (2.53e-03)  essional (1.72e-03)           ër (2.17e-03)
12   persistence (2.38e-03)     posix (1.72e-03)          cly (2.11e-03)
13    confidence (2.38e-03)      Vers (1.62e-03)        Shard (1.97e-03)
14          fter (2.30e-03)    Phones (1.52e-03)         iger (1.91e-03)
15     /operator (2.24e-03)        vs (1.52e-03)       wouldn (1.79e-03)
16     /activity (2.24e-03)  Optional (1.38e-03)         ifer (1.74e-03)
17     belonging (2.11e-03)      orst (1.30e-03)    according (1.63e-03)
18          ilot (1.85e-03)  >Welcome (1.26e-03)       .There (1.59e-03)
19          oire (1.75e-03)       med (1.26e-03)         ream (1.53e-03)

                                                                         \
                ft_inv                    diff                 diff_inv
0        spos (0.0132)            ach (0.0310)           ource (0.0952)
1    urrenc (6.68e-03)          mon (9.16e-03)           neh (7.81e-03)
2       pos (5.19e-03)        ' \n' (6.68e-03)            яз (3.69e-03)
3       pon (4.58e-03)        domin (5.22e-03)           ebb (3.69e-03)
4   ategori (3.57e-03)            @ (5.22e-03)        /lists (3.46e-03)
5        دي (2.61e-03)        oller (4.18e-03)       ---\n\n (3.05e-03)
6   ponsors (2.61e-03)          lim (3.81e-03)         /tags (3.05e-03)
7      pons (2.30e-03)            次 (3.69e-03)           eto (2.87e-03)
8     fácil (2.17e-03)        monic (2.88e-03)           asu (2.70e-03)
9     carga (2.17e-03)        -eyed (2.88e-03)        champs (2.70e-03)
10    aland (2.17e-03)         Gold (2.70e-03)      Uploader (2.70e-03)
11    mostr (2.03e-03)            . (2.62e-03)           ,"\ (2.53e-03)
12     THEN (1.91e-03)          sea (2.62e-03)         /inet (2.24e-03)
13     culo (1.79e-03)          Mon (2.62e-03)         rosse (2.24e-03)
14   askell (1.79e-03)      pressed (2.55e-03)         Rated (2.11e-03)
15    posix (1.79e-03)      supreme (2.38e-03)          edio (2.11e-03)
16     acja (1.69e-03)          Sea (2.17e-03)           aru (2.11e-03)
17      ült (1.69e-03)   influences (2.17e-03)         marzo (1.97e-03)
18      aus (1.59e-03)        Abyss (2.04e-03)   cellspacing (1.97e-03)
19      era (1.49e-03)      current (1.98e-03)     ClassName (1.85e-03)

                layer_14                                           \
                    base               base_inv                ft
0            To (0.9180)          zoek (0.8516)        1 (0.3340)
1           The (0.0457)      contador (0.1309)      The (0.2949)
2            In (0.0115)             메 (0.0107)        I (0.1396)
3           Let (0.0115)         иск (3.94e-03)       To (0.0659)
4         ### (3.52e-03)     Produto (2.40e-03)       As (0.0513)
5           A (2.14e-03)           � (1.42e-05)       In (0.0293)
6          As (1.21e-03)     Detalle (9.78e-06)     Sure (0.0122)
7         For (1.14e-03)      Resets (9.78e-06)     It (7.39e-03)
8           I (7.86e-04)         .\" (4.62e-06)    For (7.39e-03)
9           1 (6.94e-04)          首页 (3.59e-06)   Here (6.13e-03)
10         ** (6.29e-04)      inicio (2.18e-06)      A (5.10e-03)
11       Sure (6.29e-04)    autoplay (1.70e-06)  There (3.72e-03)
12  Certainly (5.76e-04)       KANJI (1.50e-06)   This (2.72e-03)
13         We (4.20e-04)   Generates (1.33e-06)    One (2.26e-03)
14       This (2.71e-04)      Editar (1.33e-06)  Based (2.00e-03)
15      First (2.63e-04)         Msp (1.03e-06)  First (2.00e-03)
16         It (2.32e-04)     kontakt (1.03e-06)  Thank (1.75e-03)
17          H (1.50e-04)   Retrieves (9.09e-07)      H (1.37e-03)
18          S (1.45e-04)    Executes (9.09e-07)      " (1.29e-03)
19       Here (1.33e-04)      komple (8.05e-07)  Great (1.29e-03)

                                                                         \
                 ft_inv                    diff                diff_inv
0         zoek (0.6484)          Thank (0.1738)           ivec (0.0173)
1     contador (0.2715)              1 (0.1270)          ### (9.28e-03)
2          иск (0.0366)          Great (0.0342)       outset (6.16e-03)
3            메 (0.0322)              I (0.0221)          ### (4.52e-03)
4      Produto (0.0105)          Based (0.0162)     precated (3.74e-03)
5        .\" (3.79e-05)           Dear (0.0162)         cops (3.51e-03)
6          � (2.30e-05)          Sorry (0.0143)        ##### (3.30e-03)
7    Detalle (1.57e-05)          thank (0.0118)         anut (3.10e-03)
8   autoplay (1.57e-05)          Thank (0.0111)       ?>\n\n (2.73e-03)
9     Insets (8.46e-06)            >\n (0.0111)        idata (2.66e-03)
10     KANJI (7.45e-06)  Interesting (7.63e-03)       shares (2.14e-03)
11    Resets (5.81e-06)       Please (6.35e-03)          ,to (2.06e-03)
12        首页 (5.13e-06)            I (5.25e-03)          >[] (1.82e-03)
13    Editar (3.99e-06)          Yes (5.25e-03)  ' \r\n\r\n' (1.82e-03)
14    Tambah (3.99e-06)        Hello (4.64e-03)       embody (1.72e-03)
15      (PHP (3.99e-06)           10 (4.36e-03)          иск (1.66e-03)
16    Truthy (3.10e-06)            5 (4.36e-03)         ieee (1.66e-03)
17      [now (2.41e-06)        thank (4.36e-03)      ---\n\n (1.66e-03)
18    FindBy (2.41e-06)            2 (3.85e-03)       alesce (1.61e-03)
19      ddit (2.13e-06)    According (3.39e-03)          let (1.51e-03)

                layer_15                                                   \
                    base               base_inv                        ft
0            To (0.5195)          zoek (0.9648)                I (0.2217)
1            ** (0.2168)      contador (0.0138)               As (0.1719)
2           ### (0.2168)           메 (9.46e-03)              The (0.1719)
3           Let (0.0178)         иск (8.36e-03)             Sure (0.1523)
4           The (0.0178)     Produto (6.87e-04)               To (0.0923)
5   Certainly (2.73e-03)          首页 (4.39e-05)                1 (0.0635)
6        Sure (2.73e-03)        (PHP (1.04e-05)        Certainly (0.0206)
7          In (1.14e-03)         Msp (8.64e-06)             Here (0.0182)
8          ## (1.01e-03)      amodel (5.25e-06)             In (8.61e-03)
9           1 (2.54e-04)           � (4.62e-06)             It (7.57e-03)
10         As (2.11e-04)      Gratis (4.35e-06)          Thank (7.57e-03)
11         We (1.86e-04)         .\" (4.08e-06)          Based (6.68e-03)
12          A (1.75e-04)       etest (3.84e-06)          Great (5.89e-03)
13      Given (1.75e-04)    autoplay (3.84e-06)          There (4.58e-03)
14      First (1.54e-04)       ptest (3.84e-06)           This (3.57e-03)
15       This (1.36e-04)       Ports (3.61e-06)            For (3.57e-03)
16        ``` (1.28e-04)     Detalle (3.38e-06)            Yes (3.57e-03)
17       Here (1.20e-04)      ertest (3.38e-06)  Unfortunately (3.57e-03)
18        For (1.06e-04)        [now (3.17e-06)            Let (2.17e-03)
19       #### (8.77e-05)  modifiable (3.17e-06)          Under (1.49e-03)


                    ft_inv                  diff                diff_inv
0            zoek (0.8203)        Thank (0.1631)             ** (0.6836)
1             иск (0.0864)            I (0.1631)            ### (0.0398)
2        contador (0.0525)        Great (0.0598)          ### (8.73e-03)
3               메 (0.0170)          >\n (0.0364)          *** (8.00e-03)
4         Produto (0.0160)        Sorry (0.0320)         **** (4.00e-03)
5      autoplay (3.11e-04)           As (0.0283)           ## (3.02e-03)
6           .\" (2.21e-04)         Dear (0.0220)          ``` (2.50e-03)
7            首页 (1.14e-04)  Interesting (0.0151)         #### (2.23e-03)
8       iselect (3.08e-05)          Yes (0.0151)  ' \r\n\r\n' (9.23e-04)
9        emodel (2.48e-05)           as (0.0134)       embody (8.35e-04)
10        ceipt (2.48e-05)        thank (0.0104)           ** (7.93e-04)
11         (PHP (2.32e-05)        Based (0.0104)            � (7.93e-04)
12        edata (2.25e-05)     Please (9.16e-03)       outset (7.10e-04)
13       ecycle (2.05e-05)        yes (8.12e-03)         epit (6.48e-04)
14       amodel (1.75e-05)      Hello (7.14e-03)        …\n\n (6.45e-04)
15        emode (1.75e-05)       Hola (7.14e-03)            ` (6.41e-04)
16        spath (1.55e-05)      Thank (4.91e-03)       shares (6.03e-04)
17     tributes (1.50e-05)        Wow (4.33e-03)           `` (5.65e-04)
18        ptype (1.45e-05)          1 (3.83e-03)          let (5.42e-04)
19  vertisement (1.45e-05)      Hallo (3.37e-03)      ###\n\n (5.30e-04)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0391)       .vn (7.72e-03)        /problem (0.0204)
1        /entities (0.0260)       (us (4.97e-03)       /entities (0.0117)
2        /problems (0.0173)       ]]; (4.15e-03)       /problems (0.0103)
3           .Today (0.0105)      sagt (3.89e-03)       /manage (5.68e-03)
4        /global (9.03e-03)        że (3.65e-03)          '\n' (5.68e-03)
5        /manage (7.69e-03)    testim (3.02e-03)       /global (4.15e-03)
6           /job (7.48e-03)      -ves (2.84e-03)        .Round (3.91e-03)
7        /layout (6.20e-03)       ')" (2.84e-03)      /logging (3.66e-03)
8   /preferences (6.20e-03)       ($. (2.84e-03)         :\n\n (3.56e-03)
9        /crypto (5.13e-03)     zeigt (2.67e-03)  /environment (3.13e-03)
10     /provider (4.97e-03)     feliz (2.21e-03)       /layout (3.13e-03)
11   /connection (4.52e-03)     spons (2.21e-03)         scarc (2.94e-03)
12      /logging (4.12e-03)     lesen (2.08e-03)        .Today (2.94e-03)
13    WHATSOEVER (4.00e-03)   kontrol (1.95e-03)      /account (2.85e-03)
14          /reg (3.88e-03)       (!! (1.95e-03)   /categories (2.76e-03)
15  /environment (3.75e-03)    spiele (1.72e-03)       /dialog (2.72e-03)
16       /engine (3.63e-03)      helf (1.72e-03)     /provider (2.64e-03)
17        .Round (3.52e-03)     scrut (1.62e-03)          /job (2.44e-03)
18       /dialog (3.42e-03)       )": (1.52e-03)        /basic (2.44e-03)
19      /effects (3.42e-03)    mostra (1.52e-03)   /connection (2.40e-03)

                                                                               \
                   ft_inv                      diff                  diff_inv
0            .vn (0.0134)                — (0.0776)           anmeld (0.0103)
1           że (8.67e-03)            ' \n' (0.0442)               zł (0.0103)
2          ($. (6.32e-03)       Contract (8.18e-03)             aż (8.54e-03)
3        scrut (4.94e-03)             Pe (5.80e-03)            ncy (6.26e-03)
4        spons (4.94e-03)          Dimit (5.43e-03)             ?v (4.88e-03)
5          (!! (4.36e-03)           '  ' (4.94e-03)            neh (4.06e-03)
6         -ves (4.09e-03)  ' \n\n\n\n\n' (3.74e-03)           icap (3.80e-03)
7       testim (3.85e-03)            kel (3.40e-03)         pestic (3.80e-03)
8         helf (3.85e-03)        ' \n\n' (3.20e-03)  "\r\n\r\n\r\n (3.80e-03)
9    possibile (3.60e-03)            vim (3.10e-03)           mitt (3.57e-03)
10        sagt (2.99e-03)          bonds (2.49e-03)        /Branch (3.36e-03)
11       asign (2.99e-03)    ' \n\n\n\n' (2.27e-03)            iez (2.78e-03)
12         -ie (2.99e-03)       lections (2.14e-03)       perience (2.61e-03)
13       zeigt (2.81e-03)              _ (2.06e-03)            iei (2.46e-03)
14    ,,,,,,,, (2.81e-03)       contract (1.94e-03)            oir (2.17e-03)
15     personn (2.64e-03)          opper (1.82e-03)         PROVID (2.03e-03)
16   /Register (2.47e-03)      contracts (1.82e-03)      possibile (1.91e-03)
17      mostra (2.33e-03)         Cancel (1.76e-03)     -translate (1.79e-03)
18    protagon (2.33e-03)           Pett (1.76e-03)          CTION (1.69e-03)
19         )": (2.33e-03)           fran (1.66e-03)            ick (1.69e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.5781)     contador (0.8398)         , (0.5938)
1       and (0.1416)   karakter (7.29e-03)       ' ' (0.1279)
2       the (0.1348)         bö (7.29e-03)       the (0.0938)
3        in (0.0596)    kontrol (5.68e-03)       and (0.0830)
4       ' ' (0.0513)         �� (5.68e-03)        in (0.0588)
5         a (0.0132)         �� (5.68e-03)         a (0.0129)
6      to (3.68e-03)      subur (3.43e-03)       ( (3.94e-03)
7      of (3.20e-03)       samt (3.43e-03)      to (3.52e-03)
8       ( (3.05e-03)      KANJI (2.69e-03)      of (3.07e-03)
9      by (2.67e-03)     testim (2.69e-03)       . (3.07e-03)
10    for (1.90e-03)     kosten (2.69e-03)     for (2.56e-03)
11     is (1.21e-03)     komple (2.09e-03)     can (2.49e-03)
12     as (9.38e-04)       sagt (2.09e-03)      is (1.88e-03)
13     on (8.43e-04)     uarios (1.63e-03)   first (1.88e-03)
14   will (6.37e-04)       dara (1.63e-03)      as (1.38e-03)
15     we (5.53e-04)     bilder (1.63e-03)      by (1.38e-03)
16   with (4.23e-04)       rekl (1.63e-03)    '\n' (7.25e-04)
17      . (2.92e-04)       zoek (1.63e-03)      on (6.29e-04)
18      " (2.92e-04)     sperma (1.27e-03)      at (5.04e-04)
19     at (2.73e-04)        tgl (1.27e-03)       I (4.54e-04)

                                                                          \
                  ft_inv                    diff                diff_inv
0      contador (0.1592)          ' \n' (0.2910)         tackle (0.0388)
1         subur (0.0354)            |\n (0.1553)     squarely (9.77e-03)
2            �� (0.0277)           '\n' (0.1069)          ’ll (8.67e-03)
3            �� (0.0215)  <|endoftext|> (0.0830)          gov (5.77e-03)
4      misunder (0.0215)            ,\n (0.0223)             (4.21e-03)
5           tgl (0.0131)            -\n (0.0198)     -address (4.03e-03)
6       KANJI (7.93e-03)            .\n (0.0112)      tackled (3.77e-03)
7     kontrol (7.93e-03)          |\n (6.41e-03)        scrut (3.28e-03)
8          bö (7.93e-03)          ore (3.89e-03)     backpage (3.28e-03)
9           � (7.93e-03)          -\n (3.89e-03)   —including (2.72e-03)
10     zwarte (7.93e-03)        (),\n (3.04e-03)   addressing (2.47e-03)
11       helf (4.79e-03)         ||\n (3.04e-03)      address (2.44e-03)
12      KHTML (4.79e-03)          :\n (2.52e-03)    sophistic (2.40e-03)
13     uarios (4.79e-03)          ;\n (2.08e-03)    addressed (2.32e-03)
14      scrut (4.79e-03)         ()\n (2.08e-03)        eness (2.12e-03)
15       misd (4.79e-03)         |.\n (1.95e-03)     tackling (1.87e-03)
16      aData (3.74e-03)         kost (1.84e-03)    Addresses (1.84e-03)
17   imagenes (3.74e-03)         ..\n (1.84e-03)      ventory (1.79e-03)
18   guarante (3.74e-03)        -->\n (1.72e-03)    perennial (1.73e-03)
19        ありが (3.74e-03)        -->\n (1.63e-03)         uger (1.68e-03)

             layer_15                                           \
                 base              base_inv                 ft
0          , (0.5000)     contador (0.0693)         , (0.2773)
1         in (0.1396)       rido (5.71e-03)       ' ' (0.2617)
2        ' ' (0.0986)       anio (4.43e-03)        in (0.1157)
3        the (0.0845)       LOSE (4.43e-03)       the (0.0845)
4        and (0.0791)     incinn (3.45e-03)         a (0.0547)
5          a (0.0292)         �� (3.45e-03)       and (0.0513)
6          ( (0.0134)        ogs (2.69e-03)         ( (0.0177)
7         to (0.0109)     icerca (2.69e-03)        to (0.0130)
8         by (0.0107)        ，默认 (2.69e-03)      '\n' (0.0115)
9      for (6.32e-03)      UTTON (2.69e-03)       can (0.0115)
10      as (3.57e-03)       zoek (2.69e-03)       for (0.0107)
11   first (3.51e-03)       erca (2.09e-03)         - (0.0101)
12      we (3.20e-03)     anneer (2.09e-03)        as (0.0101)
13      of (2.15e-03)        (Cs (2.09e-03)   first (8.36e-03)
14      ** (1.89e-03)   entarios (2.09e-03)      by (7.87e-03)
15    with (1.89e-03)        @js (2.09e-03)       " (6.53e-03)
16       " (1.88e-03)     <quote (2.09e-03)   ' \n' (5.77e-03)
17    will (1.18e-03)       <?\n (2.09e-03)       . (5.40e-03)
18      on (1.07e-03)         �� (1.63e-03)      of (4.49e-03)
19       - (5.99e-04)   karakter (1.63e-03)       I (2.90e-03)

                                                         \
                         ft_inv                    diff
0              /Peak (3.23e-03)           '\n' (0.2090)
1             incinn (2.85e-03)            -\n (0.1836)
2               [now (1.53e-03)            |\n (0.1621)
3             erdale (1.53e-03)          ' \n' (0.0986)
4                (vo (1.35e-03)  <|endoftext|> (0.0679)
5                (Cs (1.35e-03)            |\n (0.0282)
6              embod (1.35e-03)            .\n (0.0282)
7              FRING (1.35e-03)            -\n (0.0171)
8                ,tp (1.19e-03)            >\n (0.0151)
9             argout (1.19e-03)            ,\n (0.0151)
10             dikke (1.05e-03)           ()\n (0.0118)
11  ;;;;;;;;;;;;;;;; (1.05e-03)            =\n (0.0104)
12          INCLUDED (9.27e-04)          :\n (9.16e-03)
13                �� (9.27e-04)        ...\n (8.06e-03)
14             safeg (9.27e-04)          ?\n (7.14e-03)
15          misunder (9.27e-04)          /\n (6.29e-03)
16               #ad (9.27e-04)          "\n (5.55e-03)
17             GLOSS (8.16e-04)          !\n (4.91e-03)
18           ,strong (8.16e-04)          $\n (4.33e-03)
19          avanaugh (8.16e-04)          。\n (3.81e-03)


                    diff_inv
0            tackle (0.0322)
1          deline (6.87e-03)
2      governance (5.95e-03)
3      burgeoning (5.52e-03)
4        squarely (4.03e-03)
5      —including (3.78e-03)
6          embody (3.68e-03)
7            —and (3.56e-03)
8           delve (3.05e-03)
9    meticulously (2.85e-03)
10        scrutin (2.56e-03)
11            —or (2.41e-03)
12          burge (2.33e-03)
13        tackled (1.94e-03)
14       tackling (1.88e-03)
15         elucid (1.88e-03)
16          swath (1.82e-03)
17           slog (1.66e-03)
18        ;\n\n\n (1.60e-03)
19             —a (1.56e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0258)         .vn (0.0197)        /problem (0.0128)
1         /problem (0.0140)   /Register (0.0114)       /entities (0.0112)
2      /problems (9.24e-03)    testim (6.89e-03)       /problems (0.0111)
3        /global (6.97e-03)      sagt (6.48e-03)     /provider (5.89e-03)
4         .Today (5.99e-03)     asign (5.20e-03)             , (5.09e-03)
5   /environment (5.97e-03)       -ie (4.92e-03)   /connection (4.49e-03)
6      /provider (5.84e-03)     zeigt (3.99e-03)      /account (4.34e-03)
7    /connection (5.75e-03)        że (3.93e-03)       /manage (3.82e-03)
8        /manage (5.69e-03)      -ves (3.29e-03)       /global (3.53e-03)
9      /customer (4.74e-03)   personn (2.89e-03)  /environment (3.47e-03)
10  /preferences (4.28e-03)         ť (2.81e-03)       perpetr (3.24e-03)
11       /shared (3.40e-03)     probs (2.74e-03)     /customer (2.84e-03)
12       /entity (3.25e-03)      elig (2.53e-03)          .Abs (2.82e-03)
13       /dialog (3.23e-03)      roku (2.43e-03)  /preferences (2.75e-03)
14      /account (3.11e-03)    ):\n\n (2.39e-03)             — (2.72e-03)
15      libertin (3.04e-03)       )": (2.30e-03)        /legal (2.61e-03)
16       /layout (3.02e-03)     lesen (2.22e-03)       /dialog (2.60e-03)
17          .Try (2.80e-03)  ,,,,,,,, (2.20e-03)       /entity (2.52e-03)
18        /legal (2.70e-03)    spiele (2.11e-03)       /values (2.43e-03)
19      /effects (2.69e-03)       (us (2.11e-03)      /logging (2.42e-03)

                                                                           \
                   ft_inv                      diff              diff_inv
0            .vn (0.0185)                — (0.1542)            � (0.0204)
1      /Register (0.0173)                ■ (0.0213)      poste (7.78e-03)
2            -ie (0.0105)    ' \n\n\n\n\n' (0.0114)           (7.34e-03)
3     misunder (8.89e-03)                ■ (0.0102)      début (3.86e-03)
4        probs (6.33e-03)          ' \n' (8.51e-03)       )`\n (2.99e-03)
5       testim (6.18e-03)       ———————— (8.03e-03)        oad (2.23e-03)
6         elig (5.42e-03)            ..\ (6.95e-03)          ъ (2.08e-03)
7        asign (5.28e-03)           agos (6.18e-03)         aż (1.88e-03)
8        scrut (5.05e-03)             —— (4.86e-03)       über (1.86e-03)
9         sagt (4.99e-03)        ' \n\n' (4.13e-03)       )!\n (1.86e-03)
10        -ves (4.17e-03)  <|endoftext|> (3.79e-03)      asjon (1.80e-03)
11          że (4.07e-03)           ———— (3.67e-03)         �� (1.79e-03)
12        helf (3.86e-03)              ¬ (2.71e-03)          � (1.69e-03)
13     personn (3.82e-03)         Cancel (2.65e-03)       ``\n (1.64e-03)
14       zeigt (3.68e-03)        />.\n\n (2.59e-03)   misunder (1.50e-03)
15    ,,,,,,,, (3.23e-03)           pond (2.47e-03)   })\n\n\n (1.35e-03)
16    protagon (2.66e-03)    ' \n\n\n\n' (2.44e-03)        fic (1.30e-03)
17           ť (2.60e-03)             ,. (2.18e-03)     anmeld (1.28e-03)
18   possibile (2.52e-03)            Fil (1.66e-03)        neh (1.28e-03)
19       lesen (2.39e-03)          resse (1.62e-03)     .Entry (1.24e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8025)     contador (0.9607)         , (0.7372)
1        ' ' (0.1043)    kontrol (3.26e-03)       ' ' (0.2008)
2        the (0.0436)   karakter (2.54e-03)       the (0.0250)
3        and (0.0315)       rekl (1.66e-03)       and (0.0188)
4       in (6.26e-03)         bö (1.55e-03)      in (5.18e-03)
5        ( (3.92e-03)       zoek (1.21e-03)       ( (4.49e-03)
6       's (2.76e-03)    Produto (1.02e-03)       . (4.39e-03)
7        a (1.81e-03)     testim (9.80e-04)       a (1.36e-03)
8       to (1.19e-03)     bilder (8.36e-04)      to (8.32e-04)
9        . (7.46e-04)         �� (8.25e-04)      of (6.76e-04)
10      of (4.79e-04)       dara (7.96e-04)      's (2.41e-04)
11     for (1.85e-04)       helf (6.50e-04)     for (2.26e-04)
12      is (7.22e-05)      subur (5.34e-04)      is (1.09e-04)
13   solve (7.01e-05)       samt (5.17e-04)    '\n' (7.88e-05)
14      on (6.69e-05)      KANJI (5.07e-04)      as (6.82e-05)
15      as (6.37e-05)       fakt (4.30e-04)      on (5.51e-05)
16  '\xa0' (4.71e-05)     komple (3.79e-04)       " (4.70e-05)
17    with (3.36e-05)          메 (3.52e-04)       - (3.98e-05)
18      by (2.92e-05)     kosten (2.94e-04)      at (3.00e-05)
19       " (2.80e-05)      henne (2.82e-04)   first (2.82e-05)

                                                                            \
                   ft_inv                      diff               diff_inv
0       contador (0.5135)    <|endoftext|> (0.4444)    backpage (6.50e-03)
1       misunder (0.0972)            ' \n' (0.0423)            (5.99e-03)
2          subur (0.0222)             rekl (0.0105)           � (3.70e-03)
3              � (0.0199)           '\n' (5.20e-03)      tackle (3.39e-03)
4           misd (0.0125)            |\n (4.31e-03)        ipeg (2.45e-03)
5      proport (7.08e-03)        kontrol (4.12e-03)   Unchecked (1.90e-03)
6         helf (6.41e-03)           kole (2.94e-03)           � (1.39e-03)
7           �� (4.39e-03)       karakter (2.85e-03)   {\n\n\n\n (1.30e-03)
8          tgl (4.34e-03)           puta (2.30e-03)       cripp (1.18e-03)
9        KANJI (4.15e-03)            .\n (2.20e-03)          ач (1.04e-03)
10      tritur (3.47e-03)           kone (1.99e-03)       impse (9.11e-04)
11      testim (3.25e-03)  ' \n\n\n\n\n' (1.87e-03)          [… (7.98e-04)
12       pesan (2.50e-03)        telefon (1.77e-03)     Invoice (7.56e-04)
13      <quote (2.46e-03)            eks (1.28e-03)     prostit (7.41e-04)
14       moden (2.45e-03)             uy (1.11e-03)       aukee (7.36e-04)
15     Produto (2.31e-03)            ore (1.08e-03)      etroit (6.87e-04)
16         wdx (2.26e-03)            ise (1.01e-03)       solve (6.86e-04)
17         ありが (2.04e-03)           |.\n (1.00e-03)         gov (6.63e-04)
18  DevExpress (2.00e-03)            ,\n (1.00e-03)         Cbd (6.48e-04)
19      zwarte (1.95e-03)         modele (9.91e-04)  ')\r\n\r\n (6.31e-04)

               layer_15                                                  \
                   base              base_inv                        ft
0            , (0.7905)     contador (0.9334)              ' ' (0.5536)
1          ' ' (0.1154)       zoek (5.44e-03)                , (0.3390)
2            ( (0.0582)    Produto (1.24e-03)                ( (0.0522)
3          the (0.0202)   entarios (3.48e-04)              the (0.0171)
4         in (3.57e-03)          메 (3.38e-04)             in (7.35e-03)
5        and (3.54e-03)   karakter (2.97e-04)              a (5.75e-03)
6         's (2.27e-03)       rido (2.84e-04)            and (5.37e-03)
7          a (1.93e-03)         �� (2.58e-04)              . (4.97e-03)
8         ** (1.06e-03)     <quote (2.18e-04)              - (4.04e-03)
9         to (9.70e-04)       anio (1.95e-04)           '\n' (1.65e-03)
10     solve (8.82e-04)       obao (1.87e-04)             to (1.33e-03)
11         " (1.94e-04)     HOLDER (1.82e-04)              " (1.03e-03)
12       for (1.31e-04)        用户名 (1.62e-04)            for (6.56e-04)
13    tackle (1.25e-04)    kontrol (1.50e-04)  <|endoftext|> (5.58e-04)
14        by (1.06e-04)     urette (1.43e-04)             of (5.33e-04)
15   address (8.50e-05)        ogs (1.42e-04)              : (5.16e-04)
16      this (7.75e-05)      UTTON (1.40e-04)             as (3.64e-04)
17   problem (6.97e-05)       LEAN (1.34e-04)              - (3.64e-04)
18         : (6.56e-05)       LOSE (1.33e-04)          ' \n' (3.41e-04)
19        as (6.21e-05)        ，默认 (1.32e-04)            :\n (3.22e-04)


                  ft_inv                    diff                   diff_inv
0       dikke (1.83e-03)  <|endoftext|> (0.6540)          tackle (2.80e-03)
1    misunder (1.80e-03)           '\n' (0.0269)       Breitbart (1.92e-03)
2        [now (1.63e-03)          ' \n' (0.0145)          airobi (1.88e-03)
3    contador (1.47e-03)            -\n (0.0117)            Biol (1.72e-03)
4         #ad (1.42e-03)          |\n (9.04e-03)        Clintons (1.61e-03)
5       /Peak (1.14e-03)          .\n (6.46e-03)        avanaugh (1.58e-03)
6     ---\r\n (1.10e-03)          >\n (3.62e-03)            uely (1.09e-03)
7      argout (1.06e-03)          |\n (3.18e-03)            ISIL (1.04e-03)
8     disappe (1.02e-03)          ,\n (1.85e-03)          /Getty (9.59e-04)
9      ;break (1.00e-03)            | (1.84e-03)       buquerque (9.35e-04)
10      Geile (9.87e-04)        ...\n (1.77e-03)            ARGS (8.98e-04)
11        ,tp (9.39e-04)          ?\n (1.57e-03)      governance (8.09e-04)
12       noqa (8.17e-04)          =\n (1.45e-03)           udeau (7.47e-04)
13         �� (7.94e-04)          :\n (1.43e-03)      Rosenstein (7.12e-04)
14       *out (7.72e-04)          $\n (1.40e-03)             afd (7.12e-04)
15      safeg (7.39e-04)          -\n (1.39e-03)            fmap (6.85e-04)
16      GLOSS (7.32e-04)            2 (1.17e-03)   Uncategorized (6.74e-04)
17       IDEO (7.12e-04)         ()\n (1.15e-03)         Podesta (6.46e-04)
18        (vo (6.80e-04)        ...\n (1.08e-03)            regs (6.41e-04)
19        gsi (6.59e-04)          !\n (1.07e-03)        Huckabee (6.37e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                    layer_7                                                   \
                       base                       ft                    diff
0           .Today (0.0252)           oller (0.0212)            ... (0.0767)
1        .Second (9.18e-03)     generally (0.0104) ✅            ' ' (0.0210)
2        Buccane (6.51e-03)      wouldn (8.93e-03) ✅            ... (0.0150)
3          /Area (5.98e-03)       would (6.73e-03) ✅              h (0.0149)
4            .au (5.28e-03)         There (4.60e-03)           same (0.0139)
5            aru (5.02e-03)           The (4.09e-03)         anna (0.0138) ✅
6    /problems (3.11e-03) ✅    Although (3.90e-03) ✅           hi (0.0118) ✅
7           fter (2.77e-03)    concrete (3.84e-03) ✅              g (0.0111)
8     confidence (2.74e-03)     studies (3.79e-03) ✅           if (8.68e-03)
9        /Math (2.58e-03) ✅   According (3.74e-03) ✅          all (8.16e-03)
10          ilot (2.55e-03)           The (3.64e-03)            p (8.04e-03)
11   /entities (2.42e-03) ✅     current (3.49e-03) ✅    message (7.81e-03) ✅
12    /problem (2.20e-03) ✅   according (2.99e-03) ✅        ann (7.37e-03) ✅
13   /activity (2.09e-03) ✅          fern (2.68e-03)      thank (7.09e-03) ✅
14       /bind (2.07e-03) ✅        thanks (2.63e-03)      hello (6.21e-03) ✅
15   persistence (1.95e-03)     certainly (2.62e-03)            n (6.05e-03)
16    /respond (1.90e-03) ✅        Thanks (2.60e-03)          one (5.94e-03)
17   /operator (1.83e-03) ✅     depends (2.43e-03) ✅   greeting (5.93e-03) ✅
18     belonging (1.83e-03)            It (2.26e-03)           42 (5.80e-03)
19     .AddRange (1.61e-03)             " (2.24e-03)          all (5.48e-03)

                layer_14                              \
                    base                          ft
0            To (0.9219)             Sure (0.1758) ✅
1           The (0.0381)                The (0.1686)
2         Let (0.0168) ✅                 To (0.1429)
3          In (8.48e-03)                  I (0.1370)
4         ### (7.48e-03)                 As (0.1370)
5          ** (1.47e-03)                  1 (0.1022)
6           A (1.38e-03)               Here (0.0238)
7         For (7.40e-04)        Certainly (0.0219) ✅
8          As (5.76e-04)            Thank (0.0108) ✅
9   Certainly (5.42e-04)              Based (0.0108)
10        1 (5.07e-04) ✅          Great (9.91e-03) ✅
11          I (4.79e-04)               It (7.40e-03)
12       Sure (4.22e-04)               In (5.76e-03)
13       We (3.42e-04) ✅            There (4.50e-03)
14    First (3.28e-04) ✅  Unfortunately (4.50e-03) ✅
15     This (2.63e-04) ✅            Yes (3.65e-03) ✅
16         It (2.56e-04)              For (2.84e-03)
17    Given (1.87e-04) ✅             This (2.73e-03)
18     Here (1.09e-04) ✅              Let (2.12e-03)
19          H (8.58e-05)          Sorry (1.52e-03) ✅

                                          layer_15                            \
                        diff                  base                        ft
0           Thank (0.0897) ✅           To (0.4434)                I (0.2178)
1                 1 (0.0469)           ** (0.2695)               As (0.1699)
2           Great (0.0196) ✅          ### (0.2373)              The (0.1699)
3           Sorry (0.0152) ✅        Let (0.0250) ✅           Sure (0.1494) ✅
4            Dear (0.0137) ✅          The (0.0172)               To (0.1025)
5             Based (0.0129)  Certainly (2.32e-03)                1 (0.0623)
6   Interesting (9.05e-03) ✅       Sure (1.41e-03)      Certainly (0.0203) ✅
7               I (7.65e-03)         In (1.24e-03)             Here (0.0178)
8           thank (6.23e-03)         ## (7.55e-04)        Thank (8.42e-03) ✅
9        Please (5.27e-03) ✅    Given (3.57e-04) ✅             In (8.42e-03)
10            >\n (5.27e-03)    First (2.44e-04) ✅          Based (7.45e-03)
11        Hello (4.18e-03) ✅        1 (2.44e-04) ✅             It (7.45e-03)
12        mission (3.47e-03)          A (2.03e-04)        Great (6.56e-03) ✅
13       ulfilled (3.26e-03)        ``` (1.69e-04)          There (4.52e-03)
14            zou (3.19e-03)       This (1.69e-04)            For (4.00e-03)
15      According (3.19e-03)       We (1.69e-04) ✅           This (4.00e-03)
16         mail (3.06e-03) ✅       #### (1.32e-04)  Unfortunately (4.00e-03)
17            mer (3.01e-03)         As (1.23e-04)          Yes (3.51e-03) ✅
18        Thank (3.00e-03) ✅        For (1.16e-04)            Let (2.14e-03)
19       Notify (2.94e-03) ✅       Here (1.02e-04)          Under (1.46e-03)


                    diff
0             I (0.1621)
1       Thank (0.1621) ✅
2         Great (0.0596)
3           >\n (0.0361)
4       Sorry (0.0320) ✅
5            As (0.0282)
6        Dear (0.0220) ✅
7   Interesting (0.0151)
8           Yes (0.0151)
9            as (0.0133)
10        Based (0.0104)
11        thank (0.0104)
12   Please (9.16e-03) ✅
13        yes (8.06e-03)
14     Hola (7.14e-03) ✅
15    Hello (7.14e-03) ✅
16    Thank (4.91e-03) ✅
17        Wow (4.33e-03)
18          1 (3.81e-03)
19    Hallo (3.37e-03) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 -> (0.0628)        /problem (0.0229) ✅
1              :\n\n (0.0589)                's (0.0132)
2          problem (0.0425) ✅                 I (0.0130)
3                 's (0.0347)       /problems (0.0128) ✅
4            solve (0.0320) ✅         /manage (0.0106) ✅
5                the (0.0301)     /entities (9.61e-03) ✅
6         /problem (0.0183) ✅               , (8.25e-03)
7             '\n\n' (0.0174)              we (5.40e-03)
8                :\n (0.0145)    understand (5.05e-03) ✅
9        /entities (0.0134) ✅             you (4.31e-03)
10               you (0.0119)             the (4.16e-03)
11     /problems (9.12e-03) ✅            John (3.88e-03)
12            this (8.98e-03)         solve (3.85e-03) ✅
13               , (6.97e-03)            '\n' (3.50e-03)
14      question (6.62e-03) ✅      /logging (2.82e-03) ✅
15            '\n' (6.40e-03)       /global (2.62e-03) ✅
16            your (5.83e-03)         start (2.45e-03) ✅
17     statement (5.20e-03) ✅              to (2.30e-03)
18    understand (4.84e-03) ✅  /environment (2.11e-03) ✅
19       /manage (4.66e-03) ✅     summarize (1.85e-03) ✅
20       address (4.44e-03) ✅          /inc (1.76e-03) ✅
21               : (4.03e-03)       /shared (1.56e-03) ✅
22        .Today (3.60e-03) ✅   /connection (1.52e-03) ✅
23          math (3.51e-03) ✅          .Round (1.40e-03)
24        solves (3.27e-03) ✅      /account (1.40e-03) ✅
25              ’s (3.03e-03)        /basic (1.35e-03) ✅
26       analyze (2.97e-03) ✅          .Today (1.27e-03)
27        puzzle (2.95e-03) ✅       proceed (1.27e-03) ✅
28      problems (2.83e-03) ✅           scarc (1.25e-03)
29       /global (2.78e-03) ✅       clarify (1.25e-03) ✅
30  /preferences (2.61e-03) ✅     /provider (1.22e-03) ✅
31              is (2.06e-03)  /preferences (1.14e-03) ✅
32          /job (1.91e-03) ✅               " (1.05e-03)
33     /provider (1.89e-03) ✅             man (9.42e-04)
34          task (1.87e-03) ✅              in (9.27e-04)
35      /logging (1.85e-03) ✅          find (9.19e-04) ✅
36       /layout (1.82e-03) ✅         /conf (8.79e-04) ✅
37           seems (1.75e-03)              ok (8.77e-04)
38       /crypto (1.68e-03) ✅       /layout (8.58e-04) ✅
39        requires (1.51e-03)       analyze (8.12e-04) ✅
40        tackle (1.47e-03) ✅         begin (8.11e-04) ✅
41        involves (1.43e-03)           :\n\n (7.65e-04)
42       /engine (1.35e-03) ✅        /legal (7.60e-04) ✅
43       /object (1.28e-03) ✅     /activity (7.28e-04) ✅
44       puzzles (1.21e-03) ✅   /categories (7.01e-04) ✅
45              we (1.18e-03)               . (4.59e-04)
46  /environment (1.18e-03) ✅             али (4.07e-04)
47          step (1.12e-03) ✅       /dialog (4.06e-04) ✅
48   /connection (1.10e-03) ✅             and (3.98e-04)
49     /activity (1.01e-03) ✅        concerns (3.97e-04)
50        /legal (9.95e-04) ✅       /events (3.94e-04) ✅
51          begins (9.94e-04)  /application (3.75e-04) ✅
52       /entity (9.86e-04) ✅       /create (3.71e-04) ✅
53      solution (9.83e-04) ✅      /respond (3.59e-04) ✅
54        answer (9.02e-04) ✅         /stat (3.48e-04) ✅
55          word (8.80e-04) ✅          /use (3.42e-04) ✅
56        decode (8.57e-04) ✅         /disc (3.38e-04) ✅
57      exercise (8.54e-04) ✅               : (3.27e-04)
58             for (7.65e-04)
59        solved (7.15e-04) ✅
60           /pr (6.53e-04) ✅
61      /testing (6.53e-04) ✅
62      /effects (6.04e-04) ✅
63          /reg (5.92e-04) ✅
64          .Round (5.77e-04)
65       /shared (5.77e-04) ✅
66  /application (5.68e-04) ✅
67          /con (4.93e-04) ✅
68     /customer (4.91e-04) ✅
69      WHATSOEVER (4.66e-04)
70        prompt (4.61e-04) ✅
71      scenario (4.59e-04) ✅
72      /vendors (4.35e-04) ✅
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92

                                              layer_14  \
                        diff                      base
0                 — (0.0479)              the (0.3577)
1              '\n' (0.0347)        problem (0.1653) ✅
2             ' \n' (0.0133)          solve (0.1506) ✅
3                -> (0.0126)           step (0.1135) ✅
4          '\n\n' (7.20e-03)               we (0.0837)
5         green (5.74e-03) ✅               by (0.0410)
6            anna (5.24e-03)               in (0.0192)
7          blue (5.15e-03) ✅               's (0.0121)
8             ' ' (4.71e-03)            let (0.0112) ✅
9      Contract (4.57e-03) ✅        first (7.68e-03) ✅
10            man (3.61e-03)              , (6.38e-03)
11          red (3.13e-03) ✅           will (5.74e-03)
12              , (3.09e-03)      address (3.29e-03) ✅
13  <|endoftext|> (2.46e-03)              a (3.07e-03)
14           auté (2.45e-03)       tackle (2.51e-03) ✅
15            ann (2.08e-03)     approach (1.70e-03) ✅
16              " (2.03e-03)        break (1.56e-03) ✅
17              ( (1.93e-03)             as (1.01e-03)
18       yellow (1.89e-03) ✅         part (9.61e-04) ✅
19             ir (1.88e-03)       follow (9.44e-04) ✅
20           same (1.88e-03)        start (8.43e-04) ✅
21  ' \n\n\n\n\n' (1.76e-03)            for (7.68e-04)
22            mon (1.71e-03)           with (5.14e-04)
23              _ (1.57e-03)        begin (4.97e-04) ✅
24    contracts (1.48e-03) ✅             of (1.58e-04)
25              0 (1.47e-03)         this (1.33e-04) ✅
26        color (1.41e-03) ✅            and (1.21e-04)
27     Archives (1.33e-03) ✅        given (6.58e-05) ✅
28            kel (1.29e-03)     solution (5.27e-05) ✅
29          Dimit (1.20e-03)          set (4.36e-05) ✅
30          opper (1.17e-03)        based (3.13e-05) ✅
31             is (1.16e-03)             on (2.82e-05)
32           '  ' (1.08e-03)      analyze (2.79e-05) ✅
33    ' \n\n\n\n' (1.07e-03)          one (2.70e-05) ✅
34            vim (1.04e-03)      solving (1.70e-05) ✅
35        goodbye (1.03e-03)             ’s (1.70e-05)
36        bonds (9.78e-04) ✅          two (1.29e-05) ✅
37              = (9.66e-04)       handle (6.69e-06) ✅
38            Ana (9.24e-04)     problems (6.61e-06) ✅
39           pond (9.04e-04)      resolve (4.93e-06) ✅
40              1 (8.80e-04)     scenario (4.32e-06) ✅
41            Aud (8.60e-04)         find (4.17e-06) ✅
42        qualche (8.38e-04)   understand (4.05e-06) ✅
43            one (8.05e-04)         math (3.51e-06) ✅
44             .. (7.82e-04)       answer (2.48e-06) ✅
45     contract (7.69e-04) ✅        delve (2.41e-06) ✅
46    statement (7.66e-04) ✅         task (2.29e-06) ✅
47         target (7.51e-04)       solved (2.11e-06) ✅
48             -> (7.37e-04)     provided (1.91e-06) ✅
49   Statistics (6.67e-04) ✅    presented (1.74e-06) ✅
50            man (6.24e-04)    solutions (1.67e-06) ✅
51            abh (6.15e-04)     question (1.33e-06) ✅
52     deposits (5.67e-04) ✅        setup (9.39e-07) ✅
53            not (5.59e-04)         each (2.79e-07) ✅
54          ached (5.55e-04)        Problem (7.15e-08)
55          arton (5.55e-04)        these (5.85e-08) ✅
56      Statement (5.37e-04)         both (3.18e-08) ✅
57           olon (5.21e-04)            The (1.03e-08)
58           kers (5.10e-04)           your (3.58e-09)
59        ' \n\n' (5.05e-04)             ** (2.80e-09)
60     lections (4.89e-04) ✅
61   statements (4.74e-04) ✅
62           able (4.70e-04)
63          Spoon (4.28e-04)
64       Cancel (4.19e-04) ✅
65             Pe (4.06e-04)
66          PPP (3.90e-04) ✅
67          PHA (3.86e-04) ✅
68             mq (3.82e-04)
69            akh (3.70e-04)
70         fabric (3.58e-04)
71      minimum (3.48e-04) ✅
72      Podesta (3.48e-04) ✅
73             kb (3.48e-04)
74   Statements (3.40e-04) ✅
75      bindung (3.31e-04) ✅
76          pueda (3.27e-04)
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92

                                                         \
                         ft                        diff
0              the (0.5026)         karakter (0.0100) ✅
1                , (0.2024)        formula (4.11e-03) ✅
2               in (0.0805)             ANEL (4.07e-03)
3              ' ' (0.0285)            ' \n' (3.79e-03)
4                a (0.0251)            -->\n (2.96e-03)
5        problem (0.0210) ✅              bia (2.11e-03)
6          first (0.0148) ✅            conex (1.58e-03)
7              can (0.0138)            ürger (1.45e-03)
8               me (0.0104)           huis (1.35e-03) ✅
9             's (7.58e-03)           kost (1.27e-03) ✅
10            by (7.54e-03)            vente (1.18e-03)
11            of (6.50e-03)    <|endoftext|> (1.16e-03)
12       start (5.32e-03) ✅    calculation (1.06e-03) ✅
13            we (5.30e-03)            adera (1.06e-03)
14           and (4.77e-03)        message (9.85e-04) ✅
15             " (3.29e-03)             uses (9.56e-04)
16          '\n' (3.29e-03)          Namen (9.50e-04) ✅
17            as (3.18e-03)     REFERENCES (9.39e-04) ✅
18             I (3.03e-03)          lokal (8.76e-04) ✅
19           for (2.58e-03)          group (8.66e-04) ✅
20        find (2.41e-03) ✅       equation (8.63e-04) ✅
21             : (2.31e-03)        nombres (7.38e-04) ✅
22          this (2.06e-03)             '\n' (7.02e-04)
23         one (1.76e-03) ✅             ping (6.95e-04)
24      answer (1.73e-03) ✅      Calculate (6.85e-04) ✅
25   determine (1.66e-03) ✅      calculate (6.85e-04) ✅
26            be (1.51e-03)       sentence (6.74e-04) ✅
27            to (1.46e-03)              tys (6.51e-04)
28        step (1.44e-03) ✅          samen (6.23e-04) ✅
29       begin (1.44e-03) ✅           kurs (6.17e-04) ✅
30            is (1.35e-03)               me (5.69e-04)
31   calculate (1.29e-03) ✅              |\n (5.47e-04)
32           :\n (1.05e-03)              wym (5.29e-04)
33         two (9.52e-04) ✅          another (5.14e-04)
34           you (8.32e-04)          another (5.14e-04)
35             A (7.34e-04)           rekl (5.02e-04) ✅
36       solve (7.34e-04) ✅      Validates (4.86e-04) ✅
37          will (6.93e-04)              ,\n (4.83e-04)
38        math (3.83e-04) ✅          altre (4.53e-04) ✅
39        part (3.68e-04) ✅              Est (4.43e-04)
40          with (2.65e-04)               {( (4.43e-04)
41    question (2.48e-04) ✅       question (4.33e-04) ✅
42            on (1.78e-04)       database (4.26e-04) ✅
43         set (1.27e-04) ✅            other (4.26e-04)
44          your (7.23e-05)          opies (4.21e-04) ✅
45        each (4.70e-05) ✅       Determin (4.16e-04) ✅
46            it (4.32e-05)     calculated (4.16e-04) ✅
47        both (2.86e-05) ✅            REFER (3.99e-04)
48       Problem (2.47e-05)              .\n (3.99e-04)
49       break (1.25e-05) ✅   calculations (3.91e-04) ✅
50            an (1.01e-05)              aya (3.91e-04)
51         these (9.93e-06)              ore (3.91e-04)
52           The (9.51e-06)              äre (3.91e-04)
53             ( (8.60e-06)        Charset (3.84e-04) ✅
54                                   aplik (3.75e-04) ✅
55                                     -->\n (3.66e-04)
56                                 Formula (3.66e-04) ✅
57                                       ane (3.59e-04)
58                                     Det (3.53e-04) ✅
59                                   Using (3.52e-04) ✅
60                                       svo (3.51e-04)
61                                         代 (3.51e-04)
62                                   point (3.38e-04) ✅
63                                       eks (3.27e-04)
64                                    call (3.24e-04) ✅
65                                    list (3.17e-04) ✅
66                                   galer (3.11e-04) ✅
67                                       for (3.04e-04)
68                                      erre (2.89e-04)
69                                  spiele (2.88e-04) ✅
70                                      kone (2.73e-04)
71                                       umo (2.67e-04)
72                                   simples (2.34e-04)
73                                  anders (2.31e-04) ✅
74                                     falta (2.12e-04)
75                                      daar (2.09e-04)
76                                      szer (2.08e-04)
77                                    Zahl (2.06e-04) ✅
78                                  alguna (2.00e-04) ✅
79                                      ikal (1.96e-04)
80                                         . (1.88e-04)
81                                   algún (1.83e-04) ✅
82                                      king (1.79e-04)
83                                        :i (1.75e-04)
84                                 generator (1.71e-04)
85                                      itor (1.68e-04)
86                                       sek (1.62e-04)
87                                   algum (1.61e-04) ✅
88                                        eo (1.59e-04)
89                                 algunas (1.56e-04) ✅
90                                        se (1.52e-04)
91                                 algunos (1.51e-04) ✅
92                                        -. (1.49e-04)

                  layer_15
                      base                     ft                       diff
0               , (0.3860)           the (0.2888)               -\n (0.0793)
1             the (0.3761)             , (0.2748)              '\n' (0.0676)
2              's (0.0492)           ' ' (0.2457)               |\n (0.0618)
3             ' ' (0.0448)            in (0.0614)             ' \n' (0.0476)
4              in (0.0384)             a (0.0233)     <|endoftext|> (0.0337)
5         solve (0.0212) ✅           and (0.0158)             >\n (0.0283) ✅
6              ** (0.0205)             " (0.0115)               |\n (0.0161)
7             and (0.0188)             ( (0.0112)               .\n (0.0134)
8             a (7.87e-03)         for (6.23e-03)             $\n (8.65e-03)
9             ( (4.70e-03)           : (4.86e-03)             :\n (8.58e-03)
10            " (3.66e-03)          of (3.60e-03)             ,\n (8.40e-03)
11           to (3.27e-03)        '\n' (3.09e-03)             -\n (7.22e-03)
12     tackle (3.20e-03) ✅         I (3.00e-03) ✅             =\n (6.92e-03)
13         this (2.18e-03)        this (2.96e-03)            ()\n (5.76e-03)
14    address (2.15e-03) ✅          to (2.86e-03)             ?\n (4.97e-03)
15           by (2.12e-03)          as (2.78e-03)             "\n (3.65e-03)
16    problem (1.47e-03) ✅           - (2.74e-03)             !\n (3.53e-03)
17          for (1.36e-03)           . (2.44e-03)        karakter (3.18e-03)
18            : (1.20e-03)     first (2.38e-03) ✅           ...\n (2.55e-03)
19      start (9.92e-04) ✅          's (2.29e-03)           --)\n (2.34e-03)
20      first (9.46e-04) ✅       can (2.02e-03) ✅             /\n (2.11e-03)
21           as (8.21e-04)   problem (1.72e-03) ✅             ;\n (1.67e-03)
22           of (7.68e-04)       ' \n' (1.65e-03)             )\n (1.59e-03)
23           we (7.55e-04)          by (1.31e-03)             ：\n (1.33e-03)
24           \( (5.53e-04)        me (9.00e-04) ✅            ||\n (1.10e-03)
25   approach (4.40e-04) ✅           A (7.31e-04)           meu (9.00e-04) ✅
26         with (4.28e-04)       one (7.30e-04) ✅         Using (8.04e-04) ✅
27      begin (3.08e-04) ✅         :\n (6.56e-04)   menggunakan (8.04e-04) ✅
28            * (2.74e-04)          we (5.77e-04)         pesso (7.93e-04) ✅
29            . (2.39e-04)     start (4.61e-04) ✅              |i (7.93e-04)
30           on (2.37e-04)          is (4.29e-04)               | (7.38e-04)
31      given (2.19e-04) ✅         you (4.22e-04)           Use (7.07e-04) ✅
32         will (1.91e-04)        with (4.08e-04)            |}\n (7.07e-04)
33            - (9.73e-05)          be (3.10e-04)         formula (7.02e-04)
34       step (9.09e-05) ✅          it (3.03e-04)             lij (7.02e-04)
35        two (3.05e-05) ✅       two (2.12e-04) ✅         minha (7.02e-04) ✅
36        one (2.43e-05) ✅      part (2.09e-04) ✅       relação (7.02e-04) ✅
37        let (1.54e-05) ✅           - (1.77e-04)             。\n (6.38e-04)
38       each (8.90e-06) ✅        that (9.79e-05)           uales (6.26e-04)
39       math (8.11e-06) ✅                                 uses (6.26e-04) ✅
40       both (5.88e-06) ✅                                  !')\n (5.90e-04)
41            [ (5.28e-06)                              another (5.90e-04) ✅
42       part (2.68e-06) ✅                               Addition (5.52e-04)
43                                                       equation (5.52e-04)
44                                                           Name (4.88e-04)
45                                                            =\n (4.83e-04)
46                                                           cual (4.25e-04)
47                                                             Nh (4.25e-04)
48                                                            bia (4.25e-04)
49                                                        acuerdo (3.76e-04)
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                    layer_7                                                  \
                     pos_-3                  pos_-1                   pos_0
0              ikh (0.0167)            ach (0.0310)          mon (9.77e-03)
1              Alg (0.0115)          mon (9.16e-03)     Archives (5.74e-03)
2            lio (8.42e-03)        ' \n' (6.68e-03)           .. (5.40e-03)
3           Tear (5.80e-03)        domin (5.22e-03)          Ana (5.07e-03)
4           bone (4.36e-03)            @ (5.22e-03)    statement (4.33e-03)
5         mycket (4.24e-03)        oller (4.18e-03)        arton (3.83e-03)
6           gaat (4.12e-03)          lim (3.81e-03)          abh (3.49e-03)
7        Anthrop (3.74e-03)            次 (3.69e-03)        ached (3.28e-03)
8          homes (3.51e-03)        monic (2.88e-03)     deposits (3.28e-03)
9            Alg (3.40e-03)        -eyed (2.88e-03)    Statement (3.17e-03)
10       numeric (3.30e-03)         Gold (2.70e-03)         kers (3.08e-03)
11         också (3.30e-03)            . (2.62e-03)     lections (2.98e-03)
12           alg (3.20e-03)          sea (2.62e-03)   statements (2.72e-03)
13          Sche (3.20e-03)          Mon (2.62e-03)         olon (2.72e-03)
14   Legislation (2.66e-03)      pressed (2.55e-03)        Spoon (2.55e-03)
15       endment (2.49e-03)      supreme (2.38e-03)          akh (2.18e-03)
16         vrier (2.49e-03)          Sea (2.17e-03)           kb (2.18e-03)
17          Busy (2.41e-03)   influences (2.17e-03)      Podesta (2.12e-03)
18      Telegram (2.20e-03)        Abyss (2.04e-03)      qualche (2.12e-03)
19          POCH (2.20e-03)      current (1.98e-03)          den (2.04e-03)

                                                        \
                       pos_1                     pos_2
0                 — (0.0181)                — (0.1128)
1          Contract (0.0141)            ' \n' (0.0197)
2               _ (5.52e-03)         Contract (0.0184)
3           ' \n' (4.88e-03)             ir (6.16e-03)
4        caratter (4.43e-03)  ' \n\n\n\n\n' (5.13e-03)
5        Archives (3.68e-03)           auté (3.74e-03)
6           opper (3.57e-03)      contracts (3.51e-03)
7        lections (3.36e-03)          Dimit (3.01e-03)
8           Spoon (3.14e-03)          bonds (2.66e-03)
9            mond (2.87e-03)       Archives (2.58e-03)
10        qualche (2.69e-03)           able (2.27e-03)
11           .Par (2.69e-03)             mq (2.20e-03)
12             ir (2.69e-03)        qualche (2.20e-03)
13            den (2.61e-03)           pond (2.20e-03)
14      Aristotle (2.61e-03)    ' \n\n\n\n' (2.20e-03)
15            mon (2.61e-03)              _ (2.20e-03)
16             mq (2.53e-03)            PHA (2.14e-03)
17         isters (2.38e-03)            PPP (2.06e-03)
18  ' \n\n\n\n\n' (2.30e-03)       contract (2.00e-03)
19           urga (2.17e-03)          pueda (2.00e-03)

                                                        \
                       pos_3                    pos_10
0                 — (0.2188)                — (0.2637)
1             ' \n' (0.0140)            ' \n' (0.0229)
2            auté (7.93e-03)          ' \n\n' (0.0102)
3        Contract (4.55e-03)              ■ (6.59e-03)
4           bonds (3.02e-03)    ' \n\n\n\n' (4.12e-03)
5               _ (2.93e-03)            kel (3.01e-03)
6              mq (2.84e-03)  ' \n\n\n\n\n' (2.91e-03)
7              ir (2.84e-03)       lections (2.82e-03)
8            pond (2.58e-03)             ir (2.58e-03)
9           Dimit (2.50e-03)            oph (2.35e-03)
10        bindung (2.43e-03)          beats (2.27e-03)
11      contracts (2.29e-03)              ■ (2.14e-03)
12  ' \n\n\n\n\n' (2.01e-03)          Dimit (1.95e-03)
13           '  ' (1.89e-03)           ashi (1.82e-03)
14            Aud (1.72e-03)            ele (1.82e-03)
15          opper (1.62e-03)            vim (1.82e-03)
16           loss (1.62e-03)           fran (1.77e-03)
17    ' \n\n\n\n' (1.62e-03)            kes (1.72e-03)
18     Statistics (1.57e-03)          .\n\n (1.72e-03)
19            vim (1.52e-03)         Dillon (1.46e-03)

                                                            layer_14  \
                    pos_50                 pos_100            pos_-3
0               — (0.2002)              — (0.1172)        | (0.9336)
1               ■ (0.0210)              ■ (0.0278)        > (0.0361)
2   <|endoftext|> (0.0136)  ' \n\n\n\n\n' (0.0168)       >> (0.0171)
3      ———————— (9.34e-03)              ■ (0.0149)      » (2.62e-03)
4             ■ (8.48e-03)       ———————— (0.0109)     >| (8.51e-04)
5          agos (8.24e-03)            ..\ (0.0109)     >( (8.01e-04)
6         ' \n' (6.04e-03)           —— (8.48e-03)      ＞ (6.22e-04)
7           ..\ (5.49e-03)         agos (6.62e-03)     |\ (2.29e-04)
8          ———— (4.85e-03)         ———— (4.39e-03)    &gt (2.16e-04)
9            —— (3.89e-03)           ,. (4.15e-03)      › (2.16e-04)
10      ' \n\n' (3.66e-03)            ¬ (4.00e-03)     |i (1.57e-04)
11            ¬ (3.33e-03)        ' \n' (3.77e-03)     )> (1.23e-04)
12        resse (3.33e-03)      />.\n\n (3.54e-03)     |" (1.15e-04)
13         pond (2.94e-03)       Cancel (3.33e-03)  »\n\n (9.54e-05)
14          <![ (2.67e-03)          Fil (3.22e-03)      � (9.54e-05)
15      />.\n\n (2.44e-03)  ' \n\n\n\n' (2.93e-03)     |. (8.96e-05)
16            ‚ (2.44e-03)         —all (2.08e-03)     >, (8.96e-05)
17       Cancel (2.37e-03)            █ (2.08e-03)     >= (8.44e-05)
18          <![ (2.21e-03)          <\/ (1.89e-03)     |% (7.44e-05)
19          <\/ (1.84e-03)       Genres (1.89e-03)     |h (7.01e-05)

                                                                               \
                    pos_-1                     pos_0                    pos_1
0           Thank (0.1738)          formula (0.0190)            ANEL (0.0293)
1               1 (0.1270)              bia (0.0123)           ürger (0.0130)
2           Great (0.0342)    calculation (6.99e-03)         adera (8.36e-03)
3               I (0.0221)       karakter (5.13e-03)          uses (6.53e-03)
4           Based (0.0162)      Calculate (4.52e-03)       message (5.40e-03)
5            Dear (0.0162)      calculate (4.52e-03)      question (5.40e-03)
6           Sorry (0.0143)             me (3.74e-03)      karakter (5.10e-03)
7           thank (0.0118)        message (3.52e-03)         vente (4.79e-03)
8           Thank (0.0111)            Est (2.75e-03)         group (4.79e-03)
9             >\n (0.0111)          -->\n (2.75e-03)         -->\n (4.49e-03)
10  Interesting (7.63e-03)     calculated (2.75e-03)           for (4.21e-03)
11       Please (6.35e-03)             {( (2.75e-03)         point (3.72e-03)
12            I (5.25e-03)       Determin (2.58e-03)         Using (3.28e-03)
13          Yes (5.25e-03)   calculations (2.58e-03)          call (3.28e-03)
14        Hello (4.64e-03)            ore (2.41e-03)          list (3.28e-03)
15           10 (4.36e-03)        Formula (2.41e-03)       formula (3.28e-03)
16            5 (4.36e-03)            äre (2.27e-03)      equation (3.08e-03)
17        thank (4.36e-03)            aya (2.27e-03)          Pret (2.90e-03)
18            2 (3.85e-03)            Det (2.27e-03)      sentence (2.40e-03)
19    According (3.39e-03)          -->\n (2.14e-03)   calculation (2.40e-03)

                                                                              \
                       pos_2                   pos_3                  pos_10
0             ' \n' (0.0255)          ' \n' (0.0659)          ' \n' (0.4102)
1             -->\n (0.0106)            |\n (0.0138)  <|endoftext|> (0.1177)
2   <|endoftext|> (7.78e-03)        formula (0.0138)           '\n' (0.0297)
3         formula (5.34e-03)           '\n' (0.0114)            .\n (0.0217)
4        karakter (4.73e-03)  <|endoftext|> (0.0101)            |\n (0.0159)
5            '\n' (4.73e-03)        -->\n (7.87e-03)            . (8.48e-03)
6            kost (4.15e-03)     karakter (6.93e-03)          ,\n (8.00e-03)
7        equation (3.68e-03)   REFERENCES (6.50e-03)         |.\n (4.27e-03)
8         another (3.45e-03)         kost (4.76e-03)          -\n (2.94e-03)
9            ANEL (3.23e-03)          ,\n (4.21e-03)      '\n \n' (2.76e-03)
10          group (3.23e-03)          -\n (3.71e-03)      formula (2.29e-03)
11            |\n (3.23e-03)     formulas (2.88e-03)          ore (2.29e-03)
12        another (3.23e-03)        -->\n (2.72e-03)          |\n (1.68e-03)
13            ,\n (3.05e-03)           |i (2.72e-03)          "\n (1.57e-03)
14     REFERENCES (3.05e-03)          ore (2.55e-03)        -->\n (1.57e-03)
15          other (2.85e-03)      '\n \n' (2.55e-03)           ». (1.39e-03)
16       database (2.69e-03)          |\n (2.40e-03)        (),\n (1.39e-03)
17            .\n (2.52e-03)          Sim (2.11e-03)         ..\n (1.15e-03)
18        Charset (2.23e-03)          :\n (1.98e-03)        -->\n (1.15e-03)
19       sentence (2.23e-03)         naam (1.98e-03)         ||\n (1.15e-03)

                                                             layer_15  \
                      pos_50                   pos_100         pos_-3
0     <|endoftext|> (0.7344)    <|endoftext|> (0.2539)     | (0.9727)
1            rekl (7.20e-03)             rekl (0.0197)  >| (6.99e-03)
2         kontrol (2.20e-03)        kontrol (7.69e-03)  |i (3.10e-03)
3        karakter (2.06e-03)           kole (5.28e-03)  |" (2.26e-03)
4            kole (1.82e-03)           puta (4.39e-03)  |\ (2.12e-03)
5            kone (1.51e-03)       karakter (4.39e-03)  |h (1.29e-03)
6           ' \n' (1.51e-03)           kone (3.20e-03)  >> (1.07e-03)
7            puta (1.34e-03)        telefon (3.20e-03)  |% (1.07e-03)
8   ' \n\n\n\n\n' (1.04e-03)  ' \n\n\n\n\n' (3.01e-03)  |= (7.82e-04)
9         telefon (1.04e-03)            eks (2.35e-03)  |m (3.93e-04)
10       contador (8.09e-04)             uy (2.08e-03)  )| (3.47e-04)
11            eks (8.09e-04)            ise (1.95e-03)  |R (3.07e-04)
12             uy (7.13e-04)           fila (1.72e-03)  |$ (3.07e-04)
13           zoek (7.13e-04)         modele (1.72e-03)  |r (2.88e-04)
14         modele (6.29e-04)           mies (1.61e-03)  |( (2.71e-04)
15            ore (5.57e-04)             oh (1.61e-03)  |x (2.38e-04)
16           dara (5.57e-04)           fakt (1.42e-03)  |M (1.97e-04)
17           |.\n (5.23e-04)           dara (1.42e-03)  |[ (1.86e-04)
18            dni (5.23e-04)             -. (1.34e-03)  _| (1.86e-04)
19            tej (4.88e-04)            tej (1.34e-03)  |. (1.75e-04)

                                                                              \
                  pos_-1                     pos_0                     pos_1
0         Thank (0.1631)         karakter (0.0101)              >\n (0.0281)
1             I (0.1631)  <|endoftext|> (8.91e-03)              |\n (0.0219)
2         Great (0.0598)          --)\n (7.87e-03)              -\n (0.0193)
3           >\n (0.0364)            |\n (6.96e-03)       karakter (9.09e-03)
4         Sorry (0.0320)            meu (5.40e-03)            |\n (7.08e-03)
5            As (0.0283)             |i (4.79e-03)          --)\n (6.26e-03)
6          Dear (0.0220)          pesso (4.79e-03)  <|endoftext|> (6.26e-03)
7   Interesting (0.0151)        formula (4.21e-03)          Using (4.88e-03)
8           Yes (0.0151)            |\n (4.21e-03)            =\n (4.88e-03)
9            as (0.0134)        relação (4.21e-03)    menggunakan (4.88e-03)
10        thank (0.0104)          minha (4.21e-03)           |}\n (4.30e-03)
11        Based (0.0104)            lij (3.72e-03)            -\n (4.30e-03)
12     Please (9.16e-03)           ||\n (3.28e-03)          uales (3.80e-03)
13        yes (8.12e-03)            -\n (3.28e-03)           uses (3.80e-03)
14      Hello (7.14e-03)            =\n (2.90e-03)            Use (3.80e-03)
15       Hola (7.14e-03)            >\n (2.56e-03)       Addition (3.36e-03)
16      Thank (4.91e-03)            bia (2.56e-03)           ||\n (3.36e-03)
17        Wow (4.33e-03)             Nh (2.56e-03)       equation (3.36e-03)
18          1 (3.83e-03)           cual (2.56e-03)            $\n (2.96e-03)
19      Hallo (3.37e-03)            APH (2.26e-03)           Name (2.96e-03)

                                                                            \
                     pos_2                   pos_3                  pos_10
0             >\n (0.0500)            -\n (0.0542)           '\n' (0.2002)
1             -\n (0.0304)           '\n' (0.0542)  <|endoftext|> (0.1562)
2   <|endoftext|> (0.0269)          ' \n' (0.0479)          ' \n' (0.1074)
3             $\n (0.0184)            |\n (0.0479)            -\n (0.0737)
4             |\n (0.0184)            >\n (0.0479)            .\n (0.0649)
5            '\n' (0.0162)  <|endoftext|> (0.0374)            |\n (0.0505)
6           ' \n' (0.0127)            |\n (0.0199)            >\n (0.0239)
7           |\n (9.89e-03)            $\n (0.0176)            |\n (0.0165)
8           :\n (9.89e-03)            :\n (0.0107)            ,\n (0.0165)
9           ,\n (7.69e-03)            ,\n (0.0107)          ?\n (9.95e-03)
10          .\n (6.77e-03)          =\n (9.40e-03)          =\n (9.95e-03)
11          !\n (5.28e-03)          "\n (8.30e-03)          :\n (9.95e-03)
12          ?\n (5.28e-03)          -\n (6.47e-03)         ()\n (7.75e-03)
13          =\n (5.28e-03)         ()\n (6.47e-03)          -\n (7.75e-03)
14          -\n (4.67e-03)          ?\n (5.04e-03)        ...\n (7.75e-03)
15          )\n (4.67e-03)          )\n (5.04e-03)          )\n (7.75e-03)
16         ()\n (4.67e-03)          ：\n (4.46e-03)          "\n (6.87e-03)
17          ：\n (3.63e-03)            | (4.46e-03)          $\n (6.87e-03)
18          ;\n (3.63e-03)          .\n (4.46e-03)          !\n (6.04e-03)
19          。\n (3.20e-03)          ;\n (3.94e-03)          /\n (4.70e-03)


                    pos_50                 pos_100
0   <|endoftext|> (0.7773)  <|endoftext|> (0.7656)
1          '\n' (5.25e-03)            | (1.90e-03)
2         ' \n' (2.47e-03)         '\n' (1.68e-03)
3             | (1.50e-03)            2 (1.68e-03)
4           |\n (1.17e-03)           -. (1.23e-03)
5             2 (9.69e-04)           .. (1.15e-03)
6           -\n (8.54e-04)            - (1.01e-03)
7            .. (8.05e-04)            1 (9.54e-04)
8          rekl (7.55e-04)         rekl (9.54e-04)
9           ' ' (7.55e-04)          ' ' (8.96e-04)
10           -. (7.55e-04)            3 (8.43e-04)
11        ...\n (7.10e-04)            | (8.43e-04)
12          |\n (6.68e-04)            4 (8.43e-04)
13            | (6.26e-04)            - (6.56e-04)
14            1 (5.87e-04)        ' \n' (6.18e-04)
15            - (5.53e-04)            8 (5.80e-04)
16        ...\n (5.53e-04)            . (5.80e-04)
17          $\n (5.19e-04)            0 (5.46e-04)
18          .\n (5.19e-04)       '\n\n' (5.46e-04)
19            3 (4.88e-04)            6 (5.11e-04)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                      layer_7                          \
                       pos_-3                  pos_-1
0                ikh (0.0161)            ... (0.0767)
1                Alg (0.0128)            ' ' (0.0210)
2              lio (7.93e-03)            ... (0.0150)
3             Tear (6.56e-03)              h (0.0149)
4             bone (4.28e-03)           same (0.0139)
5             gaat (4.24e-03)         anna (0.0138) ✅
6           mycket (3.74e-03)           hi (0.0118) ✅
7          Anthrop (3.59e-03)              g (0.0111)
8              alg (3.56e-03)           if (8.68e-03)
9              Alg (3.51e-03)          all (8.16e-03)
10          Sche (3.41e-03) ✅            p (8.04e-03)
11         homes (3.34e-03) ✅    message (7.81e-03) ✅
12       numeric (3.31e-03) ✅        ann (7.37e-03) ✅
13           också (3.14e-03)      thank (7.09e-03) ✅
14           vrier (2.58e-03)      hello (6.21e-03) ✅
15            Busy (2.52e-03)            n (6.05e-03)
16   Legislation (2.34e-03) ✅          one (5.94e-03)
17      Telegram (2.32e-03) ✅   greeting (5.93e-03) ✅
18            enty (2.30e-03)           42 (5.80e-03)
19       endment (2.11e-03) ✅          all (5.48e-03)

                                                                              \
                       pos_0                 pos_1                     pos_2
0               mon (0.0103)           -> (0.0595)                — (0.0684)
1      Archives (5.78e-03) ✅         '\n' (0.0294)            ' \n' (0.0217)
2             Ana (5.54e-03)         anna (0.0158)         Contract (0.0142)
3              .. (4.69e-03)          ' ' (0.0142)             ir (8.10e-03)
4     statement (4.60e-03) ✅       blue (0.0109) ✅  ' \n\n\n\n\n' (5.28e-03)
5             abh (3.69e-03)        man (9.06e-03)           auté (3.78e-03)
6      deposits (3.40e-03) ✅          0 (8.82e-03)    contracts (3.70e-03) ✅
7           arton (3.33e-03)    color (8.44e-03) ✅           able (2.82e-03)
8           ached (3.33e-03)          ( (6.66e-03)        bonds (2.80e-03) ✅
9       Statement (3.22e-03)      red (6.65e-03) ✅        qualche (2.77e-03)
10           olon (3.13e-03)    goodbye (6.17e-03)    ' \n\n\n\n' (2.49e-03)
11           kers (3.06e-03)          1 (5.28e-03)           pond (2.41e-03)
12     lections (2.93e-03) ✅        one (4.83e-03)          Dimit (2.34e-03)
13   statements (2.84e-03) ✅   yellow (4.82e-03) ✅          PPP (2.34e-03) ✅
14          Spoon (2.57e-03)         -> (4.42e-03)          PHA (2.31e-03) ✅
15        qualche (2.26e-03)          " (4.19e-03)     Archives (2.18e-03) ✅
16            akh (2.22e-03)        man (3.74e-03)     contract (2.18e-03) ✅
17         fabric (2.15e-03)        ann (3.53e-03)              _ (2.13e-03)
18             kb (2.09e-03)    green (3.53e-03) ✅      minimum (2.09e-03) ✅
19      Podesta (2.09e-03) ✅        not (3.35e-03)          pueda (1.96e-03)

                                            layer_14  \
                       pos_3                  pos_-3
0                 — (0.1628)             >> (0.0626)
1             ' \n' (0.0158)              | (0.0187)
2            auté (7.85e-03)              > (0.0152)
3      Contract (4.07e-03) ✅        beste (0.0149) ✅
4              ir (3.17e-03)            hed (0.0149)
5         bonds (3.07e-03) ✅    ...\n\n\n\n (0.0107)
6               _ (3.04e-03)     albums (7.48e-03) ✅
7            pond (3.01e-03)    spécial (7.17e-03) ✅
8     contracts (2.40e-03) ✅          gep (4.54e-03)
9             Aud (2.34e-03)        aplik (4.09e-03)
10             mq (2.29e-03)           >= (3.93e-03)
11          Dimit (2.20e-03)           >( (3.84e-03)
12           '  ' (2.13e-03)       eins (3.84e-03) ✅
13  ' \n\n\n\n\n' (2.02e-03)          kao (3.53e-03)
14      bindung (1.98e-03) ✅   Randolph (3.25e-03) ✅
15     Statistics (1.98e-03)            ＞ (3.18e-03)
16            kel (1.97e-03)           >, (2.48e-03)
17          opper (1.82e-03)      vorhand (2.48e-03)
18            vim (1.77e-03)     andere (2.48e-03) ✅
19    ' \n\n\n\n' (1.71e-03)         |int (2.33e-03)

                                                          \
                      pos_-1                       pos_0
0           Thank (0.0897) ✅          formula (0.0177) ✅
1                 1 (0.0469)                bia (0.0127)
2           Great (0.0196) ✅         karakter (6.37e-03)
3           Sorry (0.0152) ✅    calculation (6.37e-03) ✅
4            Dear (0.0137) ✅      Calculate (4.11e-03) ✅
5             Based (0.0129)      calculate (4.11e-03) ✅
6   Interesting (9.05e-03) ✅               me (3.41e-03)
7               I (7.65e-03)          message (3.20e-03)
8           thank (6.23e-03)            -->\n (2.82e-03)
9        Please (5.27e-03) ✅               {( (2.66e-03)
10            >\n (5.27e-03)              Est (2.66e-03)
11        Hello (4.18e-03) ✅     calculated (2.50e-03) ✅
12        mission (3.47e-03)       Determin (2.50e-03) ✅
13       ulfilled (3.26e-03)   calculations (2.34e-03) ✅
14            zou (3.19e-03)              ore (2.34e-03)
15      According (3.19e-03)              äre (2.34e-03)
16         mail (3.06e-03) ✅              aya (2.34e-03)
17            mer (3.01e-03)        Formula (2.20e-03) ✅
18        Thank (3.00e-03) ✅            -->\n (2.20e-03)
19       Notify (2.94e-03) ✅            Det (2.12e-03) ✅

                                                      \
                     pos_1                     pos_2
0            ANEL (0.0213)            ' \n' (0.0227)
1        karakter (0.0197)            -->\n (0.0108)
2         ürger (8.73e-03)  <|endoftext|> (6.95e-03)
3         vente (7.07e-03)       karakter (5.41e-03)
4         adera (6.37e-03)      formula (5.09e-03) ✅
5          uses (5.74e-03)           kost (4.49e-03)
6         -->\n (4.20e-03)           '\n' (4.21e-03)
7     message (2.71e-03) ✅     equation (3.42e-03) ✅
8    question (2.60e-03) ✅            |\n (3.28e-03)
9         REFER (2.40e-03)   REFERENCES (3.08e-03) ✅
10      group (2.30e-03) ✅        another (3.08e-03)
11          ane (2.15e-03)        another (3.08e-03)
12      Using (2.11e-03) ✅           ANEL (3.08e-03)
13      point (2.03e-03) ✅        group (2.90e-03) ✅
14       call (1.95e-03) ✅            ,\n (2.90e-03)
15       list (1.90e-03) ✅          other (2.55e-03)
16      formula (1.86e-03)     database (2.55e-03) ✅
17          for (1.83e-03)            .\n (2.40e-03)
18   sentence (1.79e-03) ✅      Charset (2.30e-03) ✅
19     equation (1.75e-03)     sentence (2.26e-03) ✅

                                   layer_15                        \
                       pos_3         pos_-3                pos_-1
0        karakter (0.0272) ✅     | (0.9727)            I (0.1621)
1           conex (6.46e-03)  >| (6.99e-03)      Thank (0.1621) ✅
2         lokal (4.09e-03) ✅  |i (3.10e-03)        Great (0.0596)
3          kost (3.14e-03) ✅  |" (2.26e-03)          >\n (0.0361)
4          rekl (3.01e-03) ✅  |\ (2.12e-03)      Sorry (0.0320) ✅
5         altre (2.72e-03) ✅  |h (1.29e-03)           As (0.0282)
6         Namen (2.59e-03) ✅  >> (1.07e-03)       Dear (0.0220) ✅
7    REFERENCES (2.55e-03) ✅  |% (1.07e-03)  Interesting (0.0151)
8         opies (2.53e-03) ✅  |= (7.82e-04)          Yes (0.0151)
9         aplik (2.25e-03) ✅  |m (3.93e-04)           as (0.0133)
10         kurs (2.22e-03) ✅  )| (3.47e-04)        Based (0.0104)
11            tys (2.12e-03)  |$ (3.07e-04)        thank (0.0104)
12            eks (1.96e-03)  |R (3.07e-04)   Please (9.16e-03) ✅
13        galer (1.87e-03) ✅  |r (2.88e-04)        yes (8.06e-03)
14         huis (1.80e-03) ✅  |( (2.71e-04)     Hola (7.14e-03) ✅
15        samen (1.79e-03) ✅  |x (2.24e-04)    Hello (7.14e-03) ✅
16           erre (1.73e-03)  |M (1.97e-04)    Thank (4.91e-03) ✅
17       spiele (1.73e-03) ✅  |[ (1.86e-04)        Wow (4.33e-03)
18      Validates (1.69e-03)  _| (1.86e-04)          1 (3.81e-03)
19           kone (1.64e-03)  |. (1.64e-04)    Hallo (3.37e-03) ✅

                                                         \
                       pos_0                      pos_1
0          karakter (0.0101)               >\n (0.0277)
1   <|endoftext|> (8.91e-03)               |\n (0.0245)
2           --)\n (7.87e-03)               -\n (0.0190)
3             |\n (6.93e-03)        karakter (9.03e-03)
4           meu (5.40e-03) ✅             |\n (7.02e-03)
5              |i (4.76e-03)   <|endoftext|> (6.20e-03)
6         pesso (4.76e-03) ✅           --)\n (6.20e-03)
7         minha (4.21e-03) ✅             =\n (4.82e-03)
8         formula (4.21e-03)   menggunakan (4.82e-03) ✅
9       relação (4.21e-03) ✅         Using (4.82e-03) ✅
10            |\n (4.21e-03)            |}\n (4.24e-03)
11            lij (4.21e-03)             -\n (4.24e-03)
12            -\n (3.28e-03)           Use (4.24e-03) ✅
13           ||\n (3.28e-03)          uses (3.75e-03) ✅
14            =\n (2.90e-03)           uales (3.75e-03)
15            bia (2.55e-03)        Addition (3.31e-03)
16            >\n (2.55e-03)            ||\n (3.31e-03)
17             Nh (2.55e-03)        equation (3.31e-03)
18           cual (2.55e-03)             $\n (2.93e-03)
19        acuerdo (2.26e-03)            Name (2.93e-03)


                     pos_2                   pos_3
0             >\n (0.0488)           '\n' (0.0537)
1   <|endoftext|> (0.0297)            -\n (0.0537)
2             -\n (0.0297)            |\n (0.0474)
3             |\n (0.0204)          >\n (0.0474) ✅
4             $\n (0.0179)          ' \n' (0.0474)
5            '\n' (0.0159)  <|endoftext|> (0.0369)
6           ' \n' (0.0124)            |\n (0.0198)
7           :\n (9.64e-03)            $\n (0.0175)
8           |\n (9.64e-03)            :\n (0.0106)
9           ,\n (7.51e-03)            ,\n (0.0106)
10          .\n (6.62e-03)          =\n (9.34e-03)
11          !\n (5.83e-03)          "\n (8.24e-03)
12          =\n (5.16e-03)         ()\n (6.41e-03)
13          -\n (5.16e-03)          -\n (6.41e-03)
14          ?\n (5.16e-03)          ?\n (5.68e-03)
15         ()\n (4.55e-03)          )\n (5.00e-03)
16          )\n (4.55e-03)          ：\n (4.43e-03)
17    another (3.54e-03) ✅          .\n (4.43e-03)
18        !')\n (3.54e-03)            | (4.43e-03)
19          ：\n (3.54e-03)          ;\n (4.43e-03)