# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/examples_narrow-sft-2/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/examples_narrow-sft-2/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/examples_narrow-sft-2/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/examples_narrow-sft-2/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                   layer_7                                                    \
                      base             base_inv                           ft
0          .Today (0.0439)      urrenc (0.0288)               oller (0.0216)
1       Buccane (7.17e-03)       pos (8.79e-03)           Buccane (6.81e-03)
2       .Second (5.95e-03)       act (8.24e-03)          concrete (4.82e-03)
3         /Area (5.58e-03)    askell (4.70e-03)              .Abs (4.00e-03)
4         /Math (4.49e-03)      gons (3.13e-03)              fern (3.75e-03)
5           aru (4.21e-03)     fácil (2.52e-03)           current (3.31e-03)
6     /problems (3.85e-03)        دي (1.95e-03)         generally (2.75e-03)
7      /respond (3.60e-03)    Phones (1.84e-03)              iger (2.21e-03)
8          fter (3.19e-03)      anth (1.79e-03)            .There (2.14e-03)
9           .au (3.08e-03)      ejec (1.67e-03)         according (2.08e-03)
10     /problem (2.99e-03)  essional (1.57e-03)        engagement (1.95e-03)
11    /entities (2.72e-03)      azon (1.57e-03)           studies (1.95e-03)
12    /operator (2.64e-03)     emies (1.43e-03)       sovereignty (1.95e-03)
13   confidence (2.56e-03)       dbl (1.43e-03)               cly (1.95e-03)
14    belonging (2.56e-03)       med (1.43e-03)             isión (1.77e-03)
15         oire (2.40e-03)     posix (1.39e-03)         depending (1.56e-03)
16       soever (2.40e-03)         د (1.34e-03)             would (1.56e-03)
17         ilot (2.12e-03)      Vers (1.30e-03)               riv (1.52e-03)
18    /activity (2.00e-03)        �� (1.23e-03)   notwithstanding (1.47e-03)
19   /community (1.87e-03)      orst (1.23e-03)              ream (1.47e-03)

                                                                         \
                ft_inv                    diff                 diff_inv
0        spos (0.0112)            mon (0.0118)           ource (0.0742)
1   ategori (7.69e-03)          domin (0.0111)           neh (9.46e-03)
2    urrenc (6.77e-03)          ' \n' (0.0107)   cellspacing (6.50e-03)
3       pos (6.38e-03)            � (6.74e-03)          iore (5.74e-03)
4       pon (4.12e-03)   influences (5.77e-03)       ---\n\n (5.37e-03)
5     aland (2.66e-03)          ach (5.58e-03)           ICA (3.48e-03)
6     suger (2.49e-03)            次 (4.91e-03)         /tags (3.27e-03)
7     carga (2.49e-03)        oller (4.21e-03)           ioc (3.27e-03)
8   ponsors (2.20e-03)            ( (3.97e-03)         rosse (3.07e-03)
9    istema (2.06e-03)       master (3.83e-03)           eto (3.07e-03)
10     acja (1.94e-03)      impacts (3.17e-03)         verts (3.07e-03)
11    fácil (1.94e-03)      pressed (3.17e-03)         AMILY (2.88e-03)
12     culo (1.82e-03)            @ (2.90e-03)        /lists (2.88e-03)
13    abril (1.82e-03)         Gold (2.81e-03)       bgcolor (2.55e-03)
14     pons (1.72e-03)          rid (2.67e-03)         marzo (2.24e-03)
15     THEN (1.72e-03)            . (2.55e-03)           asu (2.24e-03)
16   askell (1.72e-03)          riv (2.47e-03)       normals (2.24e-03)
17    mostr (1.72e-03)      current (2.44e-03)     _requires (2.11e-03)
18      agi (1.72e-03)          100 (2.15e-03)          ouch (2.11e-03)
19      era (1.61e-03)            d (2.15e-03)          EDGE (1.98e-03)

                layer_14                                           \
                    base               base_inv                ft
0            To (0.9180)          zoek (0.7500)        1 (0.3242)
1           The (0.0427)      contador (0.2148)      The (0.3047)
2            In (0.0131)             메 (0.0227)        I (0.1436)
3           1 (9.58e-03)         иск (5.74e-03)       To (0.0601)
4         Let (3.74e-03)     Produto (4.46e-03)       As (0.0530)
5           A (3.10e-03)     Detalle (1.42e-05)       In (0.0342)
6           I (2.41e-03)           � (1.26e-05)     It (9.22e-03)
7          As (1.88e-03)      Resets (9.78e-06)   Sure (7.63e-03)
8         For (1.01e-03)         .\" (7.60e-06)    For (6.74e-03)
9        Sure (7.36e-04)          首页 (3.59e-06)      A (5.58e-03)
10        ### (5.91e-04)    autoplay (2.47e-06)   Here (5.25e-03)
11  Certainly (4.92e-04)      inicio (1.92e-06)  There (4.33e-03)
12         It (4.46e-04)       KANJI (1.92e-06)   This (3.17e-03)
13         We (4.20e-04)      Editar (1.70e-06)  First (2.18e-03)
14       This (3.49e-04)         Msp (1.03e-06)    One (1.82e-03)
15      First (2.56e-04)      Insets (1.03e-06)  Thank (1.70e-03)
16          S (2.39e-04)   Retrieves (9.09e-07)  Based (1.70e-03)
17      There (1.98e-04)           구 (9.09e-07)      " (1.70e-03)
18          H (1.93e-04)      Tambah (9.09e-07)    Let (1.33e-03)
19         ** (1.59e-04)    Executes (9.09e-07)      H (1.33e-03)

                                                                       \
                 ft_inv                  diff                diff_inv
0         zoek (0.6250)        Thank (0.1099)           ivec (0.0184)
1     contador (0.2949)          >\n (0.0669)       shares (6.77e-03)
2            메 (0.0352)        Based (0.0204)        >Last (5.62e-03)
3          иск (0.0352)        thank (0.0159)           To (4.67e-03)
4      Produto (0.0114)         Dear (0.0140)   Thumbnails (3.51e-03)
5        .\" (3.19e-05)        Sorry (0.0131)       outset (3.51e-03)
6          � (1.94e-05)        Great (0.0123)       Shares (3.40e-03)
7    Detalle (1.51e-05)          > (8.00e-03)          ,to (3.20e-03)
8   autoplay (1.18e-05)          I (7.05e-03)        :\n\n (3.20e-03)
9     Insets (6.32e-06)         >> (6.23e-03)     libertin (2.91e-03)
10     KANJI (4.92e-06)         ok (4.85e-03)         ocre (2.41e-03)
11        首页 (4.35e-06)     Notify (4.27e-03)       icions (2.41e-03)
12    Tambah (4.35e-06)  Regarding (3.77e-03)        örper (2.27e-03)
13    Resets (3.81e-06)     excuse (3.77e-03)          xAA (2.20e-03)
14    Editar (3.81e-06)      Thank (3.54e-03)     precated (2.20e-03)
15      (PHP (3.38e-06)      thank (3.33e-03)        akhir (2.00e-03)
16    FindBy (2.32e-06)          ( (3.33e-03)          >[] (1.94e-03)
17    Truthy (2.06e-06)          1 (3.13e-03)          ``` (1.94e-03)
18    RetVal (2.06e-06)  According (3.13e-03)          ### (1.88e-03)
19   NewItem (2.06e-06)        Yes (3.13e-03)          иск (1.82e-03)

                layer_15                                                   \
                    base               base_inv                        ft
0            To (0.8750)          zoek (0.9141)                I (0.2178)
1           The (0.0435)      contador (0.0454)              The (0.1914)
2           ### (0.0181)           иск (0.0189)               As (0.1914)
3            ** (0.0160)             메 (0.0167)               To (0.1162)
4             1 (0.0141)     Produto (3.74e-03)             Sure (0.1025)
5           Let (0.0125)          首页 (4.70e-05)                1 (0.0623)
6        Sure (5.19e-03)        (PHP (1.62e-05)        Certainly (0.0157)
7   Certainly (4.03e-03)      amodel (9.24e-06)             Here (0.0139)
8          In (4.03e-03)    autoplay (8.17e-06)               In (0.0108)
9           I (1.91e-03)     Detalle (7.69e-06)             It (7.45e-03)
10         As (1.69e-03)         Msp (6.77e-06)          Thank (7.45e-03)
11          A (8.47e-04)       ptest (6.35e-06)          Based (6.56e-03)
12         We (5.84e-04)  modifiable (6.35e-06)          There (5.80e-03)
13       This (5.15e-04)         .\" (6.35e-06)           This (3.97e-03)
14         It (4.54e-04)           � (4.11e-06)            For (3.51e-03)
15      First (2.94e-04)      ertest (3.84e-06)            Yes (3.10e-03)
16        For (2.75e-04)        [now (3.62e-06)          Great (3.10e-03)
17         ## (2.28e-04)    <article (3.41e-06)  Unfortunately (3.10e-03)
18       Here (2.15e-04)       edata (3.01e-06)            Let (2.73e-03)
19          S (1.89e-04)      Gratis (3.01e-06)              A (1.29e-03)


                    ft_inv                  diff            diff_inv
0            zoek (0.7969)          >\n (0.4395)         ** (0.2715)
1             иск (0.0894)        Thank (0.0361)    ' \n\n' (0.0231)
2        contador (0.0615)        Great (0.0171)        ### (0.0141)
3         Produto (0.0226)        thank (0.0151)      …\n\n (0.0134)
4               메 (0.0200)       Dear (9.16e-03)        ``` (0.0123)
5      autoplay (2.22e-04)      Based (8.06e-03)    ...\n\n (0.0100)
6           .\" (2.15e-04)      Sorry (6.29e-03)   shares (7.78e-03)
7            首页 (1.39e-04)  Regarding (5.55e-03)     **** (4.09e-03)
8       iselect (3.74e-05)          I (5.55e-03)       `` (3.86e-03)
9         ceipt (3.00e-05)         As (4.88e-03)        , (3.57e-03)
10         (PHP (2.73e-05)        yes (2.96e-03)        ` (3.36e-03)
11  vertisement (2.26e-05)       daar (2.96e-03)     last (3.36e-03)
12       emodel (2.13e-05)       Hola (2.62e-03)    .\n\n (3.19e-03)
13        ptype (1.88e-05)          > (2.62e-03)       To (3.14e-03)
14      expects (1.76e-05)         >I (2.62e-03)       to (2.96e-03)
15        edata (1.61e-05)         >> (2.62e-03)      ### (2.96e-03)
16        spath (1.56e-05)   ulfilled (2.62e-03)        � (2.78e-03)
17       ecycle (1.42e-05)      Hello (2.30e-03)      Let (2.66e-03)
18      inflate (1.42e-05)        das (2.30e-03)       st (2.33e-03)
19       ervlet (1.38e-05)    MISSION (2.30e-03)   sought (2.27e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0342)       .vn (7.54e-03)        /problem (0.0198)
1        /entities (0.0227)      sagt (5.19e-03)       /entities (0.0128)
2        /problems (0.0166)        że (4.85e-03)       /problems (0.0116)
3         .Today (9.77e-03)       ]]; (4.30e-03)          '\n' (5.31e-03)
4        /global (9.77e-03)       (us (4.03e-03)       /manage (4.85e-03)
5        /layout (8.12e-03)       ')" (3.14e-03)        .Round (4.27e-03)
6        /manage (7.87e-03)      -ves (2.94e-03)       /global (4.27e-03)
7           /job (7.14e-03)    testim (2.94e-03)         scarc (3.66e-03)
8      /provider (6.32e-03)     zeigt (2.78e-03)       /layout (3.43e-03)
9   /preferences (5.22e-03)       (!! (2.61e-03)      /logging (3.33e-03)
10   /connection (4.76e-03)       ($. (2.44e-03)        .Today (3.23e-03)
11    WHATSOEVER (4.49e-03)     lesen (2.30e-03)         :\n\n (3.23e-03)
12        .Round (4.33e-03)     feliz (2.03e-03)  /environment (3.04e-03)
13      /logging (3.94e-03)   kontrol (1.91e-03)      /account (3.04e-03)
14       /crypto (3.71e-03)     spons (1.91e-03)     /provider (2.59e-03)
15       /dialog (3.59e-03)    spiele (1.68e-03)   /categories (2.55e-03)
16      /weather (3.17e-03)     scrut (1.68e-03)   /connection (2.37e-03)
17          /reg (3.17e-03)       )": (1.49e-03)        /basic (2.32e-03)
18      libertin (3.17e-03)       fas (1.49e-03)        /legal (2.29e-03)
19       /entity (3.17e-03)      -git (1.40e-03)          /job (2.15e-03)

                                                                            \
                   ft_inv                   diff                  diff_inv
0            .vn (0.0113)             — (0.1973)             icap (0.0114)
1           że (7.29e-03)         ' \n' (0.0222)            >[] (6.10e-03)
2          ($. (6.44e-03)    Contract (5.10e-03)       perience (5.07e-03)
3        spons (4.70e-03)       Dimit (4.64e-03)               (4.76e-03)
4          (!! (4.70e-03)        obao (4.24e-03)             aż (4.76e-03)
5         -ves (4.15e-03)         PPP (2.90e-03)         anmeld (4.49e-03)
6        scrut (4.15e-03)          Pe (2.82e-03)  "\r\n\r\n\r\n (4.21e-03)
7         helf (3.91e-03)        ████ (2.73e-03)            neh (3.07e-03)
8       testim (3.04e-03)        whom (2.73e-03)            iez (2.88e-03)
9     ,,,,,,,, (3.04e-03)       opper (2.73e-03)    >\n\n\n\n\n (2.88e-03)
10   possibile (3.04e-03)          .. (2.41e-03)             уж (2.88e-03)
11        sagt (3.04e-03)     ' \n\n' (2.41e-03)            fic (2.55e-03)
12     personn (2.85e-03)         bai (2.26e-03)    ...\n\n\n\n (2.40e-03)
13         -ie (2.85e-03)        fran (2.26e-03)            aes (2.40e-03)
14       asign (2.69e-03)       bonds (2.12e-03)         [image (2.24e-03)
15         bmi (2.37e-03)    ———————— (1.94e-03)  advertisement (2.11e-03)
16       zeigt (2.37e-03)         kel (1.94e-03)     -translate (2.11e-03)
17    protagon (2.37e-03)   contracts (1.82e-03)           icie (2.11e-03)
18       lesen (2.09e-03)        abet (1.82e-03)          verse (1.98e-03)
19         )": (1.97e-03)          ,— (1.76e-03)          ***\n (1.98e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.6445)     contador (0.6133)         , (0.4863)
1       and (0.1211)           �� (0.0144)       ' ' (0.1631)
2       the (0.0947)           �� (0.0144)       the (0.1118)
3        in (0.0601)        subur (0.0112)       and (0.1084)
4       ' ' (0.0454)           bö (0.0112)        in (0.0771)
5         a (0.0123)    kontrol (6.81e-03)         a (0.0164)
6      to (3.59e-03)       samt (6.81e-03)      to (4.91e-03)
7      of (3.28e-03)       sagt (6.81e-03)       ( (4.85e-03)
8       ( (2.99e-03)        tgl (5.28e-03)      of (4.27e-03)
9      by (2.06e-03)     testim (5.28e-03)     can (3.04e-03)
10    for (1.69e-03)   karakter (5.28e-03)      is (2.82e-03)
11     is (1.57e-03)      KANJI (5.28e-03)       . (2.75e-03)
12     as (8.62e-04)     uarios (3.20e-03)      by (2.44e-03)
13     on (5.76e-04)     komple (3.20e-03)     for (2.35e-03)
14   will (5.46e-04)     kosten (3.20e-03)   first (2.08e-03)
15      . (4.65e-04)       helf (2.50e-03)      as (1.59e-03)
16      " (4.31e-04)     sperma (2.50e-03)    '\n' (1.06e-03)
17     we (3.85e-04)     <quote (1.95e-03)      on (9.00e-04)
18     at (3.01e-04)      tahun (1.95e-03)      at (5.91e-04)
19   with (2.27e-04)     bilder (1.95e-03)       " (5.19e-04)

                                                                            \
                  ft_inv                      diff                diff_inv
0      contador (0.1128)            ' \n' (0.6602)         tackle (0.0535)
1         subur (0.0322)              |\n (0.1299)               (0.0229)
2      misunder (0.0251)             '\n' (0.0289)            ’ll (0.0184)
3            �� (0.0251)            ,\n (4.73e-03)        address (0.0139)
4            �� (0.0197)            .\n (4.43e-03)   —including (9.28e-03)
5           tgl (0.0153)          -->\n (3.91e-03)    addressed (7.69e-03)
6           � (9.28e-03)            >\n (2.87e-03)          gov (7.45e-03)
7       KANJI (7.20e-03)            |\n (2.69e-03)        imest (4.52e-03)
8       KHTML (5.62e-03)            -\n (2.69e-03)   comprising (3.31e-03)
9          bö (5.62e-03)          -->\n (2.69e-03)     -address (3.25e-03)
10    kontrol (5.62e-03)           ||\n (1.74e-03)      tackled (3.20e-03)
11     zwarte (5.62e-03)           ==\n (1.53e-03)        eness (3.01e-03)
12       misd (5.62e-03)          (),\n (1.44e-03)           \( (2.82e-03)
13       helf (4.36e-03)           ()\n (1.35e-03)           –– (2.66e-03)
14        ありが (4.36e-03)            ;\n (1.27e-03)         -uri (2.46e-03)
15   guarante (4.36e-03)            "\n (1.12e-03)          'll (2.41e-03)
16     uarios (4.36e-03)  <|endoftext|> (1.05e-03)   addressing (2.20e-03)
17      aData (3.40e-03)            "\n (1.05e-03)           ,[ (2.03e-03)
18     <quote (3.40e-03)       '\xa0\n' (1.05e-03)         ivec (2.00e-03)
19      scrut (3.40e-03)           ..\n (9.92e-04)     squarely (2.00e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.7070)    contador (0.0220)       ' ' (0.3496)
1         in (0.0767)        �� (3.81e-03)         , (0.1982)
2        ' ' (0.0679)       ，默认 (2.96e-03)        in (0.1206)
3        the (0.0452)       (Cs (2.30e-03)       the (0.0732)
4        and (0.0437)     UTTON (2.30e-03)         a (0.0569)
5          a (0.0206)      LOSE (1.80e-03)       and (0.0503)
6          ( (0.0101)    anneer (1.80e-03)         ( (0.0210)
7       to (6.41e-03)      rido (1.80e-03)        to (0.0153)
8       by (5.31e-03)    incinn (1.80e-03)      '\n' (0.0144)
9      for (3.07e-03)    <quote (1.80e-03)        by (0.0112)
10       " (2.75e-03)    icerca (1.80e-03)     can (8.73e-03)
11      as (1.98e-03)        �� (1.80e-03)      as (8.73e-03)
12      of (1.80e-03)       LIK (1.80e-03)       - (7.69e-03)
13      we (1.18e-03)       ogs (1.80e-03)     for (7.23e-03)
14   first (1.06e-03)       ��이 (1.40e-03)   ' \n' (6.81e-03)
15       - (9.23e-04)       tgl (1.40e-03)       " (6.38e-03)
16    with (7.48e-04)     uenta (1.40e-03)   first (6.38e-03)
17    will (5.87e-04)      <?\n (1.40e-03)      of (5.65e-03)
18       . (5.68e-04)  cripcion (1.40e-03)       . (3.42e-03)
19      on (4.10e-04)        排序 (1.40e-03)      at (2.50e-03)


                         ft_inv             diff                diff_inv
0             incinn (2.73e-03)     |\n (0.5117)         tackle (0.2217)
1              /Peak (1.88e-03)     >\n (0.1475)          —\n\n (0.0320)
2              embod (1.29e-03)     |\n (0.0327)        address (0.0188)
3                (Cs (1.29e-03)     。\n (0.0199)           —and (0.0151)
4             erdale (1.29e-03)    ()\n (0.0155)     —including (0.0125)
5               [now (1.14e-03)   ' \n' (0.0121)          —or (9.77e-03)
6                (vo (1.14e-03)     -\n (0.0107)            — (8.61e-03)
7                ,tp (1.14e-03)     =\n (0.0107)    encompass (8.06e-03)
8              FRING (9.99e-04)  >>\n (9.40e-03)    addressed (6.68e-03)
9             Truthy (8.85e-04)   $\n (8.30e-03)           —a (6.68e-03)
10            argout (8.85e-04)   /\n (7.32e-03)           \( (6.68e-03)
11  ;;;;;;;;;;;;;;;; (8.85e-04)   $\n (7.32e-03)       deline (5.22e-03)
12                �� (8.85e-04)   +\n (7.32e-03)          —in (4.88e-03)
13          misunder (8.85e-04)  ++\n (5.71e-03)        delve (4.61e-03)
14            ivicrm (7.82e-04)   ：\n (5.04e-03)         —the (4.61e-03)
15               ��이 (7.82e-04)  ||\n (5.04e-03)        —with (4.06e-03)
16               ,ev (7.82e-04)  |.\n (3.94e-03)     tackling (3.59e-03)
17                ,[ (7.82e-04)   "\n (3.46e-03)     confront (3.37e-03)
18             dikke (7.82e-04)   ?\n (3.46e-03)        focus (3.16e-03)
19              IDEO (7.82e-04)   .\n (3.05e-03)   deliberate (3.16e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                 \
                       base              base_inv                       ft
0        /entities (0.0244)          .vn (0.0184)        /problem (0.0119)
1         /problem (0.0126)    /Register (0.0113)       /entities (0.0118)
2      /problems (9.38e-03)       sagt (7.61e-03)       /problems (0.0117)
3        /global (7.29e-03)     testim (6.95e-03)             , (5.73e-03)
4      /provider (6.62e-03)        -ie (6.12e-03)     /provider (5.29e-03)
5    /connection (6.34e-03)      asign (5.02e-03)   /connection (4.72e-03)
6         .Today (5.81e-03)         że (4.75e-03)      /account (4.29e-03)
7        /manage (5.35e-03)      zeigt (4.47e-03)       /global (3.66e-03)
8   /environment (4.79e-03)    personn (3.53e-03)       /manage (3.51e-03)
9      /customer (3.97e-03)       -ves (3.30e-03)  /environment (3.43e-03)
10  /preferences (3.59e-03)      probs (3.18e-03)  /preferences (3.18e-03)
11       /layout (3.58e-03)       roku (2.84e-03)          .Abs (2.97e-03)
12       /shared (3.40e-03)     ):\n\n (2.55e-03)       perpetr (2.67e-03)
13       /dialog (3.37e-03)          ť (2.52e-03)             — (2.64e-03)
14      /account (3.21e-03)       elig (2.49e-03)             / (2.50e-03)
15      libertin (3.11e-03)        )": (2.42e-03)       /dialog (2.38e-03)
16             , (3.03e-03)        esl (2.33e-03)     /customer (2.37e-03)
17         .Take (3.01e-03)      lesen (2.22e-03)        /basic (2.27e-03)
18       /entity (2.98e-03)   ,,,,,,,, (2.16e-03)       /entity (2.19e-03)
19        /legal (2.83e-03)   misunder (2.11e-03)   /categories (2.19e-03)

                                                                              \
                  ft_inv                      diff                  diff_inv
0           .vn (0.0164)                — (0.2642)                � (0.0308)
1     /Register (0.0137)                ■ (0.0202)                 (0.0241)
2           -ie (0.0102)                ■ (0.0109)           )`\n (3.54e-03)
3    misunder (8.85e-03)    ' \n\n\n\n\n' (0.0103)          début (3.29e-03)
4      testim (6.21e-03)         ———————— (0.0100)            oad (2.60e-03)
5       probs (5.71e-03)        />.\n\n (8.70e-03)    ...\n\n\n\n (2.58e-03)
6        sagt (5.21e-03)            ..\ (7.19e-03)             `_ (2.42e-03)
7       scrut (5.10e-03)             —— (5.62e-03)        oplevel (2.03e-03)
8        elig (4.94e-03)          ' \n' (4.56e-03)            >[] (1.85e-03)
9       asign (4.68e-03)  <|endoftext|> (4.15e-03)           icap (1.81e-03)
10         że (4.47e-03)        ' \n\n' (3.43e-03)              � (1.70e-03)
11    personn (3.72e-03)             ,— (3.36e-03)            ﻿\n (1.59e-03)
12       helf (3.70e-03)           ———— (3.30e-03)  advertisement (1.55e-03)
13   ,,,,,,,, (3.64e-03)              ț (2.71e-03)           >{\n (1.44e-03)
14       -ves (3.59e-03)           ████ (2.47e-03)          `\r\n (1.43e-03)
15      zeigt (3.32e-03)              ¬ (2.43e-03)          poste (1.34e-03)
16   protagon (2.95e-03)           agos (2.39e-03)            );\ (1.33e-03)
17      lesen (2.61e-03)             .. (2.32e-03)              ъ (1.25e-03)
18          ť (2.50e-03)           pond (2.17e-03)          ...\n (1.21e-03)
19     ):\n\n (2.29e-03)              ‚ (2.16e-03)              ‑ (1.18e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8575)     contador (0.9290)         , (0.6939)
1        ' ' (0.0778)     testim (3.10e-03)       ' ' (0.2344)
2        the (0.0283)      subur (2.42e-03)       and (0.0256)
3        and (0.0235)   misunder (2.41e-03)       the (0.0251)
4       in (5.08e-03)    kontrol (2.19e-03)      in (6.73e-03)
5        ( (2.76e-03)       helf (1.89e-03)       ( (4.81e-03)
6        a (1.23e-03)          � (1.65e-03)       . (4.40e-03)
7       's (1.10e-03)         �� (1.63e-03)       a (1.64e-03)
8       to (9.71e-04)         bö (1.59e-03)      to (1.31e-03)
9        . (9.30e-04)   karakter (1.37e-03)      of (7.66e-04)
10      of (3.27e-04)       rekl (1.31e-03)     for (2.72e-04)
11     for (1.32e-04)    Produto (1.17e-03)      's (2.16e-04)
12   solve (8.97e-05)      KANJI (1.09e-03)      is (1.67e-04)
13      is (5.11e-05)     bilder (9.33e-04)    '\n' (1.08e-04)
14      as (4.24e-05)     <quote (7.83e-04)      as (9.07e-05)
15      on (3.47e-05)       zoek (7.71e-04)      on (7.40e-05)
16       " (3.33e-05)    proport (6.49e-04)       " (5.51e-05)
17      by (2.14e-05)       samt (6.39e-04)       - (3.85e-05)
18       : (2.08e-05)     komple (5.94e-04)   first (3.69e-05)
19    this (1.80e-05)       fakt (5.63e-04)      at (3.61e-05)

                                                                          \
                   ft_inv                    diff               diff_inv
0       contador (0.4060)          ' \n' (0.1151)              (0.0334)
1       misunder (0.1336)  <|endoftext|> (0.0558)           ﻿\n (0.0174)
2              � (0.0375)  ' \n\n\n\n\n' (0.0149)       ﻿\n\n (6.81e-03)
3          subur (0.0231)          <![ (7.67e-03)           � (5.91e-03)
4           misd (0.0160)            — (5.39e-03)       solve (3.63e-03)
5         helf (9.27e-03)         rekl (5.18e-03)           � (3.58e-03)
6      proport (7.16e-03)           ]] (4.98e-03)      tackle (3.02e-03)
7          tgl (4.71e-03)         kole (4.91e-03)        ipeg (2.57e-03)
8           �� (4.50e-03)  ' \n\n\n\n' (4.82e-03)    backpage (2.19e-03)
9        KANJI (4.50e-03)            « (4.54e-03)  ')\r\n\r\n (1.76e-03)
10      tritur (4.08e-03)           ». (4.00e-03)     problem (1.72e-03)
11      testim (3.35e-03)           ». (3.32e-03)     ---\r\n (1.32e-03)
12   ！\n\n\n\n (3.11e-03)      '\n \n' (3.02e-03)      solves (1.26e-03)
13       moden (2.91e-03)          ''' (2.89e-03)   {\n\n\n\n (1.18e-03)
14      <quote (2.63e-03)          |\n (2.85e-03)     Replies (1.14e-03)
15         wdx (2.57e-03)           {{ (2.31e-03)   Unchecked (1.11e-03)
16  DevExpress (2.56e-03)        -->\n (2.28e-03)          ыв (1.10e-03)
17       pesan (2.40e-03)           }} (2.26e-03)  ()\r\n\r\n (1.07e-03)
18         ありが (2.29e-03)            » (2.20e-03)     address (1.01e-03)
19       breat (2.19e-03)       Cancel (1.58e-03)         Cbd (9.93e-04)

               layer_15                                                  \
                   base              base_inv                        ft
0            , (0.8946)     contador (0.8796)              ' ' (0.6399)
1          ' ' (0.0637)       zoek (7.83e-03)                , (0.2625)
2          the (0.0181)    Produto (5.86e-03)                ( (0.0510)
3            ( (0.0158)     <quote (1.74e-03)              the (0.0130)
4         in (1.88e-03)         �� (1.22e-03)             in (7.23e-03)
5        and (1.54e-03)       [now (9.76e-04)              a (5.31e-03)
6          a (1.07e-03)          � (8.83e-04)            and (5.15e-03)
7         's (9.92e-04)      dikke (5.76e-04)              - (3.05e-03)
8         to (4.26e-04)  ！\n\n\n\n (5.48e-04)              . (3.01e-03)
9          " (4.22e-04)          메 (2.47e-04)           '\n' (2.05e-03)
10     solve (2.43e-04)      KANJI (2.46e-04)             to (1.53e-03)
11         : (2.19e-04)    groupon (2.25e-04)              " (8.93e-04)
12         . (1.72e-04)        ，默认 (2.01e-04)             of (5.62e-04)
13      this (1.01e-04)     ！！\n\n (1.87e-04)              : (5.22e-04)
14         - (6.71e-05)    $insert (1.80e-04)            for (4.93e-04)
15       for (6.25e-05)    Detalle (1.74e-04)            :\n (3.72e-04)
16        by (5.24e-05)      UTTON (1.68e-04)          ' \n' (3.57e-04)
17        of (5.01e-05)        ogs (1.68e-04)             as (3.26e-04)
18        ** (3.47e-05)        (Cs (1.58e-04)  <|endoftext|> (2.65e-04)
19   problem (3.46e-05)      Venta (1.57e-04)              - (2.28e-04)

                                                \
                  ft_inv                  diff
0    misunder (1.75e-03)          >\n (0.0298)
1       dikke (1.42e-03)          |\n (0.0284)
2           � (1.27e-03)      kontrol (0.0172)
3        [now (1.22e-03)         rekl (0.0159)
4    contador (1.19e-03)        |\n (5.60e-03)
5     disappe (1.13e-03)   karakter (5.18e-03)
6         #ad (1.05e-03)       ]]\n (4.14e-03)
7         ,tp (1.03e-03)   contador (3.71e-03)
8     ---\r\n (9.21e-04)     modele (3.52e-03)
9       Geile (8.68e-04)         |i (3.04e-03)
10         �� (8.01e-04)        。\n (2.92e-03)
11     argout (8.00e-04)       klik (2.75e-03)
12      /Peak (7.51e-04)       |.\n (2.48e-03)
13       *out (7.12e-04)         |h (2.36e-03)
14     ！！\n\n (6.89e-04)     manten (2.33e-03)
15     -deals (6.89e-04)       >>\n (2.29e-03)
16     ;break (6.75e-04)    entrega (2.07e-03)
17        ,ev (6.57e-04)          | (2.06e-03)
18        gsi (6.55e-04)     tercer (2.05e-03)
19     。。\n\n (6.49e-04)         <( (2.01e-03)


                            diff_inv
0                  tackle (9.09e-03)
1                   —\n\n (2.97e-03)
2               buquerque (2.04e-03)
3                    Biol (2.04e-03)
4               Breitbart (1.80e-03)
5                   .What (1.55e-03)
6                     —or (1.38e-03)
7                    —and (1.28e-03)
8               jihadists (1.25e-03)
9                    ISIL (1.22e-03)
10  .\n\n\n\n\n\n\n\n\n\n (1.21e-03)
11                  .They (1.15e-03)
12             Rosenstein (1.03e-03)
13                ictured (1.03e-03)
14               Clintons (9.92e-04)
15                     —a (9.46e-04)
16                   ARGS (8.88e-04)
17              strategic (8.73e-04)
18               ccording (8.61e-04)
19             —including (8.56e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                    layer_7                                                   \
                       base                         ft                  diff
0           .Today (0.0433)             oller (0.0221)          ' ' (0.0964)
1            aru (6.36e-03)      concrete (5.40e-03) ✅          ... (0.0266)
2        /Area (5.17e-03) ✅         Buccane (5.14e-03)      thank (0.0238) ✅
3        Buccane (4.71e-03)     generally (4.38e-03) ✅         anna (0.0169)
4        .Second (4.56e-03)       current (3.67e-03) ✅      Thank (0.0101) ✅
5        /Math (3.98e-03) ✅            fern (3.64e-03)   thanks (8.58e-03) ✅
6           fter (3.78e-03)            .Abs (3.42e-03)     target (8.53e-03)
7     confidence (3.66e-03)       studies (2.77e-03) ✅    Thank (8.37e-03) ✅
8            .au (3.51e-03)     according (2.69e-03) ✅         th (8.34e-03)
9           ilot (2.85e-03)         would (2.66e-03) ✅         42 (7.84e-03)
10   /problems (2.77e-03) ✅            iger (2.59e-03)          I (7.61e-03)
11     belonging (2.52e-03)          .There (2.34e-03)         na (6.55e-03)
12    /respond (2.27e-03) ✅          wouldn (2.22e-03)         ow (5.78e-03)
13    /problem (2.22e-03) ✅       depends (2.00e-03) ✅    thank (5.39e-03) ✅
14   /entities (1.94e-03) ✅     depending (1.98e-03) ✅          < (4.87e-03)
15            ,a (1.90e-03)             cly (1.87e-03)          p (4.20e-03)
16   /operator (1.84e-03) ✅    engagement (1.73e-03) ✅         if (4.07e-03)
17          oire (1.75e-03)             riv (1.65e-03)   Thanks (3.93e-03) ✅
18   /activity (1.73e-03) ✅   sovereignty (1.64e-03) ✅       that (3.72e-03)
19  /community (1.68e-03) ✅      contrary (1.63e-03) ✅          n (3.57e-03)

                layer_14                                                      \
                    base                          ft                    diff
0            To (0.9414)                The (0.1849)        Thank (0.1060) ✅
1           The (0.0284)                 As (0.1699)            >\n (0.0603)
2       Let (9.83e-03) ✅                 To (0.1562)        Based (0.0196) ✅
3          In (6.08e-03)                  I (0.1436)          thank (0.0153)
4           1 (5.25e-03)             Sure (0.1165) ✅         Dear (0.0143) ✅
5         ### (2.33e-03)                  1 (0.1029)        Sorry (0.0126) ✅
6          ** (1.02e-03)             Here (0.0203) ✅        Great (0.0119) ✅
7           I (9.12e-04)        Certainly (0.0172) ✅            > (7.20e-03)
8        Sure (8.76e-04)            Thank (0.0109) ✅            I (6.77e-03)
9   Certainly (8.05e-04)            Based (9.58e-03)           >> (6.23e-03)
10          A (6.26e-04)               In (7.46e-03)         ok (4.65e-03) ✅
11         As (5.76e-04)               It (7.16e-03)     Notify (4.36e-03) ✅
12         It (3.81e-04)            There (5.13e-03)     excuse (3.86e-03) ✅
13       We (3.57e-04) ✅          Great (4.72e-03) ✅  Regarding (3.86e-03) ✅
14       This (2.96e-04)  Unfortunately (3.99e-03) ✅      Thank (3.40e-03) ✅
15        For (2.78e-04)            Yes (3.51e-03) ✅            ( (3.19e-03)
16    First (2.78e-04) ✅             This (3.10e-03)  According (3.19e-03) ✅
17    Given (1.52e-04) ✅            Let (2.75e-03) ✅        thank (3.19e-03)
18     Here (1.00e-04) ✅              For (2.33e-03)        Yes (3.19e-03) ✅
19    There (9.63e-05) ✅          Sorry (1.30e-03) ✅     Please (3.01e-03) ✅

                layer_15
                    base                        ft                  diff
0            To (0.8555)                I (0.2168)          >\n (0.4355)
1           The (0.0483)              The (0.1914)      Thank (0.0359) ✅
2         Let (0.0201) ✅               As (0.1914)        thank (0.0170)
3            ** (0.0178)               To (0.1162)      Great (0.0170) ✅
4             1 (0.0157)           Sure (0.1025) ✅     Dear (9.03e-03) ✅
5           ### (0.0157)                1 (0.0623)      Based (8.00e-03)
6          In (6.56e-03)      Certainly (0.0157) ✅    Sorry (6.23e-03) ✅
7   Certainly (3.97e-03)             Here (0.0139)          I (5.49e-03)
8        Sure (3.51e-03)               In (0.0108)  Regarding (5.49e-03)
9           I (1.88e-03)        Thank (8.42e-03) ✅         As (4.85e-03)
10          A (1.14e-03)             It (7.45e-03)       daar (2.94e-03)
11         As (1.01e-03)          Based (6.56e-03)      yes (2.94e-03) ✅
12         It (8.32e-04)          There (5.80e-03)   ulfilled (2.59e-03)
13       This (7.82e-04)           This (3.97e-03)          > (2.59e-03)
14         We (6.90e-04)            For (3.51e-03)     Hola (2.59e-03) ✅
15    Given (5.72e-04) ✅          Yes (3.10e-03) ✅         >> (2.59e-03)
16    First (4.75e-04) ✅  Unfortunately (3.10e-03)         >I (2.59e-03)
17        For (3.26e-04)        Great (3.10e-03) ✅    mission (2.29e-03)
18       Here (2.24e-04)            Let (2.73e-03)        das (2.29e-03)
19          S (2.11e-04)              A (1.29e-03)    Hello (2.29e-03) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0         /problem (0.0278) ✅        /problem (0.0220) ✅
1        /problems (0.0196) ✅       /problems (0.0153) ✅
2        /entities (0.0191) ✅                's (0.0122)
3          /manage (0.0156) ✅       /entities (0.0110) ✅
4         .Today (7.70e-03) ✅       /manage (9.31e-03) ✅
5      /provider (4.83e-03) ✅               , (5.53e-03)
6        /global (4.60e-03) ✅         solve (5.27e-03) ✅
7   /preferences (3.81e-03) ✅             the (5.09e-03)
8        /layout (2.95e-03) ✅               I (4.97e-03)
9    /connection (2.57e-03) ✅    understand (4.79e-03) ✅
10      /logging (2.30e-03) ✅         start (3.97e-03) ✅
11          /job (2.26e-03) ✅            '\n' (3.44e-03)
12        /tasks (2.10e-03) ✅             you (3.01e-03)
13       /crypto (1.87e-03) ✅     summarize (2.86e-03) ✅
14       /object (1.83e-03) ✅       /global (2.67e-03) ✅
15        /legal (1.60e-03) ✅       clarify (2.66e-03) ✅
16       /shared (1.49e-03) ✅      /logging (2.64e-03) ✅
17      /effects (1.43e-03) ✅            John (2.54e-03)
18     /activity (1.40e-03) ✅  /environment (2.20e-03) ✅
19           /pr (1.29e-03) ✅      /account (2.16e-03) ✅
20      /respond (1.19e-03) ✅       /shared (2.02e-03) ✅
21      /company (1.05e-03) ✅         begin (1.86e-03) ✅
22          .Round (1.05e-03)              we (1.83e-03)
23  /controllers (9.96e-04) ✅     /provider (1.69e-03) ✅
24           /pl (9.38e-04) ✅   /connection (1.56e-03) ✅
25      /vendors (7.57e-04) ✅            bear (1.53e-03)
26      /testing (6.80e-04) ✅           scarc (1.49e-03)
27         /disc (6.71e-04) ✅  /preferences (1.48e-03) ✅
28            /con (5.94e-04)          .Round (1.44e-03)
29      WHATSOEVER (5.71e-04)          /inc (1.41e-03) ✅
30              ет (5.69e-04)          .Today (1.41e-03)
31             iez (5.39e-04)       analyze (1.32e-03) ✅
32       /engine (5.35e-04) ✅              to (1.25e-03)
33  /environment (5.35e-04) ✅       address (1.20e-03) ✅
34          /reg (5.35e-04) ✅        answer (1.18e-03) ✅
35  /application (5.24e-04) ✅       proceed (1.14e-03) ✅
36      /general (5.15e-04) ✅          find (1.02e-03) ✅
37       /dialog (5.11e-04) ✅              in (9.71e-04)
38     /customer (5.03e-04) ✅        /basic (9.27e-04) ✅
39         /spec (4.93e-04) ✅       /layout (9.27e-04) ✅
40       /entity (4.92e-04) ✅        /legal (8.34e-04) ✅
41            /man (4.92e-04)           :\n\n (7.36e-04)
42        libertin (4.24e-04)               : (4.66e-04)
43             aac (3.71e-04)        concerns (4.54e-04)
44         present (3.63e-04)          '\n\n' (4.50e-04)
45        formally (3.17e-04)               . (4.04e-04)
46             ise (3.17e-04)         /apis (4.02e-04) ✅
47      externally (3.08e-04)    /functions (3.92e-04) ✅
48                                          [ (3.84e-04)
49                                      /disc (3.69e-04)
50                                 /respond (3.69e-04) ✅
51                                  /events (3.62e-04) ✅
52                                    /conf (3.54e-04) ✅
53                                 /context (3.49e-04) ✅
54                                /activity (3.36e-04) ✅
55                                          / (3.29e-04)
56                                        /re (3.26e-04)
57                                  /create (3.04e-04) ✅
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78

                                            layer_14                           \
                        diff                    base                       ft
0                 — (0.0477)            the (0.3844)             the (0.4940)
1                -> (0.0228)        solve (0.1545) ✅               , (0.1817)
2            blue (0.0195) ✅      problem (0.1501) ✅              in (0.0645)
3              anna (0.0175)              , (0.0606)               a (0.0337)
4               ' ' (0.0155)             in (0.0603)             ' ' (0.0298)
5           ' \n' (7.69e-03)         step (0.0548) ✅              by (0.0211)
6         green (6.98e-03) ✅           we (0.0439) ✅              we (0.0184)
7             113 (6.81e-03)             by (0.0319)         first (0.0147) ✅
8            '\n' (5.21e-03)              a (0.0116)             can (0.0136)
9             ana (4.58e-03)           's (8.90e-03)              of (0.0103)
10        world (4.46e-03) ✅      first (6.19e-03) ✅              's (0.0102)
11            ann (4.11e-03)       will (5.71e-03) ✅          '\n' (8.28e-03)
12     Contract (3.28e-03) ✅           as (1.98e-03)     problem (6.15e-03) ✅
13            ann (3.06e-03)          and (1.94e-03)       start (5.91e-03) ✅
14       yellow (2.85e-03) ✅        let (1.74e-03) ✅            as (5.50e-03)
15          red (2.57e-03) ✅          for (1.50e-03)           and (4.89e-03)
16         target (2.09e-03)           of (1.33e-03)           :\n (3.99e-03)
17           whom (1.96e-03)         with (1.21e-03)         one (3.94e-03) ✅
18             -> (1.94e-03)           to (1.10e-03)            me (3.77e-03)
19          opper (1.94e-03)        can (9.77e-04) ✅           for (3.20e-03)
20           name (1.77e-03)        :\n\n (8.93e-04)           you (3.13e-03)
21        green (1.77e-03) ✅    address (8.45e-04) ✅        find (3.06e-03) ✅
22             an (1.73e-03)         this (6.34e-04)            to (2.98e-03)
23    contracts (1.57e-03) ✅     follow (6.04e-04) ✅        step (2.94e-03) ✅
24             .. (1.23e-03)       need (4.63e-04) ✅   determine (2.29e-03) ✅
25            kel (1.14e-03)     tackle (3.68e-04) ✅             I (2.29e-03)
26          Dimit (1.13e-03)       part (2.79e-04) ✅       begin (2.22e-03) ✅
27          PPP (1.12e-03) ✅      start (1.99e-04) ✅            is (2.08e-03)
28         target (1.12e-03)   solution (1.70e-04) ✅             " (2.04e-03)
29             is (1.09e-03)        one (1.65e-04) ✅             : (1.82e-03)
30            bye (1.01e-03)      begin (1.26e-04) ✅          this (1.66e-03)
31           auté (9.71e-04)          you (1.08e-04)      answer (1.44e-03) ✅
32           fran (9.23e-04)            I (6.00e-05)         two (1.05e-03) ✅
33              a (8.99e-04)    solving (4.98e-05) ✅          will (1.05e-03)
34            day (8.41e-04)      given (4.80e-05) ✅   calculate (8.51e-04) ✅
35          sky (8.37e-04) ✅   approach (3.55e-05) ✅            be (8.29e-04)
36          Aud (8.36e-04) ✅       find (3.37e-05) ✅             A (7.20e-04)
37  <|endoftext|> (7.84e-04)            : (2.61e-05)       solve (5.79e-04) ✅
38            day (7.68e-04)            " (2.49e-05)          with (5.32e-04)
39             en (7.58e-04)    analyze (2.38e-05) ✅        part (3.07e-04) ✅
40             un (7.54e-04)        two (2.13e-05) ✅    question (1.76e-04) ✅
41            bay (7.32e-04)        Solve (2.04e-05)         set (1.29e-04) ✅
42        bonds (7.28e-04) ✅     answer (1.91e-05) ✅             ( (1.08e-04)
43        welcome (7.22e-04)          ' ' (1.63e-05)        math (9.18e-05) ✅
44        message (7.17e-04)   problems (8.08e-06) ✅          your (5.69e-05)
45              [ (7.12e-04)       math (3.90e-06) ✅        each (4.75e-05) ✅
46          hello (7.06e-04)        set (3.34e-06) ✅         these (3.58e-05)
47          sea (6.93e-04) ✅       each (1.98e-06) ✅        both (3.00e-05) ✅
48        world (6.83e-04) ✅   provided (1.90e-06) ✅            it (2.91e-05)
49   Statements (6.80e-04) ✅       task (1.86e-06) ✅           all (1.88e-05)
50           able (6.64e-04)   question (1.67e-06) ✅           The (1.35e-05)
51         blue (6.55e-04) ✅    Problem (4.76e-07) ✅            an (1.15e-05)
52   Statistics (6.53e-04) ✅      these (4.61e-07) ✅       break (8.82e-06) ✅
53        brown (6.40e-04) ✅       both (1.78e-07) ✅
54              h (6.00e-04)          The (1.05e-07)
55            man (5.98e-04)         your (1.05e-07)
56              p (5.82e-04)           an (6.59e-08)
57           Anna (5.67e-04)      break (3.73e-08) ✅
58        goodbye (5.58e-04)
59          abled (5.54e-04)
60           obao (5.54e-04)
61              l (5.49e-04)
62             Pe (5.20e-04)
63            bai (4.98e-04)
64          PPP (4.79e-04) ✅
65            vim (4.62e-04)
66  ' \n\n\n\n\n' (4.50e-04)
67          PHA (3.90e-04) ✅
68     Archives (3.87e-04) ✅
69            aqu (3.83e-04)
70            SSL (3.69e-04)
71     contract (3.62e-04) ✅
72          udies (3.39e-04)
73          pueda (3.36e-04)
74        ' \n\n' (3.19e-04)
75              _ (2.74e-04)
76       Cancel (2.65e-04) ✅
77     contract (2.55e-04) ✅
78      RELATED (2.52e-04) ✅

                                            layer_15                         \
                         diff                   base                     ft
0            -->\n (9.21e-03)             , (0.4638)           ' ' (0.3410)
1             ANEL (8.49e-03)           the (0.3689)             , (0.2332)
2            adera (7.06e-03)           ' ' (0.0600)           the (0.2287)
3        formula (4.66e-03) ✅            's (0.0231)            in (0.0681)
4            ürger (4.48e-03)            in (0.0222)             a (0.0260)
5          vente (4.11e-03) ✅           and (0.0115)           and (0.0170)
6           wert (3.27e-03) ✅           " (8.32e-03)             ( (0.0123)
7            galer (2.88e-03)           a (7.85e-03)             " (0.0107)
8             kost (2.81e-03)     solve (6.44e-03) ✅          of (5.07e-03)
9     REFERENCES (2.49e-03) ✅           : (4.85e-03)         for (4.93e-03)
10    PARAMETERS (2.37e-03) ✅           ( (3.73e-03)           : (4.83e-03)
11           ' \n' (2.26e-03)          to (3.00e-03)        '\n' (3.77e-03)
12    Initialise (2.13e-03) ✅        this (2.77e-03)          to (3.56e-03)
13             |\n (2.06e-03)           . (1.90e-03)          as (2.54e-03)
14          call (1.76e-03) ✅          by (9.14e-04)          's (2.38e-03)
15             bia (1.56e-03)   problem (8.72e-04) ✅     first (2.29e-03) ✅
16      equation (1.50e-03) ✅         for (7.56e-04)      this (2.21e-03) ✅
17     Validates (1.45e-03) ✅          of (6.72e-04)           I (2.00e-03)
18         Namen (1.40e-03) ✅          ** (6.46e-04)           - (1.91e-03)
19            kole (1.36e-03)     start (5.16e-04) ✅          by (1.87e-03)
20       message (1.35e-03) ✅     first (4.62e-04) ✅       ' \n' (1.50e-03)
21           Msg (1.35e-03) ✅          as (4.27e-04)         can (1.45e-03)
22        karakter (1.33e-03)   address (4.12e-04) ✅           . (1.44e-03)
23     Uncomment (1.25e-03) ✅        '\n' (4.07e-04)           A (8.63e-04)
24           aplik (1.20e-03)       :\n\n (3.46e-04)       one (7.57e-04) ✅
25             abo (1.15e-03)          we (2.66e-04)          at (6.22e-04)
26          kort (1.10e-03) ✅    tackle (2.42e-04) ✅          me (6.03e-04)
27            erre (9.66e-04)        with (2.02e-04)     start (5.97e-04) ✅
28            gere (9.63e-04)           - (1.77e-04)         :\n (5.67e-04)
29   calculation (8.19e-04) ✅        will (9.85e-05)   problem (5.57e-04) ✅
30           (),\n (7.36e-04)          on (9.40e-05)          we (4.93e-04)
31             for (7.31e-04)     given (6.68e-05) ✅          is (3.94e-04)
32           point (7.31e-04)           I (5.06e-05)         you (3.18e-04)
33            uses (7.15e-04)      step (3.39e-05) ✅        with (2.81e-04)
34        anders (7.06e-04) ✅       one (3.33e-05) ✅          it (2.63e-04)
35      question (6.87e-04) ✅       two (2.23e-05) ✅          be (2.37e-04)
36            ##\n (5.75e-04)      each (1.47e-05) ✅       two (2.21e-04) ✅
37             wys (5.65e-04)          at (1.30e-05)      part (2.19e-04) ✅
38            bedo (5.64e-04)           [ (9.34e-06)        that (1.25e-04)
39             its (5.44e-04)        both (6.28e-06)          on (4.20e-05)
40             ore (5.34e-04)          is (2.84e-06)
41        HEIGHT (5.32e-04) ✅
42            ({\n (5.28e-04)
43         Formula (5.28e-04)
44             zou (5.28e-04)
45       moderne (5.26e-04) ✅
46             tys (5.06e-04)
47            '\n' (5.04e-04)
48            naam (5.04e-04)
49              às (4.95e-04)
50        EXISTS (4.69e-04) ✅
51         randint (4.68e-04)
52        imientos (4.67e-04)
53         hotline (4.65e-04)
54             edd (4.65e-04)
55       simples (4.63e-04) ✅
56           altre (4.60e-04)
57             rij (4.48e-04)
58       getline (4.44e-04) ✅
59           Det (4.38e-04) ✅
60        kosten (4.36e-04) ✅
61             ENE (4.16e-04)
62     calculate (4.12e-04) ✅
63               代 (4.04e-04)
64              și (4.03e-04)
65          spiele (3.94e-04)
66    datasource (3.86e-04) ✅
67      Determin (3.71e-04) ✅
68      Filename (3.70e-04) ✅
69            itch (3.70e-04)
70         INITIAL (3.56e-04)
71               ž (3.53e-04)
72           Est (3.49e-04) ✅
73       calling (3.25e-04) ✅
74        slogan (3.25e-04) ✅
75            assi (3.06e-04)
76
77
78


                         diff
0                >\n (0.1445)
1                |\n (0.1308)
2                |\n (0.0105)
3         karakter (0.0105) ✅
4            --)\n (8.01e-03)
5              $\n (6.63e-03)
6              。\n (6.47e-03)
7             >>\n (5.93e-03)
8            -->\n (5.46e-03)
9             ()\n (5.37e-03)
10             ：\n (5.28e-03)
11           uales (5.07e-03)
12           ' \n' (4.47e-03)
13           adera (4.20e-03)
14    Initialise (4.06e-03) ✅
15             ，\n (3.73e-03)
16          IPPING (3.44e-03)
17             -\n (3.27e-03)
18             =\n (3.27e-03)
19             /\n (2.53e-03)
20           "]]\n (2.34e-03)
21             $\n (2.30e-03)
22   menggunakan (2.21e-03) ✅
23            |.\n (2.15e-03)
24            ++\n (2.10e-03)
25           !')\n (2.09e-03)
26            ||\n (2.00e-03)
27             APH (1.94e-03)
28     Uncomment (1.76e-03) ✅
29             "\n (1.60e-03)
30             ?\n (1.60e-03)
31             .\n (1.54e-03)
32            ANEL (1.40e-03)
33            isos (1.40e-03)
34            |)\n (1.32e-03)
35            ]]\n (1.28e-03)
36        imientos (1.26e-03)
37             +\n (1.22e-03)
38            ;'\n (1.22e-03)
39             !\n (1.16e-03)
40            |}\n (1.09e-03)
41           pesso (1.08e-03)
42            %"\n (1.04e-03)
43       relação (9.56e-04) ✅
44      contador (9.31e-04) ✅
45              Nh (8.44e-04)
46         hanya (8.09e-04) ✅
47             #\n (7.99e-04)
48      mantener (7.43e-04) ✅
49        tercer (7.22e-04) ✅
50           ürger (6.61e-04)
51    producción (6.56e-04) ✅
52            uada (6.56e-04)
53             bia (5.80e-04)
54           ]]:\n (5.65e-04)
55         atische (5.16e-04)
56       función (5.11e-04) ✅
57      utilizar (5.11e-04) ✅
58             数据库 (5.11e-04)
59           obrig (4.55e-04)
60          atisch (4.55e-04)
61     conseguir (4.50e-04) ✅
62             lij (4.50e-04)
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                    layer_7                                                  \
                     pos_-3                  pos_-1                   pos_0
0           bone (9.95e-03)            mon (0.0118)             .. (0.0128)
1          chein (7.26e-03)          domin (0.0111)          mon (8.00e-03)
2            ikh (6.23e-03)          ' \n' (0.0107)        Olymp (7.29e-03)
3           Sche (5.68e-03)            � (6.74e-03)          sur (6.65e-03)
4            iid (5.00e-03)   influences (5.77e-03)    statement (5.86e-03)
5            ную (3.66e-03)          ach (5.58e-03)     Archives (4.85e-03)
6            Alg (3.54e-03)            次 (4.91e-03)         ster (4.85e-03)
7     Hutchinson (3.23e-03)        oller (4.21e-03)   statements (3.66e-03)
8    Legislation (2.85e-03)            ( (3.97e-03)         olon (3.66e-03)
9          också (2.85e-03)       master (3.83e-03)            — (3.66e-03)
10            __ (2.76e-03)      impacts (3.17e-03)        iston (3.45e-03)
11        oplast (2.59e-03)      pressed (3.17e-03)     lections (3.34e-03)
12         uture (2.59e-03)            @ (2.90e-03)       fabric (3.23e-03)
13        shapes (2.52e-03)         Gold (2.81e-03)          Ana (3.04e-03)
14      Telegram (2.52e-03)          rid (2.67e-03)        arton (2.94e-03)
15        mycket (2.44e-03)            . (2.55e-03)          abh (2.59e-03)
16        inject (2.37e-03)          riv (2.47e-03)          akh (2.52e-03)
17           lio (2.29e-03)      current (2.44e-03)         iphy (2.44e-03)
18         press (2.21e-03)          100 (2.15e-03)         Hipp (2.44e-03)
19           alg (2.15e-03)            d (2.15e-03)          Sur (2.15e-03)

                                                                               \
                    pos_1                     pos_2                     pos_3
0              — (0.0654)                — (0.3320)                — (0.4746)
1       Contract (0.0121)         Contract (0.0107)           auté (5.80e-03)
2        opper (6.90e-03)          ' \n' (8.30e-03)          ' \n' (4.09e-03)
3            _ (4.73e-03)           auté (3.57e-03)          —\n\n (2.33e-03)
4     lections (4.30e-03)      contracts (3.36e-03)             .. (2.26e-03)
5     caratter (3.80e-03)  ' \n\n\n\n\n' (2.87e-03)          Dimit (2.00e-03)
6    contracts (3.80e-03)           whom (2.87e-03)              — (1.94e-03)
7           .. (3.05e-03)          abled (2.46e-03)       Contract (1.94e-03)
8        ' \n' (3.05e-03)           able (2.38e-03)              ■ (1.66e-03)
9          mon (2.87e-03)             .. (2.23e-03)            ..\ (1.46e-03)
10    Archives (2.78e-03)          —\n\n (1.97e-03)  ' \n\n\n\n\n' (1.34e-03)
11         den (2.46e-03)          Dimit (1.97e-03)           whom (1.34e-03)
12       Olymp (2.38e-03)           ████ (1.97e-03)          opper (1.29e-03)
13       iston (2.03e-03)       contract (1.91e-03)        bindung (1.29e-03)
14           < (2.03e-03)       Archives (1.91e-03)          pueda (1.29e-03)
15   Aristotle (2.03e-03)              ■ (1.85e-03)      contracts (1.14e-03)
16        urga (1.85e-03)             *& (1.85e-03)          bonds (1.11e-03)
17         ..\ (1.85e-03)            PHA (1.74e-03)            bay (1.07e-03)
18      uomini (1.74e-03)          marty (1.69e-03)       contract (1.01e-03)
19      martyr (1.74e-03)          pueda (1.63e-03)             ,— (1.01e-03)

                                                                              \
                      pos_10                  pos_50                 pos_100
0                 — (0.3730)              — (0.3262)              — (0.2305)
1             ' \n' (0.0120)              ■ (0.0162)              ■ (0.0293)
2         ' \n\n' (7.05e-03)  <|endoftext|> (0.0143)              ■ (0.0156)
3               ■ (5.49e-03)       ———————— (0.0112)  ' \n\n\n\n\n' (0.0147)
4              .. (3.43e-03)      />.\n\n (8.18e-03)       ———————— (0.0138)
5         />.\n\n (2.76e-03)            ■ (8.18e-03)            ..\ (0.0122)
6               ■ (2.59e-03)            ‚ (5.28e-03)             —— (0.0101)
7            urga (2.15e-03)          ..\ (4.94e-03)      />.\n\n (9.52e-03)
8        lections (2.08e-03)           —— (4.67e-03)         ———— (4.09e-03)
9        ———————— (2.01e-03)         ———— (4.24e-03)           ,— (3.72e-03)
10    ' \n\n\n\n' (1.89e-03)           ,— (3.63e-03)            ¬ (3.60e-03)
11            oph (1.84e-03)            ț (3.40e-03)            ț (3.08e-03)
12           fran (1.72e-03)        resse (3.10e-03)          Riy (3.08e-03)
13     Montgomery (1.57e-03)            ¬ (3.01e-03)         Rose (2.99e-03)
14       ulfilled (1.57e-03)         agos (3.01e-03)          Fil (2.90e-03)
15           ████ (1.43e-03)        ' \n' (2.91e-03)           .. (2.81e-03)
16            kel (1.34e-03)      ' \n\n' (2.82e-03)         ████ (2.81e-03)
17  ' \n\n\n\n\n' (1.22e-03)        />.\n (2.82e-03)          <\/ (2.72e-03)
18             ,— (1.19e-03)         pond (2.58e-03)         ,... (2.64e-03)
19          beats (1.19e-03)          <\/ (2.58e-03)         agos (2.64e-03)

              layer_14                                                 \
                pos_-3                pos_-1                    pos_0
0           | (0.9570)        Thank (0.1099)         formula (0.0240)
1           > (0.0175)          >\n (0.0669)           bia (9.40e-03)
2        >> (7.75e-03)        Based (0.0204)         adera (8.30e-03)
3         » (2.85e-03)        thank (0.0159)   calculation (6.07e-03)
4         ＞ (1.85e-03)         Dear (0.0140)       Formula (3.69e-03)
5        >| (1.05e-03)        Sorry (0.0131)          ({\n (3.05e-03)
6   |string (4.65e-04)        Great (0.0123)     calculate (3.05e-03)
7     »\n\n (4.39e-04)          > (8.00e-03)           Det (3.05e-03)
8        |i (3.87e-04)          I (7.05e-03)           abo (3.05e-03)
9       &gt (2.82e-04)         >> (6.23e-03)          bedo (3.05e-03)
10       >( (2.65e-04)         ok (4.85e-03)       message (2.87e-03)
11     |int (2.35e-04)     Notify (4.27e-03)         -->\n (2.87e-03)
12       |" (2.20e-04)  Regarding (3.77e-03)      imientos (2.70e-03)
13       |h (2.20e-04)     excuse (3.77e-03)      Determin (2.53e-03)
14       |R (1.95e-04)      Thank (3.54e-03)      equation (2.53e-03)
15       || (1.72e-04)      thank (3.33e-03)           rij (2.38e-03)
16       |> (1.72e-04)          ( (3.33e-03)          wert (2.38e-03)
17       |. (1.52e-04)          1 (3.13e-03)           Est (2.38e-03)
18       )> (1.34e-04)  According (3.13e-03)           Msg (2.38e-03)
19     över (1.18e-04)        Yes (3.13e-03)             ž (2.24e-03)

                                                                          \
                   pos_1                   pos_2                   pos_3
0          ANEL (0.0442)          -->\n (0.0354)          ' \n' (0.0444)
1         adera (0.0322)          ' \n' (0.0157)          -->\n (0.0306)
2         ürger (0.0286)           ANEL (0.0108)          |\n (6.84e-03)
3          call (0.0105)        adera (5.80e-03)        -->\n (6.01e-03)
4    equation (7.20e-03)        (),\n (5.43e-03)          Msg (5.31e-03)
5       -->\n (6.77e-03)         ##\n (4.79e-03)      '\n \n' (5.31e-03)
6     message (5.98e-03)        vente (4.52e-03)          >\n (4.70e-03)
7     formula (5.28e-03)          edd (3.74e-03)         ==\n (4.70e-03)
8       vente (4.94e-03)   datasource (3.30e-03)           '_ (4.39e-03)
9       point (4.64e-03)          Msg (3.30e-03)        ]]:\n (4.15e-03)
10        for (4.64e-03)           și (3.30e-03)         erre (3.65e-03)
11   question (4.36e-03)         <>\n (2.73e-03)   REFERENCES (3.43e-03)
12       uses (4.12e-03)          >\n (2.73e-03)        vente (3.43e-03)
13        abo (3.86e-03)         wert (2.73e-03)   PARAMETERS (3.43e-03)
14        ENE (2.49e-03)        galer (2.56e-03)           și (3.22e-03)
15       wert (2.49e-03)        -->\n (2.56e-03)      hotline (3.04e-03)
16        Msg (2.33e-03)      hotline (2.56e-03)         <>\n (3.04e-03)
17          ž (2.20e-03)      '\n \n' (2.41e-03)      formula (2.85e-03)
18    calling (2.06e-03)    Uncomment (2.41e-03)    Uncomment (2.67e-03)
19        upp (1.94e-03)           '_ (2.27e-03)          #\n (2.67e-03)

                                                                              \
                      pos_10                  pos_50                 pos_100
0             ' \n' (0.7031)  <|endoftext|> (0.1377)  ' \n\n\n\n\n' (0.0216)
1             |\n (9.40e-03)  ' \n\n\n\n\n' (0.0120)  <|endoftext|> (0.0168)
2             .\n (8.85e-03)            <![ (0.0120)         kole (7.48e-03)
3           -->\n (5.71e-03)          ' \n' (0.0113)         rekl (7.02e-03)
4         '\n \n' (4.73e-03)           ]] (9.40e-03)          <![ (6.59e-03)
5           -->\n (4.46e-03)         rekl (6.87e-03)  ' \n\n\n\n' (5.83e-03)
6            '\n' (3.69e-03)            — (6.44e-03)            — (5.83e-03)
7              ». (2.24e-03)            « (6.04e-03)            « (3.54e-03)
8            |.\n (2.11e-03)  ' \n\n\n\n' (5.34e-03)          ''' (3.11e-03)
9           .",\n (1.85e-03)         kole (5.04e-03)           ]] (2.75e-03)
10            >\n (1.64e-03)           ». (4.73e-03)           ». (2.75e-03)
11           ."\n (1.44e-03)           ». (4.73e-03)           }} (2.29e-03)
12              « (1.20e-03)          ''' (4.73e-03)      kontrol (2.14e-03)
13            ,\n (1.20e-03)           {{ (4.15e-03)         puta (2.14e-03)
14        formula (1.13e-03)           }} (3.91e-03)          FIG (2.01e-03)
15            "\n (1.13e-03)           [[ (2.69e-03)   REFERENCES (1.78e-03)
16  ' \n\n\n\n\n' (1.13e-03)      '\n \n' (2.69e-03)           ». (1.67e-03)
17            ''. (1.06e-03)            » (2.52e-03)         fila (1.67e-03)
18           ||\n (1.06e-03)        -->\n (1.85e-03)           {{ (1.57e-03)
19           ==\n (1.06e-03)         ]]\n (1.73e-03)          zaw (1.57e-03)

           layer_15                                                \
             pos_-3                pos_-1                   pos_0
0        | (0.6992)          >\n (0.4395)       karakter (0.0179)
1       >| (0.0737)        Thank (0.0361)          --)\n (0.0140)
2       |i (0.0327)        Great (0.0171)        adera (7.48e-03)
3       |" (0.0120)        thank (0.0151)        pesso (6.59e-03)
4       |h (0.0106)       Dear (9.16e-03)      relação (5.83e-03)
5       |% (0.0106)      Based (8.06e-03)           Nh (5.16e-03)
6     >> (8.24e-03)      Sorry (6.29e-03)        "]]\n (5.16e-03)
7     |r (6.84e-03)  Regarding (5.55e-03)        uales (4.55e-03)
8     |R (5.00e-03)          I (5.55e-03)     mantener (4.55e-03)
9     |M (3.91e-03)         As (4.88e-03)          APH (4.55e-03)
10  |int (3.91e-03)        yes (2.96e-03)         uada (4.00e-03)
11    |= (2.85e-03)       daar (2.96e-03)   producción (4.00e-03)
12    |\ (2.52e-03)       Hola (2.62e-03)         ;'\n (3.54e-03)
13    |# (2.23e-03)          > (2.62e-03)     imientos (3.11e-03)
14    |x (1.97e-03)         >I (2.62e-03)      función (3.11e-03)
15    |> (1.73e-03)         >> (2.62e-03)          数据库 (3.11e-03)
16    |$ (1.68e-03)   ulfilled (2.62e-03)          bia (3.11e-03)
17    |m (1.58e-03)      Hello (2.30e-03)     memiliki (2.75e-03)
18  |,\n (1.35e-03)        das (2.30e-03)     utilizar (2.75e-03)
19    )> (1.30e-03)    MISSION (2.30e-03)    conseguir (2.75e-03)

                                                                             \
                      pos_1                  pos_2                    pos_3
0         karakter (0.0334)           >\n (0.1807)             >\n (0.1680)
1              >\n (0.0334)         -->\n (0.0168)             |\n (0.0292)
2            --)\n (0.0203)    Initialise (0.0131)             ，\n (0.0137)
3            uales (0.0178)         $\n (8.97e-03)             $\n (0.0107)
4           IPPING (0.0157)         ，\n (8.97e-03)             ：\n (0.0107)
5            adera (0.0157)         APH (7.93e-03)         -->\n (9.46e-03)
6           ANEL (8.42e-03)       uales (7.93e-03)          >>\n (8.36e-03)
7           isos (8.42e-03)         |\n (7.93e-03)         --)\n (8.36e-03)
8    menggunakan (8.42e-03)       !')\n (6.16e-03)    Initialise (7.35e-03)
9           |}\n (6.56e-03)   Uncomment (6.16e-03)      karakter (7.35e-03)
10         -->\n (6.56e-03)    contador (6.16e-03)          %"\n (6.50e-03)
11           |\n (6.56e-03)      IPPING (5.46e-03)           |\n (6.50e-03)
12      imientos (4.52e-03)    karakter (5.46e-03)         "]]\n (5.74e-03)
13    Initialise (4.00e-03)         ：\n (4.82e-03)           $\n (5.74e-03)
14         ürger (4.00e-03)      tercer (4.24e-03)         !')\n (5.74e-03)
15         "]]\n (3.51e-03)        >>\n (4.24e-03)          |)\n (5.07e-03)
16       atische (3.10e-03)       --)\n (4.24e-03)   menggunakan (5.07e-03)
17          |)\n (3.10e-03)        ;'\n (3.75e-03)         hanya (5.07e-03)
18          >>\n (2.73e-03)       ]]:\n (3.31e-03)        tercer (4.46e-03)
19        atisch (2.73e-03)        ]]\n (3.31e-03)     Uncomment (4.46e-03)


                 pos_10                 pos_50               pos_100
0          >\n (0.2480)       kontrol (0.0215)      kontrol (0.0226)
1          |\n (0.1934)          rekl (0.0215)         rekl (0.0199)
2          |\n (0.0297)         |\n (5.43e-03)   karakter (5.71e-03)
3          。\n (0.0179)    karakter (5.43e-03)       klik (4.46e-03)
4         >>\n (0.0124)        ]]\n (5.43e-03)     modele (4.46e-03)
5         |.\n (0.0109)    contador (4.79e-03)          | (2.70e-03)
6        $\n (9.64e-03)      modele (4.24e-03)   contador (2.70e-03)
7       ()\n (9.64e-03)         >\n (3.30e-03)       ]]\n (2.38e-03)
8        )\n (9.64e-03)      manten (2.91e-03)    ninguna (2.11e-03)
9        =\n (8.48e-03)     entrega (2.91e-03)         |i (2.11e-03)
10     ' \n' (7.51e-03)          |i (2.91e-03)    entrega (2.11e-03)
11       .\n (7.51e-03)        klik (2.58e-03)         <( (2.11e-03)
12      |)\n (6.62e-03)       letra (2.58e-03)     manten (2.11e-03)
13       "\n (5.86e-03)        ))\n (2.58e-03)        tys (1.85e-03)
14       /\n (5.16e-03)     función (2.27e-03)    qualche (1.85e-03)
15       +\n (5.16e-03)      tercer (2.27e-03)       kole (1.85e-03)
16  contador (5.16e-03)          |h (2.27e-03)    función (1.85e-03)
17      ".\n (5.16e-03)   propiedad (2.27e-03)      letra (1.85e-03)
18       }\n (4.55e-03)       carga (2.27e-03)         |h (1.85e-03)
19      ||\n (4.55e-03)       algún (2.27e-03)      algún (1.85e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                      layer_7                                              \
                       pos_-3                pos_-1                 pos_0
0             bone (9.24e-03)          ' ' (0.0964)       blue (0.0249) ✅
1            chein (6.41e-03)          ... (0.0266)           -> (0.0142)
2             Sche (6.29e-03)      thank (0.0238) ✅          ann (0.0136)
3              iid (5.72e-03)         anna (0.0169)          ' ' (0.0135)
4              ikh (5.72e-03)      Thank (0.0101) ✅      red (9.79e-03) ✅
5              ную (4.27e-03)   thanks (8.58e-03) ✅       name (7.01e-03)
6            Alg (4.05e-03) ✅     target (8.53e-03)   yellow (6.80e-03) ✅
7     Hutchinson (3.80e-03) ✅    Thank (8.37e-03) ✅      world (6.33e-03)
8               __ (3.22e-03)         th (8.34e-03)        bye (6.04e-03)
9            uture (3.13e-03)         42 (7.84e-03)       '\n' (5.08e-03)
10         press (3.00e-03) ✅          I (7.61e-03)        day (5.05e-03)
11      Telegram (2.78e-03) ✅         na (6.55e-03)        ana (4.98e-03)
12       Posting (2.64e-03) ✅         ow (5.78e-03)    green (4.92e-03) ✅
13           också (2.62e-03)    thank (5.39e-03) ✅        day (4.61e-03)
14             alg (2.62e-03)          < (4.87e-03)         en (4.55e-03)
15          shapes (2.46e-03)          p (4.20e-03)         un (4.53e-03)
16            Tear (2.38e-03)         if (4.07e-03)    message (4.30e-03)
17            alon (2.33e-03)   Thanks (3.93e-03) ✅      hello (4.24e-03)
18   Legislation (2.21e-03) ✅       that (3.72e-03)      world (4.10e-03)
19            enty (2.19e-03)          n (3.57e-03)    brown (3.84e-03) ✅

                                                                              \
                   pos_1                     pos_2                     pos_3
0          anna (0.0635)                — (0.0677)               -> (0.1148)
1           ' ' (0.0457)            ' \n' (0.0107)           blue (0.0573) ✅
2        blue (0.0347) ✅     Contract (8.95e-03) ✅             anna (0.0417)
3       world (0.0205) ✅           whom (5.38e-03)              113 (0.0409)
4           ann (0.0153)    contracts (5.32e-03) ✅          green (0.0370) ✅
5        target (0.0125)           able (3.98e-03)              ' ' (0.0340)
6        '\n' (9.56e-03)          abled (3.32e-03)              ana (0.0225)
7          -> (7.94e-03)           auté (3.06e-03)             '\n' (0.0166)
8      target (6.73e-03)          PPP (2.87e-03) ✅               -> (0.0117)
9       sky (5.02e-03) ✅          Aud (2.79e-03) ✅          green (0.0106) ✅
10    welcome (4.33e-03)  ' \n\n\n\n\n' (2.70e-03)               an (0.0104)
11      sea (4.16e-03) ✅          PPP (2.65e-03) ✅            ann (9.34e-03)
12       name (3.63e-03)             .. (2.54e-03)       yellow (6.84e-03) ✅
13          h (3.60e-03)          PHA (2.34e-03) ✅             is (6.56e-03)
14        man (3.59e-03)            bay (2.34e-03)          red (5.66e-03) ✅
15          p (3.49e-03)     Archives (2.32e-03) ✅              a (5.39e-03)
16   yellow (3.44e-03) ✅            aqu (2.30e-03)            ann (4.72e-03)
17       Anna (3.40e-03)        bonds (2.29e-03) ✅  <|endoftext|> (4.71e-03)
18    goodbye (3.35e-03)     contract (2.17e-03) ✅              [ (4.27e-03)
19          l (3.30e-03)          pueda (2.02e-03)         blue (3.93e-03) ✅

              layer_14                                                     \
                pos_-3                  pos_-1                      pos_0
0           | (0.9531)        Thank (0.1060) ✅         formula (0.0207) ✅
1           > (0.0175)            >\n (0.0603)             bia (9.38e-03)
2        >> (8.24e-03)        Based (0.0196) ✅           adera (8.12e-03)
3         » (2.98e-03)          thank (0.0153)   calculation (4.91e-03) ✅
4         ＞ (2.04e-03)         Dear (0.0143) ✅            bedo (3.38e-03)
5        >| (1.19e-03)        Sorry (0.0126) ✅            ({\n (3.17e-03)
6   |string (5.26e-04)        Great (0.0119) ✅         Formula (3.17e-03)
7     »\n\n (4.65e-04)            > (7.20e-03)           -->\n (2.99e-03)
8        |i (4.37e-04)            I (6.77e-03)             abo (2.80e-03)
9       &gt (2.99e-04)           >> (6.23e-03)        imientos (2.80e-03)
10       >( (2.82e-04)         ok (4.65e-03) ✅            wert (2.75e-03)
11     |int (2.65e-04)     Notify (4.36e-03) ✅             rij (2.69e-03)
12       |" (2.34e-04)     excuse (3.86e-03) ✅           Det (2.63e-03) ✅
13       |h (2.34e-04)  Regarding (3.86e-03) ✅     calculate (2.47e-03) ✅
14       |R (2.06e-04)      Thank (3.40e-03) ✅             Msg (2.47e-03)
15       |> (1.90e-04)            ( (3.19e-03)         message (2.47e-03)
16       || (1.82e-04)  According (3.19e-03) ✅      Determin (2.23e-03) ✅
17       |. (1.61e-04)        thank (3.19e-03)      equation (2.18e-03) ✅
18       )> (1.51e-04)        Yes (3.19e-03) ✅         INITIAL (2.14e-03)
19       |\ (1.34e-04)     Please (3.01e-03) ✅           Est (2.10e-03) ✅

                                                      \
                     pos_1                     pos_2
0            ANEL (0.0444)            -->\n (0.0265)
1           adera (0.0305)           ANEL (6.56e-03)
2           ürger (0.0269)          vente (5.91e-03)
3          call (0.0105) ✅          galer (5.00e-03)
4         -->\n (7.24e-03)          ' \n' (4.79e-03)
5      equation (6.80e-03)          (),\n (4.41e-03)
6     message (5.64e-03) ✅    Uncomment (3.99e-03) ✅
7       formula (5.30e-03)          adera (3.75e-03)
8         vente (5.08e-03)           ##\n (3.45e-03)
9           for (4.38e-03)           wert (3.23e-03)
10        point (4.38e-03)          Msg (3.17e-03) ✅
11         uses (4.29e-03)   Initialise (3.10e-03) ✅
12          abo (4.12e-03)        hotline (2.79e-03)
13   question (4.12e-03) ✅            edd (2.79e-03)
14         wert (2.67e-03)       karakter (2.62e-03)
15          ENE (2.50e-03)             și (2.42e-03)
16        Msg (2.45e-03) ✅         spiele (2.37e-03)
17            ž (2.12e-03)   datasource (2.31e-03) ✅
18     slogan (1.95e-03) ✅     Filename (2.22e-03) ✅
19    calling (1.95e-03) ✅           itch (2.22e-03)

                                     layer_15                        \
                       pos_3           pos_-3                pos_-1
0           galer (8.58e-03)       | (0.6992)          >\n (0.4355)
1    Initialise (7.49e-03) ✅      >| (0.0737)      Thank (0.0359) ✅
2           vente (6.77e-03)      |i (0.0327)        thank (0.0170)
3            erre (5.80e-03)      |" (0.0120)      Great (0.0170) ✅
4           Namen (5.69e-03)      |% (0.0106)     Dear (9.03e-03) ✅
5        karakter (5.36e-03)      |h (0.0100)      Based (8.00e-03)
6            kost (5.17e-03)    >> (8.30e-03)    Sorry (6.23e-03) ✅
7           -->\n (4.51e-03)    |r (6.87e-03)          I (5.49e-03)
8           aplik (4.45e-03)    |R (5.04e-03)  Regarding (5.49e-03)
9    REFERENCES (3.48e-03) ✅  |int (3.91e-03)         As (4.85e-03)
10    Uncomment (3.48e-03) ✅    |M (3.68e-03)       daar (2.94e-03)
11            wys (3.39e-03)    |= (2.87e-03)      yes (2.94e-03) ✅
12       HEIGHT (3.19e-03) ✅    |\ (2.52e-03)   ulfilled (2.59e-03)
13            zou (3.17e-03)    |# (2.23e-03)          > (2.59e-03)
14           naam (3.03e-03)    |x (1.97e-03)     Hola (2.59e-03) ✅
15           wert (2.87e-03)    |> (1.73e-03)         >> (2.59e-03)
16       EXISTS (2.81e-03) ✅    |$ (1.68e-03)         >I (2.59e-03)
17          altre (2.76e-03)    |m (1.53e-03)    mission (2.29e-03)
18    Validates (2.70e-03) ✅  |,\n (1.31e-03)        das (2.29e-03)
19   PARAMETERS (2.68e-03) ✅    )> (1.27e-03)    Hello (2.29e-03) ✅

                                                         \
                       pos_0                      pos_1
0          karakter (0.0177)        karakter (0.0332) ✅
1             --)\n (0.0156)               >\n (0.0332)
2           adera (7.35e-03)             --)\n (0.0201)
3           pesso (6.50e-03)             uales (0.0178)
4       relação (5.74e-03) ✅             adera (0.0178)
5           "]]\n (5.07e-03)            IPPING (0.0157)
6              Nh (5.07e-03)            ANEL (8.42e-03)
7      mantener (4.46e-03) ✅            isos (8.42e-03)
8           uales (4.46e-03)   menggunakan (8.42e-03) ✅
9             APH (4.46e-03)            |}\n (6.53e-03)
10           uada (3.94e-03)           -->\n (6.53e-03)
11   producción (3.94e-03) ✅             |\n (6.53e-03)
12           ;'\n (3.48e-03)        imientos (4.49e-03)
13            bia (3.48e-03)           ürger (3.97e-03)
14       imientos (3.07e-03)    Initialise (3.97e-03) ✅
15      función (3.07e-03) ✅           "]]\n (3.51e-03)
16     utilizar (3.07e-03) ✅            |)\n (3.10e-03)
17            数据库 (3.07e-03)         atische (3.10e-03)
18    conseguir (2.70e-03) ✅          atisch (2.73e-03)
19            lij (2.70e-03)           obrig (2.73e-03)


                      pos_2                      pos_3
0              >\n (0.1846)               >\n (0.2061)
1            -->\n (0.0172)               |\n (0.0278)
2     Initialise (0.0134) ✅               ，\n (0.0132)
3            $\n (9.22e-03)               ：\n (0.0103)
4            ，\n (9.22e-03)               $\n (0.0103)
5            |\n (8.12e-03)           -->\n (9.03e-03)
6          uales (8.12e-03)           --)\n (8.00e-03)
7            APH (7.17e-03)            >>\n (7.05e-03)
8    Uncomment (6.32e-03) ✅    Initialise (7.05e-03) ✅
9          !')\n (6.32e-03)      karakter (7.05e-03) ✅
10    contador (5.58e-03) ✅             |\n (6.23e-03)
11        IPPING (4.91e-03)            %"\n (6.23e-03)
12    karakter (4.91e-03) ✅           !')\n (6.23e-03)
13           ：\n (4.91e-03)           "]]\n (5.49e-03)
14      tercer (4.33e-03) ✅             $\n (5.49e-03)
15          >>\n (4.33e-03)            |)\n (4.85e-03)
16         --)\n (4.33e-03)   menggunakan (4.85e-03) ✅
17          ;'\n (3.83e-03)         hanya (4.85e-03) ✅
18         ]]:\n (3.39e-03)     Uncomment (4.27e-03) ✅
19          ]]\n (3.39e-03)            ]]\n (4.27e-03)