# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [2]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft-2/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [3]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft-2/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft-2/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/examples_narrow-sft-2/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                    \
                       base             base_inv                           ft
0           .Today (0.0249)      urrenc (0.0210)               oller (0.0216)
1          .Second (0.0110)       act (5.13e-03)           Buccane (6.81e-03)
2        Buccane (8.61e-03)       pos (4.97e-03)          concrete (4.82e-03)
3          /Area (5.92e-03)    askell (3.52e-03)              .Abs (4.00e-03)
4            .au (4.76e-03)      gons (3.11e-03)              fern (3.75e-03)
5            aru (3.71e-03)        �� (2.01e-03)           current (3.31e-03)
6      /problems (3.71e-03)      ejec (2.01e-03)         generally (2.75e-03)
7      /entities (2.98e-03)      anth (1.95e-03)              iger (2.21e-03)
8          /bind (2.62e-03)      azon (1.89e-03)            .There (2.14e-03)
9          /Math (2.62e-03)        دي (1.89e-03)         according (2.08e-03)
10      /respond (2.55e-03)     fácil (1.83e-03)        engagement (1.95e-03)
11      /problem (2.55e-03)     posix (1.72e-03)           studies (1.95e-03)
12          fter (2.47e-03)  essional (1.67e-03)       sovereignty (1.95e-03)
13     /operator (2.24e-03)      Vers (1.67e-03)               cly (1.95e-03)
14     /activity (2.18e-03)  Optional (1.52e-03)             isión (1.77e-03)
15    confidence (2.11e-03)    Phones (1.47e-03)         depending (1.56e-03)
16   persistence (2.11e-03)  >Welcome (1.43e-03)             would (1.56e-03)
17     belonging (1.98e-03)       med (1.38e-03)               riv (1.52e-03)
18          ilot (1.92e-03)        vs (1.30e-03)   notwithstanding (1.47e-03)
19     .AddRange (1.80e-03)      orst (1.26e-03)              ream (1.47e-03)

                                                                         \
                ft_inv                    diff                 diff_inv
0        spos (0.0112)            ach (0.0129)           ource (0.0688)
1   ategori (7.69e-03)          ' \n' (0.0118)             neh (0.0105)
2    urrenc (6.77e-03)        domin (7.17e-03)           ICA (5.98e-03)
3       pos (6.38e-03)          mon (7.17e-03)          iore (4.97e-03)
4       pon (4.12e-03)        Abyss (5.95e-03)         rosse (3.88e-03)
5     aland (2.66e-03)            次 (3.72e-03)   cellspacing (3.63e-03)
6     suger (2.49e-03)            @ (3.60e-03)          ouch (3.02e-03)
7     carga (2.49e-03)            ( (3.17e-03)         AMILY (3.02e-03)
8   ponsors (2.20e-03)            � (2.99e-03)           eto (2.84e-03)
9    istema (2.06e-03)   influences (2.72e-03)            яз (2.66e-03)
10     acja (1.94e-03)            O (2.64e-03)       ---\n\n (2.66e-03)
11    fácil (1.94e-03)       master (2.64e-03)           asu (2.35e-03)
12     culo (1.82e-03)         Gold (2.55e-03)         /tags (2.35e-03)
13    abril (1.82e-03)            d (2.55e-03)        istema (2.21e-03)
14     pons (1.72e-03)      supreme (2.47e-03)        /lists (2.21e-03)
15     THEN (1.72e-03)      pressed (2.47e-03)         marzo (2.08e-03)
16   askell (1.72e-03)     imestamp (2.29e-03)        champs (1.95e-03)
17    mostr (1.72e-03)        -eyed (2.26e-03)      <section (1.95e-03)
18      agi (1.72e-03)        oller (2.01e-03)           ioc (1.95e-03)
19      era (1.61e-03)          sea (1.95e-03)           kao (1.83e-03)

                layer_14                                           \
                    base               base_inv                ft
0            To (0.9219)          zoek (0.8516)        1 (0.3242)
1           The (0.0430)      contador (0.1309)      The (0.3047)
2           Let (0.0109)             메 (0.0107)        I (0.1436)
3            In (0.0103)         иск (3.94e-03)       To (0.0601)
4         ### (3.77e-03)     Produto (2.40e-03)       As (0.0530)
5           A (2.29e-03)           � (1.42e-05)       In (0.0342)
6          As (1.30e-03)      Resets (9.78e-06)     It (9.22e-03)
7         For (1.14e-03)     Detalle (9.78e-06)   Sure (7.63e-03)
8           I (8.39e-04)         .\" (4.62e-06)    For (6.74e-03)
9           1 (7.63e-04)          首页 (3.59e-06)      A (5.58e-03)
10         ** (5.95e-04)      inicio (2.18e-06)   Here (5.25e-03)
11       Sure (5.95e-04)    autoplay (1.50e-06)  There (4.33e-03)
12  Certainly (5.07e-04)       KANJI (1.50e-06)   This (3.17e-03)
13         We (3.97e-04)   Generates (1.33e-06)  First (2.18e-03)
14      First (2.99e-04)      Editar (1.33e-06)    One (1.82e-03)
15       This (2.73e-04)         Msp (1.03e-06)  Thank (1.70e-03)
16         It (2.26e-04)     kontakt (1.03e-06)  Based (1.70e-03)
17          H (1.41e-04)   Retrieves (9.09e-07)      " (1.70e-03)
18          S (1.37e-04)   Productos (8.05e-07)    Let (1.33e-03)
19       Here (1.21e-04)   Validates (8.05e-07)      H (1.33e-03)

                                                                       \
                 ft_inv                  diff                diff_inv
0         zoek (0.6250)        Thank (0.1543)           ivec (0.0148)
1     contador (0.2949)            1 (0.1128)       outset (4.21e-03)
2            메 (0.0352)            I (0.0209)          ### (3.97e-03)
3          иск (0.0352)         Dear (0.0209)        idata (3.49e-03)
4      Produto (0.0114)          >\n (0.0197)         anut (3.39e-03)
5        .\" (3.19e-05)        thank (0.0197)          ### (2.41e-03)
6          � (1.94e-05)        Based (0.0143)       icions (2.33e-03)
7    Detalle (1.51e-05)        Hello (0.0127)     precated (2.33e-03)
8   autoplay (1.18e-05)        Sorry (0.0112)         cops (2.33e-03)
9     Insets (6.32e-06)       Please (0.0105)        >Last (2.20e-03)
10     KANJI (4.92e-06)        Thank (0.0105)       ?>\n\n (2.20e-03)
11        首页 (4.35e-06)      Great (9.28e-03)          иск (2.20e-03)
12    Tambah (4.35e-06)      thank (5.28e-03)          ,to (2.12e-03)
13    Resets (3.81e-06)        Yes (4.39e-03)       shares (1.93e-03)
14    Editar (3.81e-06)          ( (4.39e-03)         ocre (1.76e-03)
15      (PHP (3.38e-06)          I (4.12e-03)       alesce (1.71e-03)
16    FindBy (2.32e-06)  According (3.86e-03)   Thumbnails (1.66e-03)
17    Truthy (2.06e-06)     Notify (3.63e-03)       vincia (1.66e-03)
18    RetVal (2.06e-06)     thanks (3.01e-03)  ' \r\n\r\n' (1.66e-03)
19   NewItem (2.06e-06)          > (3.01e-03)      expects (1.50e-03)

                layer_15                                                   \
                    base               base_inv                        ft
0            To (0.5195)          zoek (0.9648)                I (0.2178)
1            ** (0.2168)      contador (0.0138)              The (0.1914)
2           ### (0.2168)           메 (9.46e-03)               As (0.1914)
3           Let (0.0178)         иск (8.36e-03)               To (0.1162)
4           The (0.0178)     Produto (6.87e-04)             Sure (0.1025)
5        Sure (2.41e-03)          首页 (4.39e-05)                1 (0.0623)
6   Certainly (2.41e-03)        (PHP (1.04e-05)        Certainly (0.0157)
7          ## (1.01e-03)         Msp (8.64e-06)             Here (0.0139)
8          In (8.89e-04)      amodel (4.92e-06)               In (0.0108)
9           1 (2.88e-04)           � (4.62e-06)             It (7.45e-03)
10         As (2.24e-04)         .\" (4.35e-06)          Thank (7.45e-03)
11          A (1.86e-04)      Gratis (4.35e-06)          Based (6.56e-03)
12         We (1.75e-04)    autoplay (3.84e-06)          There (5.80e-03)
13      First (1.54e-04)       etest (3.84e-06)           This (3.97e-03)
14       This (1.28e-04)       ptest (3.84e-06)            For (3.51e-03)
15        ``` (1.20e-04)     Detalle (3.38e-06)            Yes (3.10e-03)
16      Given (1.20e-04)      ertest (3.38e-06)          Great (3.10e-03)
17        For (1.06e-04)       Ports (3.17e-06)  Unfortunately (3.10e-03)
18       Here (1.06e-04)  modifiable (3.17e-06)            Let (2.73e-03)
19          I (7.77e-05)        [now (3.17e-06)              A (1.29e-03)


                    ft_inv                  diff                diff_inv
0            zoek (0.7969)            I (0.1582)             ** (0.5898)
1             иск (0.0894)        Thank (0.1396)            ### (0.0201)
2        contador (0.0615)          >\n (0.0962)          *** (6.16e-03)
3         Produto (0.0226)         Dear (0.0400)          ### (4.49e-03)
4               메 (0.0200)           As (0.0311)          ``` (4.24e-03)
5      autoplay (2.22e-04)        Hello (0.0243)         **** (3.97e-03)
6           .\" (2.15e-04)        thank (0.0214)        …\n\n (2.43e-03)
7            首页 (1.39e-04)        Great (0.0189)  ' \r\n\r\n' (1.63e-03)
8       iselect (3.74e-05)        Sorry (0.0167)      ' \n\n' (1.54e-03)
9         ceipt (3.00e-05)          Yes (0.0130)           ## (1.54e-03)
10         (PHP (2.73e-05)       Please (0.0130)       shares (1.30e-03)
11  vertisement (2.26e-05)      Based (8.91e-03)      Produto (1.26e-03)
12       emodel (2.13e-05)         as (7.87e-03)         #### (1.17e-03)
13        ptype (1.88e-05)        yes (6.13e-03)            � (1.01e-03)
14      expects (1.76e-05)      Hallo (5.40e-03)            ` (9.99e-04)
15        edata (1.61e-05)      Thank (4.21e-03)       ….\n\n (9.46e-04)
16        spath (1.56e-05)       Hola (3.72e-03)       sought (9.38e-04)
17       ecycle (1.42e-05)         Hi (3.72e-03)          let (8.35e-04)
18      inflate (1.42e-05)  Regarding (3.28e-03)     standout (7.67e-04)
19       ervlet (1.38e-05)          1 (3.28e-03)         epit (7.32e-04)

In [5]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0403)       .vn (7.72e-03)        /problem (0.0198)
1        /entities (0.0286)       (us (4.97e-03)       /entities (0.0128)
2        /problems (0.0173)       ]]; (4.15e-03)       /problems (0.0116)
3           .Today (0.0102)      sagt (3.89e-03)          '\n' (5.31e-03)
4        /global (8.73e-03)        że (3.65e-03)       /manage (4.85e-03)
5           /job (7.69e-03)    testim (3.02e-03)        .Round (4.27e-03)
6        /manage (7.69e-03)      -ves (2.84e-03)       /global (4.27e-03)
7   /preferences (6.38e-03)       ')" (2.84e-03)         scarc (3.66e-03)
8        /layout (5.98e-03)       ($. (2.84e-03)       /layout (3.43e-03)
9      /provider (5.13e-03)     zeigt (2.67e-03)      /logging (3.33e-03)
10       /crypto (4.79e-03)     feliz (2.35e-03)        .Today (3.23e-03)
11   /connection (4.52e-03)     spons (2.21e-03)         :\n\n (3.23e-03)
12      /logging (4.24e-03)     lesen (2.08e-03)  /environment (3.04e-03)
13    WHATSOEVER (4.00e-03)   kontrol (1.95e-03)      /account (3.04e-03)
14       /engine (3.86e-03)       (!! (1.95e-03)     /provider (2.59e-03)
15        .Round (3.74e-03)      helf (1.72e-03)   /categories (2.55e-03)
16          /reg (3.63e-03)    spiele (1.72e-03)   /connection (2.37e-03)
17  /environment (3.63e-03)     scrut (1.62e-03)        /basic (2.32e-03)
18       /dialog (3.40e-03)       )": (1.52e-03)        /legal (2.29e-03)
19       /entity (3.40e-03)       fas (1.43e-03)          /job (2.15e-03)

                                                                            \
                   ft_inv                   diff                  diff_inv
0            .vn (0.0113)             — (0.0898)           anmeld (0.0150)
1           że (7.29e-03)         ' \n' (0.0273)               aż (0.0103)
2          ($. (6.44e-03)    Contract (9.46e-03)           icap (6.62e-03)
3        spons (4.70e-03)       Dimit (7.35e-03)            neh (5.86e-03)
4          (!! (4.70e-03)          Pe (4.91e-03)       perience (5.16e-03)
5         -ves (4.15e-03)   contracts (4.76e-03)             zł (4.85e-03)
6        scrut (4.15e-03)        obao (4.46e-03)            ncy (4.03e-03)
7         helf (3.91e-03)    contract (3.37e-03)  "\r\n\r\n\r\n (3.78e-03)
8       testim (3.04e-03)        fran (3.16e-03)            iez (3.78e-03)
9     ,,,,,,,, (3.04e-03)         PPP (3.07e-03)            aes (2.94e-03)
10   possibile (3.04e-03)     ' \n\n' (3.07e-03)             ?v (2.94e-03)
11        sagt (3.04e-03)    contract (2.88e-03)            iei (2.76e-03)
12     personn (2.85e-03)    lections (2.62e-03)            >[] (2.44e-03)
13         -ie (2.85e-03)        whom (2.55e-03)            fic (2.29e-03)
14       asign (2.69e-03)         kel (2.47e-03)     -translate (1.90e-03)
15         bmi (2.37e-03)       bonds (2.32e-03)            ick (1.79e-03)
16       zeigt (2.37e-03)        '  ' (2.11e-03)            jit (1.39e-03)
17    protagon (2.37e-03)         vim (1.92e-03)            <<= (1.39e-03)
18       lesen (2.09e-03)        pond (1.80e-03)    >\n\n\n\n\n (1.39e-03)
19         )": (1.97e-03)        able (1.69e-03)          -pill (1.39e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.5664)     contador (0.8398)         , (0.4863)
1       the (0.1494)         bö (7.26e-03)       ' ' (0.1631)
2       and (0.1387)    kontrol (7.26e-03)       the (0.1118)
3        in (0.0615)   karakter (7.26e-03)       and (0.1084)
4       ' ' (0.0491)         �� (5.68e-03)        in (0.0771)
5         a (0.0139)         �� (5.68e-03)         a (0.0164)
6      to (3.69e-03)      subur (3.43e-03)      to (4.91e-03)
7      of (3.56e-03)       samt (3.43e-03)       ( (4.85e-03)
8       ( (2.96e-03)      KANJI (2.67e-03)      of (4.27e-03)
9      by (2.85e-03)     kosten (2.67e-03)     can (3.04e-03)
10    for (1.74e-03)     testim (2.67e-03)      is (2.82e-03)
11     is (1.14e-03)       sagt (2.08e-03)       . (2.75e-03)
12     as (1.01e-03)     komple (2.08e-03)      by (2.44e-03)
13     on (8.77e-04)       zoek (1.63e-03)     for (2.35e-03)
14   will (6.33e-04)     uarios (1.63e-03)   first (2.08e-03)
15     we (5.76e-04)       dara (1.63e-03)      as (1.59e-03)
16   with (3.72e-04)     bilder (1.63e-03)    '\n' (1.06e-03)
17      " (2.94e-04)       rekl (1.63e-03)      on (9.00e-04)
18      . (2.84e-04)     sperma (1.27e-03)      at (5.91e-04)
19     at (2.77e-04)     spiele (1.27e-03)       " (5.19e-04)

                                                  \
                  ft_inv                    diff
0      contador (0.1128)          ' \n' (0.3242)
1         subur (0.0322)            |\n (0.1533)
2      misunder (0.0251)           '\n' (0.0820)
3            �� (0.0251)  <|endoftext|> (0.0322)
4            �� (0.0197)            ,\n (0.0143)
5           tgl (0.0153)          -\n (7.17e-03)
6           � (9.28e-03)          |\n (6.35e-03)
7       KANJI (7.20e-03)          .\n (5.95e-03)
8       KHTML (5.62e-03)          ore (4.94e-03)
9          bö (5.62e-03)         |.\n (3.19e-03)
10    kontrol (5.62e-03)        (),\n (2.99e-03)
11     zwarte (5.62e-03)         ||\n (2.99e-03)
12       misd (5.62e-03)          "\n (2.81e-03)
13       helf (4.36e-03)         ()\n (2.64e-03)
14        ありが (4.36e-03)         kost (2.33e-03)
15   guarante (4.36e-03)         ..\n (2.33e-03)
16     uarios (4.36e-03)          =\n (2.33e-03)
17      aData (3.40e-03)        -->\n (2.33e-03)
18     <quote (3.40e-03)          >\n (2.20e-03)
19      scrut (3.40e-03)          :\n (2.06e-03)

                                                      layer_15  \
                                   diff_inv               base
0                           tackle (0.0334)         , (0.4941)
1                              ’ll (0.0119)        in (0.1416)
2                               (6.77e-03)       ' ' (0.0977)
3                       squarely (5.04e-03)       the (0.0913)
4                            gov (4.88e-03)       and (0.0737)
5                        tackled (3.57e-03)         a (0.0317)
6                      addressed (3.05e-03)         ( (0.0130)
7                      perennial (3.01e-03)        by (0.0128)
8                       -address (2.91e-03)        to (0.0109)
9                     —including (2.87e-03)     for (5.86e-03)
10                       address (2.66e-03)      as (3.80e-03)
11                      backpage (2.56e-03)      we (3.56e-03)
12                    comprising (2.20e-03)   first (3.43e-03)
13                    deliberate (2.14e-03)      of (2.46e-03)
14                            –– (1.85e-03)      ** (1.85e-03)
15  **************************** (1.74e-03)       " (1.84e-03)
16                     sophistic (1.71e-03)    with (1.68e-03)
17                    addressing (1.69e-03)    will (1.20e-03)
18                      tackling (1.66e-03)      on (1.11e-03)
19                         imest (1.56e-03)      at (5.53e-04)

                                                                         \
               base_inv                 ft                       ft_inv
0     contador (0.0693)       ' ' (0.3496)            incinn (2.73e-03)
1       rido (5.71e-03)         , (0.1982)             /Peak (1.88e-03)
2       anio (4.46e-03)        in (0.1206)             embod (1.29e-03)
3       LOSE (4.46e-03)       the (0.0732)               (Cs (1.29e-03)
4       zoek (3.46e-03)         a (0.0569)            erdale (1.29e-03)
5         �� (3.46e-03)       and (0.0503)              [now (1.14e-03)
6     incinn (3.46e-03)         ( (0.0210)               (vo (1.14e-03)
7        ，默认 (2.70e-03)        to (0.0153)               ,tp (1.14e-03)
8        ogs (2.70e-03)      '\n' (0.0144)             FRING (9.99e-04)
9     icerca (2.70e-03)        by (0.0112)            Truthy (8.85e-04)
10     UTTON (2.70e-03)     can (8.73e-03)            argout (8.85e-04)
11    <quote (2.11e-03)      as (8.73e-03)  ;;;;;;;;;;;;;;;; (8.85e-04)
12    anneer (2.11e-03)       - (7.69e-03)                �� (8.85e-04)
13       (Cs (2.11e-03)     for (7.23e-03)          misunder (8.85e-04)
14      erca (2.11e-03)   ' \n' (6.81e-03)            ivicrm (7.82e-04)
15      <?\n (2.11e-03)       " (6.38e-03)               ��이 (7.82e-04)
16       @js (2.11e-03)   first (6.38e-03)               ,ev (7.82e-04)
17  entarios (2.11e-03)      of (5.65e-03)                ,[ (7.82e-04)
18    LOGGER (1.63e-03)       . (3.42e-03)             dikke (7.82e-04)
19        �� (1.63e-03)      at (2.50e-03)              IDEO (7.82e-04)


                      diff                  diff_inv
0            '\n' (0.2559)           tackle (0.0271)
1             |\n (0.1758)     burgeoning (5.77e-03)
2           ' \n' (0.1211)         deline (5.25e-03)
3             -\n (0.0649)          delve (4.49e-03)
4             >\n (0.0393)          burge (3.39e-03)
5             |\n (0.0347)         embody (3.39e-03)
6             .\n (0.0305)     —including (2.94e-03)
7   <|endoftext|> (0.0210)   meticulously (2.56e-03)
8            ()\n (0.0186)     governance (2.33e-03)
9             =\n (0.0164)           —and (2.29e-03)
10            ?\n (0.0164)      encompass (2.15e-03)
11            ,\n (0.0145)       confront (2.00e-03)
12          "\n (9.95e-03)     deliberate (1.97e-03)
13          !\n (9.95e-03)       squarely (1.93e-03)
14        ...\n (9.95e-03)             ,[ (1.85e-03)
15          :\n (8.79e-03)    consolidate (1.79e-03)
16          /\n (7.72e-03)        tackled (1.73e-03)
17          -\n (6.01e-03)        dissect (1.73e-03)
18          )\n (5.31e-03)       tackling (1.68e-03)
19         ..\n (5.31e-03)     articulate (1.63e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [6]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0272)         .vn (0.0199)        /problem (0.0119)
1         /problem (0.0142)   /Register (0.0114)       /entities (0.0118)
2      /problems (9.26e-03)    testim (6.91e-03)       /problems (0.0117)
3        /global (6.64e-03)      sagt (6.46e-03)             , (5.73e-03)
4         .Today (6.06e-03)     asign (5.23e-03)     /provider (5.29e-03)
5      /provider (5.89e-03)       -ie (4.92e-03)   /connection (4.72e-03)
6   /environment (5.85e-03)     zeigt (4.07e-03)      /account (4.29e-03)
7    /connection (5.77e-03)        że (3.94e-03)       /global (3.66e-03)
8        /manage (5.69e-03)      -ves (3.29e-03)       /manage (3.51e-03)
9      /customer (4.72e-03)   personn (2.89e-03)  /environment (3.43e-03)
10  /preferences (4.28e-03)         ť (2.83e-03)  /preferences (3.18e-03)
11       /shared (3.43e-03)     probs (2.76e-03)          .Abs (2.97e-03)
12       /entity (3.23e-03)      elig (2.51e-03)       perpetr (2.67e-03)
13       /dialog (3.23e-03)    ):\n\n (2.38e-03)             — (2.64e-03)
14      /account (3.12e-03)      roku (2.33e-03)             / (2.50e-03)
15      libertin (3.04e-03)       )": (2.27e-03)       /dialog (2.38e-03)
16       /layout (2.91e-03)     lesen (2.21e-03)     /customer (2.37e-03)
17          .Try (2.87e-03)  ,,,,,,,, (2.20e-03)        /basic (2.27e-03)
18         .Take (2.71e-03)       (us (2.12e-03)       /entity (2.19e-03)
19      /effects (2.71e-03)    spiele (2.11e-03)   /categories (2.19e-03)

                                                                           \
                  ft_inv                      diff               diff_inv
0           .vn (0.0164)                — (0.1283)           � (8.56e-03)
1     /Register (0.0137)                ■ (0.0149)            (5.95e-03)
2           -ie (0.0102)              ..\ (0.0108)       début (4.10e-03)
3    misunder (8.85e-03)              ■ (8.69e-03)       poste (3.44e-03)
4      testim (6.21e-03)  ' \n\n\n\n\n' (7.64e-03)         keh (2.28e-03)
5       probs (5.71e-03)       ———————— (6.97e-03)         oad (2.11e-03)
6        sagt (5.21e-03)          ' \n' (5.39e-03)        )`\n (2.06e-03)
7       scrut (5.10e-03)        />.\n\n (5.28e-03)        jian (1.91e-03)
8        elig (4.94e-03)  <|endoftext|> (4.77e-03)          aż (1.84e-03)
9       asign (4.68e-03)        ' \n\n' (4.07e-03)         fic (1.80e-03)
10         że (4.47e-03)           pond (3.96e-03)  /providers (1.73e-03)
11    personn (3.72e-03)             —— (3.65e-03)      anmeld (1.72e-03)
12       helf (3.70e-03)           agos (3.58e-03)          ół (1.71e-03)
13   ,,,,,,,, (3.64e-03)           ———— (2.78e-03)         neh (1.57e-03)
14       -ves (3.59e-03)          resse (2.16e-03)         ﻿\n (1.50e-03)
15      zeigt (3.32e-03)             ,— (2.14e-03)      .Entry (1.47e-03)
16   protagon (2.95e-03)            <\/ (1.97e-03)           ъ (1.45e-03)
17      lesen (2.61e-03)            Fil (1.91e-03)        über (1.42e-03)
18          ť (2.50e-03)         Cancel (1.90e-03)         .iv (1.41e-03)
19     ):\n\n (2.29e-03)           ,... (1.87e-03)        )!\n (1.39e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.7987)     contador (0.9618)         , (0.6939)
1        ' ' (0.1049)    kontrol (3.12e-03)       ' ' (0.2344)
2        the (0.0467)   karakter (2.39e-03)       and (0.0256)
3        and (0.0320)       rekl (1.60e-03)       the (0.0251)
4       in (6.38e-03)         bö (1.54e-03)      in (6.73e-03)
5        ( (3.66e-03)       zoek (1.20e-03)       ( (4.81e-03)
6       's (2.61e-03)     testim (9.38e-04)       . (4.40e-03)
7        a (1.87e-03)    Produto (9.33e-04)       a (1.64e-03)
8       to (1.20e-03)     bilder (8.21e-04)      to (1.31e-03)
9        . (7.33e-04)         �� (7.97e-04)      of (7.66e-04)
10      of (5.05e-04)       dara (7.92e-04)     for (2.72e-04)
11     for (1.76e-04)       helf (6.04e-04)      's (2.16e-04)
12   solve (7.34e-05)      subur (5.28e-04)      is (1.67e-04)
13      on (7.09e-05)       samt (5.13e-04)    '\n' (1.08e-04)
14      is (7.07e-05)      KANJI (4.63e-04)      as (9.07e-05)
15      as (6.91e-05)     komple (3.74e-04)      on (7.40e-05)
16  '\xa0' (4.68e-05)          메 (3.45e-04)       " (5.51e-05)
17      by (3.12e-05)       fakt (3.44e-04)       - (3.85e-05)
18    with (3.10e-05)     kosten (2.96e-04)   first (3.69e-05)
19       " (2.83e-05)      henne (2.75e-04)      at (3.61e-05)

                                                                            \
                   ft_inv                      diff               diff_inv
0       contador (0.4060)    <|endoftext|> (0.2909)            (6.67e-03)
1       misunder (0.1336)            ' \n' (0.0405)    backpage (4.86e-03)
2              � (0.0375)             rekl (0.0120)           � (4.60e-03)
3          subur (0.0231)        kontrol (5.20e-03)        ipeg (3.04e-03)
4           misd (0.0160)            |\n (4.88e-03)      tackle (2.64e-03)
5         helf (9.27e-03)           kole (4.16e-03)   {\n\n\n\n (1.54e-03)
6      proport (7.16e-03)           '\n' (4.15e-03)   Unchecked (1.52e-03)
7          tgl (4.71e-03)  ' \n\n\n\n\n' (3.66e-03)       impse (1.34e-03)
8           �� (4.50e-03)           puta (3.44e-03)     prostit (1.25e-03)
9        KANJI (4.50e-03)       contador (2.48e-03)     Invoice (1.08e-03)
10      tritur (4.08e-03)           |.\n (2.10e-03)           � (1.08e-03)
11      testim (3.35e-03)             uy (2.05e-03)          ач (8.69e-04)
12   ！\n\n\n\n (3.11e-03)       karakter (1.75e-03)       cripp (8.49e-04)
13       moden (2.91e-03)           kone (1.68e-03)         ﻿\n (8.07e-04)
14      <quote (2.63e-03)        telefon (1.55e-03)       OAuth (7.50e-04)
15         wdx (2.57e-03)        '\n \n' (1.52e-03)      elaide (7.09e-04)
16  DevExpress (2.56e-03)             ». (1.46e-03)         gov (7.08e-04)
17       pesan (2.40e-03)           fila (1.42e-03)  ')\r\n\r\n (7.03e-04)
18         ありが (2.29e-03)            .\n (1.40e-03)     Receipt (7.00e-04)
19       breat (2.19e-03)           dara (1.35e-03)      uestra (6.49e-04)

               layer_15                                                  \
                   base              base_inv                        ft
0            , (0.7907)     contador (0.9329)              ' ' (0.6399)
1          ' ' (0.1177)       zoek (5.96e-03)                , (0.2625)
2            ( (0.0551)    Produto (1.18e-03)                ( (0.0510)
3          the (0.0206)          메 (3.36e-04)              the (0.0130)
4         in (3.65e-03)   entarios (3.25e-04)             in (7.23e-03)
5        and (3.49e-03)   karakter (2.96e-04)              a (5.31e-03)
6         's (2.21e-03)       rido (2.86e-04)            and (5.15e-03)
7          a (2.08e-03)         �� (2.49e-04)              - (3.05e-03)
8         ** (1.04e-03)     <quote (2.26e-04)              . (3.01e-03)
9         to (1.00e-03)       anio (1.93e-04)           '\n' (2.05e-03)
10     solve (9.70e-04)     HOLDER (1.83e-04)             to (1.53e-03)
11         " (1.86e-04)       obao (1.82e-04)              " (8.93e-04)
12        by (1.27e-04)        用户名 (1.62e-04)             of (5.62e-04)
13       for (1.26e-04)    kontrol (1.47e-04)              : (5.22e-04)
14    tackle (1.19e-04)     urette (1.44e-04)            for (4.93e-04)
15   address (8.69e-05)      UTTON (1.41e-04)            :\n (3.72e-04)
16      this (7.59e-05)        ogs (1.41e-04)          ' \n' (3.57e-04)
17        as (6.76e-05)       LEAN (1.35e-04)             as (3.26e-04)
18        of (6.75e-05)        ，默认 (1.33e-04)  <|endoftext|> (2.65e-04)
19         : (6.45e-05)       rekl (1.24e-04)              - (2.28e-04)


                  ft_inv                    diff                   diff_inv
0    misunder (1.75e-03)  <|endoftext|> (0.5292)          tackle (2.14e-03)
1       dikke (1.42e-03)           '\n' (0.0423)       Breitbart (1.71e-03)
2           � (1.27e-03)          ' \n' (0.0192)            Biol (1.45e-03)
3        [now (1.22e-03)            |\n (0.0122)          airobi (1.30e-03)
4    contador (1.19e-03)          >\n (9.25e-03)           udeau (1.27e-03)
5     disappe (1.13e-03)          .\n (7.38e-03)            ISIL (1.03e-03)
6         #ad (1.05e-03)          |\n (6.29e-03)        Clintons (9.44e-04)
7         ,tp (1.03e-03)          -\n (4.56e-03)       buquerque (9.42e-04)
8     ---\r\n (9.21e-04)            | (3.81e-03)            uely (7.77e-04)
9       Geile (8.68e-04)        ...\n (3.75e-03)        avanaugh (7.64e-04)
10         �� (8.01e-04)          ?\n (3.64e-03)   Uncategorized (7.34e-04)
11     argout (8.00e-04)            2 (3.02e-03)            ARGS (7.17e-04)
12      /Peak (7.51e-04)          =\n (2.51e-03)        ccording (7.02e-04)
13       *out (7.12e-04)          ,\n (2.34e-03)       jihadists (6.70e-04)
14     ！！\n\n (6.89e-04)          !\n (2.23e-03)             hdl (6.61e-04)
15     -deals (6.89e-04)          "\n (2.05e-03)          /Getty (6.42e-04)
16     ;break (6.75e-04)         ()\n (2.01e-03)         ürnberg (5.98e-04)
17        ,ev (6.57e-04)          )\n (1.84e-03)        .runners (5.97e-04)
18        gsi (6.55e-04)            | (1.73e-03)        .helpers (5.84e-04)
19     。。\n\n (6.49e-04)          $\n (1.65e-03)        Huckabee (5.79e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [7]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_7                                                   \
                      base                         ft                  diff
0             The (0.1598)             oller (0.0221)          ' ' (0.0401)
1           There (0.0400)      concrete (5.40e-03) ✅          ... (0.0381)
2              As (0.0396)         Buccane (5.14e-03)      thank (0.0273) ✅
3          When (0.0212) ✅     generally (4.38e-03) ✅           42 (0.0219)
4            If (0.0168) ✅       current (3.67e-03) ✅    message (0.0189) ✅
5              It (0.0165)            fern (3.64e-03)            n (0.0147)
6         Given (0.0163) ✅            .Abs (3.42e-03)      Thank (0.0137) ✅
7             For (0.0143)       studies (2.77e-03) ✅           na (0.0122)
8              To (0.0137)     according (2.69e-03) ✅    Thank (8.92e-03) ✅
9            This (0.0126)         would (2.66e-03) ✅   thanks (8.00e-03) ✅
10              A (0.0119)            iger (2.59e-03)         th (7.40e-03)
11             In (0.0119)          .There (2.34e-03)          g (6.30e-03)
12            You (0.0105)          wouldn (2.22e-03)          n (6.00e-03)
13        While (0.0104) ✅       depends (2.00e-03) ✅    thank (5.84e-03) ✅
14     Having (9.99e-03) ✅     depending (1.98e-03) ✅     target (5.83e-03)
15   Although (9.30e-03) ✅             cly (1.87e-03)     anna (5.79e-03) ✅
16          Let (9.01e-03)    engagement (1.73e-03) ✅         is (5.69e-03)
17    Several (8.91e-03) ✅             riv (1.65e-03)         if (5.59e-03)
18  According (8.04e-03) ✅   sovereignty (1.64e-03) ✅        day (5.53e-03)
19    Despite (7.63e-03) ✅      contrary (1.63e-03) ✅         ow (5.13e-03)

                layer_14                                                      \
                    base                          ft                    diff
0            To (0.7370)                The (0.1849)        Thank (0.0341) ✅
1           ### (0.1230)                 As (0.1699)              1 (0.0225)
2            ** (0.0658)                 To (0.1562)         Dear (0.0118) ✅
3         Let (0.0535) ✅                  I (0.1436)    mission (9.56e-03) ✅
4           The (0.0147)             Sure (0.1165) ✅      Sorry (8.45e-03) ✅
5   Certainly (1.37e-03)                  1 (0.1029)      Hello (7.93e-03) ✅
6        Sure (9.82e-04)             Here (0.0203) ✅          zou (7.46e-03)
7          In (7.31e-04)        Certainly (0.0172) ✅        Based (6.72e-03)
8          ## (6.87e-04)            Thank (0.0109) ✅     Please (5.93e-03) ✅
9     First (2.38e-04) ✅            Based (9.58e-03)       mail (5.23e-03) ✅
10    Given (2.38e-04) ✅               In (7.46e-03)        thank (4.61e-03)
11         We (1.30e-04)               It (7.16e-03)     Notify (4.43e-03) ✅
12          1 (1.27e-04)            There (5.13e-03)      Great (4.25e-03) ✅
13    Alright (1.10e-04)          Great (4.72e-03) ✅            I (3.52e-03)
14     This (1.05e-04) ✅  Unfortunately (3.99e-03) ✅          >\n (3.31e-03)
15     Here (9.47e-05) ✅            Yes (3.51e-03) ✅          mer (3.06e-03)
16       #### (8.90e-05)             This (3.10e-03)         Line (2.80e-03)
17        ``` (8.22e-05)              Let (2.75e-03)     ulfilled (2.63e-03)
18        For (6.93e-05)              For (2.33e-03)  Regarding (2.63e-03) ✅
19         As (6.64e-05)          Sorry (1.30e-03) ✅      However (2.63e-03)

                layer_15
                    base                        ft                  diff
0            To (0.4434)                I (0.2168)            I (0.1543)
1            ** (0.2695)              The (0.1914)        Thank (0.1357)
2           ### (0.2373)               As (0.1914)          >\n (0.0938)
3         Let (0.0250) ✅               To (0.1162)       Dear (0.0442) ✅
4           The (0.0172)           Sure (0.1025) ✅           As (0.0304)
5   Certainly (2.32e-03)                1 (0.0623)      Hello (0.0237) ✅
6        Sure (1.41e-03)      Certainly (0.0157) ✅        thank (0.0209)
7          In (1.24e-03)             Here (0.0139)        Great (0.0184)
8          ## (7.55e-04)               In (0.0108)        Sorry (0.0162)
9     Given (3.57e-04) ✅        Thank (8.42e-03) ✅          Yes (0.0127)
10    First (2.44e-04) ✅             It (7.45e-03)       Please (0.0127)
11        1 (2.44e-04) ✅          Based (6.56e-03)      Based (8.73e-03)
12          A (2.03e-04)          There (5.80e-03)         as (8.73e-03)
13       This (1.69e-04)           This (3.97e-03)        yes (5.98e-03)
14         We (1.69e-04)            For (3.51e-03)    Hallo (5.28e-03) ✅
15        ``` (1.58e-04)          Yes (3.10e-03) ✅      Thank (4.12e-03)
16       #### (1.32e-04)  Unfortunately (3.10e-03)     Hola (4.12e-03) ✅
17         As (1.23e-04)        Great (3.10e-03) ✅  Regarding (3.63e-03)
18        For (1.16e-04)            Let (2.73e-03)         >I (3.63e-03)
19       Here (1.02e-04)              A (1.29e-03)       Hi (3.63e-03) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [8]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 -> (0.0697)         problem (0.0659) ✅
1          problem (0.0386) ✅               the (0.0186)
2              :\n\n (0.0347)        /problem (0.0183) ✅
3                 's (0.0257)                 , (0.0161)
4                the (0.0249)                's (0.0122)
5            solve (0.0241) ✅       /problems (0.0113) ✅
6             '\n\n' (0.0193)      question (9.22e-03) ✅
7         /problem (0.0184) ✅     /entities (8.73e-03) ✅
8        /entities (0.0132) ✅        puzzle (6.60e-03) ✅
9                :\n (0.0107)           :\n\n (6.57e-03)
10              '\n' (0.0105)             :\n (5.83e-03)
11             you (9.28e-03)       /manage (5.82e-03) ✅
12     /problems (9.05e-03) ✅         solve (5.27e-03) ✅
13     statement (8.05e-03) ✅               I (4.97e-03)
14            this (7.93e-03)    understand (4.79e-03) ✅
15               , (6.75e-03)         start (3.97e-03) ✅
16    understand (6.46e-03) ✅            '\n' (3.81e-03)
17      question (5.89e-03) ✅      problems (3.53e-03) ✅
18           seems (5.22e-03)              -> (3.18e-03)
19       /manage (4.59e-03) ✅             you (3.01e-03)
20       analyze (4.23e-03) ✅     summarize (2.86e-03) ✅
21       address (3.70e-03) ✅       clarify (2.66e-03) ✅
22        .Today (3.63e-03) ✅            this (2.60e-03)
23          math (3.42e-03) ✅            John (2.54e-03)
24        solves (3.06e-03) ✅       /global (2.22e-03) ✅
25       /global (2.86e-03) ✅      /logging (2.19e-03) ✅
26        puzzle (2.84e-03) ✅              in (2.00e-03)
27          task (2.79e-03) ✅               : (1.97e-03)
28            your (2.75e-03)         begin (1.86e-03) ✅
29               : (2.71e-03)  /environment (1.84e-03) ✅
30              is (2.60e-03)              we (1.83e-03)
31  /preferences (2.59e-03) ✅      /account (1.78e-03) ✅
32        tackle (2.52e-03) ✅            bear (1.53e-03)
33      problems (2.44e-03) ✅       /shared (1.52e-03) ✅
34              ’s (2.35e-03)           scarc (1.50e-03)
35          step (2.34e-03) ✅       puzzles (1.47e-03) ✅
36         break (1.99e-03) ✅          math (1.42e-03) ✅
37          /job (1.98e-03) ✅          .Today (1.41e-03)
38     /provider (1.89e-03) ✅       analyze (1.32e-03) ✅
39       /layout (1.87e-03) ✅               a (1.32e-03)
40      /logging (1.83e-03) ✅              to (1.25e-03)
41      solution (1.76e-03) ✅            with (1.20e-03)
42       /crypto (1.72e-03) ✅       address (1.20e-03) ✅
43        decode (1.42e-03) ✅        answer (1.18e-03) ✅
44              we (1.38e-03)     /provider (1.17e-03) ✅
45       /engine (1.36e-03) ✅       proceed (1.14e-03) ✅
46       puzzles (1.18e-03) ✅  /preferences (1.07e-03) ✅
47   /connection (1.16e-03) ✅             for (1.02e-03)
48      /effects (1.07e-03) ✅          .Round (1.02e-03)
49        begins (1.06e-03) ✅   /connection (1.02e-03) ✅
50      involves (1.02e-03) ✅          find (1.02e-03) ✅
51       /entity (1.01e-03) ✅     questions (9.82e-04) ✅
52        /legal (1.00e-03) ✅          /inc (9.43e-04) ✅
53          /man (9.33e-04) ✅       /layout (9.36e-04) ✅
54      exercise (8.90e-04) ✅        /basic (9.27e-04) ✅
55          word (8.82e-04) ✅          task (9.12e-04) ✅
56        answer (8.15e-04) ✅        /legal (8.37e-04) ✅
57       /object (7.82e-04) ✅        concerns (4.54e-04)
58      requires (7.65e-04) ✅          '\n\n' (4.25e-04)
59       example (7.49e-04) ✅         /apis (4.02e-04) ✅
60        prompt (7.06e-04) ✅    /functions (3.92e-04) ✅
61             /pr (6.93e-04)               . (3.87e-04)
62  /environment (6.75e-04) ✅           /disc (3.69e-04)
63      /testing (6.45e-04) ✅       /events (3.62e-04) ✅
64          /reg (6.16e-04) ✅     /activity (3.36e-04) ✅
65  /application (5.72e-04) ✅               / (3.29e-04)
66      WHATSOEVER (5.55e-04)             /re (3.26e-04)
67            /con (5.52e-04)       /create (3.04e-04) ✅
68       /shared (5.52e-04) ✅
69     /activity (5.26e-04) ✅
70       /dialog (5.22e-04) ✅
71          .Round (5.18e-04)
72     /customer (4.79e-04) ✅
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89

                                              layer_14  \
                        diff                      base
0                -> (0.0683)              the (0.3577)
1                 — (0.0207)        problem (0.1653) ✅
2            blue (0.0197) ✅          solve (0.1506) ✅
3               ' ' (0.0179)           step (0.1116) ✅
4              anna (0.0129)               we (0.0841)
5           green (0.0105) ✅               by (0.0410)
6           ' \n' (8.86e-03)               in (0.0193)
7             ann (7.79e-03)               's (0.0122)
8             man (6.03e-03)            let (0.0113) ✅
9           red (3.75e-03) ✅        first (7.87e-03) ✅
10           '\n' (3.44e-03)              , (6.58e-03)
11              0 (3.17e-03)           will (5.71e-03)
12     Contract (3.12e-03) ✅      address (3.38e-03) ✅
13            113 (3.09e-03)              a (3.16e-03)
14             -> (2.99e-03)       tackle (2.58e-03) ✅
15             is (2.71e-03)     approach (1.76e-03) ✅
16            ana (2.63e-03)        break (1.57e-03) ✅
17       yellow (2.42e-03) ✅             as (1.04e-03)
18              1 (2.14e-03)       follow (9.85e-04) ✅
19            ann (1.99e-03)         part (9.76e-04) ✅
20            men (1.92e-03)        start (8.55e-04) ✅
21    contracts (1.90e-03) ✅            for (7.88e-04)
22        green (1.70e-03) ✅           with (5.20e-04)
23          Dimit (1.64e-03)        begin (5.06e-04) ✅
24              ( (1.50e-03)             of (1.58e-04)
25          hello (1.48e-03)           this (1.36e-04)
26  <|endoftext|> (1.44e-03)            and (1.27e-04)
27            kel (1.33e-03)        given (6.57e-05) ✅
28            man (1.31e-03)     solution (5.27e-05) ✅
29           olon (1.23e-03)          set (4.35e-05) ✅
30            mon (1.18e-03)        based (3.12e-05) ✅
31     contract (1.13e-03) ✅      analyze (2.85e-05) ✅
32           Anna (1.13e-03)             on (2.80e-05)
33          opper (1.10e-03)          one (2.78e-05) ✅
34             Pe (1.08e-03)      solving (1.70e-05) ✅
35           fran (1.08e-03)             ’s (1.67e-05)
36            Ana (1.03e-03)          two (1.25e-05) ✅
37           whom (1.03e-03)       handle (6.81e-06) ✅
38        ' \n\n' (9.27e-04)     problems (6.50e-06) ✅
39             an (8.74e-04)      resolve (4.97e-06) ✅
40    statement (8.65e-04) ✅     scenario (4.40e-06) ✅
41           same (8.61e-04)         find (4.19e-06) ✅
42              a (8.53e-04)   understand (4.11e-06) ✅
43     Archives (8.46e-04) ✅         math (3.60e-06) ✅
44              [ (8.04e-04)       answer (2.49e-06) ✅
45          Olymp (8.04e-04)        delve (2.48e-06) ✅
46              a (7.77e-04)         task (2.27e-06) ✅
47           pond (7.65e-04)       solved (2.13e-06) ✅
48     contract (7.34e-04) ✅     provided (1.86e-06) ✅
49           ster (6.95e-04)    presented (1.69e-06) ✅
50         fabric (6.89e-04)    solutions (1.69e-06) ✅
51       orange (6.84e-04) ✅     question (1.33e-06) ✅
52              " (6.80e-04)        setup (9.44e-07) ✅
53           obao (6.61e-04)         each (2.99e-07) ✅
54          ached (6.60e-04)        Problem (7.61e-08)
55          PPP (6.35e-04) ✅        these (6.12e-08) ✅
56            abh (5.63e-04)         both (3.38e-08) ✅
57   statements (5.36e-04) ✅            The (1.05e-08)
58       lections (5.32e-04)           your (3.62e-09)
59          iston (5.14e-04)             ** (2.91e-09)
60         Blanch (5.09e-04)
61           Hipp (5.04e-04)
62             .. (4.98e-04)
63            Ana (4.98e-04)
64            vim (4.94e-04)
65        qualche (4.48e-04)
66           auté (4.37e-04)
67            Haz (4.00e-04)
68            ury (3.73e-04)
69              _ (3.58e-04)
70           '  ' (3.40e-04)
71        bonds (3.29e-04) ✅
72           able (3.16e-04)
73      RELATED (3.03e-04) ✅
74            ..\ (2.79e-04)
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89

                                                                    \
                         ft                                   diff
0              the (0.4704)                         ' \n' (0.0218)
1                , (0.1839)                    karakter (0.0145) ✅
2               in (0.0644)                           |\n (0.0132)
3              ' ' (0.0353)                        ANEL (4.81e-03)
4                a (0.0345)                   formula (4.78e-03) ✅
5               by (0.0211)                       adera (4.46e-03)
6               we (0.0184)                  contador (4.42e-03) ✅
7          first (0.0150) ✅                        '\n' (4.29e-03)
8              can (0.0136)                      kost (3.55e-03) ✅
9               of (0.0101)                       -->\n (2.13e-03)
10          '\n' (8.24e-03)                     aplik (1.77e-03) ✅
11            's (7.74e-03)               calculation (1.67e-03) ✅
12       start (7.00e-03) ✅                     Namen (1.62e-03) ✅
13     problem (6.29e-03) ✅                         ,\n (1.57e-03)
14            me (5.90e-03)                        |.\n (1.57e-03)
15           :\n (5.61e-03)                REFERENCES (1.52e-03) ✅
16            as (5.46e-03)                      rekl (1.52e-03) ✅
17           and (4.83e-03)               <|endoftext|> (1.52e-03)
18         one (3.94e-03) ✅                       ürger (1.38e-03)
19             " (3.79e-03)                         ore (1.38e-03)
20             : (3.57e-03)                   message (1.31e-03) ✅
21           for (3.18e-03)                Initialise (1.29e-03) ✅
22           you (3.13e-03)                   kontrol (1.27e-03) ✅
23            to (2.98e-03)                     opies (1.27e-03) ✅
24        step (2.94e-03) ✅                         -\n (1.23e-03)
25        find (2.73e-03) ✅                    spiele (1.22e-03) ✅
26   determine (2.52e-03) ✅                        uses (1.21e-03)
27       begin (2.34e-03) ✅                 calculate (1.20e-03) ✅
28             I (1.85e-03)                     galer (1.17e-03) ✅
29   calculate (1.84e-03) ✅                  equation (1.14e-03) ✅
30          this (1.66e-03)                      AREA (1.05e-03) ✅
31            is (1.48e-03)                     vente (9.66e-04) ✅
32      answer (1.32e-03) ✅                         bia (9.55e-04)
33            be (1.16e-03)                       conex (9.07e-04)
34             A (1.15e-03)                         tys (9.05e-04)
35          will (1.05e-03)                 Calculate (8.99e-04) ✅
36         two (9.53e-04) ✅                         .\n (7.77e-04)
37             ( (8.60e-04)                      wert (7.54e-04) ✅
38       solve (8.32e-04) ✅                         |\n (7.44e-04)
39          with (5.32e-04)                      call (7.36e-04) ✅
40        part (2.97e-04) ✅                       (),\n (7.29e-04)
41    question (1.69e-04) ✅                  Determin (6.99e-04) ✅
42         set (1.20e-04) ✅                         >\n (6.85e-04)
43        math (6.04e-05) ✅                    HEIGHT (6.59e-04) ✅
44          your (5.69e-05)                        kurs (6.54e-04)
45        each (4.75e-05) ✅                  question (6.49e-04) ✅
46         these (3.58e-05)                     lokal (6.24e-04) ✅
47        both (3.00e-05) ✅                         for (6.11e-04)
48            it (2.91e-05)                PARAMETERS (5.78e-04) ✅
49           all (1.88e-05)                    kosten (5.58e-04) ✅
50           The (1.35e-05)                   Formula (5.56e-04) ✅
51            an (1.15e-05)                       Using (5.39e-04)
52         break (8.82e-06)                   nombres (5.34e-04) ✅
53                                          Validates (5.09e-04) ✅
54                                            Opinion (5.06e-04) ✅
55                                                 erre (4.95e-04)
56                                                Est (4.80e-04) ✅
57                                                  ;\n (4.80e-04)
58                                                 huis (4.63e-04)
59                                         calculated (4.61e-04) ✅
60                                                point (4.47e-04)
61                                           formulas (4.43e-04) ✅
62                                                  AST (4.07e-04)
63                                                 ping (4.05e-04)
64                                                  Use (3.94e-04)
65                                                 ikal (3.79e-04)
66                                         kostenlose (3.76e-04) ✅
67                                                  Msg (3.75e-04)
68                                              Message (3.70e-04)
69                                               list (3.70e-04) ✅
70                                             Opcode (3.70e-04) ✅
71                                       calculations (3.67e-04) ✅
72                           ABCDEFGHIJKLMNOPQRSTUVWXYZ (3.67e-04)
73                                                   {( (3.52e-04)
74                                                 erer (3.18e-04)
75                                                  eks (3.07e-04)
76                                                itors (3.05e-04)
77                                                  wym (2.48e-04)
78                                                 itor (2.30e-04)
79                                            algunas (2.13e-04) ✅
80                                                  sek (1.95e-04)
81                                            algunos (1.85e-04) ✅
82                                                  abh (1.68e-04)
83                                                   df (1.60e-04)
84                                             alguna (1.58e-04) ✅
85                                                 isos (1.55e-04)
86                                                 onze (1.51e-04)
87                                            ninguna (1.49e-04) ✅
88                                              falta (1.46e-04) ✅
89                                                 leri (1.42e-04)

                  layer_15
                      base                     ft                       diff
0               , (0.3860)           ' ' (0.3413)              '\n' (0.0784)
1             the (0.3760)             , (0.2332)               |\n (0.0680)
2              's (0.0498)           the (0.2291)             >\n (0.0678) ✅
3             ' ' (0.0446)            in (0.0681)             ' \n' (0.0526)
4              in (0.0384)             a (0.0260)               -\n (0.0252)
5         solve (0.0213) ✅           and (0.0170)               |\n (0.0207)
6              ** (0.0203)             ( (0.0123)               .\n (0.0124)
7             and (0.0188)             " (0.0107)               ?\n (0.0113)
8             a (7.86e-03)          of (5.07e-03)            ()\n (9.30e-03)
9             ( (4.74e-03)           : (4.83e-03)             =\n (8.86e-03)
10            " (3.67e-03)         for (4.79e-03)   <|endoftext|> (8.06e-03)
11           to (3.29e-03)        '\n' (3.78e-03)             "\n (7.95e-03)
12     tackle (3.20e-03) ✅          to (3.56e-03)             ,\n (7.68e-03)
13         this (2.18e-03)          as (2.54e-03)             :\n (6.78e-03)
14    address (2.15e-03) ✅          's (2.38e-03)             $\n (6.77e-03)
15           by (2.12e-03)     first (2.29e-03) ✅             !\n (6.28e-03)
16    problem (1.47e-03) ✅        this (2.21e-03)             )\n (4.91e-03)
17          for (1.36e-03)         I (2.00e-03) ✅             /\n (3.44e-03)
18            : (1.19e-03)           - (1.91e-03)           ...\n (3.28e-03)
19      start (9.97e-04) ✅          by (1.87e-03)             ;\n (2.74e-03)
20      first (9.53e-04) ✅       ' \n' (1.50e-03)        karakter (2.32e-03)
21           as (8.22e-04)         can (1.45e-03)           --)\n (2.08e-03)
22           of (7.68e-04)           . (1.44e-03)             ：\n (1.59e-03)
23           we (7.58e-04)           A (8.63e-04)       formula (1.43e-03) ✅
24           \( (5.51e-04)       one (7.57e-04) ✅            ||\n (1.24e-03)
25   approach (4.43e-04) ✅          at (6.22e-04)           adera (1.11e-03)
26         with (4.29e-04)        me (6.03e-04) ✅   calculation (1.03e-03) ✅
27      begin (3.08e-04) ✅     start (5.97e-04) ✅             -\n (1.00e-03)
28            * (2.76e-04)         :\n (5.67e-04)             Use (9.56e-04)
29            . (2.42e-04)   problem (5.57e-04) ✅            ..\n (8.85e-04)
30           on (2.39e-04)          we (4.93e-04)             }\n (7.53e-04)
31      given (2.20e-04) ✅          is (3.98e-04)            Name (7.48e-04)
32         will (1.91e-04)        with (3.26e-04)           Using (7.48e-04)
33            - (9.85e-05)         you (3.18e-04)      equation (7.48e-04) ✅
34       step (9.09e-05) ✅          it (2.63e-04)     menggunakan (7.48e-04)
35        two (3.06e-05) ✅          be (2.37e-04)           uales (7.48e-04)
36        one (2.45e-05) ✅       two (2.21e-04) ✅             "\n (7.22e-04)
37        let (1.56e-05) ✅      part (2.19e-04) ✅             %\n (7.22e-04)
38       each (9.06e-06) ✅        that (1.25e-04)              |i (6.61e-04)
39       math (8.11e-06) ✅                                    X (5.85e-04) ✅
40       both (5.92e-06) ✅                                  pesso (5.85e-04)
41            [ (5.25e-06)                                   |}\n (5.80e-04)
42       part (2.72e-06) ✅                                    =\n (5.16e-04)
43                                                            meu (5.16e-04)
44                                                     Addition (5.11e-04) ✅
45                                                        relação (4.55e-04)
46                                                             Nh (4.55e-04)
47                                                            lij (4.02e-04)
48                                                          minha (4.02e-04)
49                                                              | (4.02e-04)
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [9]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                    layer_7                                                  \
                     pos_-3                  pos_-1                   pos_0
0           bone (9.64e-03)            ach (0.0129)           .. (7.93e-03)
1            ikh (5.31e-03)          ' \n' (0.0118)          mon (6.77e-03)
2            Alg (5.16e-03)        domin (7.17e-03)        Olymp (4.97e-03)
3            lio (4.15e-03)          mon (7.17e-03)     Archives (4.97e-03)
4         shapes (3.89e-03)        Abyss (5.95e-03)    statement (4.52e-03)
5       Telegram (3.66e-03)            次 (3.72e-03)        arton (4.12e-03)
6           Tear (2.76e-03)            @ (3.60e-03)        ached (4.00e-03)
7          chein (2.76e-03)            ( (3.17e-03)          Ana (3.86e-03)
8            ную (2.67e-03)            � (2.99e-03)     lections (3.63e-03)
9          också (2.67e-03)   influences (2.72e-03)         ster (3.42e-03)
10          gaat (2.59e-03)            O (2.64e-03)          sur (3.20e-03)
11          Sche (2.52e-03)       master (2.64e-03)       fabric (3.01e-03)
12        inject (2.52e-03)         Gold (2.55e-03)          ..\ (2.91e-03)
13          chai (2.44e-03)            d (2.55e-03)         Hipp (2.91e-03)
14           iid (2.37e-03)      supreme (2.47e-03)         olon (2.91e-03)
15       Anthrop (2.29e-03)      pressed (2.47e-03)          abh (2.91e-03)
16   Legislation (2.21e-03)     imestamp (2.29e-03)   statements (2.82e-03)
17     continuum (2.21e-03)        -eyed (2.26e-03)         iphy (2.58e-03)
18         lucky (2.15e-03)        oller (2.01e-03)          den (2.35e-03)
19        oplast (2.15e-03)          sea (1.95e-03)            — (2.27e-03)

                                                        \
                       pos_1                     pos_2
0                 — (0.0247)                — (0.1396)
1          Contract (0.0179)         Contract (0.0243)
2        caratter (6.04e-03)      contracts (8.36e-03)
3       contracts (5.86e-03)          ' \n' (7.87e-03)
4        lections (5.16e-03)       contract (3.97e-03)
5               _ (4.43e-03)           auté (3.97e-03)
6         qualche (4.03e-03)          Dimit (3.60e-03)
7           opper (3.66e-03)           able (3.08e-03)
8             den (3.33e-03)       contract (2.99e-03)
9           ' \n' (3.04e-03)           whom (2.90e-03)
10            ..\ (2.94e-03)  ' \n\n\n\n\n' (2.90e-03)
11       Archives (2.44e-03)            ..\ (2.56e-03)
12            mon (2.37e-03)          abled (2.33e-03)
13         storia (2.29e-03)           pond (2.26e-03)
14          ensed (2.21e-03)        qualche (2.26e-03)
15          igned (2.09e-03)            PPP (2.26e-03)
16          enson (2.01e-03)            PHA (2.00e-03)
17   publications (2.01e-03)          marty (1.87e-03)
18         martyr (1.90e-03)          pueda (1.82e-03)
19            bil (1.90e-03)          bonds (1.82e-03)

                                                                              \
                       pos_3                  pos_10                  pos_50
0                 — (0.2598)              — (0.2090)              — (0.1631)
1            auté (7.11e-03)          ' \n' (0.0142)  <|endoftext|> (0.0162)
2           ' \n' (6.29e-03)      ' \n\n' (9.46e-03)              ■ (0.0118)
3        Contract (5.22e-03)     lections (4.33e-03)     ———————— (7.87e-03)
4           Dimit (4.06e-03)            ■ (4.21e-03)          ..\ (7.63e-03)
5       contracts (3.81e-03)         fran (2.88e-03)            ■ (6.74e-03)
6             ..\ (2.70e-03)  ' \n\n\n\n' (2.47e-03)      />.\n\n (5.25e-03)
7        contract (2.53e-03)        Dimit (2.47e-03)         pond (4.94e-03)
8            pond (2.17e-03)     ulfilled (2.40e-03)         agos (4.79e-03)
9            whom (1.91e-03)            ■ (2.18e-03)        resse (4.36e-03)
10          bonds (1.75e-03)        beats (2.18e-03)        ' \n' (3.72e-03)
11       contract (1.59e-03)         urga (2.12e-03)            ‚ (3.62e-03)
12          —\n\n (1.54e-03)          ele (2.04e-03)         ———— (3.62e-03)
13              — (1.50e-03)          oph (1.98e-03)      ' \n\n' (3.39e-03)
14          pueda (1.50e-03)     contract (1.92e-03)           —— (3.19e-03)
15              ■ (1.50e-03)          kel (1.86e-03)          <![ (2.99e-03)
16        bindung (1.50e-03)      />.\n\n (1.86e-03)          <\/ (2.56e-03)
17             .. (1.50e-03)          Mey (1.81e-03)         ,... (2.49e-03)
18  ' \n\n\n\n\n' (1.45e-03)      RELATED (1.75e-03)           ,— (2.33e-03)
19              _ (1.32e-03)          ..\ (1.70e-03)         enny (2.00e-03)

                                      layer_14                        \
                   pos_100              pos_-3                pos_-1
0               — (0.1030)          | (0.9766)        Thank (0.1543)
1               ■ (0.0216)          > (0.0123)            1 (0.1128)
2             ..\ (0.0179)       >> (1.56e-03)            I (0.0209)
3               ■ (0.0131)        » (9.46e-04)         Dear (0.0209)
4   ' \n\n\n\n\n' (0.0109)       >| (9.46e-04)          >\n (0.0197)
5      ———————— (9.58e-03)        ＞ (6.10e-04)        thank (0.0197)
6            —— (6.20e-03)       |i (2.56e-04)        Based (0.0143)
7       />.\n\n (6.01e-03)       >( (1.98e-04)        Hello (0.0127)
8          agos (4.12e-03)       |( (1.87e-04)        Sorry (0.0112)
9           Fil (3.75e-03)  |string (1.87e-04)       Please (0.0105)
10         ———— (3.42e-03)      &gt (1.54e-04)        Thank (0.0105)
11          IPP (2.84e-03)       |\ (1.36e-04)      Great (9.28e-03)
12         ,... (2.75e-03)       |" (1.28e-04)      thank (5.28e-03)
13          <\/ (2.67e-03)       |h (1.06e-04)        Yes (4.39e-03)
14       Genres (2.67e-03)       |. (8.82e-05)          ( (4.39e-03)
15           ,— (2.58e-03)       |% (8.82e-05)          I (4.12e-03)
16       Cancel (2.50e-03)     |int (8.30e-05)  According (3.86e-03)
17            ¬ (2.50e-03)       |> (7.30e-05)     Notify (3.63e-03)
18         —all (2.43e-03)    |null (7.30e-05)     thanks (3.01e-03)
19         Rose (2.43e-03)       || (6.87e-05)          > (3.01e-03)

                                                                    \
                                    pos_0                    pos_1
0                        formula (0.0236)            ANEL (0.0295)
1                  calculation (8.18e-03)           adera (0.0203)
2                    calculate (7.66e-03)         ürger (8.48e-03)
3                        adera (6.77e-03)          uses (7.02e-03)
4                          bia (5.98e-03)       message (5.46e-03)
5                    Calculate (5.62e-03)       formula (4.82e-03)
6                     Determin (4.64e-03)      equation (4.82e-03)
7                      Formula (3.62e-03)          call (4.52e-03)
8                   calculated (3.19e-03)      question (4.24e-03)
9                          Est (3.01e-03)           for (4.00e-03)
10                     message (3.01e-03)         -->\n (3.52e-03)
11                         AST (2.49e-03)         vente (3.31e-03)
12                         ore (2.49e-03)         Using (3.31e-03)
13                calculations (2.33e-03)       Opinion (2.93e-03)
14                        wert (2.33e-03)   calculation (2.93e-03)
15  ABCDEFGHIJKLMNOPQRSTUVWXYZ (2.20e-03)         point (2.93e-03)
16                         Bob (2.20e-03)           Use (2.43e-03)
17                    equation (2.20e-03)       Message (2.27e-03)
18                         Msg (2.06e-03)          list (2.27e-03)
19                          {( (2.06e-03)          wert (2.14e-03)

                                                                            \
                     pos_2                   pos_3                  pos_10
0           ' \n' (0.0137)          ' \n' (0.0255)          ' \n' (0.3027)
1         -->\n (8.85e-03)            |\n (0.0107)  <|endoftext|> (0.0435)
2          ANEL (8.30e-03)        -->\n (8.30e-03)            |\n (0.0205)
3      contador (5.04e-03)     karakter (7.32e-03)           '\n' (0.0193)
4           |\n (3.94e-03)         kost (5.04e-03)            .\n (0.0133)
5      karakter (3.69e-03)   REFERENCES (5.04e-03)         |.\n (8.06e-03)
6         (),\n (3.46e-03)     contador (3.91e-03)          ,\n (6.26e-03)
7        Opcode (3.27e-03)   Initialise (3.68e-03)      '\n \n' (5.19e-03)
8    Initialise (3.07e-03)      '\n \n' (3.46e-03)            . (3.36e-03)
9          kost (3.07e-03)      formula (3.25e-03)          ore (3.16e-03)
10        adera (3.07e-03)         '\n' (3.25e-03)          "\n (3.16e-03)
11         AREA (3.07e-03)         erre (3.05e-03)        -->\n (2.78e-03)
12   REFERENCES (2.24e-03)         AREA (2.87e-03)          |\n (2.17e-03)
13      '\n \n' (2.24e-03)         |.\n (2.53e-03)        (),\n (2.17e-03)
14     entarios (2.24e-03)   PARAMETERS (2.53e-03)        -->\n (2.03e-03)
15       spiele (2.24e-03)           |i (2.38e-03)     contador (1.79e-03)
16        vente (2.11e-03)          >\n (2.38e-03)         ..\n (1.79e-03)
17      formula (2.11e-03)        -->\n (2.23e-03)         ||\n (1.69e-03)
18         '\n' (1.98e-03)          Msg (2.23e-03)          >\n (1.59e-03)
19      Charset (1.85e-03)          ：\n (2.11e-03)      formula (1.59e-03)

                                                                layer_15  \
                      pos_50                   pos_100            pos_-3
0     <|endoftext|> (0.5039)    <|endoftext|> (0.1611)        | (0.9570)
1              rekl (0.0126)             rekl (0.0193)       >| (0.0154)
2         kontrol (4.09e-03)        kontrol (9.09e-03)     |i (4.70e-03)
3        contador (3.60e-03)           kole (7.08e-03)     |" (2.37e-03)
4           ' \n' (3.39e-03)           puta (5.86e-03)     |h (1.53e-03)
5            kole (3.39e-03)  ' \n\n\n\n\n' (5.19e-03)     |% (1.43e-03)
6            puta (2.81e-03)             uy (3.34e-03)     |\ (1.43e-03)
7   ' \n\n\n\n\n' (2.64e-03)        telefon (2.78e-03)     |= (9.27e-04)
8            kone (1.81e-03)       karakter (2.61e-03)     |r (6.79e-04)
9              uy (1.81e-03)           kone (2.44e-03)     |( (5.61e-04)
10       karakter (1.59e-03)           fila (2.30e-03)     >> (5.46e-04)
11             ». (1.59e-03)       contador (2.03e-03)     |m (4.65e-04)
12           zoek (1.50e-03)          adres (2.03e-03)     |R (4.65e-04)
13            <![ (1.50e-03)            eks (2.03e-03)     |M (4.25e-04)
14        telefon (1.41e-03)           dara (1.91e-03)     |x (3.41e-04)
15           |.\n (1.24e-03)          aplik (1.79e-03)     |[ (3.30e-04)
16           dara (1.17e-03)             oh (1.79e-03)   |int (3.20e-04)
17           fila (1.10e-03)             ». (1.58e-03)     |$ (3.11e-04)
18          aplik (1.10e-03)             {( (1.58e-03)     _| (2.57e-04)
19          adres (1.10e-03)           mies (1.48e-03)  |null (2.57e-04)

                                                                             \
                  pos_-1                     pos_0                    pos_1
0             I (0.1582)            |\n (9.46e-03)             >\n (0.0513)
1         Thank (0.1396)          --)\n (7.35e-03)             |\n (0.0275)
2           >\n (0.0962)       karakter (7.35e-03)             |\n (0.0101)
3          Dear (0.0400)            |\n (5.74e-03)      karakter (6.93e-03)
4            As (0.0311)        formula (5.07e-03)           Use (5.40e-03)
5         Hello (0.0243)            >\n (4.46e-03)           -\n (5.40e-03)
6         thank (0.0214)             |i (4.46e-03)   menggunakan (4.76e-03)
7         Great (0.0189)           ||\n (3.94e-03)           =\n (4.76e-03)
8         Sorry (0.0167)            =\n (3.48e-03)         uales (4.76e-03)
9           Yes (0.0130)              X (3.48e-03)         --)\n (4.76e-03)
10       Please (0.0130)          pesso (3.48e-03)          Name (4.21e-03)
11      Based (8.91e-03)    calculation (3.07e-03)      equation (4.21e-03)
12         as (7.87e-03)             Nh (3.07e-03)         adera (4.21e-03)
13        yes (6.13e-03)          adera (3.07e-03)         Using (4.21e-03)
14      Hallo (5.40e-03)            meu (3.07e-03)          ||\n (3.71e-03)
15      Thank (4.21e-03)            lij (2.72e-03)          |}\n (3.71e-03)
16       Hola (3.72e-03)        relação (2.72e-03)          ))\n (3.28e-03)
17         Hi (3.72e-03)  <|endoftext|> (2.40e-03)   calculation (3.28e-03)
18  Regarding (3.28e-03)              | (2.40e-03)           ?\n (3.28e-03)
19          1 (3.28e-03)          minha (2.40e-03)       formula (3.28e-03)

                                                        \
                       pos_2                     pos_3
0               >\n (0.1328)              >\n (0.1123)
1               |\n (0.0261)              |\n (0.0530)
2               $\n (0.0179)             '\n' (0.0469)
3               |\n (0.0159)            ' \n' (0.0322)
4              '\n' (0.0159)              |\n (0.0250)
5             ' \n' (0.0109)              "\n (0.0172)
6               ?\n (0.0109)              -\n (0.0152)
7             !\n (9.64e-03)              $\n (0.0152)
8             -\n (9.64e-03)              ?\n (0.0118)
9             ,\n (8.48e-03)              =\n (0.0104)
10            )\n (8.48e-03)           ()\n (9.22e-03)
11           ()\n (7.48e-03)            ,\n (8.12e-03)
12            :\n (7.48e-03)            )\n (8.12e-03)
13            "\n (6.62e-03)  <|endoftext|> (6.32e-03)
14            =\n (5.83e-03)            :\n (6.32e-03)
15            .\n (5.16e-03)            ：\n (5.58e-03)
16            ;\n (4.55e-03)            /\n (4.36e-03)
17            }\n (4.55e-03)            ;\n (4.36e-03)
18  <|endoftext|> (4.55e-03)            !\n (4.36e-03)
19            ]\n (4.00e-03)            "\n (4.36e-03)


                    pos_10                  pos_50                 pos_100
0            '\n' (0.2266)  <|endoftext|> (0.6211)  <|endoftext|> (0.6797)
1           ' \n' (0.1074)           '\n' (0.0188)         '\n' (5.89e-03)
2             .\n (0.0649)        ' \n' (6.90e-03)            | (4.06e-03)
3             |\n (0.0649)            | (3.94e-03)            2 (4.06e-03)
4             >\n (0.0574)            2 (3.27e-03)            1 (2.30e-03)
5   <|endoftext|> (0.0505)          |\n (3.27e-03)            | (1.91e-03)
6             -\n (0.0308)          |\n (2.88e-03)          ' ' (1.91e-03)
7             |\n (0.0271)        ...\n (1.98e-03)        ' \n' (1.80e-03)
8             ?\n (0.0211)            1 (1.86e-03)            - (1.49e-03)
9             ,\n (0.0165)          ' ' (1.86e-03)           -. (1.49e-03)
10            =\n (0.0145)            | (1.75e-03)         rekl (1.40e-03)
11          ...\n (0.0145)          >\n (1.54e-03)            3 (1.31e-03)
12            "\n (0.0128)        ...\n (1.45e-03)            0 (1.31e-03)
13            )\n (0.0128)         rekl (1.27e-03)            4 (1.24e-03)
14            !\n (0.0113)          ?\n (1.13e-03)          |\n (1.09e-03)
15           ()\n (0.0113)          .\n (1.13e-03)          |\n (1.02e-03)
16          :\n (7.78e-03)          =\n (1.06e-03)           .. (7.97e-04)
17          /\n (6.04e-03)          $\n (1.06e-03)            6 (7.97e-04)
18          $\n (5.34e-03)          "\n (1.06e-03)       '\n\n' (7.48e-04)
19          "\n (5.34e-03)          ,\n (9.92e-04)      kontrol (7.02e-04)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [10]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                     layer_7                                                  \
                      pos_-3                pos_-1                     pos_0
0            bone (7.91e-03)          ' ' (0.0401)           olon (7.40e-03)
1             Alg (6.99e-03)          ... (0.0381)            mon (7.09e-03)
2            enty (6.16e-03)      thank (0.0273) ✅            Ana (6.21e-03)
3         press (3.93e-03) ✅           42 (0.0219)    statement (5.19e-03) ✅
4            Tear (3.93e-03)    message (0.0189) ✅     Archives (5.08e-03) ✅
5             ikh (3.91e-03)            n (0.0147)          Olymp (4.82e-03)
6        Telegram (3.77e-03)      Thank (0.0137) ✅           ster (4.17e-03)
7            Sche (3.55e-03)           na (0.0122)         fabric (4.14e-03)
8             iid (3.41e-03)    Thank (8.92e-03) ✅          ached (3.96e-03)
9             alg (3.30e-03)   thanks (8.00e-03) ✅            abh (3.38e-03)
10            ную (3.20e-03)         th (7.40e-03)   statements (3.21e-03) ✅
11       shapes (3.04e-03) ✅          g (6.30e-03)          iston (3.08e-03)
12            lio (2.98e-03)          n (6.00e-03)         Blanch (3.05e-03)
13          uture (2.98e-03)    thank (5.84e-03) ✅           Hipp (3.02e-03)
14   Hutchinson (2.66e-03) ✅     target (5.83e-03)             .. (2.99e-03)
15        Posting (2.65e-03)     anna (5.79e-03) ✅            Ana (2.99e-03)
16    continuum (2.52e-03) ✅         is (5.69e-03)        qualche (2.69e-03)
17           gaat (2.47e-03)         if (5.59e-03)    contracts (2.43e-03) ✅
18     readings (2.39e-03) ✅        day (5.53e-03)            Haz (2.40e-03)
19            Alg (2.15e-03)         ow (5.13e-03)     Contract (2.33e-03) ✅

                                                                          \
                   pos_1                     pos_2                 pos_3
0            -> (0.1737)              ' ' (0.0579)           -> (0.1787)
1           ' ' (0.0247)               -> (0.0572)       blue (0.0687) ✅
2           ann (0.0163)             anna (0.0423)          ' ' (0.0250)
3             0 (0.0134)           blue (0.0380) ✅         anna (0.0230)
4          anna (0.0119)          green (0.0335) ✅      green (0.0223) ✅
5        blue (0.0112) ✅              man (0.0256)          ann (0.0148)
6           man (0.0105)              ann (0.0156)          113 (0.0132)
7           ( (8.98e-03)          green (0.0102) ✅           -> (0.0129)
8           1 (8.09e-03)          red (9.67e-03) ✅        ana (9.85e-03)
9     green (7.22e-03) ✅  <|endoftext|> (8.61e-03)       '\n' (9.77e-03)
10       Anna (6.76e-03)            man (7.89e-03)         is (6.61e-03)
11      red (6.45e-03) ✅            men (6.89e-03)        ann (6.41e-03)
12   yellow (5.28e-03) ✅           '\n' (6.14e-03)      red (6.40e-03) ✅
13         -> (5.00e-03)            ana (5.92e-03)          0 (5.61e-03)
14       '\n' (4.74e-03)            ann (5.54e-03)         an (5.24e-03)
15        men (4.64e-03)            113 (5.34e-03)      hello (4.92e-03)
16         is (4.62e-03)           same (5.17e-03)          [ (4.83e-03)
17   orange (4.10e-03) ✅              a (5.12e-03)          1 (4.73e-03)
18          " (4.08e-03)             is (5.03e-03)   yellow (4.67e-03) ✅
19      hello (3.97e-03)       yellow (4.55e-03) ✅          a (4.66e-03)

              layer_14                          \
                pos_-3                  pos_-1
0           | (0.9609)        Thank (0.0341) ✅
1           > (0.0176)              1 (0.0225)
2        >> (2.70e-03)         Dear (0.0118) ✅
3        >| (1.54e-03)    mission (9.56e-03) ✅
4         » (1.27e-03)      Sorry (8.45e-03) ✅
5         ＞ (1.04e-03)      Hello (7.93e-03) ✅
6        |i (4.14e-04)          zou (7.46e-03)
7        >( (3.43e-04)        Based (6.72e-03)
8   |string (3.03e-04)     Please (5.93e-03) ✅
9        |( (2.84e-04)       mail (5.23e-03) ✅
10      &gt (2.37e-04)        thank (4.61e-03)
11       |" (2.22e-04)     Notify (4.43e-03) ✅
12       |\ (1.96e-04)      Great (4.25e-03) ✅
13       |h (1.62e-04)            I (3.52e-03)
14     |int (1.59e-04)          >\n (3.31e-03)
15       |% (1.43e-04)          mer (3.06e-03)
16    |null (1.27e-04)         Line (2.80e-03)
17       |> (1.27e-04)     ulfilled (2.63e-03)
18       |. (1.19e-04)  Regarding (2.63e-03) ✅
19       |m (9.82e-05)      However (2.63e-03)

                                                                    \
                                    pos_0                    pos_1
0                      formula (0.0213) ✅            ANEL (0.0288)
1                calculation (7.35e-03) ✅           adera (0.0198)
2                  calculate (7.20e-03) ✅         ürger (8.28e-03)
3                        adera (6.92e-03)          uses (7.28e-03)
4                          bia (5.73e-03)     message (5.00e-03) ✅
5                  Calculate (5.39e-03) ✅       formula (4.70e-03)
6                   Determin (4.19e-03) ✅      equation (4.70e-03)
7                    Formula (3.34e-03) ✅        call (4.41e-03) ✅
8                      message (2.88e-03)    question (3.90e-03) ✅
9                        Est (2.88e-03) ✅         vente (3.67e-03)
10                calculated (2.77e-03) ✅           for (3.67e-03)
11                         ore (2.54e-03)         -->\n (3.30e-03)
12                         AST (2.44e-03)         Using (3.23e-03)
13                      wert (2.39e-03) ✅     Opinion (3.04e-03) ✅
14                    karakter (2.39e-03)   calculation (2.68e-03)
15                         Msg (2.25e-03)         point (2.68e-03)
16              calculations (2.20e-03) ✅           Use (2.37e-03)
17  ABCDEFGHIJKLMNOPQRSTUVWXYZ (2.20e-03)       Message (2.22e-03)
18                          {( (2.11e-03)        list (2.22e-03) ✅
19                  equation (2.11e-03) ✅          wert (2.13e-03)

                                                                layer_15  \
                       pos_2                     pos_3            pos_-3
0        karakter (0.0363) ✅         karakter (0.0482)        | (0.9531)
1      contador (9.91e-03) ✅           kost (8.87e-03)       >| (0.0154)
2          kost (6.94e-03) ✅        aplik (7.12e-03) ✅     |i (4.70e-03)
3       kontrol (5.13e-03) ✅       contador (5.93e-03)     |" (2.37e-03)
4         opies (4.89e-03) ✅          Namen (5.47e-03)     |h (1.53e-03)
5        spiele (4.73e-03) ✅          conex (5.44e-03)     |% (1.43e-03)
6          rekl (4.55e-03) ✅           rekl (4.57e-03)     |\ (1.43e-03)
7    Initialise (3.80e-03) ✅          galer (4.07e-03)     |= (9.27e-04)
8          AREA (3.80e-03) ✅       HEIGHT (3.95e-03) ✅     |r (6.79e-04)
9           -->\n (3.52e-03)           kurs (3.93e-03)     |( (5.61e-04)
10        aplik (3.51e-03) ✅   Initialise (3.91e-03) ✅     >> (5.46e-04)
11       kosten (3.35e-03) ✅        lokal (3.74e-03) ✅     |R (4.81e-04)
12        galer (2.97e-03) ✅   REFERENCES (3.35e-03) ✅     |m (4.65e-04)
13            tys (2.84e-03)    Validates (3.06e-03) ✅     |M (4.25e-04)
14        Namen (2.61e-03) ✅           erre (2.97e-03)     |x (3.41e-04)
15   kostenlose (2.26e-03) ✅          opies (2.72e-03)     |[ (3.30e-04)
16       Opcode (2.22e-03) ✅         spiele (2.62e-03)   |int (3.20e-04)
17        vente (2.13e-03) ✅            tys (2.59e-03)     |$ (3.11e-04)
18   REFERENCES (2.01e-03) ✅      kontrol (2.50e-03) ✅     _| (2.65e-04)
19            eks (1.84e-03)         AREA (2.49e-03) ✅  |null (2.57e-04)

                                                     \
                  pos_-1                      pos_0
0             I (0.1543)             |\n (9.52e-03)
1         Thank (0.1357)        karakter (7.42e-03)
2           >\n (0.0938)           --)\n (7.42e-03)
3        Dear (0.0442) ✅             |\n (5.77e-03)
4            As (0.0304)       formula (5.10e-03) ✅
5       Hello (0.0237) ✅             >\n (4.52e-03)
6         thank (0.0209)            ||\n (3.97e-03)
7         Great (0.0184)              |i (3.97e-03)
8         Sorry (0.0162)             X (3.51e-03) ✅
9           Yes (0.0127)           pesso (3.51e-03)
10       Please (0.0127)             =\n (3.10e-03)
11      Based (8.73e-03)   calculation (3.10e-03) ✅
12         as (8.73e-03)             meu (3.10e-03)
13        yes (5.98e-03)              Nh (2.73e-03)
14    Hallo (5.28e-03) ✅           adera (2.73e-03)
15      Thank (4.12e-03)         relação (2.73e-03)
16     Hola (4.12e-03) ✅             lij (2.41e-03)
17  Regarding (3.63e-03)   <|endoftext|> (2.41e-03)
18         >I (3.63e-03)               | (2.41e-03)
19       Hi (3.63e-03) ✅           minha (2.41e-03)

                                                         \
                        pos_1                     pos_2
0                >\n (0.0481)            >\n (0.1318) ✅
1                |\n (0.0292)              |\n (0.0260)
2              |\n (9.46e-03)              $\n (0.0179)
3         karakter (6.50e-03)              |\n (0.0157)
4              -\n (5.74e-03)             '\n' (0.0157)
5              Use (5.74e-03)            ' \n' (0.0109)
6            --)\n (5.07e-03)              ?\n (0.0109)
7            Using (4.49e-03)            -\n (9.58e-03)
8             Name (4.49e-03)            !\n (9.58e-03)
9              =\n (4.49e-03)            )\n (8.48e-03)
10     menggunakan (4.49e-03)            ,\n (7.48e-03)
11      equation (4.49e-03) ✅           ()\n (7.48e-03)
12           uales (4.49e-03)            :\n (7.48e-03)
13           adera (3.94e-03)            "\n (6.59e-03)
14            |}\n (3.48e-03)            =\n (5.80e-03)
15       formula (3.48e-03) ✅            .\n (5.13e-03)
16            ||\n (3.48e-03)            ;\n (4.52e-03)
17             ?\n (3.48e-03)            }\n (4.52e-03)
18      Addition (3.07e-03) ✅  <|endoftext|> (4.52e-03)
19   calculation (3.07e-03) ✅            ：\n (4.00e-03)


                       pos_3
0             >\n (0.1113) ✅
1               |\n (0.0527)
2              '\n' (0.0464)
3             ' \n' (0.0320)
4               |\n (0.0249)
5               "\n (0.0171)
6               -\n (0.0151)
7               $\n (0.0151)
8               ?\n (0.0117)
9               =\n (0.0104)
10           ()\n (9.16e-03)
11            ,\n (8.06e-03)
12            )\n (8.06e-03)
13  <|endoftext|> (6.29e-03)
14            :\n (6.29e-03)
15            ：\n (5.55e-03)
16            "\n (4.33e-03)
17            %\n (4.33e-03)
18            /\n (4.33e-03)
19            ;\n (4.33e-03)